### ISSUE TITLE
Banning mechisiam for unstable hashrate.

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#10]
When using pool farm like nicehash, the hashrate is very unstable during bidding. 
the current mechisiam is checking the last 51 shares validition ratio. if it over 51%, the miningcore will ban the client. when low diff, and fast start from nicehash, shares submitted is too quick. once rejects occurs, it mush be banned as it can submit 51 invalid shares in one second.
so i would suggest to change the banning mechisiam to checking invalid ratio in period of time instead of hecking last n shares. it would be better for ubstable hashrate clients.

**Comment by oliverw** [comment]
Yes I agree. That would be a reasonable improvement.

**Comment by oliverw** [comment]
Feel free to submit a PR.
