### ISSUE TITLE
[2021-11-23 08:47:13.5498] [E] [ltc1] Daemon reports pool-address 'litecoinpool.org:8080' as invalid 

### ISSUE THREAD

**Issue by Iweirdo** [coinfoundry/miningcore#1003]
Hi, could you have a look at this pool address error and tell me whats going on?
I used the same address as my other mining software like minerd, cpuminer etc, but its not working for mingcore,
besides, I would like to know whats the difference between miningcore and other mining software?
Many thanks.

**Comment by oliverw** [comment]
Pool address is supposed to be a wallet address, not a network endpoint.

**Comment by riabikov** [comment]
> Hi, could you have a look at this pool address error and tell me whats going on? I used the same address as my other mining software like minerd, cpuminer etc, but its not working for mingcore, besides, I would like to know whats the difference between miningcore and other mining software? Many thanks.

Miningcore is not a program for mining cryptocurrency, it is a program for creating and launching a pool to which hundreds of ordinary miners will connect, combine their capacities and receive a reward for it.

In the settings of the miningcore, you must specify the address of the wallet launched as a daemon on the server. This is not a personal wallet where you receive payments when mining.

**Comment by oliverw** [comment]
> Miningcore is not a program for mining cryptocurrency, it is a program for creating and launching a pool to which hundreds of ordinary miners will connect, combine their capacities and receive a reward for it.

Duh, didn't occur to me that he was trying to use it as a miner. 😄

**Comment by Iweirdo** [comment]
> > Hi, could you have a look at this pool address error and tell me whats going on? I used the same address as my other mining software like minerd, cpuminer etc, but its not working for mingcore, besides, I would like to know whats the difference between miningcore and other mining software? Many thanks.
> 
> Miningcore is not a program for mining cryptocurrency, it is a program for creating and launching a pool to which hundreds of ordinary miners will connect, combine their capacities and receive a reward for it.
> 
> In the settings of the miningcore, you must specify the address of the wallet launched as a daemon on the server. This is not a personal wallet where you receive payments when mining.

Thanks, Riabikov, you may leave a ETC address that I would buy a cup of coffee for you, I may have further little questions in the future, and no coffee for Duh bulb guy, 😄😄😄

**Comment by oliverw** [comment]
I'm closing this one since everyone appears to be happy now 😄
