### ISSUE TITLE
validSharesPerSecond: 0

### ISSUE THREAD

**Issue by Serpent6877** [coinfoundry/miningcore#101]
{
      "poolHashRate": 236446192.0,
      "connectedMiners": 2,
      "validSharesPerSecond": 0,
      "created": "2017-11-30T16:00:00"
    },
    {
      "poolHashRate": 178282912.0,
      "connectedMiners": 1,
      "validSharesPerSecond": 0,
      "created": "2017-11-30T17:00:00"
    }

Also, most other pools have a API option that shows each share for an address. I see them logged to the DB but currently no way to see them in the API.

**Comment by oliverw** [comment]
This is already tracked in #27 and actively being worked on. 😄
