### ISSUE TITLE
Error build windows 10

### ISSUE THREAD

**Issue by Raspimann** [coinfoundry/miningcore#1017]
hi,
on a windows 10 fresh installed system with download vc2022 and minigcore build 63 i become this error when i execute "window-build.bat":

C:\Users\me\Miningcore\src\Miningcore>windows-build.bat

C:\Users\me\Miningcore\src\Miningcore>dotnet publish -c Release --framework net6.0  -o ../../build
Microsoft (R)-Build-Engine, Version 17.0.0+c9eb9dd64 für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Wiederherzustellende Projekte werden ermittelt...
  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
  Cannot find the .git directory
C:\Users\me\.nuget\packages\gitversion.msbuild\5.8.0\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: Der Befehl "dotnet --roll-forward Major "C:\Users\me\.nuget\packages\gitversion.msbuild\5.8.0\tools\netcoreapp3.1/gitversion.dll" "C:\Users\me\Miningcore\src\Miningcore" -output file -outputfile obj\gitversion.json" wurde mit dem Code 1 beendet. [C:\Users\me\Miningcore\src\Miningcore\Miningcore.csproj]

Thx for helping me

**Comment by oliverw** [comment]
Currently building from a tarball (or zipball in your case) is not supported because of the GitVersion dependency. Please build from a inside a cloned git repo.

**Comment by Raspimann** [comment]
so i used:
git clone https://github.com/coinfoundry/miningcore
to clone

then i start windows-build.bat
here the output:

C:\Users\me\Miningcore\src\Miningcore>dotnet publish -c Release --framework net6.0  -o ../../build
Microsoft (R)-Build-Engine, Version 17.0.0+c9eb9dd64 für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Wiederherzustellende Projekte werden ermittelt...
  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
  Cannot find the .git directory
C:\Users\me\.nuget\packages\gitversion.msbuild\5.8.0\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: Der Befehl "dotnet --roll-forward Major "C:\Users\me\.nuget\packages\gitversion.msbuild\5.8.0\tools\netcoreapp3.1/gitversion.dll" "C:\Users\me\Miningcore\src\Miningcore" -output file -outputfile obj\gitversion.json" wurde mit dem Code 1 beendet. [C:\Users\me\Miningcore\src\Miningcore\Miningcore.csproj]

this is the error after i clone your repro ...
