### ISSUE TITLE
Question about adding new algo PHI1612 (LUX)

### ISSUE THREAD

**Issue by Joykiller** [coinfoundry/miningcore#106]
Would someone spare the time to add support for a new specific coin that uses PHI1612 algo called LUX?

https://bitcointalk.org/index.php?topic=2254046.0

I'm probably too busy at the moment to look into how it all works for now, so would rather pay someone for their time in adding it. Just inquiring to see if anyone would be interested and what they think would be sufficient pay would be.

**Comment by Konstantin35** [comment]
I can add in the near future
