### ISSUE TITLE
Coin support request: TOP 10 from WhatToMine

### ISSUE THREAD

**Issue by SergeySypalo** [coinfoundry/miningcore#107]
Hello guys,

I have an idea/proposal for you to add new coins support based on WhatToMine stats.
For example use 1 as a quantity for each card type from older ones to latest, the click calculate.
Site will display you list of most profitable coint to mine.
If you support most profitable coins you will earn more money on the pool comission.
For now, these coins are missing:

Altcommunity(ALTCOM) - Skunkhash
Sibcoin(SIB) - X11Gost
Zencash(ZEN) - Equihash
Feathercoin(FTC) - NeoScrypt
Vivo(VIVO) - NeoScrypt
Trezarcoin(TZC) - NeoScrypt

**Comment by calvintam236** [comment]
Someone is working on Zencash support - https://github.com/coinfoundry/miningcore/pull/84
I don't know the rest, but look like they have to wait. We have several important items in the backlog.

**Comment by oliverw** [comment]
Closing this as too broad. Please file individual issues.
