### ISSUE TITLE
Payment process problem.

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#111]
Dears,

I have a payment process problem on GLT pool wallet to my private address. even It has a 1000 GLT on pool wallet but its show me following errors

[2017-12-13 20:24:45.3511] [I] [PayoutManager] Processing payments for pool GLT
[2017-12-13 20:24:45.3806] [I] [PayoutManager] Processing payments for pool GLT, block 265485
[2017-12-13 20:24:45.3953] [I] [PayoutManager] Processing payments for pool GLT, block 265503
[2017-12-13 20:24:45.3953] [I] [PayoutManager] Processing payments for pool GLT, block 265560
[2017-12-13 20:24:45.5928] [I] [GLT] [Bitcoin Payout Handler] Paying out 770.305 GLT to 2 addresses
**[2017-12-13 20:24:45.6185] [E] [GLT] [Bitcoin Payout Handler] sendmany returned error: Account has insufficient funds code -6**

My pool wallet fund status. it has 1,000 GLT now.
![image](https://user-images.githubusercontent.com/18043565/33936839-4fd839a4-e044-11e7-9b09-f6f86611758b.png)

Regards,
John Ahn

**Comment by oliverw** [comment]
Does 47f7ffb47b415bf4807a005e4f3c996b28b3763d make a difference?

**Comment by jeong760** [comment]
Dears,

The result is same as before. still, I have an error.  

[2017-12-13 22:50:56.5796] [I] [GLT] [Bitcoin Payout Handler] Paying out 770.305 GLT to 2 addresses
[2017-12-13 22:50:56.6466] [E] [GLT] [Bitcoin Payout Handler] sendmany returned error: Account has insufficient funds code -6
[2017-12-13 22:50:56.6940] [I] [GLT] [Pool] Online
[2017-12-13 22:50:56.7038] [I] [GLT]

Regards
John Ahn

**Comment by jeong760** [comment]
Dears

Today I update another patch from master git. but the problem is same. 

17-12-14 23:04:19.8890] [I] [PayoutManager] Processing payments for pool GLT, block 265998
[2017-12-14 23:04:19.8890] [I] [PayoutManager] Processing payments for pool GLT, block 266008
[2017-12-14 23:04:19.9004] [I] [PayoutManager] Processing payments for pool GLT, block 266016
[2017-12-14 23:04:19.9004] [I] [PayoutManager] Processing payments for pool GLT, block 266080
[2017-12-14 23:04:19.9822] [I] [GLT] [Bitcoin Payout Handler] Paying out 5570.30877 GLT to 2 addresses
[2017-12-14 23:04:20.0415] [E] [GLT] [Bitcoin Payout Handler] sendmany returned error: Account has insufficient funds code -6

Regards,
John Ahn

**Comment by oliverw** [comment]
Could it be the case that the wallet has not enough confirmed balance? What do you get when running 

`glt-cli getwalletinfo`

**Comment by jeong760** [comment]
Dears,

Here is the result and your commented command is **globaltoken-cli getwalletinfo**. 
I think I have enough GLT for payment in pool wallet.
{
  "walletname": "wallet.dat",
  "walletversion": 139900,
  "balance": 68081.94378614,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 600.00171120,
  "txcount": 864,
  "keypoololdest": 1501847646,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "unlocked_until": 1513694129,
  "paytxfee": 0.00000000,
  "hdmasterkeyid": ""
}

**Comment by oliverw** [comment]
@jeong760 I agree. Hmm ...

**Comment by jeong760** [comment]
Dears,

Let me check more on this it seems to be payment process bug...

Regards,
John Ahn

**Comment by oliverw** [comment]
@jeong760 Did you resolve the problem?

**Comment by jeong760** [comment]
@oliverw No, I still have a payment issue even enough coin is in pool wallet. I think this caused by some source code change on payment process.

**Comment by jeong760** [comment]
@oliverw Do you think if I change a payment code as previous one then I can solve this?

**Comment by osnwt** [comment]
Any updates on this issue? I used a Docker image prebuilt for Dash fork. It processes payments but has exactly the same problem with sendmany call.

**Comment by osnwt** [comment]
RESOLVED.

The problem occurs when you create a new account for pool wallet using deprecated `getaccountaddress pool_wallet_name`. Pool uses default account "" to send from. If a pool wallet belongs to a named account, the pool tries to send from empty default account "" instead of named one and returns this error. So do not use named accounts for pool.

Accounts are deprecated. Maybe labels have no such problem, but I did not look yet what's the real difference. Anyway, replacing a wallet file with the empty one and importing old named account's private key resolved the issue for me.

**Comment by jeong760** [comment]
@osnwt,  so if I uses a default address without named, which provides by wallet. Theb we will not happened. Right?

**Comment by osnwt** [comment]
If you use unnamed default account address, it should work (works for me).

The pool internally uses `sendmany` RPC command with empty `""` string for `"fromaccount"`:
`sendmany "fromaccount" {"address":amount,...} ( minconf "comment" )`
If it works from console, it should work for the pool (try to send something to own address to test).

**Comment by osnwt** [comment]
Or better use this command to check balances (here is my test coin wallet):

`listaccounts`

```{
  "": 1549671.25056482,
  "InstantReceive": 400.00000000,
  "miningcore": 398.09667652,
  "miningfee": 0.00000000,
  "mn1": 173581.25009214
}
```

You should have positive balance for account `""`. This is the account the pool pays from.

**Comment by AgentWhite000** [comment]
Once you determine which address you want to pay from you can remove the account name by using setaccount and providing a blank account name

setaccount <YOUR_ADDRESS> ""

This will move your address to the account with no name and next payout attempt will work.
