### ISSUE TITLE
Payout scheme - Solo / Entire block

### ISSUE THREAD

**Issue by woblit** [coinfoundry/miningcore#112]
Thanks for a great product! And keep up the good work. 

Just a small request (hopefully small). Is it possible to have a payout scheme that allows miners to accumulate shares (which are irrelevant other than  just showing that the client is mining). And the entire block reward, after pool fees and (if enabled) dev donation are sent to the block finder after confirmation?

If this is possible this would be great. Otherwise I might have to write an entire payment system - which wouldn't be so much fun. :) 

Many thanks!

**Comment by oliverw** [comment]
Will be implemented soon.

**Comment by dmshel** [comment]
any news?

**Comment by oliverw** [comment]
This is now implemented in /dev

**Comment by dmshel** [comment]
mb can add PPS?

**Comment by Heraisu** [comment]
People requesting specific features from devs and still trying to disable 1/1000 dev donation... what a hoot. 2% for me NONE FOR YOU!
Putting a second hat in for PPS. Basically been waiting for this payment system to use it.  I have the general idea from looking at PPLNS, but I am concerned that if a calculation is off one would massively overpay for valid shares. Seems pretty straight-forward from looking at PPLNS, but certain details, like the mystery bug of  Lyra2REv2 algos' estimation of hashrate being very off in MiningCore gives me pause regarding PPS.
Sorry to semi-hijack.

**Comment by oliverw** [comment]
@Heraisu You are spot on. Running a PPS pool is a high-risk business for sure. Implementing a PPS payout scheme is not that difficult on the other hand.
