### ISSUE TITLE
Missing payments?

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#113]
I set up my pool with Straks and had my first few blocks but there is a discrepancy on the amount mined to what has been sent. 
The Reward receipent also hasn't received anything from what I can tell.

You can see the stats here http://5.189.159.254/pools/straks1
Pool address: https://straks.info/address/SMZ19bB68FwgZoMhM534QsjZ7DT6oCv9ZN

**Comment by oliverw** [comment]
> there is a discrepancy on the amount mined to what has been sent

Could you elaborate a bit? I don't understand.

> The Reward receipent also hasn't received anything from what I can tell.

Currently, reward recipients are paid like a miner which means they are subject to the pool's minimum payout. I'm going to add an option to pay reward recipients immediately either within the coinbase tx or bypassing the pool minimum payout.

To verify your balance you could issue an API call to the pool:

`curl http://127.0.0.1:4000/api/pools/<pool>/miner/<address>/stats`

**Comment by Kukks** [comment]
`The Reward receipent also hasn't received anything from what I can tell.`
Sorry about that part, I misunderstood how it worked. That part seems fine for now.

I do have 2 block rewards which were never distributed though. The first 2. Maybe I had a broken build or some bad configuration. I'll close this until it happens again.

**Comment by pfeiflelukas** [comment]
@Kukks How long did it take to find your first block? I havent found one yet and i have been mining for 12 hours with about 300Mh/s

**Comment by Kukks** [comment]
@pfeiflelukas Add me on discord User is Kukks

**Comment by pfeiflelukas** [comment]
@Kukks The last digest? Wont let me add it just as Kukks

**Comment by Kukks** [comment]
@pfeiflelukas  https://discordapp.com/invite/PM9j5XQ
