### ISSUE TITLE
Notifications Via Email

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#114]
Hi All,

I see there is a notifications area in the configurations area and was confused what this actually does. Does this notify the pool admin when a daemon goes offline etc. Or does it notify the user if their miner connects or disconnects?

Thanks

**Comment by bjorntheart** [comment]
From what I can see in the config it notifies the admin whether a block was found or not, if `notifyBlockFound: true`

Personally, I'm not aware of any other configuration options to notify the user about their miner connection status. Maybe it's just not documented. @oliverw is the notification system only to notify an admin via email about the `notifyBlockFound`, or other things it can do?

```json
    "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
```

**Comment by oliverw** [comment]
@bjorntheart @pfeiflelukas The purpose of the notification system is handle various notifications to both pool admin and the miners. Currently the number and possible recipients of notification is quite limited and needs to be improved.

**Comment by bjorntheart** [comment]
@oliverw I get that the functionality is limited, but to what extent? 
As far as I can see from the config file the admin is the only one who would receive email notifications if `notifyBlockFound` is set to true? Am, I right?

Upon further reflection, the `email` settings tell me that should be able to can configure any mailbox from a third party service, for example, GSuite, and that it's not required to run your own mail server. Correct?

Lastly. I couldn't gauge from your reply whether 3rd party transactional mail services will indeed work out of the box with Minincore. Would it take extra development to implement such a feature?

**Comment by oliverw** [comment]
@bjorntheart Yes your assumption is correct. To notify miners, we would have to implement some basic miner-account concept in order to store the miner's email in the first place.

And yes every service that supports SMTP for sending email should work.
