### ISSUE TITLE
Customiziable webhook

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#115]
Since you added Slack notification, maybe you can modify it and allow admin to add callback URLs for the webhooks instead?

https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Configuration/ClusterConfig.cs#L219

**Comment by oliverw** [comment]
Its an old issue, but nevertheless. What's missing here?

**Comment by oliverw** [comment]
Closing since notifications have been externalized through WebSockets.
