### ISSUE TITLE
Bitcoin Cash Incorrectly Supported

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#117]
@oliverw Bitcoin Cash has a symbol of BCH but is labelled as BCC

Thanks

**Comment by arubinofaux** [comment]
@pfeiflelukas just did a pull request #127 to correct that

**Comment by pfeiflelukas** [comment]
@arubinofaux Thanks

**Comment by oliverw** [comment]
Fixed by #https://github.com/coinfoundry/miningcore/commit/892b1bbcf147580c95684de875a08ff8c6a9f098
