### ISSUE TITLE
How can i run two PARITY at the same time on same machine 

### ISSUE THREAD

**Issue by 8bitidea** [coinfoundry/miningcore#128]
https://github.com/coinfoundry/miningcore/wiki/Coin-Daemon-&-Wallet-RPC

Here you have wirte the configuration of parity ? But how can i run more parity on one machine ?

**Comment by calvintam236** [comment]
@8bitidea If you want to run more than one `parity` instance not in a container (e.g. Docker), replace `--no-ipc` for `--ipc-path "/data/<unique-name>.ipc"`.
