### ISSUE TITLE
Introduce Migration scripts and versioning

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#130]
I noticed in the last PR, there was a schema change where some columns changed from a type to another. While this scenario wasn't breaking in itself, it has made older running implementations different. 
You should introduce tags for breaking changes on master. And a migration sql script to each new version.

**Comment by calvintam236** [comment]
@oliverw I think we should do this.

**Comment by oliverw** [comment]
See: https://github.com/coinfoundry/miningcore/releases/tag/0.11
