### ISSUE TITLE
Redundant Masternode object?

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#131]
In the Dash and Straks Block Template response, I can see that there is a Masternode object. After inspecting both Straks and Dash's `getblocktemplate` result, this object just does not exist. The `Payee` and `PayeeAmount` on the root seems to handle masternode payments.

**Comment by oliverw** [comment]
I agree it appears to be a remnant of the past. Probably of an earlier version of the consensus rules but I'd rather keep it to be safe.
