### ISSUE TITLE
Electroneum support

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#132]
It seems it is using Monero codebase (looks like a Monero clone), so it should be easily implemented.

https://github.com/electroneum/electroneum

**Comment by Konstantin35** [comment]
I added it to my pool but I could not find the unit to fully test

**Comment by oliverw** [comment]
Fixed by https://github.com/coinfoundry/miningcore/commit/c990ebed9fd51c5b00b1c52ef7aa14c71014b5c5
