### ISSUE TITLE
Parity configuration

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#133]
Hi all,

I see the configuration described here:

$ parity --chain mainnet --base-path <data-folder-path> --mode active --no-ui --no-dapps --no-ipc --jsonrpc-interface "0.0.0.0" --jsonrpc-threads 4 --jsonrpc-port 8545 --no-discovery --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --author <your-wallet-address> --cache-size 512 --logging info --ws-port 8546 --ws-interface all

But where can i set the user password? Is it under the "data-folder-path" and set here as per below?

[account]
unlock = ["0xdeadbeefcafe0000000000000000000000000000"]
password = ["$HOME/.safe/password.file"] <-- the password in a JSON file?
keys_iterations = 10240

Thanks for the help

**Comment by Konstantin35** [comment]
`parity --author 0xc13122b00000000000000000000 --chain "ellaism.json" --extra-data 2zo.pw --usd-per-tx 0 --no-dapps --no-ui --no-ws --jsonrpc-hosts all --rpcaddr=192.168.100.1 --jsonrpc-port 3213 --unlock 0xc13122b00000000000000000000 --password "password.txt"`

**Comment by pfeiflelukas** [comment]
@Konstantin35 Thanks for the configuration. I assume that uses the Ellaism coin though. Would i just swap
--chain "ellaism.json" with --chain "ethereum.json" or leave it as --chain mainnet as described above?

thanks

**Comment by Konstantin35** [comment]
I just showed an example consider a sequence of parameters and file paths

**Comment by pfeiflelukas** [comment]
ok no worries i will give it a try
