### ISSUE TITLE
Add support for more coins

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#134]
Can these coins be included in the pool?

- XMCC
- ARC
- ENT
- CHC
- XCXT

Thanks

**Comment by Konstantin35** [comment]
Will be a excitement with the launch of Segwit2x and I will try to add and test these coins

**Comment by Kukks** [comment]
@Konstantin35 The segwit2x fork is a scam; it has nothing to do with the official segwit2x team and is just another cash grab.

**Comment by Konstantin35** [comment]
Yes, I know a few scammers from Ukraine

**Comment by oliverw** [comment]
@Konstantin35 Could you please provide some basic information about those coins?

- Coin Family (Bitcoin, Monero, Ethereum etc) - if known
- Proof of work algo - if known
- Github Repo
- Website

**Comment by bjorntheart** [comment]
@oliverw Here you go. I couldn't get all the information

#### XMCC
Family: ???
Algo: X11
Github: https://github.com/monoeci
Website: https://monoeci.io

#### ARC
Family: ???
Algo: ???
Github: https://github.com/ArcticCore/arcticcoin
Website: https://arcticcoin.org/

#### ENT
Family: ???
Algo: X11
Github: https://github.com/eternity-group/eternity
Website: http://eternity-group.org/

#### CHC
Family: ???
Algo: ???
Github: https://github.com/chaincoin/chaincoin
Website: https://www.chaincoin.org/

#### XCXT
Family: ???
Algo: X11
Github: https://github.com/coinonat/CoinonatX
Website: http://coinonatx.com/

**Comment by oliverw** [comment]
@bjorntheart Thanks for the break-down. Unfortunatly I'm swamped in work. If you'd like one of those coins supported you are welcome to submit a PR. :)

**Comment by bjorntheart** [comment]
@oliverw I'm not particularly interested in those coins. I was just trying to help @Konstantin35 out :)
