### ISSUE TITLE
Does this software support coins of the same algo

### ISSUE THREAD

**Issue by mario1987** [coinfoundry/miningcore#137]
Hi,

As the topic suggest does this software support other coins that have the same also as dash ?? 
Or does it only support the coin itself?

**Comment by Kukks** [comment]
@mario1987 With a few code changes, you can add it in if it's identical in function to the DASH consesus.

**Comment by oliverw** [comment]
@mario1987 The X11 PoW algorithm used by Dash is supported of course. Additionally we support Dash's special blocktemplate. There's no general answer to the question if a particular coin can be supported. What coin are you referring to?

**Comment by 8bitidea** [comment]
@mario1987 i am sorry to interrupt this , but i have the same question in deferent coin , @oliverw the [pirl](https://pirl.io/)  coin uses dagger algorithm can the mining core run the pool for it like eth ?

**Comment by oliverw** [comment]
@8bitidea My previous comment applies to your question as well.

**Comment by 8bitidea** [comment]
@oliverw i have putted the url of the official web site of the coin in my previous comment and the git repo : https://github.com/pirl/pirl

**Comment by oliverw** [comment]
@8bitidea Regarding pirl, we have to wait for parity to support that coin.
