### ISSUE TITLE
API miner stats HTTP ERROR 500

### ISSUE THREAD

**Issue by coreinfo77** [coinfoundry/miningcore#147]
An error occurs after  Dev (#135)

/api/pools   >> ok.,
/api/pool/<poolid>/stats/hourly   >> ok.,
/api/pool/<poolid>/miner/<miner-wallet-address>/stats  >> HTTP ERROR 500
/api/pool/<poolid>/blocks   >> ok.,
/api/pool/<poolid>/payments   >> ok.,

only mininer stats error

**Comment by oliverw** [comment]
The api urls have been consolidated to all start with /api/pools to bring them in line with REST semantics.
