### ISSUE TITLE
New block notify by connecting to daemons as peer rather than block template polling

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#151]
Mining core discover new block mined via polling, however, this method has delay(polling interval(. Will you consider to connect to daemons as peer and let daemons to notify a new block is mined. The same feature is implemented in https://github.com/zone117x/node-stratum-pool/blob/master/lib/peer.js
Thanks.

**Comment by oliverw** [comment]
Planned already.

**Comment by Kukks** [comment]
Really cool stuff!

**Comment by oliverw** [comment]
@shwuhk This is now implemented using ZMQ pub/sub which is a much cleaner solution that's equally fast.

**Comment by Kukks** [comment]
How does this work? Any configuration needed?

**Comment by oliverw** [comment]
@Kukks Checkout the release notes for Release 0.15 that I'm just preparing.

**Comment by oliverw** [comment]
Here you go: https://github.com/coinfoundry/miningcore/releases/tag/0.15

**Comment by shwuhk** [comment]
This is awesome. It is much better than connecting it via peer method.
I would like to propose that it would be much nicer if it support multiple zmq publisher socket just like what we can have multiple daemons.

**Comment by oliverw** [comment]
@shwuhk I agree could you file a seperate issue for that?

**Comment by shwuhk** [comment]
Sure
