### ISSUE TITLE
Hashrate history for a miner

### ISSUE THREAD

**Issue by StarbuckBG** [coinfoundry/miningcore#153]
Hello!

I have been reviewing and running the code. Great work!
Isn't it possible to add hashrate history for a mining address for the separate mining rigs - https://github.com/coinfoundry/miningcore/blob/44bc44fcd44184822cf98b1f6d89339f1dac15e4/src/MiningCore/Persistence/Postgres/Repositories/StatsRepository.cs#L137

That will bring a lot of load on the DB server, but will provide a lot more info to the users. 
- It is possible to use Redis to collect data about the momentary hashrate. It will be faster for fetching..
- Other approach is just to do clean up of older than 1 day entries every few hours.

I'm currently modifying the miningcore-ui by calvintam236 and have submitted PR with some changes. 

Keep up the good work!

**Comment by calvintam236** [comment]
This is requested in #27 already.

**Comment by StarbuckBG** [comment]
Nice. I will just add my comments there and close this.
