### ISSUE TITLE
Use Nicehash setting?

### ISSUE THREAD

**Issue by coreinfo77** [coinfoundry/miningcore#155]
Are there any settings for using Nicehash?

My order Ends with an unstable hash rate.

**Comment by shtse8** [comment]
You should set the min diff for nicehash.

**Comment by coreinfo77** [comment]
"3073": {
                "listenAddress": "0.0.0.0",
                "difficulty": 0.9,
                "varDiff": {
                    "minDiff": 0.9,
                    "maxDiff": null,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30
                 }
            }

nicehash not working.. my order dead...

**Comment by oliverw** [comment]
Not sure what they changed but I couldn't get a single algorithm work with poolmining.org after they re-launched. Used to work fine - except for Ethereum.

**Comment by coreinfo77** [comment]
Thank you for answer.

**Comment by StarbuckBG** [comment]
<img width="1131" alt="screen shot 2018-01-07 at 2 59 53" src="https://user-images.githubusercontent.com/3859373/34645475-0900f9d2-f357-11e7-92c8-0a28d25332ae.png">
I think that Nicehash are enforcing tcp connections now. I cannot find if that is implemented or not. Thanks!

**Comment by Konstantin35** [comment]
`Pool user:` should be the appropriate purse

**Comment by oliverw** [comment]
@StarbuckBG But the stratum has always been tcp based. What do you mean?

**Comment by StarbuckBG** [comment]
Nevermind. There is an address validation. My fault.
