### ISSUE TITLE
I should add, Network Hashrate

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#156]
I should add, Network Hashrate at ` eth, etc, exp, ella`
Network Difficulty / Block Target Time
Parity Supports Musicoin (`MUSIC`) also you can add 
https://coinmarketcap.com/currencies/musicoin/

**Comment by calvintam236** [comment]
Please split coin support to another issue. I'm closing this since `networkHashRate` is available in the API: https://github.com/coinfoundry/miningcore/wiki/API#api-pools
