### ISSUE TITLE
how to launch Pool om Ubuntu 16

### ISSUE THREAD

**Issue by gblass** [coinfoundry/miningcore#158]
I went through all the steps and compile/build the miningcore, the db is built, and dotnet is installed.
I do not  see a miningcore.dll anywhere?  Please help, I know this sounds dumb, but im lost.

**Comment by bjorntheart** [comment]
Let's say you clone the repo in /home/ubuntu/miningcore and the build was successful. You should see a directory named `/build`. The MiningCore.dll is in this directory.
You should be able to confirm that with this command, `ls -l build/ | grep MiningCore.dll`, and see the following output
`-rw-rw-r--  1 ubuntu ubuntu  580096 Jan  4 14:50 MiningCore.dll`

**Comment by gblass** [comment]
thanks
