### ISSUE TITLE
MoonCoin

### ISSUE THREAD

**Issue by gblass** [coinfoundry/miningcore#159]
Would like to add MoonCoin.  I have successfully run MoonCoin on Rav3n P2Pool and UNOMP.  I would love to run it on this site.

**Comment by arubinofaux** [comment]
#176 here it is

**Comment by oliverw** [comment]
Merged.

**Comment by gblass** [comment]
thank you.  I am wondering if there are any UI I can try.  I am very
unfamiliar with setting up my on UI with API

On Mon, Jan 15, 2018 at 11:13 AM, Oliver Weichhold <notifications@github.com

**Comment by oliverw** [comment]
@calvintam236 Is working [on a GUI](https://github.com/calvintam236/miningcore-ui) and I believe there are others. Perhaps we should add an official sub-project for the GUI.
