### ISSUE TITLE
Errors when trying to run.

### ISSUE THREAD

**Issue by OmarWazzan** [coinfoundry/miningcore#160]
Hello, I'm trying to start miningcore, but it spits out this error:

> Error: After parsing a value an unexpected character was encountered: ". Path 'banning.manager', line 12, position 8.

Any ideas?

Thanks!

**Comment by Kukks** [comment]
Your configuration seems to be invalid. Can you check if your json is correct. try pasting it in here: https://jsonlint.com

**Comment by OmarWazzan** [comment]
Was a config issue, thanks!
