### ISSUE TITLE
Share Relay support

### ISSUE THREAD

**Issue by pool2mine** [coinfoundry/miningcore#1612]
Hello @oliverw 

I am making some tests and i was trying to use share relay but when i start the slave i get a persistence error, i obviously added "enabled": false, under persistence section, i remember before that when that line was added, persistence was not checked and pool started normally, just wondering if now is mandatory, because if it is, it would try to write locally

**Comment by pool2mine** [comment]
Does anyone tried to run an instance with only "pools" enabled? everything else disabled and no persistence? it used to work before, just don't know why now persistence is mandatory

**Comment by jon4hz** [comment]
Can you try deleting the entire "postgres" section from the persistence? The persistence config has no "enabled" logic. 

https://github.com/oliverw/miningcore/blob/a553f62301f44c6df80891e408b6526d1dd98692/src/Miningcore/Program.cs#L846-L849

**Comment by pool2mine** [comment]
ohhhh how is that i didn't tried that before posting?? haha, thanks man! that did the trick, i just thought that persistence needed to be in config (as api) either it was enabled or not. anyway, it's working now, i'm already creating DAG.

Thanks!

**Comment by jon4hz** [comment]
imagine having to create DAGs :eyes:
