### ISSUE TITLE
https and api

### ISSUE THREAD

**Issue by papagruz** [coinfoundry/miningcore#1613]
Hello.
When a enable ssl on web site, api connect don`t work, frontend say maintenance work.
I try add revers proxy but it`s not help.
my config on proxy pass server:

server {
    listen 80;
    server_name ethash.altcoinpool.ru;
    access_log /var/log/nginx/ethash.altcoinpool.ru-access.log;
    error_log /var/log/nginx/ethash.altcoinpool.ru-error.log;
    set_real_ip_from 95.165.168.191;
    real_ip_header X-Real-IP;
    return 301 https://$server_name$request_uri;
    }

server {
    listen 443 ssl http2;
    server_name ethash.altcoinpool.ru;
    access_log /var/log/nginx/ethash.altcoinpool.ru-ssl-access.log;
    error_log /var/log/nginx/ethash.altcoinpool.ru-ssl-error.log;
    set_real_ip_from 95.165.168.191;
    real_ip_header X-Real-IP;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/altcoinpool.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/altcoinpool.ru/privkey.pem;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    location /.well-known/acme-challenge/ {
        root /var/www/html/acme-challenge/;
    }
    location / {
        proxy_pass http://192.168.0.136;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /api/ {
        proxy_pass http://192.168.0.136:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $scheme;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }

}

config on api and web server:

server {
    listen 80;
    server_name ethash.altcoinpool.ru;
    access_log /var/log/nginx/altcoinpool.ru-access.log;
    error_log /var/log/nginx/altcoinpool.ru-error.log;
    set_real_ip_from 95.165.168.191;
    real_ip_header X-Real-IP;

     root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm stats.html index.nginx-debian.html;

        server_name ethash.altcoinpool.ru;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        location /api/ {
        proxy_pass http://192.168.0.136:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $scheme;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Reverse-Proxy true;
       }
}

Who can help with this problem?

**Comment by pool2mine** [comment]
I see you pasted your nginx file, but did you enabled ssl/tls in API section on config.json?

    "api": {
        "enabled": true,
        "listenAddress": "0.0.0.0",
        "port": 4000,
        "metricsIpWhitelist": ["x.x.x.x","x.x.x.x"],
        "adminIpWhitelist": ["x.x.x.x"],
        "tls": {
          "enabled": true,
          "tlsPfxFile": "/home/user/cert/api.pfx",
          "tlsPfxPassword": "password"
        },
        "rateLimiting": {
          "disabled": true,
          "rules": [
            {
              "Endpoint": "*",
              "Period": "1s",
              "Limit": 25
            }
          ],
          "ipWhitelist": [ "x.x.x.x" ]
        }

for me, it didn't work pointing config directly at the certificate folder, so i just made a "cert" folder in home, copied certificate there, set ownership to current user and somehow i also had to chmod 777, otherwise it had permission issues.

I hope it helps!

**Comment by papagruz** [comment]
Thanks for you help, try now

**Comment by papagruz** [comment]
Try add to conf ssl:

"api": {
        "enabled": true,
        "listenAddress": "0.0.0.0",
        "port": 4000,
        "metricsIpWhitelist": [],
        "ssl": {
           "enabled": true,
           "sslPfxFile": "/home/papagruz/cert/cert1.pem",
           "sslPfxPassword": ""
        },
        "rateLimiting": {
            "disabled": false,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            "ipWhitelist": [
                "0.0.0.0"

            ]
Not help, when switch site to https, no connect to api

**Comment by pool2mine** [comment]
ok, it's because you are using the wrong certificate file, you need to create a PFX file.

Login as root, then go to certificate folder and type:
sudo openssl pkcs12 -export -out cert1.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem

it will ask for a password to secure the file, enter a password... the output will be "cert1.pfx", then copy cert1.pfx to your home certificate folder and that is the one you need to put on your config.json with the same password you entered when creating

**Comment by papagruz** [comment]
Thanks, try now

**Comment by papagruz** [comment]
pfx file make, but after miningcore don`t start

![image](https://user-images.githubusercontent.com/35342330/217007005-0e365cb4-da25-4cff-abc3-d47c1d406e00.png)

**Comment by papagruz** [comment]
Not work. After create pfx, http not work, but and https not work :(
In api.log writing keys will not be encrypted, may be it this problem?
![image](https://user-images.githubusercontent.com/35342330/217011446-b6d3facd-3f25-4040-a49d-d0a4c745ea30.png)

**Comment by papagruz** [comment]
May be you can help my in discord? I can pay you for help. My nick in discord papagruz#5745

**Comment by pool2mine** [comment]
Don't worry, no need to pay anything, we're all here to help. if you still want to donate something i would recommend doing it to the miningcore project. all information is on the readme.

**Comment by minershaven** [comment]
Easiest way I found to do it was to create a subdomain for the API and then proxy pass that to port 4000.  So you have for example domain.com and api.domain.com.  Use certbot to secure them both and on the miningcore config just leave the API ssl setting disabled.  Hope that makes sense. If not let me know and I'll paste a nginx config example when I get to my pc

**Comment by papagruz** [comment]
Thanks, ok try add api subdomen.

**Comment by pool2mine** [comment]
I haven't tried that... i'm not sure if api will show over https if disabled in config, but if you already did it then there is another way. 

what i did was make a simple nginx file for my api subdomain

server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name api.pool2mine.net;

    location / {
        try_files $uri $uri/ =404;
    }
}

then secure it with certbot (i set the automatic redirection to https)... make the pfx file... copy to home... chown to user... chmod 777... set location and password in api section in config and that worked for me

**Comment by papagruz** [comment]
api subdomain make. add subdomain to certbt certificate.
In miningcore api log see reguest, on web "The pool is currently down for maintenance." 
Not try on ssl in mining core conf

**Comment by minershaven** [comment]
my nginx config is,

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	

	root /var/www/html;

	
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		
		try_files $uri $uri/ =404;
            
	}

	
}



server {

	

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;
    server_name minershaven.com; # managed by Certbot


	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
            
	}

	


    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/minershaven.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/minershaven.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = minershaven.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80 ;
	listen [::]:80 ;
    server_name minershaven.com;
    return 404; # managed by Certbot


}

server {
    if ($host = api.minershaven.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        server_name api.minershaven.com;

        location / {
            rewrite ^(.*)$  https://$host/$1 permanent;
            
        }
    

}

    server {
        listen 443 ssl http2;
        server_name api.minershaven.com;
    ssl_certificate /etc/letsencrypt/live/api.minershaven.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.minershaven.com/privkey.pem; # managed by Certbot
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://localhost:4000/api/;            
            
        }

}
```

then in my pool config i have 

```
"api": {
    "enabled": true,
    "ApiTlsConfig": false,
    "tlsAuto": false,
    "tlsPfxFile": "",
    "tlsPfxPassword": "",
    "listenAddress": "127.0.0.1",
    "port": 4000,
    "metricsIpWhitelist": [],
    "rateLimiting": {
      "disabled": false,
      "rules": [
        {
          "Endpoint": "*",
          "Period": "1s",
          "Limit": 125
```

i have been using it like that for over a year with no issues

**Comment by pool2mine** [comment]
problem was solved today. he got it working this afternoon. @papagruz please close the issue!

**Comment by papagruz** [comment]
Thanks for all. problem was solved

**Comment by ghost** [comment]
Would be nice if this was documented, he got it working but what was the solution?
