### ISSUE TITLE
Worker names

### ISSUE THREAD

**Issue by linuxdr0** [coinfoundry/miningcore#164]
How can you connect giving a worker name?  I've tried connecting with WalletAddress.workername and it does not seem to work.  Do you currently have to edit DB manually?

**Comment by oliverw** [comment]
No you don't. It should work out of the box.

**Comment by linuxdr0** [comment]
Should it work as: walletaddress.workername as the username then?  If so, does it have to be the very first time?

**Comment by linuxdr0** [comment]
Sorry.  Seems to work now.  Just a good while for API to show change compared to last version I was running before.
