### ISSUE TITLE
API doesn't seem correct

### ISSUE THREAD

**Issue by linuxdr0** [coinfoundry/miningcore#165]
I noticed that the API seems slower on some of the info changing like connected miners from previous version I was running.  After all miners were stopped for over 60 minutes, the API still showed 1 connected miner.  I then restarted the pool server and it still shows 1 connected miner.  The clientconnectiontimeout is set at 600.  The pool hash rate and miner rate hasn't changed as well.  It almost looks like whatever process checks periodically to change this isn't functioning.  Is there anything I can check?

**Comment by oliverw** [comment]
This is now all managed by this code: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Mining/StatsRecorder.cs

If it's a bug, it must be there.

**Comment by linuxdr0** [comment]
Found the issue.

These lines:
pool.PoolStats.ConnectedMiners = byMiner.Length;
pool.PoolStats.PoolHashRate = poolHashrate;
pool.PoolStats.ValidSharesPerSecond = (int) (poolHashesCountAccumulated / windowActual);

have now been put inside a loop that depends on windowActual being calculated which won't change if shares are not coming in.  So in my case with no connected miners the lastShare time will never change and the code to calculate these values will never run.

**Comment by oliverw** [comment]
@linuxdr0 Could you come up with a PR by chance?

**Comment by oliverw** [comment]
This has been fixed a couple releases ago by not including records older than 20 minutes in the API results.
