### ISSUE TITLE
Straks hashrate is not accurate

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#168]
One of my users reported that his hashrate was being marked as half what his miner was reporting. I've doubled the hashrate of the pool, pool 24 h history and miner stat on the ui for the time being.

**Comment by Kukks** [comment]
How big of a multiplier did you add? Currently at 2.0 herr

**Comment by Gadflyii** [comment]
I am looking at this at well, has anyone else started working on this item?
