### ISSUE TITLE
db error

### ISSUE THREAD

**Issue by M1neK1ng** [coinfoundry/miningcore#1684]
**Describe the bug**
A clear aDETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.)
[2023-05-07 13:37:04.3309] [W] [ShareRecorder] Retry 3 in 00:00:08 due to Npgsql: PostgresException (23514: no partition of relation "shares" found for row

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.)

I installed Miningcore foloowing all instruction to a T and yet console keeps spitting out this error.
Im not very good in postgresql so could someone help me fix this issue please.

thanks!

**Comment by jon4hz** [comment]
You have to create a shares partition per pool you're launching. 

```sql
CREATE TABLE shares_mypool1 PARTITION OF shares FOR VALUES IN ('mypool1');
```

_(as described in the README)_

**Comment by M1neK1ng** [comment]
So to be clear I have to add the shares partion per coin pool and not the cluster name?
Ive googled and searched github but every answer is read the readme paragraph..
Thanks for the help much apreciated.

**Comment by jon4hz** [comment]
If you launch a pool called btc1 you have to create a partition shares_btc1. If you launch a pool called eth1, you have to create shares_eth1 and so on.

**Comment by M1neK1ng** [comment]
awesome! thank you! no more errors
