### ISSUE TITLE
Invalid message start in communication with Node

### ISSUE THREAD

**Issue by StarbuckBG** [coinfoundry/miningcore#169]
2018-01-12 05:55:09 PROCESSMESSAGE: INVALID MESSAGESTART version peer=442992
2018-01-12 05:55:09 PROCESSMESSAGE: INVALID MESSAGESTART version peer=442993
2018-01-12 05:55:09 PROCESSMESSAGE: INVALID MESSAGESTART version peer=442994
2018-01-12 05:55:09 PROCESSMESSAGE: INVALID MESSAGESTART version peer=442995

This is what I've got from the logs. Also in BTG - 
2018-01-12 05:55:08 ERROR: ProcessNewBlock: AcceptBlock FAILED currently looking for more info.

**Comment by StarbuckBG** [comment]
This happens on BTG core, version 0.15.0.2. It causes a lot of ping.

**Comment by StarbuckBG** [comment]
After investigation I found out that the traffic was caused by 2 IPs that were trying to reach the nodes. Is there a possibility that the pool somehow exposes information about the IPs of the coin daemons ? After blocking the IPs the traffic dropped 6 times .... I have no such problems on my other nodes and the 2 for the pool were made specially for the pool. Moreover upon changing the nodes I have seen on the graphs that the traffic rises where the pool is pointed.

**Comment by StarbuckBG** [comment]
The drop is when I have banned the IPs
<img width="467" alt="screen shot 2018-01-12 at 12 30 05" src="https://user-images.githubusercontent.com/3859373/34870946-64288b68-f794-11e7-8b09-070c168e363c.png">

**Comment by rterbush** [comment]
These messages are caused by some "feature" of the BTG node software. Not clear if this change has yet to be implemented. 

https://github.com/BTCGPU/BTCGPU/issues/160

We should probably not be banning based on this warning.

**Comment by oliverw** [comment]
@StarbuckBG Nope. The pool does not expose the daemons anywhere.

**Comment by StarbuckBG** [comment]
The problem with the rejected blocks is fixed by this - https://github.com/coinfoundry/miningcore/pull/157/commits/f5bd439acaacd49d9135143b95e6cc0ebdd43179 

Tested in private BTG regtest network and working. Seems that the BTC segwit block is ok, but please double check.

**Comment by StarbuckBG** [comment]
Closing for now.
