### ISSUE TITLE
how is the PPLNS?

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#17]
Today morning, I successfully mined my first block.

Here is the block detail:
```
[
{
blockheight: 742811,
status: 3,
transactionConfirmationData: "c9912c782bece63abf234d7d75d532e6415ecee516f816fb1c3c755b34cdd4e9",
reward: 1.79557754,
infoLink: "https://chainradar.com/dsh/block/c9912c782bece63abf234d7d75d532e6415ecee516f816fb1c3c755b34cdd4e9",
created: "2017-09-24T22:46:38.099633"
}
]
```

Here is the log for paying process.
```
[2017-09-25 03:18:43.2074] [I] [PayoutProcessor] Processing payments for pool dash 
[2017-09-25 03:18:43.2147] [I] [PayoutProcessor] Processing payments for pool dash, block 742811 
[2017-09-25 03:18:44.0077] [I] [PayPerLastNShares] Adding 0.44637 DASH to balance of XrQsEqFfabd5mGy7W9vjBnvk6K19oc97gB for 39203 shares 
[2017-09-25 03:18:44.0236] [I] [PayPerLastNShares] Adding 0.00001 DASH to balance of Xe2Hbpb2ZJgc9WAuZJfUyN4QwDRhn7pzL6 for 869 shares 
[2017-09-25 03:18:44.0843] [I] [PayPerLastNShares] Deleting 73 obsolete shares before 9/23/17 11:39:07 PM 
[2017-09-25 03:18:44.1171] [I] [PayoutProcessor] No balances over configured minimum payout for pool dash 
```
`XrQsEqFfabd5mGy7W9vjBnvk6K19oc97gB` is me.
`Xe2Hbpb2ZJgc9WAuZJfUyN4QwDRhn7pzL6` is my friend.
I finally got 0.44637, and my friend got 0.00001. So where is others as the block reward is 1.79557754

**Comment by oliverw** [comment]
The pool kept the rest for the next payout round because there were most likely not enough shares to hit the X spot during calculation. Please read [this article by the inventor of PPLNS](https://bitcointalk.org/index.php?topic=39832) for further information. 

> If the pool has just started, and a block is found before there are shares totaling a score of X, there will be leftover rewards and it should be decided what to do with them. It doesn't matter much, but I recommend that the operator keeps them (in a macroscopic view, if the pool ever changes, this is compensation for the funds needed to cash participants out). Other options include donating to charity, or distributing among the miners.

Could you check the pool's wallet and confirm that it holds the left-over funds?

**Comment by oliverw** [comment]
By the way I've just [fixed](https://github.com/coinfoundry/miningcore/commit/9e464d6aabd1d72eb6ee0b09ad61657f6da0103e) the wrong info link for your block.

**Comment by shtse8** [comment]
Yes, I have checked. the whole balance is still in my wallet.

**Comment by oliverw** [comment]
I believe there haven't been any transfers yet because from the logs it looks like the minimum payouts for the pool haven't been hit yet.

**Comment by shtse8** [comment]
Yes. Thanks for your information. I have read that article. I thought PPLNS is round-based. I don't know it is not about round. and the shares before X will not be paid. 😮

**Comment by oliverw** [comment]
You got that wrong. With PPLNS shares are eligible for multiple payouts. They will be paid, when the next block is found.

**Comment by oliverw** [comment]
And by the way since I assume what you are doing here is solo mining using Nicehash, I proportional ([PROP](https://en.bitcoin.it/wiki/Comparison_of_mining_pools)) payout-scheme would be a better fit. I had this on my list anyway.

**Comment by shtse8** [comment]
Yes, that would be better if it is available.
At the moment, I would be solo mining using Nicehash. After everything is tested and the website is ready, I make my pool public. This is my first time to be a pool operator, just for fun. 👍
