### ISSUE TITLE
Block found but not recognized by miningcore or api

### ISSUE THREAD

**Issue by cimam95** [coinfoundry/miningcore#1719]
Block was found for a coin that uses Ghostrider algorithm. However the miningcore and api never picked it up. Block reward was deposited into a pool wallet, but because it was never recognized it wasn't paid out to a miner. Fortunately in this case the miner is only me and I can manually transfer the balance but how do I investigate this? What could potentially cause this behaviour?

**Comment by cimam95** [comment]
I'm looking at everything possible does my database look okay?

miningcore=# \dt
                     List of relations
 Schema |      Name       |       Type        |   Owner
--------+-----------------+-------------------+------------
 public | balance_changes | table             | miningcore
 public | balances        | table             | miningcore
 public | blocks          | table             | miningcore
 public | miner_settings  | table             | miningcore
 public | minerstats      | table             | miningcore
 public | payments        | table             | miningcore
 public | poolstats       | table             | miningcore
 public | shares          | partitioned table | miningcore
 public | shares_mecuai   | table             | postgres
 public | shares_pgn11    | table             | postgres
 public | shares_rtm1     | table             | postgres
 public | shares_skyt1    | table             | postgres
(12 rows)

**Comment by cimam95** [comment]
[2023-09-28 22:16:39.1660] [I] [skyt1] Submitting block 20040 [99d86e7fe2097cad8453bfd77632b8bd2fa13ade04647f391a1117c927ab0286] 
[2023-09-28 22:16:39.2087] [W] [skyt1] Block 20040 submission failed with: bad-cb-payee 

How to fix the (bad-cb-payee) 
Does anyone know?

**Comment by MiningCryptoLive** [comment]
Bad-cb-payee means the wallet is not valid. Double check the wallet address you are using

**Comment by cimam95** [comment]
> Bad-cb-payee means the wallet is not valid. Double check the wallet address you are using

Thank you, Bad-cb-payee went away once I enabled the smartnodes in coins.json. 
Now since then pool has found 5 blocks, the rewards were deposited into pools wallet. 

But… the API has not picked those up, it shows 0 blocks found so paymentprocessor never kicked in. 
I’m stuck not sure where to investigate API problem.

**Comment by MiningCryptoLive** [comment]
What coin are you mining?

**Comment by cimam95** [comment]
Skytere right now, but it happens to any Ghostrider algo coins. Because I also found two blocks on Mecuai, same thing funds deposited into the wallet but API doesn't register it.

**Comment by cimam95** [comment]
Anyone knows where I can look? I have perpool logging enabled, but no visible errors are showing up.

**Comment by cimam95** [comment]
> Bad-cb-payee means the wallet is not valid. Double check the wallet address you are using

I just checked the mining core database and blocks are not there. How do I make sure that the blocks are added to psql database?

**Comment by MiningCryptoLive** [comment]
Do the shares show in the database?

**Comment by cimam95** [comment]
> Do the shares show in the database?

Yes shares show up in (public | shares | partitioned table | miningcore ) and in ( public | shares_skyt1    | table | postgres ).

**Comment by cimam95** [comment]
> Do the shares show in the database?

Found the following error, which appears right after the block is found.
[2023-10-01 02:35:53.1977] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist

Do I create a new table in miningcore database called minereffort?

Here are the Tables already in database:

                     List of relations
 Schema |      Name       |       Type        |   Owner
--------+-----------------+-------------------+------------
 public | balance_changes | table             | miningcore
 public | balances        | table             | miningcore
 public | blocks          | table             | miningcore
 public | miner_settings  | table             | miningcore
 public | minerstats      | table             | miningcore
 public | payments        | table             | miningcore
 public | poolstats       | table             | miningcore
 public | shares          | partitioned table | miningcore
 public | shares_mecuai   | table             | miningcore
 public | shares_rtm1     | table             | miningcore
 public | shares_skyt1    | table             | miningcore

**Comment by MiningCryptoLive** [comment]
None of my databases have minereffort. Maybe that’s a provision for that
particular coin. I would try making it and see if it works

**Comment by MiningCryptoLive** [comment]
I did a quick google search and found this.

SQLSTATE=42703 means "*An undefined column or parameter name was detected*."
That error is expected because the current database table is missing the
corresponding column for the newly added attribute.So I would definitely create a table and try it out.

**Comment by cimam95** [comment]
> …

So I looked at the createdb.sql and the only time "minereffort" is mentioned is under "blocks" table.
CREATE TABLE blocks
(
	id BIGSERIAL NOT NULL PRIMARY KEY,
	poolid TEXT NOT NULL,
	blockheight BIGINT NOT NULL,
	networkdifficulty DOUBLE PRECISION NOT NULL,
	status TEXT NOT NULL,
    type TEXT NULL,
    confirmationprogress FLOAT NOT NULL DEFAULT 0,
	effort FLOAT NULL,
	minereffort FLOAT NULL,
	transactionconfirmationdata TEXT NOT NULL,
	miner TEXT NULL,
	reward decimal(28,12) NULL,
    source TEXT NULL,
    hash TEXT NULL,
	created TIMESTAMPTZ NOT NULL,

    CONSTRAINT BLOCKS_POOL_HEIGHT UNIQUE (poolid, blockheight, type) DEFERRABLE INITIALLY DEFERRED
);


But the error came from sharerecorder, I wonder under CREATE TABLE shares if I should add the minereffort.

**Comment by MiningCryptoLive** [comment]
Did you look in your database table for Blocks and see if minereffort is there?

**Comment by cimam95** [comment]
Yup it’s there, so I’m really getting confused now😐 

To be honest I’m not even sure that’s the reason why blocks are not being registered in the database.

could it be that missing something in daemon conf file? My pool and coin.json look exactly the same as the samples for Raptoreum.

**Comment by MiningCryptoLive** [comment]
Let me know if you figure it out. I will keep looking

**Comment by cimam95** [comment]
@MiningCryptoLive  I wonder if it's because I'm using @xiaolin1579 repo. I get the following errors after finding the block now.
[2023-10-03 22:14:24.3940] [I] [skyt1] Submitting block 23552 [1e5f7c0670573ff848636180b71208c40d34f57869e091b670f56a609532b5c1] 
[2023-10-03 22:14:24.4153] [I] [skyt1] Daemon accepted block 23552 [1e5f7c0670573ff848636180b71208c40d34f57869e091b670f56a609532b5c1] submitted by ST1nKbvSChKhM98M3pKA5fwMqtgb92M3JY 
[2023-10-03 22:14:24.5093] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271) 
[2023-10-03 22:14:26.5120] [W] [ShareRecorder] Retry 2 in 00:00:04 due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271)
[2023-10-03 22:14:30.5170] [W] [ShareRecorder] Retry 3 in 00:00:08 due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271) 
[2023-10-03 22:14:38.5192] [W] [ShareRecorder] Fallback due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271) 
[2023-10-03 22:14:38.5235] [F] [ShareRecorder] Fatal error during policy fallback execution. Share(s) will be lost! System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/recovered-shares.txt'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Miningcore.Mining.ShareRecorder.OnExecutePolicyFallbackAsync(Context context, CancellationToken ct) in /home/max/miningcore/src/Miningcore/Mining/ShareRecorder.cs:line 128    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Miningcore.Mining.ShareRecorder.OnExecutePolicyFallbackAsync(Context context, CancellationToken ct) in /home/max/miningcore/src/Miningcore/Mining/ShareRecorder.cs:line 128

@xiaolin1579 any ideas why this might be happening?

**Comment by cimam95** [comment]
Hey @MiningCryptoLive I haven't figured it out yet. Can you please show me your daemon conf file if you have any ghostrider coins? I got it to the point where there's only one error now [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271) which is normal based on @xiaolin1579 and his repository.

I believe I'm missing something in my daemon conf, as the blocks are not recorded in miningcore database.
Please let me know, thank you in advance. :)

Ps. I couldn't get original oliverw master repo working at all for ghostrider.

**Comment by ghost** [comment]
Are you sure there is a minereffort column? There is an "effort" column and there is a "minereffort" column.

**Comment by ghost** [comment]
> > Do the shares show in the database?
> 
> Found the following error, which appears right after the block is found. [2023-10-01 02:35:53.1977] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist
> 
> Do I create a new table in miningcore database called minereffort?
> 
> Here are the Tables already in database:
> 
> ```
>                  List of relations
> ```
> 
> Schema | Name | Type | Owner --------+-----------------+-------------------+------------ public | balance_changes | table | miningcore public | balances | table | miningcore public | blocks | table | miningcore public | miner_settings | table | miningcore public | minerstats | table | miningcore public | payments | table | miningcore public | poolstats | table | miningcore public | shares | partitioned table | miningcore public | shares_mecuai | table | miningcore public | shares_rtm1 | table | miningcore public | shares_skyt1 | table | miningcore

These are tables and not columns of tables.  The "minereffort" an column of "block" table 
![image](https://github.com/oliverw/miningcore/assets/108800590/053d77d4-695b-4c4a-bd46-ab7eda93de79)

**Comment by xiaolin1579** [comment]
@cimam95 Try remove insert to db from Blockrepository.cs
![image](https://github.com/oliverw/miningcore/assets/10980342/c5227ad3-8cc5-4c45-b919-a4e1c97988d9)

**Comment by cimam95** [comment]
> > > Do the shares show in the database?
> > 
> > 
> > Found the following error, which appears right after the block is found. [2023-10-01 02:35:53.1977] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist
> > Do I create a new table in miningcore database called minereffort?
> > Here are the Tables already in database:
> > ```
> >                  List of relations
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Schema | Name | Type | Owner --------+-----------------+-------------------+------------ public | balance_changes | table | miningcore public | balances | table | miningcore public | blocks | table | miningcore public | miner_settings | table | miningcore public | minerstats | table | miningcore public | payments | table | miningcore public | poolstats | table | miningcore public | shares | partitioned table | miningcore public | shares_mecuai | table | miningcore public | shares_rtm1 | table | miningcore public | shares_skyt1 | table | miningcore
> 
> These are tables and not columns of tables. The "minereffort" an column of "block" table ![image](https://user-images.githubusercontent.com/108800590/273543283-053d77d4-695b-4c4a-bd46-ab7eda93de79.png)
How did you export the database like that?

**Comment by cimam95** [comment]
> @cimam95 Try remove insert to db from Blockrepository.cs ![image](https://user-images.githubusercontent.com/10980342/273561715-c5227ad3-8cc5-4c45-b919-a4e1c97988d9.png)

Thank you, I removed it. Let's see what happens. :)

**Comment by cimam95** [comment]
@xiaolin1579 Code was changed just like you suggested. Found a few more blocks after that but they are still not registering in the database :(

**Comment by ghost** [comment]
> @xiaolin1579 Code was changed just like you suggested. Found a few more blocks after that but they are still not registering in the database :(

please copy the MC error log

**Comment by cimam95** [comment]
> > @xiaolin1579 Code was changed just like you suggested. Found a few more blocks after that but they are still not registering in the database :(
> 
> please copy the MC error log

[2023-10-10 17:46:12.4393] [I] [skyt1] Submitting block 28358 [0a65c7b80f7ef4f98efd7ff30dc09de8e84d045d573ca7b66448f0da8adb4] 
[2023-10-10 17:46:12.4574] [I] [skyt1] Daemon accepted block 28358 [0a65c7b80f7ef4f98efd7ff30dc09de8e84d045d573ca7b66448f0da8adb4] submitted by ST1nKbvSChKhM98M3pKA5fwMqtgb92M 

[2023-10-10 17:46:16.7131] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271) 

miningcore=# SELECT * FROM blocks;
 id | poolid | blockheight | networkdifficulty | status | type | confirmationprogress | effort | transactionconfirmationdata | miner | reward | source | hash | created | minereffort
----+--------+-------------+-------------------+--------+------+----------------------+--------+-----------------------------+-------+--------+--------+------+---------+-------------
(0 rows)

**Comment by ghost** [comment]
> > > > Do the shares show in the database?
> > > 
> > > 
> > > Found the following error, which appears right after the block is found. [2023-10-01 02:35:53.1977] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist
> > > Do I create a new table in miningcore database called minereffort?
> > > Here are the Tables already in database:
> > > ```
> > >                  List of relations
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Schema | Name | Type | Owner --------+-----------------+-------------------+------------ public | balance_changes | table | miningcore public | balances | table | miningcore public | blocks | table | miningcore public | miner_settings | table | miningcore public | minerstats | table | miningcore public | payments | table | miningcore public | poolstats | table | miningcore public | shares | partitioned table | miningcore public | shares_mecuai | table | miningcore public | shares_rtm1 | table | miningcore public | shares_skyt1 | table | miningcore
> > 
> > 
> > These are tables and not columns of tables. The "minereffort" an column of "block" table ![image](https://user-images.githubusercontent.com/108800590/273543283-053d77d4-695b-4c4a-bd46-ab7eda93de79.png)
> > How did you export the database like that?

pgAdmin  (like a phpMyAdmin)

**Comment by ghost** [comment]
> > > @xiaolin1579 Code was changed just like you suggested. Found a few more blocks after that but they are still not registering in the database :(
> > 
> > 
> > please copy the MC error log
> 
> [2023-10-10 17:46:12.4393] [I] [skyt1] Submitting block 28358 [0a65c7b80f7ef4f98efd7ff30dc09de8e84d045d573ca7b66448f0da8adb4] [2023-10-10 17:46:12.4574] [I] [skyt1] Daemon accepted block 28358 [0a65c7b80f7ef4f98efd7ff30dc09de8e84d045d573ca7b66448f0da8adb4] submitted by ST1nKbvSChKhM98M3pKA5fwMqtgb92M
> 
> [2023-10-10 17:46:16.7131] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "minereffort" does not exist POSITION: 271)
> 
> miningcore=# SELECT * FROM blocks; id | poolid | blockheight | networkdifficulty | status | type | confirmationprogress | effort | transactionconfirmationdata | miner | reward | source | hash | created | minereffort ----+--------+-------------+-------------------+--------+------+----------------------+--------+-----------------------------+-------+--------+--------+------+---------+------------- (0 rows)

The "blocks" table looks correct....

**Comment by cimam95** [comment]
@xiaolin1579 Any suggestions on what else I might try? The blocks are just not registering in the block database.

**Comment by MiningCryptoLive** [comment]
What repo are you using? Try using another repo or rebuild Miningcore. Maybe there was an error during the build or the repo you are using has changes that are affecting it

**Comment by cimam95** [comment]
> What repo are you using? Try using another repo or rebuild Miningcore. Maybe there was an error during the build or the repo you are using has changes that are affecting it

I had the same idea so I just built the original OliverW Master repo just now. I'm hoping I can close this thread soon :(

**Comment by cimam95** [comment]
@MiningCryptoLive  when using OliverW Master repo I get the following error. Which I thought I have fixed already by enabling smartblocks in coins.json. I know you mentioned before to check the wallet address, which I know is good because it was working with Xiaolin579 repo. 

[2023-10-11 17:29:46.2540] [I] [skyt1] Submitting block 29163 [969008d57f7525c0aa98056606229d6fd7941949bb050f2df2b0572635810172] 
[2023-10-11 17:29:46.2874] [W] [skyt1] Block 29163 submission failed with: bad-cb-payee 

@MiningCryptoLive @xiaolin1579 @Papiitoo  any ideas?

**Comment by MiningCryptoLive** [comment]
You can try jon4hz/miningcore-foss and see if it works for you

**Comment by cimam95** [comment]
@MiningCryptoLive  I tried john4hz repo and same thing:
 core log:
[2023-10-11 18:55:44.5134] [I] [skyt1] Submitting block 29208 [d68abc551c5c8e68bc0caada36d637fac12c4ac7e7041fef87a470763b483bce] 
[2023-10-11 18:55:44.5450] [W] [skyt1] Block 29208 submission failed with: bad-cb-payee 

Daemon debug log:
2023-10-11T22:55:44Z CGovernanceManager::UpdateCachesAndClean -- Governance Objects: 0 (Proposals: 0, Triggers: 0, Other: 0; Erased: 0), Votes: 0
2023-10-11T22:55:44Z ConnectBlock(SKYTERE): spork is off, skipping transaction locking checks
2023-10-11T22:55:44Z CSmartnodePayments::IsTransactionValid -- ERROR failed to find expected payee Si1M2P4rb9jLZG86CrA9ctWMC5C57MjDFi in block at height 29208
2023-10-11T22:55:44Z IsBlockPayeeValid -- ERROR: Invalid smartnode payment detected at height 29208: CTransaction(hash=ca3b47410d, ver=3, type=5, vin.size=1, vout.size=2, nLockTime=0, vExtraPayload.size=70)
    CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 02187204412727650030000005020000000a4d696e696e67636f7265, nSequence=0)
    CTxOut(nValue=500.00000000, scriptPubKey=76a914d59c03d3480e0635fb1dea88)
    CTxOut(nValue=4500.00000000, scriptPubKey=76a9143dc764a74a764451f2d3c5dc)
2023-10-11T22:55:44Z ERROR: ConnectBlock(SKYTERE): couldn't find smartnode or superblock payments
2023-10-11T22:55:44Z InvalidChainFound: invalid block=d68abc551c5c8e68bc0caada36d637fac12c4ac7e7041fef87a470763b483bce  height=29208  log2_work=43.61537935  date=2023-10-11T22:52:49Z
2023-10-11T22:55:44Z InvalidChainFound:  current best=5b04e8c24a239ff43f1ae767b8225db887f7bdee9c2bba99322f4e58de8e31f0  height=29207  log2_work=43.61537036  date=2023-10-11T22:52:24Z
2023-10-11T22:55:44Z ERROR: ConnectTip(): ConnectBlock d68abc551c5c8e68bc0caada36d637fac12c4ac7e7041fef87a470763b483bce failed with bad-cb-payee (code 16)
2023-10-11T22:55:44Z InvalidChainFound: invalid block=d68abc551c5c8e68bc0caada36d637fac12c4ac7e7041fef87a470763b483bce  height=29208  log2_work=43.61537935  date=2023-10-11T22:52:49Z

**Comment by MiningCryptoLive** [comment]
Looks like it has to do with being a smart node. Changes will need to be
made. Check with the devs of the project

**Comment by cimam95** [comment]
@xiaolin1579 would you please be so kind to show me your Coins.json pool.json and daemon conf. How you have ghostrider coins setup?

**Comment by cimam95** [comment]
@MiningCryptoLive @xiaolin1579 @Papiitoo Thank you guys so much for helping me, I really appreciate it. I figured it out finally and will be closing this issue.

**Comment by xiaolin1579** [comment]
> @xiaolin1579 would you please be so kind to show me your Coins.json pool.json and daemon conf. How you have ghostrider coins setup?

coins.json
![image](https://github.com/oliverw/miningcore/assets/10980342/58805058-be60-44b0-a9f4-4bd0f9f4a1e2)

**Comment by MiningCryptoLive** [comment]
Could you please post what you had to do to resolve the issue for others to follow.
