### ISSUE TITLE
Gradual response time increasing in the daemon communication

### ISSUE THREAD

**Issue by StarbuckBG** [coinfoundry/miningcore#177]
I see on the graph with the node communication response time that it is rising a lot:
<img width="489" alt="screen shot 2018-01-12 at 19 01 42" src="https://user-images.githubusercontent.com/3859373/34920331-ebbcce0e-f979-11e7-9f18-031dd93b3919.png">
<img width="467" alt="screen shot 2018-01-12 at 12 30 05" src="https://user-images.githubusercontent.com/3859373/34920332-edeebf70-f979-11e7-952b-1857827b9b7b.png">

Every 2 hours there is a reset or until I stop the miningcore for like 1 minute.

Please advice. 2 blocks orphaned.

**Comment by rewrewby** [comment]
@StarbuckBG Martin, how did you resolve orphaned blocks issue?

**Comment by StarbuckBG** [comment]
Check this - https://github.com/coinfoundry/miningcore/issues/150#issuecomment-357604054

**Comment by oliverw** [comment]
The new feature of Release 0.15 should help with this issue.

**Comment by StarbuckBG** [comment]
Will check. Thanks.

**Comment by oliverw** [comment]
Is this issue still present?

**Comment by StarbuckBG** [comment]
When the ZMQ is used there are no problems. However I still see gradually rising response times :/ It must be investigated to be understood where the problem comes from.

**Comment by oliverw** [comment]
I'm unable to repro this.
