### ISSUE TITLE
Payments To Pool's wallet

### ISSUE THREAD

**Issue by YoptaScriptDenis** [coinfoundry/miningcore#185]
Thank you for your product.

I created a pool, with the help of your samples, the power of my miners is 20kh / s, they have been working for 2 days, but so far no single solved block, can you explain why? And also, in miningcore-ui does not show the solved blocks - hence they do not exist.

On the wallet of the pool - empty
Shares are accpeting.
[I] [xmr1] [Pool] [0HLB0M04KNBT0] Share accepted: D=36686.233

[2018-01-21 10:29:11.9073] [I] [PayoutManager] No updated blocks for pool xmr1 
How i can just check, that everythink is working fine ?

PS : i'm running XMR

**Comment by Kukks** [comment]
Switch to testnet and see if you get any blocks there.

**Comment by oliverw** [comment]
@YoptaScriptDenis I'm confused how is the UI supposed to show blocks if you didn't mine any?
