### ISSUE TITLE
Support for x17 algorithm

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#188]
I am trying to integrate Verge coin to MiningCore. However, I can't merge x17 algo to the Native project as I am not familiar with C. Even I put the x17.c and related files there, it just can't built(it should be due to some dependency problem.) Is there anyone can help to add x17 algo to the Native project? Thanks.

The x17 algo in C is implemented in this project https://github.com/tpruvot/yiimp/tree/next/stratum/algos

**Comment by oliverw** [comment]
I can do that for you tommorow. Has been on my list anyway.

**Comment by oliverw** [comment]
This is now in dev: 1c6112acf7e5b0211674bda41321b1e471c61568

**Comment by oliverw** [comment]
@shwuhk By the way. Please stop working on this. Verge has been recently implemented on the dev branch.

**Comment by shwuhk** [comment]
That's very good! Is Verge tested and working in dev branch?
I finish implemented it but it seems cannot submit block successfully, don't know what goes wrong. May be the header composition is different than BTC? I don't see Verge has regtest and testnet is very slow. Testing is painful and I already lost several thousand there.

**Comment by shwuhk** [comment]
@oliverw 
I have just checked the code in dev branch.
Is it working as VERGE doesn't even support getblockchaininfo/getnetworkinfo command.
It is the exactly same way of what I did except that I have change the command that VERGE doesn't support to getinfo or other equivalent.

**Comment by shwuhk** [comment]
From what I know, VERGE should be POW instead of POS https://github.com/vergecurrency/VERGE/issues/562 . However, MC detect it as POS due to "            isPoS = difficultyResponse.Values().Any(x => x.Path == "proof-of-stake");". Not sure if I am correct.
