### ISSUE TITLE
No response from API

### ISSUE THREAD

**Issue by Crazytoo01** [coinfoundry/miningcore#189]
Hi guys iam trying to get this to work but it seems that the webserver cant get access to the programs api
the program is running and hashing but how do i connect it
both webserver and software is running on the same machine and default settings so i should be able to connect the the api on 127.0.0.1 / localhost port 4000 but when i setup the java file wtih this info and pool id ltc1 it get no response from api ??????
what am i doing wrong

**Comment by calvintam236** [comment]
Are you calling the API in the same network in the Javafile?

**Comment by Crazytoo01** [comment]
yes i have nginx install and downloaded the repo til /var/www/html/min........

     And the site shows up fine but when the site calls the api its says that it got no response 
    the minincore pool software is located i that home dir and the pool is running fine got a few miners working

**Comment by Crazytoo01** [comment]
btw 
Thanks for the amazing quick response

**Comment by Crazytoo01** [comment]
do you have any other setup instructions

**Comment by DeaVulTan** [comment]
Nope, you must set your public ip instead 127.0.0.1

**Comment by Crazytoo01** [comment]
okay so what u are saying is that i have to set the ip of the api services to 0.0.0.0 when the two program is running internally on the same linux machine ????

**Comment by Crazytoo01** [comment]
But what about the ui web frontend so that have to connect to local ip address??

**Comment by calvintam236** [comment]
@Crazytoo01 your API need to be accessible on Internet. the binding IP has to be either your public IP or `0.0.0.0` if you want to access the UI outside your network.
