### ISSUE TITLE
Unsupported RPC request: {"jsonrpc":"2.0","method":"mining.multi_version","params":[1],"id":1403} 

### ISSUE THREAD

**Issue by DeaVulTan** [coinfoundry/miningcore#192]
Now I'm testing LTC. I use the LTC setup from your examples, but I'll also attach it, with miningcore logs.
I rent ASIC, but the connection is constantly interrupted, and ASIC is trying to reconnect. On the site where I rent ASIC, the following is said:

"**Low Worker Difficulty
One or more workers on this rig has been assigned a share / worker difficulty by your pool that is too low. Hashrate performance issues may occur.
The OPTIMAL Difficulty range for this rig is 76,294 - 458k
Please either adjust your worker's settings at your pool or change pools. Thanks!** "

I changed the **difficulty** settings, but it does not work.

**MiningCore Trace Log**
https://pastebin.com/8g5RXs0k

**uname -a**
`4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**dotnet --version**
2.1.4

**LTC config.json**

```

{
    "logging": {
        "level": "trace",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "Mypasswd",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
  "api": {
    "enabled": true,
    "listenAddress": "MY_IP", // Binding address for API, Default: 127.0.0.1
    "port": 4000 // Binding port for API, Default: 4000
  },
    "pools": [{
      "id": "ltc1",
      "enabled": true,
      "coin": {
        "type": "LTC"
      },
      "address": "LP4B5Jd5t4KTGg84iHx4NumHft5zPBDn96",
      "rewardRecipients": [
        {
          "address": "LP4B5Jd5t4KTGg84iHx4NumHft5zPBDn96",
          "percentage": 0.5
        }
      ],
      "blockRefreshInterval": 500,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3042": {
          "listenAddress": "MY_IP",
          "difficulty": 200000,
          "name": "ASIC Mining",
          "varDiff": {
            "minDiff": 100000,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30,
            "maxDelta": 500
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 9332,
          "user": "ltc",
          "password": "ltc"
    }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }]
}
```

**My Litecoind config** 
```

rpcuser=ltc
rpcpassword=ltc
rpcport=9332
daemon=1
server=1
gen=0
```

**Comment by saltyminer** [comment]
It looks like the error that you are seeing in the pool trace is related to ASICBOOST.  I found this after a quick google search https://github.com/zone117x/node-open-mining-portal/issues/510.  It looks like the coin daemon doesn't like the RPC request for "mining.multi_version".

```
[2018-01-27 23:31:40.4767] [D] [ltc1] [Pool] [0HLB5QMQO7FSQ] Dispatching request 'mining.multi_version' [1518]
[2018-01-27 23:31:40.4767] [D] [ltc1] [Pool] [0HLB5QMQO7FSQ] Unsupported RPC request: {"jsonrpc":"2.0","method":"mining.multi_version","params":[1],"id":1518}
[2018-01-27 23:31:40.4767] [T] [StratumClient] [0HLB5QMQO7FSQ] Sending: {"error":{"code":20,"message":"Unsupported request mining.multi_version","data":null},"id":1518}
```

Related to the difficulty, have you tried using the NiceHash pool verifier to see if it accepts your difficulty settings?  Try running a test against the NiceHash pool verifier and see what the results are:
https://api.nicehash.com/poolver.jsp?a=14&l=1&poolhost=&poolport=&pooluser=&poolpass=

**Comment by DeaVulTan** [comment]
I know that this is connected with diff. The same day, I checked the settings with the help of nicehash. With nicehash, I have everything working, but on another site for rent ASIC, my pool does not work. By the way, nicehash also does not like the diff of coinfoundry. But here, that same ASIC lease site, works when mining at coinfoundry

**Comment by saltyminer** [comment]
I found this post about the ASICBOOST setting and multi_version.  Check out this article 
 https://www.reddit.com/r/Bitcoin/comments/63yo27/some_circumstantial_evidence_supporting_the_claim/dfy5o65/

**Comment by oliverw** [comment]
@saltyminer 

<  It looks like the coin daemon doesn't like the RPC request for "mining.multi_version".

This has nothing to do with the coin daemon. Miners do not directly talk to the daemon but to the pool and stratum requests are never directly relayed to coin daeamons. In this case BitcoinPoolBase simply is not aware of that particular request. Its simply not implemented.

**Comment by saltyminer** [comment]
Thanks, Oliver.  Ok, I mistakenly thought the trace line below was the pool trying to talk to the coin daemon.  Understood that the miners don't communicate directly to the coin daemon, but rather to the pool/stratum.  

In any event, it sounds like DeaVulTan is out of luck unless they implement that request in [BitcoinPoolBase](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs#L312).

`[2018-01-27 23:31:29.7152] [T] [StratumClient] [0HLB5QMQO7FS3] Sending: {"jsonrpc":"2.0","method":"mining.notify","params":["00000003","2a933402a7161d8049d127e626f206ab85598889adeae3761b801090cf8a33fc","01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1f0328b91404b6fd6c5a08","0c2f4d696e696e67436f72652f00000000020000000000000000266a24aa21a9edd8fc16b97283b9407ca5f8366404c563ce10eafb637da534c6b8c58e0bebd7b771beb296000000001976a9142a0709d2d6825ee93b5da85a69a39608f705743f88ac00000000",["4065983f5d36296af91f784434c50ba5cbec67fdbe4e69367d121feee6415094","5e465144dd3c859369c8e94dea4baccaad915e11eedc8c364ef18b336386c1dc","390e2aebd68503758c9e5b40831f7ff199c501f80832a1fbed1d26901c700464","116bf889ffa41687820920e5f1245bafa660758a8b1151d3b3035cff69dc2612","691a6f074a68e8fcd0cdca3c920f102a9088ad9652eb513c8a4b44968e83e939","1646482128a3700e42012a79624082159c1c6d097350c0d3e893a33bd2e97684","862dab7df3d9bd2c74a093c96150d4ccc42470a6af5d015dac128b11c7711e27"],"20000000","1a047f14","5a6cfdb6",false]}`

**Comment by saltyminer** [comment]
@oliverw 

Oliver, out of curiosity could @DeaVulTan add an additional case below [here](https://github.com/coinfoundry/miningcore/blob/8996c0d97c96ed46d438bf8a0245a89b5ed9459d/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs#L339) to ignore this request so that the pool doesn't throw an error? This would at least allow for debugging or further analysis.  I am not familiar with multi_version request, just trying to pick your brain.

**Comment by oliverw** [comment]
@DeaVulTan Absolutely.

**Comment by DeaVulTan** [comment]
Everything as a whole works, I'm only concerned about the fact that I can not mine from this site, although this site works on coinfoundry pool, so I want to understand my mistake.
