### ISSUE TITLE
Equihash difficulty calculation

### ISSUE THREAD

**Issue by saltyminer** [coinfoundry/miningcore#194]
I am working on adding HUSH coin support so I can contribute to the project.  I have the pool running on MAINNET and TESTNET successfully using the ZCLCoinbaseTxConfig (no founders reward).  The difficulty calculated in the init of the ZCash job using the BlockTemplate Target vs the difficulty of submitted shares seems to be incorrect.  Below is a scenario from debugging.

In the ZCashJob.Init the following line is calculating the difficulty as 8.038809381260992E+58

`Difficulty = (double) new BigRational(ZCashConstants.Diff1b, BlockTemplate.Target.HexToByteArray().ToBigInteger());`

BitcoinJob Manager is then setting the job network difficulty to the same value in the BitCoinJob.UpdateJob method here:

`BlockchainStats.NetworkDifficulty = job.Difficulty;`

In order to submit shares in a timely fashion I need to set the config.json as follows

```
"ports": {
	"3097": {
	  "listenAddress": "0.0.0.0",
	  "difficulty": 0.1,
	  "varDiff": {
		"minDiff": 0.1,
		"targetTime": 15,
		"retargetTime": 90,
		"variancePercent": 30
	  }
	},
	
```
When shares are submitted the share difficulty is averaging around 0.5 vs the network difficulty that was calculated by the job of 8.038809381260992E+58.  As a result payouts are never calculated since the shares submitted in the PPLNS window have too low a difficulty to accumulate a score.  I could manipulate the PPLNS factor or change the share multiplier, but I suspect the difficulty is not being calculated correctly from the block template target.  

I ran some tests using ZCash on the MAINNET and TESTNET and I see similar calculations.  When testing with Lyra2Rev2 for VTC and MONA the difficulty calculations for MONA and VTC both appear correct or at least more reasonable.  Am I missing a parameter in config.json for Equihash? Is the target difficulty being calculated correctly?  Would this impact finding a block?

**Comment by lucas556** [comment]
I also encountered such a problem.


      "ports": {
        "3392": {
          "listenAddress": "172.21.16.11",
          "difficulty": 0.1,
          "varDiff": {
            "minDiff": 0.04,
            "maxDiff": 16.0,
            "maxDelta": 1.0,
            "targetTime": 15.0,
            "retargetTime": 90.0,
            "variancePercent": 30.0
          }
        },
        "3393": {
          "listenAddress": "172.0.0.0",
          "difficulty": 1.0
        }
      },
      "networkStats": {
        "networkHashRate": 335053392.0,
        "networkDifficulty": 1.2785081528045759E+57,
        "lastNetworkBlockTime": "2018-02-05T02:01:59.914593",
        "blockHeight": 266725,
        "connectedPeers": 11
      },

**Comment by monkins1010** [comment]
I'm still having issues with the target not calculating correct..  the target is something like 0000000004737000000000  but when i  connect the miner it receives 089999999999999999999998
