### ISSUE TITLE
Future Dev

### ISSUE THREAD

**Issue by actionTurtle** [coinfoundry/miningcore#199]
Even though the pool engine can be used to run a production-pool, doing so currently requires to develop your own website frontend talking to the pool's API-Endpoint at http://127.0.0.1:4000. This is going to change in the future.

Just curious when this might change and what that means? Will miningcore have its own front end?

Thanks!!!

**Comment by bjorntheart** [comment]
@actionTurtle See this thread #3

**Comment by actionTurtle** [comment]
Thanks... Ok makes since... Saw the UI repo... Just wondering how this might change in the future or if it will...

**Comment by actionTurtle** [comment]
Why can i not mark this as a question... Guess only admins can... Thanks again
