### ISSUE TITLE
config.json possible values for some params

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#2]
I tried to edit `config.json` params, and I don't know the possible values for some of the params. For example, what are the possible types [here](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/config.json#L65), and [here](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/config.json#L55).

**Comment by oliverw** [comment]
1. https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Configuration/ClusterConfig.cs#L56
2. https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Configuration/ClusterConfig.cs#L27

I agree those fields should be documented.

**Comment by calvintam236** [comment]
How about [here](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/config.json#L134)? Is PPLNS is the only payoutScheme?

**Comment by oliverw** [comment]
PPLNS is currently the only implemented payout scheme because it's simply the most widely used one. Implementing other payout schemes should be straight forward.

**Comment by oliverw** [comment]
Relevant information have been added to README.md
