### ISSUE TITLE
EthereumStratum: jobs are sent before dififculty

### ISSUE THREAD

**Issue by jgillich** [coinfoundry/miningcore#204]
I've noticed the pool is sending jobs before setting a difficulty, which is a [spec violation](https://github.com/nicehash/Specifications/blob/master/EthereumStratum_NiceHash_v1.0.0.txt#L160):

> Before first job (work) is provided, pool MUST set difficulty by sending[...]

It also says miner can assume a difficulty of 1 when none is set, so it's not a big deal, just wanted to make sure you're aware of this.

**Comment by oliverw** [comment]
@jgillich Thanks for reporting. Will fix.
