### ISSUE TITLE
Payment process problem Dash-Paccoin

### ISSUE THREAD

**Issue by foxrtb** [coinfoundry/miningcore#205]
Im using the pool to mine a dash fork named paccoin.

Im getting the block in the wallet address but the payouts are not beying processed.

**[Dash Payout Handler] sendmany returned error: Account has insufficient
 funds code -6 **

**Comment by oliverw** [comment]
Could you post the output of <code>dash-cli getbalance</code> and the following query (run in pgsql) 

`SELECT sum(amount) from balances where poolid = 'your poolid';`

**Comment by foxrtb** [comment]
miningcore=# SELECT sum(amount) from balances where poolid = 'paccoin1';
        sum        
-------------------
 6721.357404288004
(1 row)

**Comment by foxrtb** [comment]
paccoin-cli getbalance
9660.00000000
