### ISSUE TITLE
Network Diff number/calc wrong? Or am I missing a conversion?

### ISSUE THREAD

**Issue by jmoeltjen** [coinfoundry/miningcore#208]
Network Diff is showing up as "6.570702248007084e+40 E" for example, when reported network diff by coin is 14281.24, for example.

Am I missing a conversion value or something here, or is the wrong number being reported to the API?

**Comment by oliverw** [comment]
Fixed in dev

**Comment by calvintam236** [comment]
Reopen if not fixed.

**Comment by jmoeltjen** [comment]
Appears to still be broken. Seeing `4.6674359872960025e+35` as the value for ZEN Net Diff, for instance.

**Comment by oliverw** [comment]
Fixed by 46a0c843165aede73547ec0b72435aa394337fa1

**Comment by dmshel** [comment]
I have error 2
![default](https://user-images.githubusercontent.com/37098267/37470573-6290291e-289a-11e8-9cac-6615214c6547.JPG)
check code 46a0c84 its ok, but network diff error
