### ISSUE TITLE
Blocks API Endpoint should show all blocks found

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#21]
I suggest blocks endpoint should show all blocks found including pending blocks with the confirmation count. I just mined two blocks half hour ago. the endpoint still show no blocks. But when I use the DashCore Windows Wallet. It can show two pending transactions are coming. Dash Explorer also can show the blocks.

**Comment by oliverw** [comment]
Confirmation count is currently not stored in the database and can thus not be returned - for now.
