### ISSUE TITLE
Block found, but never picked up by payment process, miners not credited with pending balance

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#210]
I am testing a new little pool, and we found a block (Zelcash, Zcash fork). 

The block shows on the API, it shows the reward, it confirmed, but it was never paid out, and the miners were never credited with a pending balance. 

The payment process just reports that there is no update blocks and no balances. 

Any ideas?

**Comment by foxrtb** [comment]
did you enabled the logging?

**Comment by Gadflyii** [comment]
It is enabled now, but not when the block was found. Is there any way to get the payment processor to pick up the block?

**Comment by Gadflyii** [comment]
Ok, we picked up another block, here is the logs:

Block found:

> 
> [2018-02-15 11:50:25.2599] [I] [Zel] [Bitcoin Job Manager] Submitting block 12593 [000000101efa861d9119e6c5adbc9c50f762e73ec8ed4ad4be8ccaf819e1434f] 
> [2018-02-15 11:50:25.3174] [I] [Zel] [Pool] [0HLBJU18UJV61] Booting zombie-worker (post-connect silence) 
> [2018-02-15 11:50:25.4203] [I] [Zel] [Bitcoin Job Manager] Detected new block 12594 via RPC polling 
> [2018-02-15 11:50:25.4203] [I] [Zel] [Pool] Broadcasting job 
> [2018-02-15 11:50:25.4306] [I] [Zel] [Bitcoin Job Manager] Daemon accepted block 12593 [000000101efa861d9119e6c5adbc9c50f762e73ec8ed4ad4be8ccaf819e1434f] submitted by t1MZ4pBVuSXxAtbYW72AjsAcqQyt74Au5Az 

Here is the first payment process that ran after the block was mined:

> [2018-02-15 11:57:14.2360] [I] [PayoutManager] Processing payments for pool Zel 

> [2018-02-15 11:57:14.2561] [I] [PayoutManager] Processing payments for pool Zel, block 12593 
> [2018-02-15 11:57:14.3326] [I] [PayoutManager] No balances over configured minimum payout for pool Zel

So it shows that it sees the block.

API shows both found blocks:

> [
>   {
>     "blockHeight": 12593,
>     "networkDifficulty": 6.6793907000059492E+58,
>     "status": "pending",
>     "confirmationProgress": 0.24509803921568626,
>     "effort": 1.5010500882948905E-54,
>     "transactionConfirmationData": "bbb603f43c843b69fca4edd554d14de095b15da8a13800de8fb7e4a841efe8e1",
>     "reward": 150.0002,
>     "infoLink": "http://explorer.zel.cash/block-index/12593",
>     "created": "2018-02-15T11:50:25.431028"
>   },
>   {
>     "blockHeight": 10058,
>     "networkDifficulty": 6.655480697278179E+58,
>     "status": "confirmed",
>     "confirmationProgress": 1.0,
>     "effort": 1.7149024269077449E-54,
>     "transactionConfirmationData": "a73352115af6076463147bade0b1b51adc481070b52eecdaee976c984f424e0f",
>     "reward": 150.0,
>     "infoLink": "http://explorer.zel.cash/block-index/10058",
>     "created": "2018-02-11T22:12:48.700605"
>   }
> ]

API result for a worker that was mining for the entire block showing zero pending balance

> {
>   "pendingShares": 27697,
>   "pendingBalance": 0.0,
>   "totalPaid": 0.0,
>   "performance": {
>     "created": "2018-02-15T12:52:30.117565",
>     "workers": {
>       "cw1": {
>         "hashrate": 1291.8604496326027,
>         "sharesPerSecond": 0.12099391567203485
>       }
>     }
>   },
>   "performance24H": [
>     {
>       "created": "2018-02-14T22:00:00",
>       "workers": {
>         "cw1": {
>           "hashrate": 1469.2180224195386,
>           "sharesPerSecond": 0.13865284319828369
>         }
>       }
>     },
>     {
> ...

@oliverw @StarbuckBG 

Any thoughts?

**Comment by foxrtb** [comment]
can you try to do the following:
on your server type  "coin-wallet-name"-cli listaccounts   (eg. litecoin-cli or bitcoin-cli)
check that the default account named "" has balance

**Comment by oliverw** [comment]
Please run with full debug log (set loglevel to "debug" in your config) and post the log.

**Comment by Gadflyii** [comment]
Ok, I restarted with the debug log, this is all it says before it just shows miners connecting and the Daemon client doing rpc block checks.




> [2018-02-16 02:33:10.0840] [I] [ShareRecorder] Online 
> [2018-02-16 02:33:10.1527] [I] [ApiServer] Launching ... 
> [2018-02-16 02:33:10.4019] [I] [ApiServer] Online @ 0.0.0.0:4000 
> [2018-02-16 02:33:10.4174] [I] [PayoutManager] Online 
> [2018-02-16 02:33:10.4242] [I] [PayoutManager] Processing payments for pool Zen 
> [2018-02-16 02:33:10.4301] [I] [StatsRecorder] Online 
> [2018-02-16 02:33:10.5300] [I] [Zen] [Pool] Launching ... 
> [2018-02-16 02:33:10.5557] [I] [Zen] [Bitcoin Job Manager] Launching ... 
> [2018-02-16 02:33:10.6240] [D] [DaemonClient] ExecuteCmdAllAsync(getblockchaininfo) 
> [2018-02-16 02:33:10.7208] [I] [Zel] [Pool] Launching ... 
> [2018-02-16 02:33:10.7336] [I] [Zel] [Bitcoin Job Manager] Launching ... 
> [2018-02-16 02:33:10.7336] [D] [DaemonClient] ExecuteCmdAllAsync(getblockchaininfo) 
> [2018-02-16 02:33:10.8031] [I] [Zel] [Bitcoin Job Manager] All daemons online 
> [2018-02-16 02:33:10.8120] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo) 
> [2018-02-16 02:33:10.8402] [D] [DaemonClient] ExecuteCmdAllAsync(getblocktemplate) 
> [2018-02-16 02:33:10.8775] [I] [Zen] [Bitcoin Job Manager] All daemons online 
> [2018-02-16 02:33:10.8775] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo) 
> [2018-02-16 02:33:10.8902] [I] [Zel] [Bitcoin Job Manager] All daemons synched with blockchain 
> [2018-02-16 02:33:10.8902] [D] [DaemonClient] ExecuteCmdAllAsync(getblocktemplate) 
> [2018-02-16 02:33:10.9231] [D] [DaemonClient] ExecuteBatchAnyAsync(validateaddress, getdifficulty, submitblock, getblockchaininfo) 
> [2018-02-16 02:33:11.0645] [I] [Zen] [Bitcoin Job Manager] Daemons still syncing with network. Manager will be started once synced 
> [2018-02-16 02:33:11.0903] [D] [Zel] [Bitcoin Job Manager] UpdateNetworkStatsAsync() 
> [2018-02-16 02:33:11.0960] [D] [DaemonClient] ExecuteBatchAnyAsync(getblockchaininfo, getmininginfo, getnetworkinfo) 
> [2018-02-16 02:33:11.0916] [D] [DaemonClient] ExecuteCmdAllAsync(getblockchaininfo) 
> [2018-02-16 02:33:11.1028] [D] [DaemonClient] ExecuteCmdAnyAsync(getpeerinfo) 
> [2018-02-16 02:33:11.1460] [I] [Zen] [Bitcoin Job Manager] Daemons have downloaded 98.06% of blockchain from 8 peers 
> [2018-02-16 02:33:11.2105] [I] [Zel] [Bitcoin Job Manager] Online 
> [2018-02-16 02:33:11.3964] [D] [BlockRepository] GetPendingBlocksForPool(Zen) 
> [2018-02-16 02:33:11.5431] [I] [PayoutManager] No updated blocks for pool Zen 
> [2018-02-16 02:33:11.5506] [D] [BalanceRepository] GetPoolBalancesOverThreshold() 
> [2018-02-16 02:33:11.5616] [I] [PayoutManager] No balances over configured minimum payout for pool Zen 
> [2018-02-16 02:33:11.5616] [I] [PayoutManager] Processing payments for pool Zel 
> [2018-02-16 02:33:11.5616] [D] [BlockRepository] GetPendingBlocksForPool(Zel) 
> [2018-02-16 02:33:11.5635] [I] [PayoutManager] No updated blocks for pool Zel 
> [2018-02-16 02:33:11.5635] [D] [BalanceRepository] GetPoolBalancesOverThreshold() 
> [2018-02-16 02:33:11.5635] [I] [PayoutManager] No balances over configured minimum payout for pool Zel 
> [2018-02-16 02:33:11.8007] [D] [Zel] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-16 02:33:11.8091] [D] [Zel] [Bitcoin Job Manager] GetBlockTemplateAsync() 
> [2018-02-16 02:33:11.8091] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocksubsidy) 
> [2018-02-16 02:33:11.8313] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
> [2018-02-16 02:33:11.9509] [I] [Zel] [Bitcoin Job Manager] Detected new block 13035 via RPC polling 
> [2018-02-16 02:33:11.9577] [I] [Zel] [Pool] Broadcasting job 
> [2018-02-16 02:33:11.9709] [D] [Zel] [Pool] Loading pool stats 
> [2018-02-16 02:33:11.9757] [D] [StatsRepository] GetLastPoolStats() 
> [2018-02-16 02:33:12.0873] [I] [Zel] [Pool] Online 
> [2018-02-16 02:33:12.0923] [I] [Zel] 
> 
> Mining Pool:            Zel
> Coin Type:              ZEL
> Network Connected:      Main
> Detected Reward Type:   POW
> Current Block Height:   13035
> Current Connect Peers:  8
> Network Difficulty:     5.88719698326473E+58
> Network Hash Rate:      1 MH/s
> Stratum Port(s):        5052, 5053
> Pool Fee:               0.5%
>  
> [2018-02-16 02:33:12.1366] [I] [Zel] [Pool] Stratum port 0.0.0.0:5053 online 
> [2018-02-16 02:33:12.1366] [I] [Zel] [Pool] Stratum port 0.0.0.0:5052 online 
>

**Comment by Gadflyii** [comment]
@foxrtb Yes, the daemon wallet received the block reward and shows the balance confirmed to the T-addy configured in the config.json for the pool.

**Comment by Gadflyii** [comment]
@oliverw  Is there anything else I can provide that will help troubleshoot this issue? I am stumped. 

I can't see anything wrong, but for what ever reason shares are not being converted to a pending balance when a block is found. 

If I am reading it right, Share process is working correct, miners have shares credited to them, block is found, API sees the block, payment process detects the block is new, but since there is no pending balance, it moves on and marks the block as complete. 

So where / how is the pending balance calculated and credited to the miners?

@StarbuckBG Any thoughts on this?

**Comment by Gadflyii** [comment]
@oliverw  Please close the behavior changed with Release 18, this issue is no longer valid.
