### ISSUE TITLE
Hashrate showing double for each miner (VTC / Lyra2REv2)

### ISSUE THREAD

**Issue by Heraisu** [coinfoundry/miningcore#211]
Platform: Windows 10 x64
Daemon: Vertcoin Core node / full sync / no prune
Using the head build at time of writing.

I have 7 different workers connected; been running for a day. I have viewed what their miners are reporting for real hashrate and also I know what they all show on other Lyra2Rev2 pools (like any p2pool).
They all display a hashrate which appears to be double (hashrate*2.0) what they should all approximate based on share rate the pool receives.  
Viewing from API sites such as http://localhost:4000/api/pools/vtc1
About 18h hours of data supports this.

I have tried:
Rebuilds
Default config (changed minimally for VTC)
Different miners
Altering the vardiff settings to give miners a more consistent estimate.

The only thing I can see which would have that multiplying effect is the config value 

> factor: 2.0

 (also, 2.0 is used as a default in the source code if no config value is found for Factor).
My understanding is that Factor is used to determine PPLNS frames / "rounds".  Is it possible though that this is somehow being used to miscalculate the displayed hashrates as well?
I'm still becoming acclimated to some parts of the source, so, admittedly, I am probably missing something. The issue seems clear; I just don't know where the problem is caused.

**Comment by oliverw** [comment]
@Heraisu The culprit is this: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs#L357

I have yet to figure out how to correctly calculate the hashrate for Lyra2re2 based currencies from the [coin parameters alone](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinProperties.cs).

**Comment by Heraisu** [comment]
I see, thank you for the reply.
Being that all workers return shares over a time period-- What is the specific detail about the algorithm Lyra2Re2 that causes this issue?

**Comment by oliverw** [comment]
I have no idea.

**Comment by oliverw** [comment]
Hashrate multiplier is now customizable in coins.json.
