### ISSUE TITLE
Status of Verge implementation

### ISSUE THREAD

**Issue by seansch** [coinfoundry/miningcore#214]
I was looking to mine Verge (scrypt) and I see some commits recently on dev that lead me to believe it might be possible. I was hoping for a quick heads up of the status on that and if it might be merged into master any time soon.

**Comment by oliverw** [comment]
@seansch Currently testing it in producton on coinfoundry.org. Finding the correct blockhasher for Verge was a tough one. Will post here if it works.

**Comment by seansch** [comment]
Thanks, I appreciate the update, Ill wait to hear how it goes.

**Comment by oliverw** [comment]
Current status: Improved but block submission still fails with: rejected. Ergo, still unusable.

**Comment by oliverw** [comment]
Please continue here: https://github.com/coinfoundry/miningcore/issues/265
