### ISSUE TITLE
Column "miner" missing from createdb.sql listed in readme

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#224]
@oliverw 

I built a new server with new DB for release 18, When running the createdb.sql listed in the readme it complained that there was no column "miner" in table balance_changes while creating the Index. 

Here is the portion of the script:

> CREATE TABLE balance_changes
> (
> 	id BIGSERIAL NOT NULL PRIMARY KEY,
> 	poolid TEXT NOT NULL,
> 	coin TEXT NOT NULL,
> 	address TEXT NOT NULL,
> 	amount decimal(28,12) NOT NULL DEFAULT 0,
> 	usage TEXT NULL,
> 	created TIMESTAMP NOT NULL
> );
> 
> CREATE INDEX IDX_BALANCE_CHANGES_POOL_ADDRESS_CREATED on balance_changes(poolid, miner, created desc);

I added the line: 

> miner TEXT,

In the CREATE TABLE balance_changes; I left it allowing null as rewards have a null miner value. 

Cheers!

**Comment by oliverw** [comment]
Fixed in Release 19.
