### ISSUE TITLE
Payment issue: Balance-calculation for pool , block completed with accumulated score 0 (0%)

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#226]
@oliverw  I performed a clean build of Release 19 and I am now getting this error. 

Here is the debug output:

> [2018-02-26 20:49:57.0086] [D] [BalanceRepository] GetPoolBalancesOverThreshold() 
> [2018-02-26 20:49:57.0476] [I] [Vision] [ZCash Payout Handler] Shielding ZCash Coinbase funds 
> [2018-02-26 20:49:57.0476] [D] [DaemonClient] ExecuteCmdSingleAsync(z_shieldcoinbase) 
> [2018-02-26 20:49:57.0852] [E] [PayoutManager] [Vision] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.
>    at Newtonsoft.Json.JsonReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\miningcore19\src\MiningCore\DaemonInterface\DaemonClient.cs:line 380
>    at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 101
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 167
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 97    at Newtonsoft.Json.JsonReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\miningcore19\src\MiningCore\DaemonInterface\DaemonClient.cs:line 380
>    at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 101
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 167
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 97
> [2018-02-26 20:49:57.1101] [D] [ZelCash] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-26 20:49:57.1101] [D] [NotificationService] SendNotificationAsync 
> [2018-02-26 20:49:57.0086] [D] [BalanceRepository] GetPoolBalancesOverThreshold() 
> [2018-02-26 20:49:57.0476] [I] [Vision] [ZCash Payout Handler] Shielding ZCash Coinbase funds 
> [2018-02-26 20:49:57.0476] [D] [DaemonClient] ExecuteCmdSingleAsync(z_shieldcoinbase) 
> [2018-02-26 20:49:57.0852] [E] [PayoutManager] [Vision] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.
>    at Newtonsoft.Json.JsonReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\miningcore19\src\MiningCore\DaemonInterface\DaemonClient.cs:line 380
>    at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 101
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 167
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 97    at Newtonsoft.Json.JsonReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\miningcore19\src\MiningCore\DaemonInterface\DaemonClient.cs:line 380
>    at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 101
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 167
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 97
> [2018-02-26 20:49:57.1101] [D] [ZelCash] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-26 20:49:57.1101] [D] [NotificationService] SendNotificationAsync 

Other related log entries before the error:

> 
> [2018-02-26 20:49:56.3166] [D] [BlockRepository] GetPendingBlocksForPool(Vision) 
> [2018-02-26 20:49:56.5622] [D] [DaemonClient] ExecuteBatchAnyAsync(gettransaction, gettransaction, gettransaction, gettransaction, gettransaction, gettransaction, gettransaction) 
> [2018-02-26 20:49:56.5778] [I] [Vision] [ZCash Payout Handler] Unlocked block 22088 worth 11.2501 VIS 
> [2018-02-26 20:49:56.5778] [I] [Vision] [ZCash Payout Handler] Unlocked block 22091 worth 11.2502 VIS 
> [2018-02-26 20:49:56.5778] [I] [PayoutManager] Processing payments for pool Vision, block 22088 
> [2018-02-26 20:49:56.6013] [I] [Vision] Adding 0.1125 VIS to balance of v1hpdaVbdMYh9JdxJicBFbAK6p9iqaj3G4f 
> [2018-02-26 20:49:56.6121] [D] [BalanceRepository] AddAmount() 
> [2018-02-26 20:49:56.6372] [D] [Vision] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-26 20:49:56.6542] [D] [Vision] [Bitcoin Job Manager] GetBlockTemplateAsync() 
> [2018-02-26 20:49:56.6372] [D] [ZelCash] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-26 20:49:56.6658] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocksubsidy) 
> [2018-02-26 20:49:56.6658] [D] [ZelCash] [Bitcoin Job Manager] GetBlockTemplateAsync() 
> [2018-02-26 20:49:56.6658] [I] [PPLNS] Fetching page 0 of shares for pool Vision, block 22088 
> [2018-02-26 20:49:56.6812] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocksubsidy) 
> [2018-02-26 20:49:56.6812] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
> [2018-02-26 20:49:56.6812] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
> [2018-02-26 20:49:56.7667] [D] [ShareRepository] ReadSharesBeforeCreated(Vision) 
> [2018-02-26 20:49:56.8155] [I] [ZelCash] [Bitcoin Job Manager] Detected new block 20683 via RPC polling 
> [2018-02-26 20:49:56.8155] [I] [Vision] [Bitcoin Job Manager] Detected new block 22207 via RPC polling 
> [2018-02-26 20:49:56.8315] [I] [PPLNS] Balance-calculation for pool Vision, block 22088 completed with accumulated score 0 (0%) 
> [2018-02-26 20:49:56.8315] [I] [Vision] [Pool] Broadcasting job 
> [2018-02-26 20:49:56.8386] [D] [BlockRepository] UpdateBlock() 
> [2018-02-26 20:49:56.8386] [D] [Vision] [Pool] Loading pool stats 
> [2018-02-26 20:49:56.8572] [D] [StatsRepository] GetLastPoolStats() 
> [2018-02-26 20:49:56.8806] [I] [PayoutManager] Processing payments for pool Vision, block 22091 
> [2018-02-26 20:49:56.8806] [I] [Vision] Adding 0.1125 VIS to balance of v1hpdaVbdMYh9JdxJicBFbAK6p9iqaj3G4f 
> [2018-02-26 20:49:56.8842] [D] [BalanceRepository] AddAmount() 
> [2018-02-26 20:49:56.8842] [I] [PPLNS] Fetching page 0 of shares for pool Vision, block 22091 
> [2018-02-26 20:49:56.8842] [D] [ShareRepository] ReadSharesBeforeCreated(Vision) 
> [2018-02-26 20:49:56.9463] [I] [PPLNS] Balance-calculation for pool Vision, block 22091 completed with accumulated score 0 (0%)

**Comment by Gadflyii** [comment]
@oliverw 

Little bit of an Update on this issue.

Here is the the flow of events that lead to this error:

- Block is found
- Block reaches 100% confirmed
- Next payment cycle runs:

Log output:

>  [2018-02-27 04:22:52.3705] [I] [Vision] [ZCash Payout Handler] Unlocked block 22281 worth 11.25 VIS 
> [2018-02-27 04:22:52.3705] [I] [PayoutManager] Processing payments for pool Vision, block 22281 
> [2018-02-27 04:22:52.3705] [I] [Vision] Adding 0.1125 VIS to balance of v1hpdaVbdMYh9JdxJicBFbAK6p9iqaj3G4f 
> [2018-02-27 04:22:52.3705] [D] [BalanceRepository] AddAmount() 
> [2018-02-27 04:22:52.3856] [D] [ZelCash] [Bitcoin Job Manager] No new blocks for 10 seconds - updating transactions & rebroadcasting work 
> [2018-02-27 04:22:52.3856] [D] [ZelCash] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-27 04:22:52.3856] [D] [ZelCash] [Bitcoin Job Manager] GetBlockTemplateAsync() 
> [2018-02-27 04:22:52.3856] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocksubsidy) 
> [2018-02-27 04:22:52.3856] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
> [2018-02-27 04:22:52.3856] [I] [ZelCash] [Pool] Broadcasting job 
> [2018-02-27 04:22:52.4135] [I] [PPLNS] Fetching page 0 of shares for pool Vision, block 22281 
> [2018-02-27 04:22:52.4135] [D] [ShareRepository] ReadSharesBeforeCreated(Vision) 
> [2018-02-27 04:22:52.4628] [I] [PPLNS] Balance-calculation for pool Vision, block 22281 completed with accumulated score 0 (0%) 
> [2018-02-27 04:22:52.4684] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.4684] [I] [PayoutManager] Processing payments for pool Vision, block 22282 
> [2018-02-27 04:22:52.4684] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.4684] [I] [PayoutManager] Processing payments for pool Vision, block 22293 
> [2018-02-27 04:22:52.4684] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.4814] [I] [PayoutManager] Processing payments for pool Vision, block 22318 
> [2018-02-27 04:22:52.4814] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.4814] [I] [PayoutManager] Processing payments for pool Vision, block 22321 
> [2018-02-27 04:22:52.4814] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.4814] [I] [PayoutManager] Processing payments for pool Vision, block 22328 
> [2018-02-27 04:22:52.4814] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.4814] [I] [PayoutManager] Processing payments for pool Vision, block 22340 
> [2018-02-27 04:22:52.5095] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5139] [I] [PayoutManager] Processing payments for pool Vision, block 22342 
> [2018-02-27 04:22:52.5139] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5139] [I] [PayoutManager] Processing payments for pool Vision, block 22343 
> [2018-02-27 04:22:52.5139] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5139] [I] [PayoutManager] Processing payments for pool Vision, block 22345 
> [2018-02-27 04:22:52.5139] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5139] [I] [PayoutManager] Processing payments for pool Vision, block 22346 
> [2018-02-27 04:22:52.5264] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5264] [I] [PayoutManager] Processing payments for pool Vision, block 22352 
> [2018-02-27 04:22:52.5264] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5264] [I] [PayoutManager] Processing payments for pool Vision, block 22358 
> [2018-02-27 04:22:52.5264] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5264] [I] [PayoutManager] Processing payments for pool Vision, block 22360 
> [2018-02-27 04:22:52.5264] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5422] [D] [ZelCash] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-27 04:22:52.5422] [D] [ZelCash] [Bitcoin Job Manager] GetBlockTemplateAsync() 
> [2018-02-27 04:22:52.5422] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocksubsidy) 
> [2018-02-27 04:22:52.5422] [D] [Vision] [Bitcoin Job Manager] UpdateJob() 
> [2018-02-27 04:22:52.5422] [D] [Vision] [Bitcoin Job Manager] GetBlockTemplateAsync() 
> [2018-02-27 04:22:52.5422] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocksubsidy) 
> [2018-02-27 04:22:52.5422] [I] [PayoutManager] Processing payments for pool Vision, block 22362 
> [2018-02-27 04:22:52.5422] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
> [2018-02-27 04:22:52.5422] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5422] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
> [2018-02-27 04:22:52.5638] [I] [PayoutManager] Processing payments for pool Vision, block 22366 
> [2018-02-27 04:22:52.5638] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5638] [I] [PayoutManager] Processing payments for pool Vision, block 22367 
> [2018-02-27 04:22:52.5638] [D] [BlockRepository] UpdateBlock() 
> [2018-02-27 04:22:52.5638] [D] [BalanceRepository] GetPoolBalancesOverThreshold() 
> [2018-02-27 04:22:52.5949] [I] [Vision] [ZCash Payout Handler] Shielding ZCash Coinbase funds 
> [2018-02-27 04:22:52.5949] [D] [DaemonClient] ExecuteCmdSingleAsync(z_shieldcoinbase) 
> [2018-02-27 04:22:52.6154] [E] [PayoutManager] [Vision] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.
>    at Newtonsoft.Json.JsonReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\miningcore19\src\MiningCore\DaemonInterface\DaemonClient.cs:line 380
>    at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 101
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 167
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 97    at Newtonsoft.Json.JsonReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\miningcore19\src\MiningCore\DaemonInterface\DaemonClient.cs:line 380
>    at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in C:\miningcore19\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 101
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 167
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\miningcore19\src\MiningCore\Payments\PayoutManager.cs:line 97
> [2018-02-27 04:22:52.6376] [D] [NotificationService] SendNotificationAsync 

And the process repeats every time a new block is unlocked. That said, the shielding does in fact go though.

> [
>   {
>     "id": "opid-d270ef70-106f-40f4-9d23-8661328ac225",
>     "status": "success",
>     "creation_time": 1519705372,
>     "result": {
>       "txid": "29cc7a4eff79d9b440c024c2dbe24d434514cd61ae7a91604de840c8398dca29"
>     },
>     "execution_secs": 82.241494641,
>     "method": "z_shieldcoinbase",
>     "params": {
>       "fromaddress": "v1wfJcReBMBBe9c9TRz5xthvASAZwpYhmE6",
>       "toaddress": "zcBHvmaMqeLGrMZKy23kbVVtQbKUChaqK76E2MDJ6vkEu7PWbHvNqKgBF3q4H88bzhfDrk9NTjWL6i8R9AC4ZchsTLqCw3p",
>       "fee": 0.00010000
>     }
>   },
>   {
>     "id": "opid-18271e14-6c8c-482e-9c51-fb447916f8c4",
>     "status": "success",
>     "creation_time": 1519705409,
>     "result": {
>       "txid": "d73601d613c2e86bc1b72dccf7e172e2e17c707d6ac2f7ebb4a2927c93fc3007"
>     },
>     "execution_secs": 83.036204975,
>     "method": "z_shieldcoinbase",
>     "params": {
>       "fromaddress": "v1wfJcReBMBBe9c9TRz5xthvASAZwpYhmE6",
>       "toaddress": "zcBHvmaMqeLGrMZKy23kbVVtQbKUChaqK76E2MDJ6vkEu7PWbHvNqKgBF3q4H88bzhfDrk9NTjWL6i8R9AC4ZchsTLqCw3p",
>       "fee": 0.00010000
>     }
>   }
> ]

The pool also pays the pool fee to the OP addy without issues.

**Comment by lucas556** [comment]
Release 19?

**Comment by Gadflyii** [comment]
https://github.com/coinfoundry/miningcore/releases

**Comment by lucas556** [comment]
@Gadflyii This should be a bug.

**Comment by Gadflyii** [comment]
Also...  I have only tested this on ZCash forks, Hush, etc.

**Comment by Gadflyii** [comment]
@oliverw  @lucas556 Please close, This is resolved in Dev, 

https://github.com/coinfoundry/miningcore/commit/46a0c843165aede73547ec0b72435aa394337fa1

**Comment by oliverw** [comment]
@Gadflyii Well I recently saw the "Unexpected token" problem when coinfoundry.org paid the recent ZCash block. Sure the problem went away on the next payment cycle but I'd rather fix the issue completely before closing.

**Comment by Gadflyii** [comment]
@oliverw I understand, I was referring to the PPLNS calculations resulting in 0. Happy to hear you are working on the unexpected token.

**Comment by oliverw** [comment]
Fixed ages ago.
