### ISSUE TITLE
[Urgent] Bitcoin Gold blocks mined but no rewards

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#228]
We use MiningCore to mine Bitcoin Gold. We mined three blocks but all of them MiningCore report orphaned.
I checked the mined block # in public explorer and show that the address is different than what I set in config and the reward amount is 0 BTG too. It was weird.

https://btg-bitcore2.trezor.io/block/000000000918995eafb39cf65ab26fba1a5948f108051efb905c8d0b4cea1922
https://btg-bitcore2.trezor.io/address/GVqHDv6m69TfRszCQB9mLTqKBqJBw49giE
https://btg-bitcore2.trezor.io/block/0000000006e433843db931bfe955317c76c72ab80d83cc3c8e93713c986fb698

The links above are the blocks that we mined. You can see that the received address are the same but they are not I set in the config file. Also, the reward amount is 0.

```json
[
{
blockHeight: 515993,
networkDifficulty: 1.244095332233174e+57,
status: "orphaned",
confirmationProgress: 0,
effort: 1.6453723014341652e-51,
transactionConfirmationData: "793867ef4f9109d22873992da1c7ca09d93906ca4d4457fdd6ca7f57fda7d851",
reward: 12.5,
infoLink: "https://btg-bitcore2.trezor.io/block/515993",
created: "2018-02-27T14:25:23.397183"
},
{
blockHeight: 515479,
networkDifficulty: 4.543992887921659e+56,
status: "orphaned",
confirmationProgress: 0,
effort: 5.495915292117103e-52,
transactionConfirmationData: "7ab9cbe478dd04d0910bbfa144502ddfe63d327c8152e7fd0938fdb3e80e730e",
reward: 12.5,
infoLink: "https://btg-bitcore2.trezor.io/block/515479",
created: "2018-02-24T06:22:35.603601"
},
{
blockHeight: 515386,
networkDifficulty: 2.3929183733830937e+56,
status: "orphaned",
confirmationProgress: 0,
effort: 1.3464638141604415e-50,
transactionConfirmationData: "91ee0981189c9c9e69d0aefaece1e0b64437c21ef6132e944d689fd9f94f9f42",
reward: 12.50009911,
infoLink: "https://btg-bitcore2.trezor.io/block/515386",
created: "2018-02-23T12:07:56.572381"
}
]
```

Any ideas with that?

**Comment by shwuhk** [comment]
https://github.com/coinfoundry/miningcore/blob/6eb5f6fbf6f9e90489989e8a001d63c1f6c1a030/src/MiningCore/Blockchain/BitcoinGold/BitcoinGoldJob.cs#L47-L55

I find that this block of codes seems have some error.  blockRewards and rewardFees seems to be zero as the init function is overrided and so those values aren't calculated. Also, the rewardToPool seems not used.

**Comment by Gadflyii** [comment]
@StarbuckBG

**Comment by shtse8** [comment]
I have the same issue.

**Comment by shtse8** [comment]
It seems the override Init missing the calculating rewards, or using wrong variable in `CreateOutputTransaction()`

**Comment by shwuhk** [comment]
@oliverw We updated to this version but it is still the same. Can you please check?
https://btg-bitcore2.trezor.io/tx/d1787df331a1b4cc0b8fb42e9e9549e526a2532b59967cdf2bebfeb4aa4263dc
This is the block we found after using the mentioned version. Thanks

**Comment by shwuhk** [comment]
@oliverw Any updates?
