### ISSUE TITLE
Networkdifficulty of ZEC: way to high number (Release 19)

### ISSUE THREAD

**Issue by IKqlXKPyQHlHrv1YI71Hw829W9uaLOjE** [coinfoundry/miningcore#229]
When I start miningcore the networkdifficulty for zcash (zec) is way to high although the zcash-cli is calculating it correctly. 

Output of zcash-cli:
> root:~# ./zcash/src/zcash-cli getinfo
> {
>   "version": 1001450,
>   "protocolversion": 170002,
>   "walletversion": 60000,
>   "balance": 0.00000000,
>   "blocks": 280122,
>   "timeoffset": 0,
>   "connections": 0,
>   "proxy": "",
>   "difficulty": 7861648.55892655,
>   "testnet": false,
>   "keypoololdest": 1519319213,
>   "keypoolsize": 101,
>   "paytxfee": 0.00000000,
>   "relayfee": 0.00000100,
>   "errors": ""
> }

Output of miningcore:
> [2018-02-28 11:52:03.5658] [I] [ZEC]
> Mining Pool:            ZEC
> Coin Type:              ZEC
> Network Connected:      Main
> Detected Reward Type:   POW
> Current Block Height:   280126
> Current Connect Peers:  8
> Network Difficulty:     2,31134862333789E+56
> Network Hash Rate:      412 MH/s
> Stratum Port(s):        3092, 3093
> Pool Fee:               1%

Configfile:

> {
>         "id": "ZEC",
>         "enabled": true,
>         "coin": {
>             "type": "ZEC"
>         },
>         "address": ".....",
>         "z-address": ".....",
>         "rewardRecipients": [
>             {
>                 "type": "op",
>                 "address": ".....",
>                 "percentage": 1.0
>             }
>         ],
>         "blockRefreshInterval": 500,
>         "jobRebroadcastTimeout": 10,
>         "clientConnectionTimeout": 600,
>         "banning": {
>             "enabled": true,
>             "time": 600,
>             "invalidPercent": 50,
>             "checkThreshold": 50
>         },
>         "ports": {
>             "3092": {
>                 "difficulty": 0.1,
>                 "varDiff": {
>                     "minDiff": 0.01,
>                     "maxDiff": null,
>                     "targetTime": 15,
>                     "retargetTime": 90,
>                     "variancePercent": 30,
>                     "maxDelta": 1
>                 }
>             },
>             "3093": {
>                 "difficulty": 1
>             }
>         },
>         "daemons": [
>             {
>                 "host": "127.0.0.1",
>                 "port": 8232,
>                 "user": ".....",
>                 "password": "....."
>             }
>         ],
>         "paymentProcessing": {
>             "enabled": true,
>             "minimumPayment": 0.01,
>             "payoutScheme": "PPLNS",
>             "payoutSchemeConfig": {
>                 "factor": 2.0
>             }
>         }
>     },

**Comment by lucas556** [comment]
Is bug

**Comment by oliverw** [comment]
This is weird, as the difficulty is taken directly from the blocktemplate.

**Comment by lucas556** [comment]
@oliverw thank you,Modified after the test is not correct.

./zcash-cli getinfo { "version": 1001250, "protocolversion": 170002, "walletversion": 60000, "balance": 22.40000430, "blocks": 196944, "timeoffset": 0, "connections": 8, "proxy": "", "difficulty": 1184.003669757143, "testnet": true, "keypoololdest": 1519637379, "keypoolsize": 101, "paytxfee": 0.00000000, "relayfee": 0.00000100,
and api is ：

"networkStats": { "networkHashrate": 231.0, "networkDifficulty": 3.6802212535360552, "lastNetworkBlockTime": "2018-03-01T02:43:37.374664", "blockHeight": 196816, "connectedPeers": 8 },
api's difficulty is not the whole network difficult?

**Comment by oliverw** [comment]
@lucas556 Difficulty reported by the API is the difficulty calculated from the "target" field of the latest blocktemplate (RPC "getblocktemplate").

**Comment by lucas556** [comment]
@oliverw API difficulty calculation is not network difficulty?

**Comment by lucas556** [comment]
Api networkstats "networkDifficulty" is not equal to zcash network difficulty?
