### ISSUE TITLE
About database migration in Release 0.17

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#231]
As per the instruction of database migration of Release 0.17, the following SQL cannot be run
```sql
ALTER TABLE blocks ADD miner TEXT NULL;
```
It returns
```
ERROR:  column "miner" of relation "blocks" already exists
SQL state: 42701
```

Help would be appreciated. Thanks.

**Comment by oliverw** [comment]
You can ignore this.

**Comment by shwuhk** [comment]
So you mean I can just skip this query?

**Comment by oliverw** [comment]
Yes. The column is already present.

**Comment by shwuhk** [comment]
Great. THanks.
