### ISSUE TITLE
Question: Anyway to enable https on the API?

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#232]
Is there anyway to enable https on the API without SSL offloading?

**Comment by interbiznw** [comment]
Second this, Can't have pool page HTTPS with api, get mixed content error and stats do not load.

**Comment by oliverw** [comment]
What I would like to recommend for the time being is to reverse proxy the API using [bud](https://github.com/indutny/bud) (yes, funny name but very reliable software used for all coinfoundry SSL stratum ports) or HAProxy.
