### ISSUE TITLE
Block reward of XVG is wrong.

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#233]
We have mined XVG successfully. However, the block reward showing in MC is wrong. Multiplication 100x is needed. Please help to fix as this cause us distributing reward wrongly or hope can provide some quick fix so that we can fix it first. Thanks.

```json

[
  {
    "blockHeight": xxxxx,
    "networkDifficulty": xxxxxx,
    "status": "pending",
    "confirmationProgress": 0.23529411764705882,
    "effort": 0.4166229435076656,
    "transactionConfirmationData": "xxxxxxxxxx",
    "reward": 15.6060,
    "infoLink": "https://verge-blockchain.info/block/xxxxxxx",
    "created": "xxxxxxxx"
  }
]

```

**Comment by Gadflyii** [comment]
Are you still having this issue?

**Comment by oliverw** [comment]
@Gadflyii There's a configuration option for coins exhibiting quirks like this: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/Configuration/BitcoinPoolPaymentProcessingConfigExtra.cs#L33

**Comment by bitspill** [comment]
Old issue but I just found it on a search and wanted to point out the origin of this quirk.

Some coins such as Verge have changed the amount of Satoshi per COIN which then causes later unit conversions to be off by some multiple of 10

Bitcoin uses 1e8 Satoshi/Coin
Verge uses 1e6 Satoshi/Coin

https://github.com/bitcoin/bitcoin/blob/fa84723/src/amount.h#L14
https://github.com/MetacoSA/NBitcoin/blob/b10b978/NBitcoin/Money.cs#L63
https://github.com/vergecurrency/VERGE/blob/6a75a11/src/util.h

**Comment by oliverw** [comment]
Very interesting.

**Comment by oliverw** [comment]
Fortunately this poses no longer a problem as newer versions of Miningcore read back the correct block-reward from the Coinbase Tx during the block-unlocking phase.
