### ISSUE TITLE
50% of XVG blocks orphaned!

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#234]
We have deployed the latest release of MC and launch XVG-Scrypt and XVG-lyra. More than 50 blocks are mined and nearly half of them got orphaned. This case is even more serious in XVG-lyra. Is there any problem so that the blocks orphaned that much?

**Comment by oliverw** [comment]
This ain't a problem with Miningcore but a common problem with Verge. Make sure you are running the "Clearnet" branch of the Verge daemon.

**Comment by shwuhk** [comment]
@oliverw Do you mean this version? 
https://github.com/vergecurrency/VERGE/tree/4.0clearnet
One more thing, how did you know that we should use this version, I just want to make sure that I won't get it wrong next time. Thanks.

**Comment by oliverw** [comment]
https://github.com/vergecurrency/VERGE/issues/502

**Comment by shwuhk** [comment]
@oliverw Thanks.
I have switched to 4.0clearnet. However, after mining 10 blocks, I still got ~50% blocks orphaned. Tt seems doesn't help.

**Comment by oliverw** [comment]
Could it be that the latency of your network setup is quite high?

**Comment by shwuhk** [comment]
@oliverw It should not be. We have other daemons in the same machine and it doesn't have this problem. The should be some problem either on MC or XVG. Did you have the same problem with XVG or it just working fine?

**Comment by shwuhk** [comment]
@oliverw I find that only scrypt will have this problem. I run scrypt + blake2s. Block mined with blake2s has no problem but ~50% blocks mined with scrypt will be orphaned. I find that coinfoundry.org has this problem with scrypt too. Can you please have a look on that? Thanks.
