### ISSUE TITLE
about Payment processing failed Newtonsoft.Json

### ISSUE THREAD

**Issue by lucas556** [coinfoundry/miningcore#237]
Error in miningcore:
`[2018-02-08 09:46:28.5987] [E] [PayoutManager] [zec] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.`

After searching, this error belongs to Newtonsoft.Json did not get the data.
The error should be in DaemonRequests or DaemonResponses inside.

@oliverw @saltyminer 
Please check here:  https://stackoverflow.com/questions/17317227/reading-json-using-json-net
Do not know whether this advice can help.

**Comment by interbiznw** [comment]
Getting this same error

**Comment by oliverw** [comment]
The error appears to be intermittent and goes away after a retry. I fix is still needed. Working on that.

**Comment by lucas556** [comment]
Ths.@oliverw ，The testnet is this error,
Do not know if the mainnet will appear?

**Comment by oliverw** [comment]
@lucas556 Sorry, what?

**Comment by lucas556** [comment]
@oliverw This error will appear in the zcash testnet,There is no test in mainnet.

**Comment by interbiznw** [comment]
Getting this error on live BTCP Pool, Any Updates? @oliverw

**Comment by oliverw** [comment]
Fixed in master.
