### ISSUE TITLE
miningcore gitter 

### ISSUE THREAD

**Issue by lucas556** [coinfoundry/miningcore#241]
I created a miningcore gitter, we can discuss here.

https://gitter.im/lucas556/miningcore

Welcome everyone to discuss miningcore.

PS:Please use https://gitter.im/miningcore/Lobby, sorry.

**Comment by bitspill** [comment]
Isn't there already https://gitter.im/miningcore/Lobby ?

**Comment by lucas556** [comment]
oh.thank you
