### ISSUE TITLE
Coin Daemon and Wallet RPC for Monero

### ISSUE THREAD

**Issue by felipecastaneda** [coinfoundry/miningcore#242]
Regarding binding monerod and monero-wallet-rpc:

`$ monerod --data-dir <data-folder-path> --log-file /dev/null --non-interactive --rpc-bind-ip 127.0.0.1 --out-peers 32 --p2p-bind-ip 0.0.0.0 --p2p-bind-port 18080`

`$ monero-wallet-rpc --daemon-address 127.0.0.1:18081 --wallet-file=<wallet-file-path> --rpc-bind-port 18082 --rpc-bind-ip 127.0.0.1 --rpc-login <username>:<password> --log-level 1`

Can someone provide a way to do this on a Windows 10 system? I was able to map pool ports using Docker for Windows and they seem to be working right.

I am running a Monero Node in my Windows 10 system that I just finished syncing and it seems to be running fine. I think that the remaining obstacle that I need to cross is figuring out how to execute the above-mentioned code; can I use Docker? If so, what would be the command to do it? Can the commands be executed in Windows? If so, how?

**Comment by calvintam236** [comment]
I would not recommend using Windows for server purpose. It is not stable and secure as Linux.

**Comment by oliverw** [comment]
The folks at Stackoverflow might beg to differ: https://meta.stackexchange.com/a/10370/260947
