### ISSUE TITLE
Question: View amount of shares in API?

### ISSUE THREAD

**Issue by xlogicex** [coinfoundry/miningcore#243]
Is it possible to add opportunity to view shares found by miners (for example in 10 minutes interval) via API?

**Comment by oliverw** [comment]
@xlogicex What do you mean? The actual share records? The number of shares? The accumulated difficulty of the shares?

**Comment by xlogicex** [comment]
The number of shares
Thanks

**Comment by oliverw** [comment]
Not at the moment. The number of shares is a meaningless number anyway. You probably want the accumulated difficulty of all shares. This is were we run into performance problems for busier pools. The database query to get that information simply takes too much time at the moment.

**Comment by calvintam236** [comment]
Duplicate of #27
