### ISSUE TITLE
Pool Clustering

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#245]
Is there a way to set up a pool cluster to balance the server load? I tried creating two pools, one with the payment processing enabled (as the "master") and the other without (as the "slave" and I have them both connected to the same database sharing the same daemons.

However no data was sent to the database from the "slave" pool. I might have configured it incorrectly, but I wanted to see if this is the correct direction before pushing further.

**Comment by oliverw** [comment]
The setup we are using at coinfoundry is similar to what you describe, with a subtle difference. We are running four Miningcore instances that don't even have a database connection configured. Payment processing is turned off as well. These servers are using the shareRelay option to publish submitted shares over ZeroMQ:

```
"shareRelay": {
    "publishUrl": "tcp://0.0.0.0:6000"
}
```

Additionally there's one master pool instance that both a database connection and payment processing enabled. It collects shares from the edge servers using the externalStratum option for every pool:

```
{
    "id": "ltc1",
    "enabled": true,
    "coin": {
        "type": "LTC"
    },
    ....
    "enableInternalStratum": false,
    "externalStratums": [{
        "url": "tcp://pool-us-east:13042",
        "topic": "ltc1"
    },{
        "url": "tcp://pool-us-west:13042",
        "topic": "ltc1"
    }, {
        "url": "tcp://pool-eu:13042",
        "topic": "ltc1"
    },{
        "url": "tcp://pool-asia:13042",
        "topic": "ltc1"
    }],
    ...
}
```

**Comment by Gadflyii** [comment]
@ oliver If I were to turn this into a pair of example configs for the example config would they look like this?

SlaveConfig Example

>  {
> 
>     "logging": {
>         "level": "info",
>         "enableConsoleLog": true,
>         "enableConsoleColors": true,
>         "logFile": "",
>         "logBaseDirectory": "",
>         "perPoolLogFile": false
>     },
>     "banning": {
>         "manager": "integrated",
>         "banOnJunkReceive": true,
>         "banOnInvalidShares": false
>     },
>     "notifications": {
>         "enabled": true,
>         "email": {
>             "host": "smtp.example.com",
>             "port": 587,
>             "user": "user",
>             "password": "password",
>             "fromAddress": "info@yourpool.org",
>             "fromName": "support"
>         },
>         "admin": {
>             "enabled": false,
>             "emailAddress": "user@example.com",
>             "notifyBlockFound": true
>         }
>     },
>     "shareRelay": {
>     "publishUrl": "tcp://0.0.0.0:6000"
>      },
>     "paymentProcessing": {
>         "enabled": false,
>         "interval": 600,
>         "shareRecoveryFile": "recovered-shares.txt"
>     },
>     "pools": [{
>         "id": "ltc1",
>         "enabled": true,
>         "coin": {
>             "type": "LTC"
>         },
>         //Address of Payment Processor wallet
>         "address": "LNDA11u4HWzbJaBGiHDvs6SmA8M6avB3wH", 
>         "rewardRecipients": [{
>             "address": "LUWYwkz6DQLVeqJqHRtGjNhWUxBvBmE3SX",
>             "percentage": 1
>         }],
>         "blockRefreshInterval": 500,
>         "jobRebroadcastTimeout": 10,
>         "clientConnectionTimeout": 600,
>         "banning": {
>             "enabled": true,
>             "time": 600,
>             "invalidPercent": 50,
>             "checkThreshold": 50
>         },
>         "ports": {
>             "3042": {
>                 "listenAddress": "0.0.0.0",
>                 "difficulty": 1024,
>                 "name": "ASIC Mining",
>                 "varDiff": {
>                     "minDiff": 512,
>                     "targetTime": 15,
>                     "retargetTime": 90,
>                     "variancePercent": 30
>                 }
>             }
>         },
>         //Daemon used for block submits, does not own pool wallet used for payments
>         "daemons": [{
>             "host": "127.0.0.1", 
>             "port": 9332,
>             "user": "user",
>             "password": "password"
>         }],
>         "paymentProcessing": {
>             "enabled": false,
>             "minimumPayment": 0.5,
>             "payoutScheme": "PPLNS",
>             "payoutSchemeConfig": {
>                 "factor": 2.0
>             }
>         }
>     }
>     }]
> }
> 


And Master

>  {
> 
>     "logging": {
>         "level": "info",
>         "enableConsoleLog": true,
>         "enableConsoleColors": true,
>         "logFile": "",
>         "logBaseDirectory": "",
>         "perPoolLogFile": false
>     },
>     "banning": {
>         "manager": "integrated",
>         "banOnJunkReceive": true,
>         "banOnInvalidShares": false
>     },
>     "notifications": {
>         "enabled": true,
>         "email": {
>             "host": "smtp.example.com",
>             "port": 587,
>             "user": "user",
>             "password": "password",
>             "fromAddress": "info@yourpool.org",
>             "fromName": "support"
>         },
>         "admin": {
>             "enabled": false,
>             "emailAddress": "user@example.com",
>             "notifyBlockFound": true
>         }
>     },
>     "shareRelay": {
>     "publishUrl": "tcp://0.0.0.0:6000"
>      },
>     "paymentProcessing": {
>         "enabled": true,
>         "interval": 600,
>         "shareRecoveryFile": "recovered-shares.txt"
>     },
>     "pools": [{
>         "id": "ltc1",
>         "enabled": true,
>         "coin": {
>             "type": "LTC"
>         },
>         //Address of Payment Processor wallet
>         "address": "LNDA11u4HWzbJaBGiHDvs6SmA8M6avB3wH", 
>         "rewardRecipients": [{
>             "address": "LUWYwkz6DQLVeqJqHRtGjNhWUxBvBmE3SX",
>             "percentage": 1
>         }],
>         "blockRefreshInterval": 500,
>         "jobRebroadcastTimeout": 10,
>         "clientConnectionTimeout": 600,
>         "banning": {
>             "enabled": true,
>             "time": 600,
>             "invalidPercent": 50,
>             "checkThreshold": 50
>         },
>         "enableInternalStratum": false,
>          "externalStratums": [{
>        "url": "tcp://slaveaddress:6000",
>        "topic": "ltc1"
>         }],
>         "daemons": [{
>             "host": "127.0.0.1", //Daemon that host wallet used for payments
>             "port": 9332,
>             "user": "user",
>             "password": "password"
>         }],
>         "paymentProcessing": {
>             "enabled": true,
>             "minimumPayment": 0.5,
>             "payoutScheme": "PPLNS",
>             "payoutSchemeConfig": {
>                 "factor": 2.0
>             }
>         }
>     }
>     }]
> }
>
