### ISSUE TITLE
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#246]
I have been seeing a few of these which lead to a miningcore crash. 

> [2018-03-08 18:15:18.7410] [E] [Program] System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
> --- End of inner exception stack trace ---
> at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at MiningCore.DaemonInterface.DaemonClient.MapDaemonBatchResponse(Int32 i, Task1 x) in C:\miningcore-cp-master\src\MiningCore\DaemonInterface\DaemonClient.cs:line 402
> at MiningCore.DaemonInterface.DaemonClient.d__14.MoveNext() in C:\miningcore-cp-master\src\MiningCore\DaemonInterface\DaemonClient.cs:line 216
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at MiningCore.Blockchain.Bitcoin.BitcoinJobManager2.<UpdateNetworkStatsAsync>d__26.MoveNext() in C:\miningcore-cp-master\src\MiningCore\Blockchain\Bitcoin\BitcoinJobManager.cs:line 241 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MiningCore.Blockchain.Bitcoin.BitcoinJobManager2.d__60.MoveNext() in C:\miningcore-cp-master\src\MiningCore\Blockchain\Bitcoin\BitcoinJobManager.cs:line 795
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at MiningCore.Blockchain.JobManagerBase`1.d__18.MoveNext() in C:\miningcore-cp-master\src\MiningCore\Blockchain\JobManagerBase.cs:line 86
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

I saw issue#56 , which was closed but no solution.

**Comment by oliverw** [comment]
Is "hasLegacyDaemon" on by chance?

**Comment by Gadflyii** [comment]
hmm would that be in the config?

**Comment by oliverw** [comment]
Yes.

**Comment by Gadflyii** [comment]
Found the issue, it was in our environment, not an issue with mining core.

**Comment by mohdshine** [comment]
Hi Gadflyii , can you please inform wht was the environment issue?

**Comment by edtrade** [comment]
I have the same issue, @Gadflyii can you please tell us have you manage to fix this problem. thank you
@oliverw hasLegacyDaemon is true since i'm using peercoin
