### ISSUE TITLE
[question] cluster configuration guide

### ISSUE THREAD

**Issue by 21void** [coinfoundry/miningcore#249]
Hi, I would like to how is it possible for have following clustering setup mining core.

My current setup plan, 
slave : miningcore-site1, miningcore-site2, miningcore-site3
master : miningcore-master

Slave will be running stratum port only and relay all informations to master.
On master side, it will have the persistent db and handle payment.

Now what not so clear to me is, where should i put my wallet daemon?
Does it make sense to have a setup where only master talk with wallet RPC?

Illustration,

![image](https://user-images.githubusercontent.com/36566344/37190350-42202586-2394-11e8-86d6-9f3abae5d47c.png)

Thanks

**Comment by oliverw** [comment]
That's basically what coinfoundry.org is running.

**Comment by 21void** [comment]
How does miningcore handle communication between miner and stratum? ie "blocksubmit"
Does it goes into zmq and push to/pull from master? 
I havent dive deeply into the code yet. Just try to get some sense is this configuration fully supported or require some tweaking. The goal here is to hide the wallet from slave.

**Comment by oliverw** [comment]
@21void You could either go with one additional server for each location running the coin daemons or a master coin daemon server available to all three pool servers. Pool-Daemon communication is definitely not going through ZMQ which is exclusively used for streaming back processed shares to the master.

**Comment by 21void** [comment]
Thanks for the answer. 
Look like I have to implement somekind of RPC call filtering to protect the wallet.

**Comment by oliverw** [comment]
@21void You mean protect the wallet against a compromised pool site accessing the daemon?

**Comment by 21void** [comment]
Yes @oliverw , that is what I mean. From my understanding, once a pool is compromised, attacker can have full access to wallet via RPC call to daemon.

**Comment by oliverw** [comment]
@21void By the way, is this for http://pool.btcprivate.org?

**Comment by 21void** [comment]
@oliverw Nope. Actually, havent started mine. Currently still in research mode. Looking for solution that is not only robust but  secure as well. Been trying different stratums, so far miningcore is the simplest and easy to play with. 

@off topic, do we have any chatroom/slack for miningcore? Perhaps I can learn a thing or two there.

**Comment by bitspill** [comment]
@21void There's a Gitter that's not often used https://gitter.im/miningcore/Lobby
