### ISSUE TITLE
What is required to support the upcoming Monero fork to the V7 Algo?

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#257]
@oliverw 

Have you seen this? 

https://getmonero.org/2018/02/11/PoW-change-and-key-reuse.html

https://github.com/xmrig/xmrig/issues/434

http://xmr.noctism.com/

Have you started working on this? Want some help?

**Comment by oliverw** [comment]
@Gadflyii Not yet started but following the Monero Dev Blob. Required changes will most likely be in LibMultihash sub-project.

**Comment by rymdluo** [comment]
Would appreciate if support for the new the Monero Cryptonight V7 algo and previous versions will be easy to switch since many cryptonote coins exist and may either take time to adopt or not at all.

Something like (in CoinMetaData):
```
{ CoinType.XMR, (coin, alg)=> CryptonightMoneroV7 },
{ CoinType.ETN, (coin, alg)=> CryptonightMoneroV6 },
```

**Comment by oliverw** [comment]
Don't worry. I'm planning to implement it exactly like that.

**Comment by Gadflyii** [comment]
Want some help @oliverw  ?

**Comment by oliverw** [comment]
@Gadflyii Absolutely. Just make sure that backwards compatibility is ensured.

**Comment by Gadflyii** [comment]
@oliverw  I saw you added v7 in release 21,  Is there anything else to be done?
