### ISSUE TITLE
Question: Multiple Servers & Multiple Daemons Best Practices

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#261]
@oliverw 

What is the best practice for running multiple MiningCore Servers with multiple Daemon Servers? Can you explain "relay mode" without persistence and how that works in release 20?

I do not believe it is possible to have say, 3 daemons, and specify in the config that only one of them is to be used for payment processing? (BTW, thanks for turning off wallet ownership checks for non-payment processing servers :)))))))))) )

**Comment by oliverw** [comment]
@Gadflyii I've explained it here: https://github.com/coinfoundry/miningcore/issues/245

**Comment by Gadflyii** [comment]
Great, I will build this out in dev, try it out
