### ISSUE TITLE
Miner stats not removed upon disconnection

### ISSUE THREAD

**Issue by dangerm0us** [coinfoundry/miningcore#262]
### Description

When a miner disconnects, the pool still sees an active miner and active hashrate.  This *may* only be applicable to testing with a single miner.

### Steps to Reproduce

1. Connect the very first miner to the pool and observe correct values are shown for hashrate etc
2. Disconnect the miner
3. Observe the value for 'hashrate' which remains constant even though the miner has disconnected, and also 'Miners' is still set to '1' returned from the API
4. Check psql, and observe the values in the DB indicate the miner is still connected

### Expected behavior

'Miners' drops to '0' (zero) and the hashrate also drops to '0' H/s

### Actual behavior

Pool thinks miner is still connected and sending hashes.  DB and API return data for 'ghost' miner.

### Reproduces how often

100% (for me)

### Version

Latest miningcore as at 12th March 2018 from master

### Additional Information

I have only tested with one single miner (single wallet, single worker) connecting and disconnecting.

**Comment by oliverw** [comment]
Known bug in the StatsRecorder that needs to be fixed.

**Comment by dangerm0us** [comment]
Thanks for clarifying Oliver!

**Comment by eketubol** [comment]
Hello, I am still receiving this bug. Has this been fixed?
