### ISSUE TITLE
Question: "Mined by" on insight based explorers.

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#263]
Insight based explorers (which are commonly used on my coins) have a "Mined by" field in which a pool can send a Hex based value to identify which pool mined the block. 

In NOMP/uNOMP/zNOMP and other node.js based pools the value is added in transactions.js , in the generate new transactions section, it looks like this:

>     tx.addInput(new Buffer('0000000000000000000000000000000000000000000000000000000000000000', 'hex'),
>         4294967295,
>         4294967295,
>         new Buffer.concat([serializedBlockHeight,
>             Buffer('5a2d4e4f4d50212068747470733a2f2f6769746875622e636f6d2f6a6f7368756179616275742f7a2d6e6f6d70', 'hex')]) //Z-NOMP! https://github.com/joshuayabut/z-nomp
>     );
> 

If this buffer exists in MiningCore, and I just missed it, I am sorry; I if not where would the best place be to add this buffer? Script GenerateScriptSigInitial() ?

**Comment by bitspill** [comment]
I believe you could add that to `GenerateScriptSigInitial` if you do

```
        protected virtual Script GenerateScriptSigInitial()
        {
            var now = ((DateTimeOffset) clock.Now).ToUnixTimeSeconds();

            // script ops
            var ops = new List<Op>();

            // push block height
            ops.Add(Op.GetPushOp(BlockTemplate.Height));

            // optionally push aux-flags
            if (!string.IsNullOrEmpty(BlockTemplate.CoinbaseAux?.Flags))
                ops.Add(Op.GetPushOp(BlockTemplate.CoinbaseAux.Flags.HexToByteArray()));

            // push timestamp
            ops.Add(Op.GetPushOp(now));
            
            // push pool name
            ops.Add(Op.GetPushOp(Encoding.ASCII.GetBytes("MyPoolName")));

            return new Script(ops);
        }
```

**Comment by Gadflyii** [comment]
hmmm... I will setup an insite explorer real quick test it

**Comment by Gadflyii** [comment]
guess I could just push the hex string as ASCII and let the explorer figure it out.

**Comment by oliverw** [comment]
@Gadflyii We already have a ClusterName property in the ClusterConfig. Id's suggest to use this with @bitspill's suggestions and bundle it up in a PR.
