### ISSUE TITLE
Mining BTC based coin donation error issue

### ISSUE THREAD

**Issue by jaschadub** [coinfoundry/miningcore#264]
### Description

We have a BTC based coin we are test mining and get error:
`[2018-03-13 23:46:40.1072] [E] [<coin>1] [Bitcoin Payout Handler] sendmany returned error: Invalid coin address: 17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm code -5 `

We tried adding `devDonation = 0.0` and a variation in json file with no luck. Seems to prevent us from sending any payouts.

**Comment by oliverw** [comment]
Are you trying to use a BTC derived coin as Bitcoin?

**Comment by jaschadub** [comment]
Yes, it is basically the same.

**Comment by oliverw** [comment]
Basically is not the same. Using a derived coin with the symbol name of another is not supposed to be working.
