### ISSUE TITLE
Verge block rejections

### ISSUE THREAD

**Issue by oliverw** [coinfoundry/miningcore#265]
Currently there's 40% rejection rate for Verge blocks (briefly tested on our 30 TH production pool). I'm currently clueless as to why this happens. I suspect a problem due to Verge's hybrid PoW/PoS nature. 

Another open [source implementation](https://github.com/zone117x/node-stratum-pool) does **not** suffer from this problem.

Tracking: https://github.com/vergecurrency/VERGE/issues/641

**Comment by justinvforvendetta** [comment]
we aren't based on digibyte though. multi algo but still different

**Comment by oliverw** [comment]
@justinvforvendetta Digibyte, was a typo. I'm solely talking about verge here. Sorry for the confusion.

**Comment by justinvforvendetta** [comment]
well pos is completely disabled but ntime is still in the block header

**Comment by oliverw** [comment]
@justinvforvendetta But if nTime is the only difference to a regular PoW coin why is node-stratum-pool jumping through so many hoops:

- https://github.com/zone117x/node-stratum-pool/blob/f2c90d45822562aaa9e418c9069a70aaa2b88005/lib/blockTemplate.js#L113
- https://github.com/zone117x/node-stratum-pool/blob/f2c90d45822562aaa9e418c9069a70aaa2b88005/lib/pool.js#L416
- https://github.com/zone117x/node-stratum-pool/blob/0cd4fcbc0e0c5cf5f65ba767f32645f42b38d0ca/lib/transactions.js#L190

**Comment by justinvforvendetta** [comment]
can you paste some specific errors? also, are you mining thru tor or clearnet? it's been a few years since I've ran a pool, but it should mine no differently than any other pow coin

**Comment by oliverw** [comment]
Here's a rejection:

> ThreadRPCServer method=submitblock
> InvalidChainFound: invalid block=038462545a8fc302b1e3  height=1950681  trust=1950682  date=03/13/18 16:56:57
> InvalidChainFound:  current best=00000000000005365e3f  height=1950680  trust=1950681  date=03/13/18 16:55:50
> ERROR: SetBestChain() : SetBestChainInner failed
> ERROR: AcceptBlock() : AddToBlockIndex failed
> ERROR: ProcessBlock() : AcceptBlock FAILED

What's even more baffling is that the pool successfully submitted 5 blocks before the rejections started.

**Comment by justinvforvendetta** [comment]
using clearnet or tor daemon?

**Comment by oliverw** [comment]
@justinvforvendetta Sorry forgot to answer that:

> On branch 4.0clearnet
> Your branch is up-to-date with 'origin/4.0clearnet'.
>

**Comment by oliverw** [comment]
@justinvforvendetta Do you suspect that it was just bad luck instead of a bug considering where the rejection happened?

**Comment by justinvforvendetta** [comment]
ok yes I suspect bad luck because on occassion I check pools and haven't seen anything like that

**Comment by oliverw** [comment]
Hmm, but 5 times in a row? Weird.

**Comment by justinvforvendetta** [comment]
well since we are multi algo we do have checks, like one algo can't find more than x number of blocks in a row, difficulty retargeting etc..

to clarify, they were rejected, or orphaned?

**Comment by oliverw** [comment]
@justinvforvendetta Rejected, please see the log snippet above.

**Comment by oliverw** [comment]
@justinvforvendetta Any ideas on the rejections?

**Comment by justinvforvendetta** [comment]
@oliverw why not reach out to another yiimp admin?

**Comment by oliverw** [comment]
@justinvforvendetta Already did.

**Comment by justinvforvendetta** [comment]
what did they say? since they aren't getting any rejections, maybe the configured something differently?

**Comment by Gadflyii** [comment]
@oliverw I can spin up a Verge pool this weekend and see if we get similar results.

**Comment by oliverw** [comment]
@Gadflyii Cool, please post your results.

**Comment by Gadflyii** [comment]
@oliverw  What algo are you using? Where do I set the algo for XVG?

**Comment by oliverw** [comment]
@Gadflyii The rejections happened with blake2s. You can set the algo directly below the cointype:

```
"coin": {
    "type": "XVG",
    "algorithm": "blake"
},

```

**Comment by Gadflyii** [comment]
Cool, getting closer, now I get:

"[Verge] [Bitcoin Job Manager] Waiting for daemons to connect to peers ..."

Not sure why, IP is right, Daemon is up and synced, has lots of connections,

**Comment by oliverw** [comment]
Verge needs: "hasLegacyDaemon": true in the pool config element.

**Comment by Gadflyii** [comment]
like so?

"        "id": "Verge",
        "enabled": true,
        "coin": {
			"type": "XVG",
			"Algorithm": "lyra"
        },
		"hasLegacyDaemon": true,

**Comment by oliverw** [comment]
Yes.

**Comment by Gadflyii** [comment]
[2018-03-26 06:07:17.3123] [E] [Verge] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnectedLegacyAsync>d__30.MoveNext() in C:\Users\gadfl\Desktop\miningcore-0.21\src\MiningCore\Blockchain\Bitcoin\BitcoinJobManager.cs:line 337

**Comment by oliverw** [comment]
Master branch?

**Comment by Gadflyii** [comment]
Yes, release 21

**Comment by oliverw** [comment]
Investigating.

**Comment by Gadflyii** [comment]
NP, Just want to help, I will be online for a few hours, I am on discord if you want to chat.

**Comment by Gadflyii** [comment]
You want the full stack trace?

**Comment by bitspill** [comment]
possibly related? https://bitcointalk.org/index.php?topic=3256693.0

**Comment by justinvforvendetta** [comment]
@bitspill that isn't related, but we just pushed a quick fix for it. 

he should contact other yiimp pool admins, since they have no issues like this. maybe @tpruvot can lend a hand

**Comment by oliverw** [comment]
@justinvforvendetta We aren't running yiimp and I agree this is not related to the rejections we've seen. Just updated our daemons with the timewarp fix. Our verge-pool looks pretty grim after todays massacre. 

https://coinfoundry.org/pool/xvg2 ("Blocks" tab)

**Comment by oliverw** [comment]
I will give this another shot with the new verge-codebase.
