### ISSUE TITLE
Payment metod

### ISSUE THREAD

**Issue by dmshel** [coinfoundry/miningcore#266]
Only PPLNS only support?

**Comment by oliverw** [comment]
Yes.

**Comment by dmshel** [comment]
Other methods to implement possible?

**Comment by oliverw** [comment]
Yes the architecture is modular: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Payments/Abstractions.cs#L40

**Comment by dmshel** [comment]
@oliverw Can i get some guide how i can change payment metod? or mb u have ready project?
