### ISSUE TITLE
Blocks source attribute (API and DB) is empty

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#267]
### Description

```source``` in blocks api is empty, the corresponding database similarly shows no value. Other data columns are correctly filled.

### Steps to Reproduce

1. Database migration from 0.19 to 0.20

### Reproduces how often

100% of the time

### Version

Release 0.20 w/ db migration steps. Coming from release 0.19 on Ubuntu 16.04

**Comment by oliverw** [comment]
Block source is only used for clustering scenarios where the value is supposed to contain of the geographic peer receiving and validating a share. When that share results in a block, the block's source property will reflect the originating share's source property. If you want that value to be filled, configure the "clusterName" property of the main config.
