### ISSUE TITLE
DB error: column "source" of relation "shares" does not exist

### ISSUE THREAD

**Issue by Heraisu** [coinfoundry/miningcore#272]
### Description

Tried pool with Vertcoin. Worked fine. Now I set up a Litecoin testnet.  Every time a share is submitted by a worker, the pool prints the following warning:

> [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "source" of relation "shares" does not exist)

After several retries, it prints

> [ShareRecorder] Fallback due to Npgsql: PostgresException (42703: column "source" of relation "shares" does not exist)

After which it seems to wait about 60 seconds before starting to throw the same warning again.
Very strange that it only started with the LTC pool... please let me know what other information I can supply, or if this is a known issue / acceptable behavior.

I did upgrade to the head build recently. (Master after Dev#271 was committed).

**Comment by Heraisu** [comment]
It is dumping data into the recovered-shares.txt file, instead of the DB. Did I get a sudden DB corruption that it cannot recover from somehow?  Was there a breaking change to the DB interface recently in the master branch? 
If this was a "real" run, what's would be  the path forward with the recovered shares file?
Thanks.

**Comment by Heraisu** [comment]
I created the column described (manually) and it seems to have cleared out the errors for now... although all the data inserts are simply putting "null" for the value in "source" anyways...
Am I now supposed to convert "recovered shares" into a query to add back into the database?

**Comment by calvintam236** [comment]
Please state the version / commit you installed..

**Comment by oliverw** [comment]
@Heraisu The "source" column is mainly used for clustering setups where the value corresponds to a geographical region or datacenter.
