### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by swanseahost** [coinfoundry/miningcore#277]
Hi there,

I would love to create a multi pool myself.  I have seen the guides and I can setup node and nomp for cryptonight currencies but this looks so much better.

Would someone mind helping me out set this up ? 

Will to make a donation.

Thanks

**Comment by DeaVulTan** [comment]
Hi, i can help you to create your own pool with web interface
Email: deavultan@gmail.com
Telegram: DeaVulTan
Skype: deavultan

**Comment by oliverw** [comment]
Again, this is an issue tracker, not a messagboard.
