### ISSUE TITLE
BTCP Network Difficulty reported as about double

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#279]
### Description

BTCP Network Diff reported by API to be about double correct value

### Steps to Reproduce

Create BTCP Pool, check API

### Expected behavior

BTCP network diff to match network diff reported by daemons

### Actual behavior

API reports double that of the daemon

### Reproduces how often

100%

### Version

Release 20
Windows Server 2016 Datacenter
Latest release of BTCP Daemon

### Additional Information

API output BTCP Pool:

> 
>  {
>   "pool": {
>     "id": "BitcoinPrivate",
>     "coin": {
>       "type": "BTCP",
>       "algorithm": "Equihash"
>     },
>     "ports": {},
>     "paymentProcessing": {
>       "enabled": true,
>       "minimumPayment": 0.01,
>       "payoutScheme": "PPLNS",
>       "payoutSchemeConfig": {
>         "factor": 1.0
>       }
>     },
>     "clientConnectionTimeout": 600,
>     "jobRebroadcastTimeout": 10,
>     "blockRefreshInterval": 500,
>     "poolFeePercent": 0.5,
>     "address": "bxxxx",
>     "poolStats": {
>       "connectedMiners": 1,
>       "poolHashrate": 5912,
>       "validSharesPerSecond": 0
>     },
>     "networkStats": {
>       "networkHashrate": 11602926.0,
>       **"networkDifficulty": 53850773.360238023,**
>       "lastNetworkBlockTime": "2018-03-22T08:26:59.256113",
>       "blockHeight": 290063,
>       "connectedPeers": 8
> 
> 

Daemon output:

> {
>   "version": 1001051,
>   "protocolversion": 180003,
>   "walletversion": 60000,
>   "balance": 0.00000000,
>   "blocks": 290063,
>   "timeoffset": 0,
>   "connections": 8,
>   "proxy": "",
>   **"difficulty": 219797.8098820399,**
>   "testnet": false,
>   "keypoololdest": 1519150400,
>   "keypoolsize": 11,
>   "paytxfee": 0.00000000,
>   "relayfee": 0.00000100,
>   "errors": ""
> }
>

**Comment by oliverw** [comment]
Reason is this: https://github.com/BTCPrivate/BitcoinPrivate/pull/131

Working as intended. The pool's calculation exposed by the API is the correct one.
