### ISSUE TITLE
MPOS compatibility mode support

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#28]
It's better to support MPOS compatibility mode so that it can function as a drop-in-replacement for python-stratum-mining. And we can have a good front end for usage while this project have no website provided at this moment.

**Comment by shtse8** [comment]
https://github.com/zone117x/node-open-mining-portal/blob/master/libs/mposCompatibility.js

**Comment by oliverw** [comment]
Going to work on this soon unless somebody else wants to do it.

**Comment by oliverw** [comment]
Not going to happen sorry.

**Comment by shtse8** [comment]
Yes, I don't think we need it too.
