### ISSUE TITLE
Setup Questions

### ISSUE THREAD

**Issue by swanseahost** [coinfoundry/miningcore#280]
Hi there,

Does this have an admin are like nodejs-poolui ?

Would someone be willing to be help me ? I got started here

195.201.158.190

Thanks
Steve

**Comment by oliverw** [comment]
Sorry but this is our issue tracker, not a message board.

**Comment by calvintam236** [comment]
Take a look at [miningcore-ui](https://github.com/calvintam236/miningcore-ui)
