### ISSUE TITLE
[GLT1] [Bitcoin Job Manager] Daemon does not own pool-address 

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#284]
Dears

After Globaltoken has been update its wallet to 2.1.0 version it uses a GetAddressInfo() to validate a pool address IsMine result. so I want to know where I can add these command

**The following error and Bitcoin Job Manager haltdown due to IsMine result is false.** 
[2018-03-25 02:51:54.8119] [E] [GLT1] [Bitcoin Job Manager] Daemon does not own pool-address 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

Regards.
John Ahn

**Comment by jeong760** [comment]
Dears.

Validateaddress will deprecated soon from on v0.17.0 of bitcoin wallet. so I think Globaltoken developer has been updated a new branch. 

**￼getaddressinfo** xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
￼
{
  "address": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "scriptPubKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  **"ismine": true,**
  "iswatchonly": false,
  "isscript": false,
  "iswitness": false,
  "pubkey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "iscompressed": true,
  "account": "Pool_OP",
  "timestamp": 1501847644,
  "hdkeypath": "m/0'/0'/0'",
  "hdmasterkeyid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

**validateaddress** xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{
  "isvalid": true,
  "address": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "scriptPubKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "isscript": false,
  "iswitness": false
}

Regards,
John Ahn

**Comment by oliverw** [comment]
@jeong760 I hope to implement support for getaddressinfo for one of the coming releases. Meanwhile you could change the implementation here if this is urgent: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs#L619

**Comment by jeong760** [comment]
@oliverw I found it but how miningcore recognize a getaddressinfo() command for GLT wallet. I mean there is no separate constant like a if (Coinname == GLT) etc?

**Comment by oliverw** [comment]
@jeong760 Yes, a clean solution will require some additional "magic" for coins that require the use of getaddressinfo instead of validateaddress.

**Comment by jeong760** [comment]
@oliverw  Could you look up this? if I added then it return to IsMine result. or if you have any idea could you guide me how to?


**- Create a GetAddressinfoReponse.cs**
 namespace MiningCore.Blockchain.Bitcoin.DaemonResponses
{
    class GetAddressinfoResponse
    {
        public string Address { get; set; }
        public string ScriptPubKey { get; set; }
        public bool IsMine { get; set; }
        public bool Iswatchonly { get; set; }
        public bool IsScript { get; set; }
        public bool IsWittness { get; set; }
        public List<string> Addresses { get; set; }
        public int SigsRequired { get; set; }
        public string Account { get; set; }
        public string PubKey { get; set; }
    }
}

- BitcoinConstants.cs
public const string GetAddressinfo = "getaddressinfo";

- BitcoinManager.cs

        public virtual async Task<bool> ValidateAddressAsync(string address)
        {
            Contract.Requires<ArgumentException>(!string.IsNullOrEmpty(address), $"{nameof(address)} must not be empty");

            var result = await daemon.ExecuteCmdAnyAsync<ValidateAddressResponse>(
                BitcoinCommands.ValidateAddress, new[] { address });

            await GetAddressinfo(address);

            return result.Response != null && result.Response.IsValid;
        }

        private async Task GetAddressinfo(string address)
        {
            var resultnew = await daemon.ExecuteCmdAnyAsync<GetAddressinfoResponse>(
                BitcoinCommands.GetAddressinfo, new[] { address });
        }

Regards,
John Ahn

**Comment by jeong760** [comment]
@oliverw  the above code change is generate desalinizing problem when Minincore try to  initialize a pool. 
Also in pool configuration, what about maximum support  able coins? Because I was configured a 5 of different coin in one pool.josn but only one pool  can initializing and works.  Also each coin pools are  necessary their own  database?

Regards,
John Ahn

**Comment by stalizard** [comment]
Have same issue with latest digibyte wallet.  Has there been a work around yet?
Thanks
Alan

**Comment by oliverw** [comment]
Fixed a long time ago.
