### ISSUE TITLE
Where are transaction fees taken from?

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#291]
Are the transaction fees taken from the pool fee? If so, how do we ensure that the pool doesn't run at a deficit besides increasing pool percentage?

It seems that even running at 0.5% on a new coin might be unprofitable.

If the pool fee is 0.5%, and the block reward is 25, it seems that it would only take 3 payments to exhaust the pool fee "profits" if the transaction fee is 0.059 (taken from my example).
```
25 / 100 * 0.5 = 0.125
```

**Comment by oliverw** [comment]
That's why you can configure the payment processor to distribute the transaction fees over the payment recipients (at pool level):

```
"paymentProcessing": {
    "minersPayTxFees": true,
}

```

**Comment by rymdluo** [comment]
Thanks, was not able to find documentation for this anywhere. (And I clearly missed this when looking into the code)
