### ISSUE TITLE
Support for Cryptonight Heavy

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#298]
Many alt-coins are adopting the Cryptonight Heavy algorithm instead of Monero v7, among others are Sumokoin and Haven. Hope that you would include this too since it seems to be a simple task (according to the author), but not in my field.

Ref: https://github.com/curie-kief/cryptonote-heavy-design

**Comment by oliverw** [comment]
Thanks for the info. Hard to keep track on everyhing going on in Crypto. Will have a look.

**Comment by rymdluo** [comment]
No worries, I'm uncertain if you are informed on Aeon's POW changes- I'll leave this here for your review as well.

> Last but not least, the same POW change (variant 1) from Monero is applied to Aeon's CryptoNight-Lite.
> To ease the adoption (particularly for 3rd-party miners and pools), it's decided to bump the fork version from v1 to v7 at once (instead of v2 as usual).

Ref: https://github.com/aeonix/aeon-rebase/pull/4#issuecomment-374611047

**Comment by oliverw** [comment]
Impelemented in master.
