### ISSUE TITLE
Web front-end progress/ code

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#3]
I saw your comment on reddit saying that the web front-end is in the works. Can you tell us how's the progress? If there are some codes, can you push the incomplete code to GitHub in a different branch (so anyone can help)? If not, I can try to port other UI e.g. `poolui`?

**Comment by oliverw** [comment]
The web-frontend is not yet ready to be checked in for public consumption. Giving porting poolui a shot would be actually great idea since it's quite popular and would ease the transition for operators who have already experience with that frontend.

**Comment by mario1987** [comment]
Is there any update on the web-frontend? 
The frontend on https://poolmining.org/ looks nice it this the one that will be used for this pool software?

**Comment by calvintam236** [comment]
I am working on it. Check https://github.com/calvintam236/miningcore-ui/issues/2 for updates.

**Comment by calvintam236** [comment]
@oliverw if you add the header globally, all of the API methods can be called externally. you said don't open API to internet, so how you want us to use it?

to protect some API methods, add basic auth/IP whitelist?

**Comment by oliverw** [comment]
@calvintam236 I added the headers so your web-frontend may call the API even if hosted on a totally different domain/host than the pool server. This is the only recommended use-case for the Pool's API interface. If you really need to expose the API from your web-frontend it should be done by just proxying a subset through your web-layer. poolmining.org does something like that for the Monero Pool: https://poolmining.org/api/cryptonote-pool/xmr/stats

**Comment by rterbush** [comment]
In case it is helpful to someone, I've done the following with nginx which allows me to secure the api with it's own hostname using SSL. Example shows I was adding the CORS header to work around the issue. Any number of other auth methods could be applied using this same approach so that @oliverw is not wasting his time recreating the wheel. :-)

```
server {
        listen 80;
        server_name api.example.com;

        location / {
            rewrite ^(.*)$  https://$host/$1 permanent;
        }
    }

    server {
        listen 443 ssl http2;
        server_name api.example.com;

        ssl_certificate /path/to/cert.pem;
        ssl_certificate_key /path/to/key.pem;
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://localhost:4000/api/;
            add_header Access-Control-Allow-Origin *;
        }
}
```

**Comment by calvintam236** [comment]
@oliverw API auth reference: http://blog.restcase.com/restful-api-authentication-basics/
i would suggest to use same username/password on the server to simplify user control.

alternatively, split public access and security critical APIs on two ports, which we only need to open the public port?

**Comment by mikeghen** [comment]
Solid frontend, thanks

**Comment by minernl** [comment]
I have made myself a simple frontend for my site 
http://eth.coinstomine.eu 
http://xmr.coinstomine.eu

https://github.com/minernl/miningcore/tree/MiningCore.Web/src/MiningCore.Web
Needs some improvements but it runs nice for now

**Comment by xborow** [comment]
@minernl can you please write some steps how to get it working?
I have downloaded the folder MiningCore.Web, moved it to /var/www folder, running apach2 server, but webpage is not getting info from the pool, even it looks not so nice like yours, there is no collors etc..
Running ubuntu 16.04
I would really approciate some steps, to get it fully working, dependencies and so on..

Thanks a lot

**Comment by seperatis** [comment]
Is anyone "officially" working on front-end development?

I've started a GoFundMe to speed along development for anyone interested. I've seen a lot of people asking for a front-end, let's get it done!

https://www.gofundme.com/miningcore-frontend-ui-development

I'm currently working with a front-end dev to make a simple front-end for my own personal needs, but I'd love to build on top of that and get a **stunning**, **feature-rich** web front-end banged out to the caliber that it can be added to the MiningCore repo for everyone to use.

**Comment by oliverw** [comment]
Closing as this is not really an issue with the project itself.

**Comment by minernl** [comment]
my new webUI is at
https://github.com/minernl/Miningcore.WebUI
