### ISSUE TITLE
[xmr] [Pool] Share rejected: bad hash

### ISSUE THREAD

**Issue by ffrouin** [coinfoundry/miningcore#305]
### Description

mining core complains for 'bad hash' on Monero pool while miners have not changed (it worked before I recompile miningcore with latest available sources).

### Steps to Reproduce

1. using this miner : https://github.com/tpruvot/cpuminer-multi
2. wait for share results to be submitted to monero pool
3. see miningcore result : should reject 100% of share submit because of 'bad hash' error.

### Expected behavior

my shares to be accepted while they are all refused now because of "bad hash" error.

### Actual behavior

shares rejected because of 'bad hash'

### Reproduces how often

100%

### Version

 cat .git/refs/heads/master
 a057083bdea6d8e44d515ba22609933865e3d695

Running inside a docker container based on Ubuntu 16.04.

### Additional Information

xmr pool is configured using the template included with miningcore sources.

**Comment by oliverw** [comment]
That miner has not been updated for the Monero v7 hardfork. Please tell your miners to upgrade to a v7 compatible miner such as XMRig or XMR-Stak.
