### ISSUE TITLE
Proxy protocol for Mining Core

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#306]
I've been trying to wedge haproxy without losing miningcore's banning functionality but to no avail. I tried send-proxy and send-proxy-v2 versions which was alluded to in the Wiki/Configuration, but that results in an error.

> If running behind something like HAProxy be sure to enable 'tcpProxyProtocol', otherwise you'll end up banning your own IP address (and therefore all workers).

**Comment by oliverw** [comment]
This is in our wiki? I didn't write that for sure. I'm not sure how this would ever work without haproxy being able to communicate the real IP to MC.

**Comment by rymdluo** [comment]
Yeah it's in there. I don't think it's possible either unless MC starts supporting proxy protocols or via transparent proxying. The latter being more of a workaround and not quite ideal.

- [Proxy Protocol](https://www.haproxy.com/blog/haproxy/proxy-protocol/)
- [Haproxy TProxy](https://www.haproxy.com/blog/howto-transparent-proxying-and-binding-with-haproxy-and-aloha-load-balancer/)
- [Transpareny Proxy via a proxy app](https://github.com/ryanchapman/go-any-proxy)

**Comment by oliverw** [comment]
Could you elaborate a bit on your specific use-case?

**Comment by bitspill** [comment]
As for where that appears in the wiki it's in the example configuration at https://github.com/coinfoundry/miningcore/wiki/Configuration and appears to have been copied over from the example configuration in the Readme of NOMP at https://github.com/zone117x/node-stratum-pool

NOMP has this extra configuration option which is what that statement refers to
```
     /* Enable for client IP addresses to be detected when using a load balancer with TCP proxy
       protocol enabled, such as HAProxy with 'send-proxy' param:
       http://haproxy.1wt.eu/download/1.5/doc/configuration.txt */
    "tcpProxyProtocol": false,
```

**Comment by rymdluo** [comment]
I use (or at least want to use) HAProxy to automatically switch slave (external stratum) MC servers that are down for maintenance (or are just down) to other servers. 

So far using HAProxy works, but it runs without MC's banning feature.

@bitspill thanks for pointing out the source.

**Comment by oliverw** [comment]
@bitspill @rymdluo I've cleaned up wiki page.

**Comment by rymdluo** [comment]
I just tried it out. I keep getting the ```Received spoofed Proxy-Protocol header``` message. This is the debug log. 

```
[2018-04-15 19:25:07.8798] [D] [monero-testnet] [Pool] Accepting connection [0HLD30Q6QV807] from ###.###.###.###:33856
[2018-04-15 19:25:07.8798] [E] [StratumClient] [0HLD30Q6QV807] Received spoofed Proxy-Protocol header from ###.###.###.###
[2018-04-15 19:25:07.8798] [D] [StratumClient] [0HLD30Q6QV807] Last subscriber disconnected from receiver stream
```

**Comment by oliverw** [comment]
@rymdluo Of course the first person to try it out would hit the shortcut I took with the implementation 😁 . Right now the proxy-header is only accepted when sent from localhost. I'm going to improve this tommorow.

**Comment by rymdluo** [comment]
@oliverw No worries, please hit me again when I can test it out!

**Comment by oliverw** [comment]
Pushed an update to dev. Updated configuration options:

```json
            "ports": {
                "4032": {
                    "difficulty": 1000,
                    "tcpProxyProtocol": {
                        "enable": true,
                        "mandatory": false,
                        "proxyAddresses": []
                    }
                }
            },
```

**Comment by rymdluo** [comment]
It appears to be working quite well, MC is able to expose the ip address of the miner through HAProxy. Great work!

There is a small bug I noticed though, the program seems to refuse to fully shut down now via CTRL-C. It takes a pid kill to do it.
```
^C
[2018-04-17 10:28:37.9765] [I] [Program] SIGINT received. Exiting.
SIGINT received. Exiting.
[2018-04-17 10:28:37.9778] [I] [Program] Shutdown ...
Shutdown...
[2018-04-17 10:28:37.9778] [I] [ShareRecorder] Stopping ..
[2018-04-17 10:28:37.9778] [I] [ShareRecorder] Stopped
[2018-04-17 10:28:37.9778] [I] [StatsRecorder] Stopping ..
[2018-04-17 10:28:37.9778] [I] [StatsRecorder] Stopped
[2018-04-17 10:28:39.5596] [I] [StratumClient] [0HLD49N47KLV0] Real-IP via Proxy-Protocol: ###.###.###.###
[2018-04-17 10:28:41.5604] [I] [StratumClient] [0HLD49N47KLV1] Real-IP via Proxy-Protocol: ###.###.###.###
```

**Comment by calvintam236** [comment]
@rymdluo looks like this is the same bug I filed at #260 .
