### ISSUE TITLE
Payout Scheme - PayPerShare / PPS

### ISSUE THREAD

**Issue by Heraisu** [coinfoundry/miningcore#318]
I searched the opened Issues, did not see PPS (although I swear I saw it in the past).

Much like #112, this is a request for an officially listed PPS system.  I understand this is a more risky system and requires an upfront pool as much as 10x the reward block size to guarantee payouts (depending on the  desired odds against a full failure).

Extra options could include not issuing new work packages if the current share payout allocations exceed the balance of the wallet account  (so if people are running a backup pool configuration, their miners can switch to that in the case of a PPS failure), this will also guarantee all work is paid for.

**Comment by mikeghen** [comment]
>Extra options could include not issuing new work packages if the current share payout allocations exceed the balance of the wallet account (so if people are running a backup pool configuration, their miners can switch to that in the case of a PPS failure), this will also guarantee all work is paid for.

Interesting suggestion

**Comment by oliverw** [comment]
PR is welcome as I don't have time for this in the forseeable future.
