### ISSUE TITLE
Wrong hashrate statistics on x16r

### ISSUE THREAD

**Issue by W944** [coinfoundry/miningcore#319]
### Description

Wrong hashrate statistics on x16r

### Steps to Reproduce

1. Connect miners to pool
2. Start mining
3. Watch the DB entries in minerstats

### Expected behavior

Hashrate should be something similar to the reported value in the miner.

### Actual behavior

Hashrate is about 3.5 - 4.0 times lower then the reporterd hashrate in the miner.
Ex: miner: 97.90, DB: 26285122.3782077 = 25.06

### Reproduces how often

100%

### Version

Dev version from 2018-04-18

### Additional Information

I searched this repo and for another coin it was suggested to just apply a multiplier to the DB values to make them more in line with that the miner reports. Is it the same case here?

// Update
No reported hashrate improvement after running a miner on it for almost 24h.
The API also reports the low hashrate, seems to be using the same values as the DB.

**Comment by W944** [comment]
No reported hashrate improvement after running a miner on it for almost 24h.
The API also reports the low hashrate, seems to be using the same values as the DB.

**Comment by oliverw** [comment]
Yes the API pulls the hashrate directly from the DB. I'll look into this tommorow.

**Comment by W944** [comment]
Looks like playing with the vardiff really did increase the hashrate in the long term.
Here's the hashrate with a 6h SMA: https://pasteboard.co/HhE6om8.gif

**Comment by Dradden** [comment]
I have noticed this as well on my RVN pool. Have been playing with settings to see if it helps, so far very little difference and reported has is pretty consistently 1/2 of what miner reports.

**Comment by W944** [comment]
I have tried the latest release 24 and this behavior persists.
Did anyone find a solution?
Thanks,

**Comment by structdjm** [comment]
@W944 what value are you using for jobRebroadcastTimeout

**Comment by W944** [comment]
Someone asked what value I used for jobRebroadcastTimeout in my conf.
I have this:

"jobRebroadcastTimeout": 10

**Comment by structdjm** [comment]
"jobRebroadcastTimeout": 10     im usnig 55, seems to be working better

**Comment by structdjm** [comment]
could somebody tell me if its ok to use static diff -p d=1024 on my rvn pool, its just myself solo mining basically, thanks

**Comment by akshaynexus** [comment]
This is still noticeable on x16rv2,used the same setting suggested here and seeing some improvements.
