### ISSUE TITLE
Configuration file for two-three coins

### ISSUE THREAD

**Issue by sfoxdev** [coinfoundry/miningcore#33]
Is there any example file of how to configure Miningcore for run several coins at one pool?
Also interested is there any posibility to connect Miningcore with MPOS or any other webui?

**Comment by oliverw** [comment]
> Is there any example file of how to configure Miningcore for run several coins at one pool?

https://github.com/coinfoundry/miningcore/blob/master/examples/litecoin_dash_pool.json

> Also interested is there any posibility to connect Miningcore with MPOS or any other webui?

Coming up with a reasonable webfront solution is one of the main tasks left to do. I originally wanted to support MPOS but the idea of pumping data in one database only to take it out and shovel it into another (MPOS-MySql) somehow feels weird.

**Comment by sfoxdev** [comment]
Great, thank you very much for multi-pool example.

I know that MPOS is not a great webui for pool at nowtime, but it's still most popular. Do you plan to develop front-end for Miningcore?

**Comment by oliverw** [comment]
It depends. If the community does contribute one, I'll probably do it myself. It's a matter of available time.

**Comment by sfoxdev** [comment]
I see. Thank you for great tool (pool).
