### ISSUE TITLE
NiceHash_extranonce_subscribe_extension

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#330]
I think you need to make changes
https://github.com/nicehash/Specifications/blob/master/NiceHash_extranonce_subscribe_extension.txt
https://github.com/ethereum-mining/ethminer/issues/1041

**Comment by oliverw** [comment]
Why do you think action is required?

**Comment by RapidMark** [comment]
Note: Difficulty must be between 1 and 100 (so set min and max), and also you will need to allow for a login name, not an address

I added this line

`if (minerName.Equals("robotpool"))
            minerName = "0x654c0228ee9c207c992d651380b5fe27e183ad6d";
`

in EthereumPool.cs (as below)


           // extract worker/miner
            var workerParts = workerValue?.Split('.');
            var minerName = workerParts?.Length > 0 ? workerParts[0].Trim() : null;
            var workerName = workerParts?.Length > 1 ? workerParts[1].Trim() : null;

            if (minerName.Equals("robotpool"))
                minerName = "0x654c0228ee9c207c992d651380b5fe27e183ad6d";

            // assumes that workerName is an address
            context.IsAuthorized = !string.IsNullOrEmpty(minerName) && manager.ValidateAddress(minerName);
            context.MinerName = minerName;
            context.WorkerName = workerName;



and then used that name to login (with x as the password)...

I got up to 300 Gh/s with no issues :)

**Comment by oliverw** [comment]
The problem was not related to the extranonce but due to an incompatibility discovered by @RapidMark that was fixed in Release 38.

**Comment by RapidMark** [comment]
I was going to add it to the config for each pool (since we'll need it for any pool we buy from), but I haven't gotten there yet.
