### ISSUE TITLE
1 Users ,even after he stopped mining

### ISSUE THREAD

**Issue by sennevb** [coinfoundry/miningcore#333]
![image](https://user-images.githubusercontent.com/6636264/39671935-b1ac6184-5121-11e8-872a-b539ca642435.png)

I am currently testing miningcore, all works fine, but when the miners stop mining , so 0 users, the hashrate displayed (also on api) , keeps showing latest hahsrate, also it displays 1 miner.

Any ideas how to fix?

**Comment by calvintam236** [comment]
I believe @oliverw said the API gives the data within last 10 minutes - not realtime.

**Comment by sennevb** [comment]
Even after a day the data is the same..

**Comment by pfeiflelukas** [comment]
I also get the same thing. Even after ~4 days the graph and stats still show that miner mining.

I am currently trying to work out why, but so far no luck.

**Comment by calvintam236** [comment]
Merging into #262.
