### ISSUE TITLE
Threeye Explorer No Longer Maintained

### ISSUE THREAD

**Issue by Dradden** [coinfoundry/miningcore#335]
Threeye block explorer for RVN is no longer maintained, and should be changed as the go to explorer for RVN in miningcore.

Alternative that is not Iquidus based: https://exp.virtopia.ca

API information: https://github.com/underdarkskies/insight-api

**Comment by be4i** [comment]
I would recommend https://ravencoin.network because its not affiliated with any pool.

**Comment by Dradden** [comment]
The fact that exp.virtopia is also used by the Virtopia pool is not a negative, it is a positive and makes it more likely that it will be kept online and up to date.

**Comment by be4i** [comment]
I don't see any reason for explorer to be more like kept online because its also a pool, pools are closed every day.Also i want the explorer to be maintained by the community not by some pool.And last but not least why would i want to redirect my users to another pool ?

**Comment by Dradden** [comment]
You are not redirecting your users to another pool. Explorers as well are even more frequently closed and worse left to go out of date which causes confusion for users.

My above point stands.

**Comment by calebcall** [comment]
I guess the winner on this one is clearly the one that was "more likely that it will be kept online and up to date" because it was a pool...oh wait, that's right, that one shut down but https://ravencoin.network is still online and current.

**Comment by oliverw** [comment]
Fixed in master.
