### ISSUE TITLE
Occasional json corruption on stratum receive

### ISSUE THREAD

**Issue by Dradden** [coinfoundry/miningcore#342]
### Description
 
Occasional JSON corruption on stratum receive
 
### Steps to Reproduce
 
Running the pool on x16r algo, couldn't reproduce solo but occurs on our pool of ~20 miners
 
### Expected behavior
 
Normal JSON, not occasionally corrupted JSON
 
### Actual behavior
 
Thee server console shows errors about invalid JSON from various handlers
 
### Reproduces how often
 
Every few minutes, and immediately after miners reconnect after a pool restart
 
### Version
 
Latest master branch at commit df1348e
 
### Additional Information
 
An example error is
 
> [2018-05-19 00:45:44.3500] [E] [RVNS] [Pool] [0HLDSNJ4LNTJF] Connection json error state: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
> [2018-05-19 00:45:44.3500] [E] [RVNS] [Pool] [0HLDSNJ4LNTJF] Received request data: 
> [2018-05-19 00:45:44.3500] [E] [RVNS] [Pool] [0HLDSNJ4LNTJF] Connection json error state: Unexpected character encountered while parsing value: �. Path '', line 0, position 0.
> [2018-05-19 00:45:44.3500] [E] [RVNS] [Pool] [0HLDSNJ4LNTJF] Received request data: �Z����
> [2018-05-19 00:45:44.3500] [E] [RVNS] [Pool] [0HLDSNJ4LNTJF] Connection json error state: Unexpected character encountered while parsing value: ߽. Path '', line 0, position 0.
> [2018-05-19 00:45:44.3500] [E] [RVNS] [Pool] [0HLDSNJ4LNTJF] Received request data: 
> �Z����
> ߽�߽�t", "params": ["redacted", "00001241", "00000000", "5aff73a6", "ddc
 
We ran WireShark to capture the exact packets which the server was receiving over the network and the data is 100% being received correctly as completely valid json, and it's being corrupted some point after that

**Comment by Dradden** [comment]
This has caused a larger problem now as we see more traffic. Shares after the json corruption issue pops up for a user are seen as low diff and ends up in a temporary ban.

Any ideas where this json issue might be coming from?

**Comment by W944** [comment]
I've also ran into this issue once with a single miner and have disabled the ban on invalid json feature.

**Comment by Dradden** [comment]
Unfortunately ours is not that easy to fix and disabling that option only partially fixes the issue.

**Comment by virtopiarvn** [comment]
This is an issue to be sure. We are actually considering swapping out for another stratum as I cannot find why this happens.

**Comment by oliverw** [comment]
I'm only seeing this for script kiddie connects on stratum ports. Otherwise no occurences of this problem with any of Coinfoundry's production pools using the latest releases. Please re-open if encountered again.
