### ISSUE TITLE
Raven Coin Json File

### ISSUE THREAD

**Issue by structdjm** [coinfoundry/miningcore#349]
cannot not find any examples online for rvn json.config settings

**Comment by Konstantin35** [comment]
Everything is described in detail here [Configuration](https://github.com/coinfoundry/miningcore/wiki/Configuration)

**Comment by structdjm** [comment]
Thank you for that Konstantin35, also does anyone know why the field data in networkdifficulty shares table does not reflect the actual network difficulty, the numbers in this field are much higher then they should, is there a multiplier I`am missing ?

**Comment by zhuk2303** [comment]
Why do you think that the field networkdifficulty does not reflect the actual network difficulty. With what do you compare? What cryptocurrency do you use?

**Comment by structdjm** [comment]
@zhuk2303 im using rvn, and the field doesn't match up with rvn's actual network diff, but like @arubinofaux suggested it probably does if you know the formula

**Comment by structdjm** [comment]
does anyone know the best setting for jobRebroadcastTimeout on rvn, if i set to low i get stale jobs, to high and no new block work

**Comment by structdjm** [comment]
this is my json file any advise would be very appreciated, keep in mine its just me solo mining on the pool:
 {
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "192.168.1.101",
            "port": 5432,
            "user": "miningcore",
            "password": "Master",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": false,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "RVN",
        "enabled": true,
        "coin": {
            "type": "RVN"
        },
        "address": "RJt2mcAGMFWh3cJmuKzFLvAnEcQRWkH5TZ",
        "rewardRecipients": [{
            "address": "RJt2mcAGMFWh3cJmuKzFLvAnEcQRWkH5TZ",
            "percentage": 0
        }],
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 0,
        "clientConnectionTimeout": 0,
        "banning": {
            "enabled": false,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3332": {
                "listenAddress": "192.168.1.101",
                "difficulty": 16,
                "name": "SOLO Mining",
                "varDiff": {
                    "minDiff": 1,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30,

                }
            }
        },
        "daemons": [{
            "host": "192.168.1.101",
            "port": 3333,
            "user": "struct",
            "password": "pass123",
	    "zmqBlockNotifySocket": "tcp://192.168.1.101:8767",
      }
    ],

    "paymentProcessing": {
      "enabled": true,
      "minimumPayment": 0.01,
      "payoutScheme": "PPLNS",
      "payoutSchemeConfig": {
        "factor": 2.0
      }
    }
  }]
}

**Comment by structdjm** [comment]
This is my json file for rvn and advise would be greatly appreciated, keep in mind that its just me solo mining on the pool
 {
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "192.168.1.101",
            "port": 5432,
            "user": "miningcore",
            "password": "MasterYeKs79",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": false,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "RVN",
        "enabled": true,
        "coin": {
            "type": "RVN"
        },
        "address": "RJt2mcAGMFWh3cJmuKzFLvAnEcQRWkH5TN",
        "rewardRecipients": [{
            "address": "RJt2mcAGMFWh3cJmuKzFLvAnEcQRWkH5TN",
            "percentage": 0
        }],
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 10,
        "clientConnectionTimeout": 0,
        "banning": {
            "enabled": false,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3332": {
                "listenAddress": "192.168.1.101",
                "difficulty": 16,
                "name": "SOLO Mining",
                "varDiff": {
                    "minDiff": 1,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30,

                }
            }
        },
        "daemons": [{
            "host": "192.168.1.101",
            "port": 3333,
            "user": "struct",
            "password": "master",
	    "zmqBlockNotifySocket": "tcp://192.168.1.101:8767",
      }
    ],

    "paymentProcessing": {
      "enabled": true,
      "minimumPayment": 0.01,
      "payoutScheme": "PPLNS",
      "payoutSchemeConfig": {
        "factor": 2.0
      }
    }
  }]
}
