### ISSUE TITLE
zmqBlockNotifySocket RVN

### ISSUE THREAD

**Issue by structdjm** [coinfoundry/miningcore#352]
### Description

I have tried the zmqBlockNotifySocket method with blockRefreshInterval set to 0, but its just polling via Job Refresh at the interval of whatever jobRebroadcastTimeout is set to

### Steps to Reproduce

1. Disable blockRefreshInterval set to 0
2. Set jobRebroadcastTimeout set to 10
3. "zmqBlockNotifySocket": "tcp://127.0.0.1:8767"

Looking at console is doesn't detected new block immediately from network, it will only check for new blocks after jobRebroadcastTimeout value lapse via Job Refresh

Ver miningcore-0.24

**Comment by structdjm** [comment]
Also the console shows its using RPC polling even tho is should be using zmqBlockNotifySocket
[2018-06-01 12:25:30.6079] [I] [RVN] [Bitcoin Job Manager] Detected new block 23
7252 via RPC polling

**Comment by structdjm** [comment]
This is the json.config file I`am using
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "192.168.1.101",
            "port": 5432,
            "user": "miningcore",
            "password": "pass",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": false,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "RVN",
        "enabled": true,
        "coin": {
            "type": "RVN"
        },
        "address": "RJt2mcAGMFWh3cJmuKzFLvAnEcQRWkH5T6",
        "rewardRecipients": [{
            "address": "RJt2mcAGMFWh3cJmuKzFLvAnEcQRWkH5T6",
            "percentage": 0
        }],
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 10,
        "clientConnectionTimeout": 0,
        "banning": {
            "enabled": false,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3333": {
                "listenAddress": "192.168.1.101",
                "difficulty": 1024,
                "name": "SOLO Mining",
            }
        },
        "daemons": [{
            "host": "192.168.1.101",
            "port": 42068,
            "user": "struct",
            "password": "passs",
	"zmqBlockNotifySocket": "tcp://192.168.101:8767",
      }
    ],

    "paymentProcessing": {
      "enabled": true,
      "minimumPayment": 0.01,
      "payoutScheme": "PPLNS",
      "payoutSchemeConfig": {
        "factor": 2.0
      }
    }
  }]
}

**Comment by structdjm** [comment]
Hey guys I can across this file BitcoinDeamonEndpointConfigExtra.cs, do I need to set this up? and if so how ?

namespace MiningCore.Blockchain.Bitcoin.Configuration
{
    public class BitcoinDaemonEndpointConfigExtra
    {
        public int? MinimumConfirmations { get; set; }

        /// <summary>
        /// Address of ZeroMQ block notify socket
        /// Should match the value of -zmqpubhashblock daemon start parameter
        /// </summary>
        public string ZmqBlockNotifySocket { get; set; }

        /// <summary>
        /// Optional: ZeroMQ block notify topic
        /// Defaults to "hashblock" if left blank
        /// </summary>
        public string ZmqBlockNotifyTopic { get; set; }
    }
}

**Comment by Konstantin35** [comment]
I can not understand what you want to configure and what purpose can be more please

**Comment by structdjm** [comment]
trying to configure ZmqBlockNotifyTopic, but I can't get it to work

**Comment by structdjm** [comment]
This is my raven.config file

rpcuser=struct
rpcpassword=passs
rpcallowip=192.168.1.1/24
rpcport=42068
server=1
listen=1
daemon=1
gen=0

**Comment by Konstantin35** [comment]
```
"daemons": [{
"host": "192.168.1.101",
"port": 42068,
"user": "struct",
"password": "passs",
"zmqBlockNotifySocket": "tcp://192.168.101:8767",
}
```

Add raven.config
zmqpubhashblock=tcp://192.168.101:8767

**Comment by structdjm** [comment]
@Konstantin35 thankyou I have added zmqpubhashblock=tcp://127.0.0.1:8767 to raven.config, however I don't understand the rest of your instructions 
ZeroMQ notification options:
  -zmqpubhashblock=<address>
       Enable publish hash block in <address>

**Comment by structdjm** [comment]
@Konstantin35  Thankyou so much, that worked, cheers

**Comment by Konstantin35** [comment]
I showed the option in the help of the demon RVN
in the future, study the parameters of the demon and it will be easier to solve the problem
[HELP.txt](https://github.com/coinfoundry/miningcore/files/2063937/HELP.txt)
