### ISSUE TITLE
Pool fee shows 0.1% higher than configured

### ISSUE THREAD

**Issue by AgentWhite000** [coinfoundry/miningcore#356]
**Description**

Pool fee showing 0.6 from API despite being set to 0.5 in config.json

**Steps to Reproduce**

Check poolFeePercent API results for /api/pools
      },
      "clientConnectionTimeout": 600,
      "jobRebroadcastTimeout": 10,
      "blockRefreshInterval": 400,
      "poolFeePercent": 0.6,

_config.json_
 "rewardRecipients": [
      {
        // Pool wallet
        "address": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "percentage": 0.5
      }
    ],

**Expected behavior**

I would expect the pool fee to return 0.5% as configured

**Actual behavior**

Pool fee returns 0.6% which is 0.1% higher than configured

**Reproduces how often**

Always

### Version

Not sure how to tell, but I pulled master branch on May 31, 2018

**Comment by Dradden** [comment]
Minincore has a hardcoded .1% dev fee.

**Comment by arubinofaux** [comment]
This is not a bug, this is a feature
