### ISSUE TITLE
How do miners connect??

### ISSUE THREAD

**Issue by chamisrx** [coinfoundry/miningcore#367]
Could someone tell me that how do the users (miners) connect to a running miningcore?

**Comment by McKlavishnikov** [comment]
Hello guys! I'm interested in the same question. How do miners connect to my pool? I've read the configuration as @arubinofaux suggested but it's still not clear

**Comment by arubinofaux** [comment]
@McKlavishnikov when you set up your configuration you are going to define the ports with the vardiff, so when you run miningcore you will use the IP address of the server plus the port number defined in the configuration, for example, `stratum+tcp://ip_address:port`   when you run the software the terminal will also output all the pool servers you can connect to

**Comment by McKlavishnikov** [comment]
@arubinofaux Thank you very much. Another question: how does a miner authentificate? They just need to pass their reward address, right?

**Comment by arubinofaux** [comment]
@McKlavishnikov yup in the miner software they use the address as the user

**Comment by McKlavishnikov** [comment]
@arubinofaux thanks a lot!
