### ISSUE TITLE
Error after load balancing， OnClientConnected NetUV.Core.Native.OperationException: ENOTCONN (ENOTCONN) : ENOTCONN : socket is not connected

### ISSUE THREAD

**Issue by zheng9980419** [coinfoundry/miningcore#373]
### Description

The following problem with using Aliyun's load balancing

### Steps to Reproduce

Enable 2 servers to deploy the same mine pool

### Expected behavior

Load balancing mine pool functioning normally

### Actual behavior

[E] [dash1] OnClientConnected NetUV.Core.Native.OperationException: ENOTCONN (ENOTCONN) : ENOTCONN : socket is not connected
   at NetUV.Core.Native.NativeMethods.ThrowOperationException(uv_err_code error)
   at NetUV.Core.Native.NativeMethods.TcpGetPeerName(IntPtr handle)
   at NetUV.Core.Handles.Tcp.GetPeerEndPoint()
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, ValueTuple`2 endpointConfig, Loop loop)    at NetUV.Core.Native.NativeMethods.ThrowOperationException(uv_err_code error)
   at NetUV.Core.Native.NativeMethods.TcpGetPeerName(IntPtr handle)
   at NetUV.Core.Handles.Tcp.GetPeerEndPoint()
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, ValueTuple`2 endpointConfig, Loop loop)

### Version

ubuntu 16.04 Release0.24

### Additional Information
None

**Comment by calvintam236** [comment]
@zheng9980419 can you attach your miningcore config here (please redact sensitive info)?

**Comment by zheng9980419** [comment]
At present, there is no problem with using the mine pool alone, but using Aliyun's load balancing will cause this problem. For help, you can provide Aliyun account for debugging.

**Comment by zheng9980419** [comment]
@calvintam236  At present, there is no problem with using the mine pool alone, but using Aliyun's load balancing will cause this problem. For help, you can provide Aliyun account for debugging.

**Comment by zheng9980419** [comment]
@calvintam236 {
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "47.xx.xx.177",
            "port": 5432,
            "user": "miningcore",
            "password": "948948",
            "database": "miningcore"
        }
    },
    // API Settings
    "api": {
      "enabled": true,

      // Binding address (Default: 127.0.0.1)
      "listenAddress": "0.0.0.0",

      // Binding port (Default: 4000)
      "port": 4000
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 60,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "dash1",
        "enabled": true,
        "coin": {
            "type": "DASH"
        },
        "address": "XugdYeACxxxxxxxxxxx9686zhdi",
        "rewardRecipients": [{
            "address": "XugdYeACxxxxxxxxxxx9686zhdi",
            "percentage": 0
        }],
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout": 10,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3533": {
                "listenAddress": "0.0.0.0",
                "difficulty": 64,
                "name": "ASIC Mining",
                "varDiff": {
                    "minDiff": 64,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30
                }
            }
        },
        "daemons": [{
            "host": "47.xx.xx.177",
            "port": 8930,
            "user": "yiimprpc",
            "password": "53Md3XeBDXD0p9rXlSksKQ"
        }],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 10,
            "payoutScheme": "PPS",
            "payoutSchemeConfig": {
                "factor": 2.0
            }
        }
    }]
}

**Comment by zheng9980419** [comment]
solved

**Comment by Timopheym** [comment]
> solved

how? @zheng9980419

**Comment by oliverw** [comment]
> > solved
> 
> how? @zheng9980419

We've dropped NetUV a long time ago, so this error should be gone.

**Comment by Timopheym** [comment]
> > > solved
> > 
> > 
> > how? @zheng9980419
> 
> We've dropped NetUV a long time ago, so this error should be gone.

@zheng9980419 @oliverw We have fork from May without updates =(( Do you know if it was solved without dropping NetUV?

**Comment by oliverw** [comment]
@Timopheym Sorry, no idea.
