### ISSUE TITLE
tx-overwinter critical problem Zcash will not mine blocks 2 blocks lost on mainnet

### ISSUE THREAD

**Issue by osheen2241** [coinfoundry/miningcore#374]
tx overwinter active is the error when submitting block to daemon, impossible to mine a block with Zcash node. 

### Steps to Reproduce

1. set up latest coinfoundry pool 
2. download latest daemon zcash 1.1.2
3. mine on the mainet and block solutions are rejected by daemon 

### Expected behavior
solution accepted by daemon, block reward received
[What you expect to happen]

### Actual behavior
solution submission fails (submission failed with: tx-overwinter-active)
[What actually happens]

### Reproduces how often
every instance 
[What percentage of the time does it reproduce?]
100% 
### Version

ubuntu 18.04, miningcore latest release, zcash daemon 1.1.2 

### Additional Information
submission failed with: tx-overwinter-active

**Comment by oliverw** [comment]
Working on it.
