### ISSUE TITLE
MiningCore doesn't working with tdxminer.

### ISSUE THREAD

**Issue by MikalaiR** [coinfoundry/miningcore#375]
### Description

Tdxminer can't connect to MiningCore pool. It throws an error: 

```
Pool gin.wingpool.com failed to parse server rpc: 
{"jsonrpc":"2.0","method":"mining.set_difficulty","params":[0.1]}
```
It looks like MiningCore doesn't following JSON-RPC specefication (id property ?).

### Steps to Reproduce

1. Install MiningCore (with lyra2z support from my fork)
2. Try to start mining using tdxminer

### Expected behavior

Mining should be started

### Actual behavior

```
Pool gin.wingpool.com failed to parse server rpc: 
{"jsonrpc":"2.0","method":"mining.set_difficulty","params":[0.1]}
```

### Reproduces how often

100%

### Version

Fork of release branch with lyra2z algorithm. (i haven't made any changes in RPC part)

**Comment by calebcall** [comment]
I rented some hashing power today to test out my pool configs and the rig happened to be running tdxminer.  It could connect and mine but was supposed to be getting 60+ MH/s and was only getting 10-12 MH/s.  Since it was rented I couldn't see if there were errors from the miner, but there wasn't any errors on the stratum.  I can get the expected hashing (18 MH/s) from my personal rig running trex miner.  I also previously rented 2GH/s on this same lyra2z algo and it worked fine and was able to get the full advertised hashing power, it was using ccminer.

**Comment by oliverw** [comment]
Neither of you mentioned what coin you are talking about. As a matter of fact, the hashrate calculation is one of the few areas in MiningCore that I'm totally unsatisfied with as the calculation for many Bitcoin derived currencies is currently [riddled with hacks.](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs#L398) Therefore I'm quite sure mining worked at full speed in both cases but the calculation was off.

Feel free to come up with a PR to fix that.

**Comment by RapidMark** [comment]
> I rented some hashing power today to test out my pool configs and the rig happened to be running tdxminer. It could connect and mine but was supposed to be getting 60+ MH/s and was only getting 10-12 MH/s. Since it was rented I couldn't see if there were errors from the miner, but there wasn't any errors on the stratum. I can get the expected hashing (18 MH/s) from my personal rig running trex miner. I also previously rented 2GH/s on this same lyra2z algo and it worked fine and was able to get the full advertised hashing power, it was using ccminer.
> 
> I assumed it was something to do with the difficulty settings as no matter what I tried to set the difficulty to, the rig kept changing to a really low diff and would then complain that the diff is too low.

@calebcall 
Where did you rent Hashing Power?

 (I've been trying NiceHash, and I've got all the test to pass, but my buying is always getting canceled or marked Dead) (in watching the logs, I can see that I subscribe, authorize, set difficulty, and then start sending notify, but their pool never sends traffic and kills my connection with "Zero speed" (can't figure out what I'm missing).

If you have a site that works... let me know.

Thanks

**Comment by oliverw** [comment]
@RapidMark It happened with ETH or ETC right?

**Comment by RapidMark** [comment]
Yes, ETH

**Comment by RapidMark** [comment]
OK, well, I also fixed mine to always send the ID already.... (as you show above)

I'll keep trying and post here if I ever get it to work... 

Meanwhile, are there any other places I could look to push ETH to my pool?

**Comment by calebcall** [comment]
@RapidMark I've been using https://miningrigrentals.com with good success.  After selecting the algo you want, if you click on a rig and then on it's workers tab, you can usually see what miner they are using.

@oliverw I don't remember which coin/algo I was testing at this time but I believe it was a lyra2z coin (so not currently in your branch of miningcore).  Other miners worked but the tdxminer wasn't working.  I even had the rig owner reach out to me and tell me that whatever stratum I was connected to didn't support tdxminer (he could see errors on his side).  Using a non-tdxminer worked just fine on the algo/coin I was testing.  I don't think this was a case of misreporting hashing, unfortunately.

**Comment by RapidMark** [comment]
@calebcall thanks... I'm interested in pumping in ETH traffic, and they're using eth_getWork not mining.subscribe, (and they're working with me on making changes, so that's nice...)

While I work with them, are there any other places to buy NiceHash style ETH hash?

**Comment by domajor** [comment]
[zephyr] Starting Pool ...
[2023-09-29 02:25:48.0305] [E] [zephyr] System.NullReferenceException: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Cryptonote.CryptonoteJobManager.Configure(PoolConfig pc, ClusterConfig cc) in /home/mining/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonoteJobManager.cs:line 282
What are the chances of Zephyr working?
