### ISSUE TITLE
Any fronted pls

### ISSUE THREAD

**Issue by xborow** [coinfoundry/miningcore#379]
Hello,
First, really thanks, good job done by creating miningcore 

Anybody with exact steps how to implement webfronted, please?

Thanks a lot

**Comment by calebcall** [comment]
The frontend is really quite easy.  You need to write something that uses the API to populate the data.   I create mine in Django and it made it quick work of building a frontend.  You could also do what many do and use the miningcore-ui that calvin on here created.  It's pretty basic and looks like 99% of the other miningcore sites out there but does get you a ui.

https://gitlab.com/calvintam236/miningcore-ui

**Comment by xborow** [comment]
thanks
