### ISSUE TITLE
submission failed with: bad-cb-payee

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#381]
### Description

I Added HTH (Help The Homeless, X16R) coin and upon finding a block I get the following errors:

* **On the Stratum** 
[2018-08-26 05:50:04.0041] [W] [HTH] [Bitcoin Job Manager] Block 76589 submission failed with: bad-cb-payee

* **On the Daemon** 
2018-08-26 05:48:14 CMasternodeBlockPayees::IsTransactionValid -- ERROR: Missing required payment, possible payees: 'HNjc6VSkeKmeg6PjnyvtfdyoYYi3UQqpTz', amount: 468.750000 HTH
2018-08-26 05:48:14 IsBlockPayeeValid -- ERROR: Invalid masternode payment detected at height 76588: CTransaction(hash=dc98d167a4, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 032c2b0104f23e825b0024300f3f040000000c2f4d696e696e67436f72652f, nSequence=0)
    CTxOut(nValue=1875.00000000, scriptPubKey=76a914cb0481bf4667f24da0a6f8a2)
2018-08-26 05:48:14 ERROR: ConnectBlock(HTH): couldn't find masternode or superblock payments

### Steps to Reproduce

1. Add HTH
2. Find a block
3. reproduce error 100% of the time

### Expected behavior

Be rewarded with the block

### Actual behavior

Block fails to submit

### Reproduces how often

100%

### Version

v.24 (with the addition of HTH following the basic steps in #61)

### Additional Information

Looking around, I'm guessing I implemented the coin wrong since it has masternodes.  So do I need to re-implement it similar to Straks, or can I just add the treasuryAddresses config to my pool config?

**Comment by calebcall** [comment]
Figured this out.

**Comment by wilsonpc** [comment]
I'm having the same issue.  Can you please share with me what you figured out.  Thanks.

**Comment by calebcall** [comment]
You need to look at the code for the coin you’re trying to enable. This usually means it’s a masternode coin and it’s not properly getting the masternode payment.

**Comment by oliverw** [comment]
@calebcall Care to submit a PR for your coin so we can include it in coins.json?

**Comment by calebcall** [comment]
@oliverw sure, I’d be happy to. I’m out of town till tomorrow but when I get back I’ll submit a pr.

**Comment by calebcall** [comment]
@oliverw Just submitted the pr for this coin template (did it off another repo since my fork of this is currently a mess from all my "testing" of things.  I have several I've added to mine that I'll create prs for, you can deny/accept whichever ones you want :) . Also, I have the geek algo used with Geekcash working good, I'll submit a pr for that as well.
