### ISSUE TITLE
Pool Clusters

### ISSUE THREAD

**Issue by LoneyNightCoder** [coinfoundry/miningcore#384]
## Clusters
I have a couple questions about the pool clustering.

I have 2 slave servers and 1 master server, I want maximum security.
Slave will be running stratum port only and relay all information to master.
On master side, it will have the persistent db, coin daemons, handle payments, and host a site.

### Questions

1. Is this a good configuration?
2. What should be the characteristics of the server slave and the master server ?
3. How can I secure the connection between a slave and coin daemons, like parity ?
4. What configuration do you use?

**Comment by calebcall** [comment]
I would personally (for the sake of scalability) separate out the coin daemons to their own cluster, and move the site to it's own cluster.  Then when you need to add more daemons and need to grow, the stratum doesn't necessarily have to be scaled as well, same with the frontend.  Or the stratum can scale without the need scale the other pieces too.  This also allows you to open only the necessary ports for each cluster (daemons only allow connections from the stratum, frontend only allows 80/443 from the internet, stratum only allows the stratum ports, etc)
