### ISSUE TITLE
Can you set minimum confirmations required?

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#391]
I've added a few new coins and they work great except some of them will show 100% confirmed but are still in a pending state.  Im guessing they require more confirmations (one of them requires 360 confirmations before it's fully confirmed).  Is there a config I can set for minimum confirmations for each coin?

I see this in the code:
`var minConfirmations = extraPoolConfig?.MinimumConfirmations ?? BitcoinConstants.CoinbaseMinConfimations;`

So I'm hopeful there is.  Is it as simple as adding `"minimumConfirmations": 360,` to my config for that coin?

**Comment by oliverw** [comment]
Yes exactly.
