### ISSUE TITLE
Wrong hashrate for miner from API after running for a while

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#393]
### Description

After running for a while, the API seems to increase the hashrate for individual miners until it changes to Infinity.

### Steps to Reproduce

1. Connect miner
2. Wait ~12hours
3. Hashrate changes to Infinity from the API

### Expected behavior

To reflect actual hashrate of the miner

### Actual behavior

Initially the hashrate is correct that's returned from the API.  After some time (several hours), it starts to increase.  Last I saw, it was approx 3X-4X of what it should be and then it just went to Infinity.  I've tested this on different coins and different algos.  I currently have X16r and X16s coins setup and it happens on both of those.

API endpoint: http://api.minerscore.com

### Reproduces how often

Everytime for the last couple days.

### Version

V26
Docker container running on CentOS 7.5

### Additional Information

The hashrate recorded in the database in minerstats is correct, it's just when returned form the API it changes.

**Comment by oliverw** [comment]
Actually the hashrate in the Db is not correct. The values are all positive infinity.

**Comment by oliverw** [comment]
Would be nice to get more infos about the conditions under this happens.

**Comment by calebcall** [comment]
I haven't seen this behavior in quite some time.

**Comment by oliverw** [comment]
Closing until this pops up again.
