### ISSUE TITLE
Invalid shares information

### ISSUE THREAD

**Issue by ingenius** [coinfoundry/miningcore#397]
Missing invalid shares information per worker. I can't find any way to extract this information.

**Comment by oliverw** [comment]
Extract from what? Do you mean the API or internally?

**Comment by ingenius** [comment]
I have found that the information is registered in the logs and reading the sources, I see that you count the amount of invalid shares, but I can not find another place where it is shown (API / database) (please, if I'm wrong, correct me.)

I have seen in almost all the mining pools, that in the statistics section there is the amount of invalid shares, I have spoken with some miners, and this allows them to determine if the hardware is failing.

**Comment by LunarExplorer** [comment]
Invalid shares could manifest in bans and disconnects. So miners should know when their IPs get blocked by ban manager and all miners get booted out.  This is actually a bit of a design issue.  As there is no stratum response for ban/disconnect.

**Comment by LunarExplorer** [comment]
I have noticed some "invalid job" stratum errors and ban manager killing whole mining farms too. Not able to reproduce in test environment but suspect some kind of race condition where miner is still mining old job but a block was found and not yet broadcasted to miner.

**Comment by ycusoy** [comment]
In my report cant found wallet online.
