### ISSUE TITLE
Windows 10 install failed

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#399]
Getting a dotnet error when trying to install using the windows-build.bat file.

The output from the typing windows-build.bat is:

```
C:\Users\src\MiningCore>windows-build.bat

C:\Users\miningcore\src\MiningCore>REM publish

C:\Users\miningcore\src\MiningCore>mkdir ..\..\build
A subdirectory or file ..\..\build already exists.

C:\Users\miningcore\src\MiningCore>dotnet publish -c Release --framework netcoreapp2.0 -o ..\..\build
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

C:\Usersminingcore\src\MiningCore>
```

Do I need to actually install the SDK also, or just the Runtime as the Readme here states? If I need to also install the SDK, you should probably add that info to the Readme.

Thanks for any help with this. I'm anxious to try this out after dealing with ConiumServ

**Comment by seperatis** [comment]
After downloading the dotnet SDK, it was apparent this is actually needed to install the windows-build.bat, but you must use dotnet SDK 2.1, any other version WILL NOT WORK. Also, this makes the windows-build.bat file kick out an error: 

`\.nuget\packages\microsoft.aspnetcore.all\2.1.4\build\netcoreapp2.1\Microsoft.AspNetCore.All.targets(14,5): error : This version of Microsoft.AspNetCore.All is only compatible with the netcoreapp2.1 target framework. Please target netcoreapp2.1 or choose a version of Microsoft.AspNetCore.All compatible with netcoreapp2.0. [C:\Users\seper\miningcore\src\MiningCore\MiningCore.csproj]`

To fix the above error, you need to modify the file windows-build.bat and change `netcoreapp2.0` to `netcoreapp2.1` in order to match the correct version of dotnet SDK version installed.

Maintainers, please add dotnet SDK 2.1 to the Readme file for Windows dependencies, and either update the windows-build.bat file to target `netcoreapp2.1` or advise others how to make the modification.

**Comment by oliverw** [comment]
Fixed in dev branch. Thanks for reporting. Since virtually nobody appears to be using Miningcore on Windows, I simply forgot to update <code>windows_build.bat</code>.

**Comment by seperatis** [comment]
Thanks for the fix and quick update. Closing this issue now.
