### ISSUE TITLE
Peer authentication failed for user "miningcore"

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#403]
Trying to get this running on Ubuntu 16.04 64bit.

When doing this step:

`psql -d miningcore -U miningcore -f createdb.sql`

I get the following error: `psql: FATAL:  Peer authentication failed for user "miningcore"`

Unfortunately I'm not at all familaiar with Postgresl....I've seen people talk about switching to an md5 authentication method but have no idea how to do this.

Any thoughts?

**Comment by seperatis** [comment]
Thanks for the info. I was able to fix the issue by re-doing the steps in the readme. I think I removed the quotes when entering the password in the setup process.

**Comment by GoZippy** [comment]
same thing for me many times using latest versions of all .. so simply added -h 127.0.0.1 to define local host not over net and it worked fine...
psql -h 127.0.0.1 -d miningcore -U miningcore -f createdb.sql

I also suggest changing user and db names for a little extra security but you'll have to work out any conflicts in the scripts
