### ISSUE TITLE
block show orphaned in miningcore but block hash shows good on coin explorer

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#406]
## Note
Please use the following format to file an issue. Issues that fail to comply will delay our responses.
Please remove this section when you submit the issue. Thank you for your cooperation.

### Description

I've added a new coin to my miningcore, Actinium (ACM).  It's a lyra2z coin (also added the algo using the pull request from #198 ).  This was working fine until the coin started to support segwit addressing by default and I upgraded to miningcore v26 around the same time from v24.  Now when blocks are found, they are accepted by the daemon, but later come up orphaned.  However, when you follow the block hash, it shows as good (normally an orphaned hash isn't found on the blockchain).

Some examples:

https://www.minerscore.com/pool/ACM/ at the bottom in the blocks table, you can see they show as abandoned according to their status but the hash is good.

### Steps to Reproduce

1. Find block on ACM
2. Wait till it starts to confirm and it will orphan

### Expected behavior

Not to orphan every block

### Actual behavior

It orphans every block

### Reproduces how often

100% of the time

### Version

Release 31 + ACM and Lyra2z added.

### Additional Information

I understand this could very well be the way I've added Lyra2z.  However, lyra2z was previously working fine.  I've also added several coins so I'd be suspect to it being the way ACM was added.  I'm open to anything though.

**Comment by oliverw** [comment]
Its extremely likely that the blockhasher algorithm for the coin is wrong. 

`private static readonly BitcoinCoinProperties lyra2zCoin = new BitcoinCoinProperties(Math.Pow(2, 8), sha256D, lyra2z, sha256DReverse, "Lyra2Z");
`
I'd try replacing <code>sha256DReverse</code> with <code>new DigestReverser(lyra2z)</code>

**Comment by calebcall** [comment]
Thanks, I'll try that and see what happens.

**Comment by calebcall** [comment]
Just to follow-up, I did try that and it didn't work.  However, I now have a better understanding of the blockhasher (stupid, but I didn't realize the hash would match from the submitted block hash on the stratum and the hash for the block in the daemon logs, etc...sounds really dumb not to realize this when I type it out!) so I'll check that on this issue.  I'll close this as neither lyra2z or ACM are in your branch.

**Comment by tenlans** [comment]
I have the same question . There are serveral blocks show orphaned in miningcore but show correct in explorer.
I think my conig is incorrect, the payment interval only 60 seconds

"paymentProcessing": {
        "interval": 60
}

Could I update block status in database to payout coin ?

=============
Ubuntu 16.04
Latest miningcore as at Thu Oct 25 2018 from master
Parity v2.0.8-stable
Ellaism network.
