### ISSUE TITLE
ZMQ Curve

### ISSUE THREAD

**Issue by RapidMark** [coinfoundry/miningcore#409]
## Note
I realize you're still working on ZMQ Curve shared keys (but I love it and want to test it..., as a prep for integration)

### Description

Can you give me a quick config file slice for what you're thinking (I'm trying something like this)

{
	"url": "tcp://10.1.3.161:6000",
	"topic": "tube",
	"sharedEncryptionKey": "MySharedKey"
}

and

"shareRelay": {
	"publishUrl": "tcp://0.0.0.0:6000",
	"sharedEncryptionKey": "MySharedKey"
},

also, it appears externalStratum is not use ??? (maybe I'm looking at it wrong).

Also, I think I need to have libcurve on linux.

Any thoughts would be appreciated.

Thanks in advance, and sorry to be peeking over your shoulder on dev... it's exciting.

**Comment by oliverw** [comment]
Sure 😏 

On the relay node:

```
"shareRelay": {
  "publishUrl": "tcp://0.0.0.0:6000",
  "sharedEncryptionKey": "foobar"
}
```

On the master (receiver):

```
"shareRelays": [{
    "url": "tcp://relay1:6000",
    "sharedEncryptionKey": "foobar"
}],
```

Be advised that the new <code>shareRelays</code> element resides at the cluster-level as opposed to the old <code>externalStratums</code> element that used to live at pool-level, which is completely replaced by <code>shareRelays</code>. You also don't need to specify topics anymore. 

The encryption key doesn't have to be cryptographically strong as it is processed by 5000 PBKDF2 rounds.

**Comment by RapidMark** [comment]
Excellent... thanks

**Comment by oliverw** [comment]
And be careful. The dev branch is highly unstable at times. Currently its not as it is basically the upcoming release.
