### ISSUE TITLE
Block not found after submission but get rewards in wallet (new algo, Lbk3)

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#411]
### Description

I get the following error after submitting the block:

Block 3243 submission failed for pool <poolid>because block was not found after submission

However, looking at the daemon, it's accepting the block and I get the rewards in my wallet.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

block would show up as rewarded

### Actual behavior

block doesn't show up but rewards do (in the wallet only)

### Reproduces how often

100%

### Version

Running v.30 but have added Lbk3 support

### Additional Information

Looking through the code, I'm not sure why it's not able to track the submission after it submits it.  I'm sure I missed something on my attempt to add Lbk3 support.  This is on a testnet, could that have anything to do with it?

**Comment by oliverw** [comment]
I'm pretty sure that the blockhasher digest is configured wrongly. Try with Sha256D or alternatively with DigestReverser(your-header-hasher). 

Ohh and please don't file bugs against a private release :)
