### ISSUE TITLE
Blocks...

### ISSUE THREAD

**Issue by RapidMark** [coinfoundry/miningcore#412]
## BitTube
I'm finally done with testing, starting to Mine and pump traffic in.

Mining for BitTube, I found 3 blocks, but unfortunately the wallet file was corrupted (not sure how, but I did reboot several times) so I make a new wallet file, and started again.

The Blocks show as pending in the DB, and on the Blockchain, it's like 300 Tube, each, but my wallet shows no balance (AFAICT)

With the bad wallet, I create a new one, and start again.

I've found a new block, and again, it says pending. I'm afraid to stop the wallet-rpc because I don't want to find another corrupt wallet.

Can you explain how the Blocks, how it gets assigned to the main wallet (which I assume is the main wallet I created and point to with my wallet-rpc, and assign in the config as 
      "id": "tube",
      "enabled": true,
      "coin": {
        "type": "TUBE"
      },
      "address": "wallet_address_here"

Is there a step I'm missing? (let me know and I can send you my configs

Thanks

RapidMark

**Comment by RapidMark** [comment]
Yes, I generated a new address, but when I try to run wallet-cli it says file is open in another program (running linux), so I'm afraid to force quit wallet-rpc to run it.

While I know the first blocks are lost, they still haven't shown up in the first wallets balance (or so it appears).... Should I be able to see them in the explorer?

regardless of the first wallet... the 2nd wallet is currently running and not showing any issues (yes, again I have a new address for the new wallet), and I updated the config and relaunched miningcore.

Guess I'll give it time to appear in the new wallet and see what happens.

**Comment by calebcall** [comment]
You can check what has wallet-cli held open (lsof | grep wallet-cli) or (ps wauxf | grep wallet-cli).  That shouldn't be held open by anything.

**Comment by calebcall** [comment]
You won't see anything on either address until those blocks confirm.  Not sure how long that takes for bittube, but some chains take a LONG time to confirm blocks.  I've seen them require 300+ confirmations and if the volume on that chain is low, that could take a very long time.

**Comment by oliverw** [comment]
@RapidMark @calebcall remarks are spot on. I've never seen something like this on any of our pools. I'v tested Bittube with its testnet and everything worked just fine. https://github.com/coinfoundry/bittube-private-testnet

**Comment by RapidMark** [comment]
OK, thanks.

I'll give it time to process, but after 10 hours, still pending.

**Comment by oliverw** [comment]
It shouldn't take that long. 

Could you paste the output of?

`cat /path/to/logs/core.log | grep -i pay
`

**Comment by calebcall** [comment]
I’m planning to add bittube to my pool today (was going to do it last night but their pre-compiled linux release is against 17.10, so I need to recompile it) and I’ll see if I can replicate this on my pool.

**Comment by RapidMark** [comment]
Been out of town... sorry for the absence... I'll post that when I get a chance... I see some comments in your dev branch, does that mean you found something?

**Comment by oliverw** [comment]
Nope. Coinfoundry's first Bittube block was unlocked without problems.

**Comment by RapidMark** [comment]
OK, figured it out... I was running 16.04 and compiled it myself... I switched to 18.04 and downloaded the release (instead of compiling myself), and immediately got the `Received money: value`

Thanks
