### ISSUE TITLE
Digibyte-Scrypt pool API shows 1 miner connected, when there are 2 miners connected

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#414]
I noticed when running the Digibyte-Scrypt pool, if you look at the API when using unique worker names (Digibyte Addresses) for each miner, it counts them **correctly**, but if you **append a number** (like most miners are used to doing), then the API only counts it as **one** miner. The problem I see here is that a person may have 100 miners connected to the pool, but the API is going to display it as "1 Miners Connected" unless they use a different Digibyte Address for each miner, and realistically, who wants to do that?

Is there a fix for this besides using a different Digibyte address for each miner that I connect to the pool?

See attached pictures;
![dgb-scrypt_4](https://user-images.githubusercontent.com/32314615/46575672-6998b080-c96e-11e8-9955-35802ae0868e.jpg)
![dgb-scrypt_2](https://user-images.githubusercontent.com/32314615/46575647-01e26580-c96e-11e8-9e79-1fa8afd34b36.jpg)
![dgb-scrypt_3](https://user-images.githubusercontent.com/32314615/46575648-03ac2900-c96e-11e8-8e7d-a9bdb44592f4.jpg)

**Comment by oliverw** [comment]
It depends on how you define a "miner". You are correct in your assessment that currently miners are only distinguished by wallet. The definition of a miner being an entity controlling them rather a concrete mining rig.

**Comment by seperatis** [comment]
After mining various coins with various pools over the last 5 years, it has been my experience that the majority of pools define both "workers" and "users".

For example, if I have two miners connected to your pool, I'd append the worker names something like `17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm.1` and for worker 2,  `17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm.2`

The pool would count this as two "workers" but it would only count it as one "user", as currently the API is just counting "miners" which I believe should be changed to a metric named "users" and another metric called "workers" added that calculates the total number of workers in each pool. 

This is very useful information for the miners, especially in smaller and/or Solo pools even. I've made a descision to use this pool or that pool many times based on the number of actually "workers" that are connected vs the "users" number.

And it's my opinion and belief that this is the most commom configuration seen in modern mining pools today. (please see attached pictures)

So this is probably an **improvement** or a **feature request**, and like any good request should be made, I've added a small donation to this request. ---> https://live.blockcypher.com/ltc/tx/e3d9cac2ef059de6c9b981a7fce9fe0940386f7a2d41358f48a7557f7bb660d6/

MiningCore is pretty great, and I would like to see it keep improving. I mention this small detail not to be picky or a nuisssaince but because I believe it makes MiningCore better..

**Comment by seperatis** [comment]
Maybe this should be merged to Improving API responses #27

**Comment by oliverw** [comment]
Tracked in #27

**Comment by oliverw** [comment]
Implemented with 358bf79aa87bcfd109501147e6bae1fe80b5e515.
