### ISSUE TITLE
NiceHash compatibility

### ISSUE THREAD

**Issue by RapidMark** [coinfoundry/miningcore#424]
## Note
I noticed that miningcore differs from the NiceHash spec in that it add's "0x" to the seed and header when returning mining.notify

From NiceHash Spec 
https://github.com/nicehash/Specifications/blob/master/EthereumStratum_NiceHash_v1.0.0.txt

`{
  "id": null,
  "method": "mining.notify",
  "params": [
    "bf0488aa",
    "abad8f99f3918bf903c6a909d9bbc0fdfa5a2f4b9cb1196175ec825c6610126c",
    "645cf20198c2f3861e947d4f67e3ab63b7b2e24dcc9095bd9123e7b33371f6cc",
    true
  ]
}`

### Expected behavior

Sending: {"id":null,"method":"mining.notify","params":["0000042c","a8348bb965adfd8fe9a1d8b4485850049eb46d9e2305335a499b48e3d47ae3d3","80e621f1e925ebc29ad93d5415de667566ae6f0826ce51987a06f7794e400c96",true],"jsonrpc":"2.0"}

### Actual behavior

Sending: {"id":null,"method":"mining.notify","params":["0000042c","`0x`a8348bb965adfd8fe9a1d8b4485850049eb46d9e2305335a499b48e3d47ae3d3","`0x`80e621f1e925ebc29ad93d5415de667566ae6f0826ce51987a06f7794e400c96",true],"jsonrpc":"2.0"}

### Change this function

        private object[] GetJobParamsForStratum(bool isNew)
        {
            var job = currentJob;

            if (job != null)
            {
                return new object[]
                {
                    job.Id,
                    // trim "0x" from header and seed for NiceHash compatibility
                    job.BlockTemplate.Seed.Substring(2),
                    job.BlockTemplate.Header.Substring(2),
                    isNew
                };
            }

            return new object[0];
        }

This will allow you to buy hashing power from NiceHash (although I'm still having one issue, and I'll post here when I've confirmed)

**Comment by oliverw** [comment]
Thanks. Fixes integrated.

**Comment by oliverw** [comment]
Anything else to fix or are we go to go?

**Comment by RapidMark** [comment]
Good to go...

One extra note... difficulty must be between 1 and 100 and bid has to be high enough.

I had 300 Gh/s

- Mark

On Oct 11, 2018, at 6:34 AM, Oliver Weichhold <notifications@github.com<mailto:notifications@github.com>> wrote:


Anything else to fix or are we go to go?

**Comment by oliverw** [comment]
@RapidMark Thanks. Closing.
