### ISSUE TITLE
API is not showing Network Hashrate for DGB-Scrypt pool

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#428]
The API is pulling all the other info from the network; the difficulty, the block height, etc, but it displays "0.0" for the network hashrate. I double checked the Digibyte Core Client just in case, and the Core Client shows the network hashrate as it should, but for some reason the API isn't pulling it. The other two pools I am testing MiningCore on (LTC, BTC), the network hashrate is showing properly in the API. Just seems to be with Digibyte-Scrypt, so far as I have seen is not displaying the network difficulty for Scrypt.

Can anyone explain this?

![dgb-api-network_hashrate](https://user-images.githubusercontent.com/32314615/47679512-aaf13a00-db81-11e8-8675-bbc622b70755.jpg)

![dgb-core-hashrate](https://user-images.githubusercontent.com/32314615/47679523-b0e71b00-db81-11e8-9cf8-033032bfe520.jpg)

**Comment by oliverw** [comment]
Fixed in dev branch.
