### ISSUE TITLE
Problem with API call

### ISSUE THREAD

**Issue by 20dec** [coinfoundry/miningcore#429]
## Note
Please use the following format to file an issue. Issues that fail to comply will delay our responses.
Please remove this section when you submit the issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior
![capture](https://user-images.githubusercontent.com/26274812/47062448-48eb1900-d200-11e8-9d92-17813dcbadb9.PNG)

### Actual behavior

[What actually happens]

### Reproduces how often
**Always**
### Version
**Lastest
Ubuntu 16.04**

### Additional Information
Try with other port or don't set api field in config.json (will bind with 127.0.0.1) but cannot CURL from local machine too.

**Comment by calebcall** [comment]
Not sure what you're trying to do, you've provided pretty much no info.  What does your api section config look like?  What url are you trying to curl or hit in the browser?  If you're just trying to hit http://127.0.0.1:4000 (or whatever port you used) then you'll get a 404.  You need to hit one of the api paths (e.g. `http://127.0.0.1:4000/api/pools`)

**Comment by 20dec** [comment]
I use a frondend web, they use IP:4000 only, then i think API problem. add "/api/" then work well.
Thank you very much.

20dec
