### ISSUE TITLE
Proper way to add a second coin daemon?

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#440]
I've read the documentation on this but would like to clarify a couple things.
 When adding a second coin daemon, should the zmqBlockNotifySocket point to each individual daemon (like snippet below)?  Will the rewards always go to the same wallet (thus payments always come from that wallet)?  Lastly, I know if you try to start the stratum using an address that doesn't belong to the wallet you're connecting to it will complain/fail.  How does it work having two, does it just check to make sure that address belongs to one of the daemons?

Example config, is this correct assuming I have daemons on two different hosts?
```
"daemons": [
        {
          "host": "10.138.168.45",
          "port": 8766,
          "user": "daemonuser",
          "password": "daemonpassword",
          "zmqBlockNotifySocket": "tcp://10.138.168.45:8767"
        },
        {
          "host": "10.138.168.145",
          "port": 8766,
          "user": "daemonuser",
          "password": "daemonpassword",
          "zmqBlockNotifySocket": "tcp://10.138.168.145:8767"
        }
      ],
```

**Comment by oliverw** [comment]
The DaemonClient supports multiple daemons and your configuration is correct but I believe it was never tested in production. Certainly not at CF. Payments are always done using the first configured daemon in the list.

**Comment by calebcall** [comment]
Thanks.  I tested this config out and any blocks that were found would eventually go in to an orphaned status.  They weren't really orphaned though as their tx shows correctly on the explorer and once removing the second daemon config and changing their status back to pending, the stratum would pick them back up and start tracking the confirmation progress.

**Comment by oliverw** [comment]
@calebcall If you'd get it working I happily accept a PR.
