### ISSUE TITLE
Pool Fee ignored when payout is calculated

### ISSUE THREAD

**Issue by ZhiKosta** [coinfoundry/miningcore#445]
### Description
Pool does not calculate and will not keep the OP fee. Instead, it will send all the remaining coins to the miners.  "rewardRecipients" is set to 1%

### Steps to Reproduce

build v40, find block, pay to miners.

### Expected behavior
Pool needs to remove the OP fee from the block amount before calculating the miner payments.

### Actual behavior

Pool calculates and sends all the coins from the block to it's miners, including dev fee. Pool fee is ignored.

### Reproduces how often
Every time.

### Version

v40

### Additional Information

changing setting variable "rewardRecipients" to "RewardRecipients" may work. Currently in testing.
UPDATE: case is not the problem.

**Comment by seperatis** [comment]
@ZhiKosta What coin are you mining? Paste your config. (minus anything sensitive)

**Comment by ZhiKosta** [comment]
Hey there, I just checked back my testnet logs. Using same address used for coinbase rewards and pool fee rewardRecepients never worked (as long as i remember dealing with MC)
I only found this issue yesterday since i put actual fee's on.

But since you ask, here is the proof:

https://explorer.bitcoingold.org/insight/block/00000000de2db420c7127300c9480160af065ad347c7f6336a88b8ecb28c07df
block mined

https://explorer.bitcoingold.org/insight/tx/2c792867abb7d6362780becc0f1bd12f3cd68d2c70a5d537a6fe8ba241b38c38
block paid

`                        "id": "btg",
                        "enabled": true,
                        "enableInternalStratum": false,
                        "coin": "bitcoin-gold",
                        "networks": "main",
                        "address": "GLuatJRozfXt1vwY9SGLiqxXaVeSBbSP2p",
                        "rewardRecipients": [
                            {
                            "address": "GLuatJRozfXt1vwY9SGLiqxXaVeSBbSP2p",
                            "percentage": 1
                            }
                        ],
`
This never worked, even on testnet. Only way your pool gets paid is using different wallet address for fee and coinbase.

I've managed to get Oliver before he went to bed. He'll look at this issue when he finds some time. In the mean time, i would love to know if you can confirm this.

**Comment by bitspill** [comment]
Miningcore intentionally does not include the poolAddress in the payout but does calculate the rewards to reserve the respective percentage, it's not sending all of the reward to the miners one of those addresses will be a change address within your own wallet -- it's behaving as intended.

https://github.com/coinfoundry/miningcore/blob/bf5015a/src/Miningcore/Blockchain/Bitcoin/BitcoinPayoutHandler.cs#L195-L216
```C#
        public virtual async Task<decimal> UpdateBlockRewardBalancesAsync(IDbConnection con, IDbTransaction tx, Block block, PoolConfig pool)
        {
            var blockRewardRemaining = block.Reward;

            // Distribute funds to configured reward recipients
            foreach(var recipient in poolConfig.RewardRecipients.Where(x => x.Percentage > 0))
            {
                var amount = block.Reward * (recipient.Percentage / 100.0m);
                var address = recipient.Address;

                blockRewardRemaining -= amount;

                // skip transfers from pool wallet to pool wallet
                if (address != poolConfig.Address)
                {
                    logger.Info(() => $"Adding {FormatAmount(amount)} to balance of {address}");
                    await balanceRepo.AddAmountAsync(con, tx, poolConfig.Id, poolConfig.Template.Symbol, address, amount, $"Reward for block {block.BlockHeight}");
                }
            }

            return blockRewardRemaining;
        }
```

**Comment by ZhiKosta** [comment]
OK. i confirmed that if you use your coinbase wallet to receive pool fee with it, you actually get the calculated amount as a change sent to a change address associated with your wallet.

I got this wrong only because i expected that pool will send the amount to the miners but leave the pool fee value in the same address. (using it as  address to send the change in instead of hashing new one)

I hope this help someone else who is wondering about the same. Thank you @bitspill for the insights!
