### ISSUE TITLE
Unreadable block problems and payout not sent to wallet

### ISSUE THREAD

**Issue by ycusoy** [coinfoundry/miningcore#446]
@oliverw .. I get a bit of a problem from the results of miningcore v.4-1 operations for 2x24 hours and in the work report there are unreadable block problems, payments that are not sent to the wallet.

For more details, log:

**Info Log minigcore.v41:**
> [2018-10-26 20:21:53.7036] [I] [digibyte-scrypt] Detected new block 7557225 via Job-Refresh
> [2018-10-26 20:21:53.7036] [I] [digibyte-scrypt] Broadcasting job
> [2018-10-26 20:21:53.7684] [I] [dogecoin] Broadcasting job
> [2018-10-26 20:21:54.7971] [I] [digibyte-scrypt] [0HLHR6CK1T3PV] Share accepted: D=7.308
> [2018-10-26 20:21:56.7141] [I] [digibyte-scrypt] Broadcasting job
> [2018-10-26 20:21:56.7786] [I] [dogecoin] Broadcasting job
> [2018-10-26 20:21:58.4053] [I] [digibyte-scrypt] Detected new block 7557226 via RPC polling
> [2018-10-26 20:21:58.4053] [I] [digibyte-scrypt] Broadcasting job
> [2018-10-26 20:21:59.5062] [I] [PayoutManager] Processing payments for pool dogecoin
> [2018-10-26 20:21:59.5062] [I] [PayoutManager] No updated blocks for pool dogecoin
> [2018-10-26 20:21:59.5141] [I] [PayoutManager] No balances over configured minimum payout for pool dogecoin
> [2018-10-26 20:21:59.5141] [I] [PayoutManager] Processing payments for pool digibyte-scrypt
> [2018-10-26 20:21:59.5141] [I] [PayoutManager] No updated blocks for pool digibyte-scrypt
> [2018-10-26 20:21:59.5141] [I] [PayoutManager] No balances over configured minimum payout for pool digibyte-scrypt
> [2018-10-26 20:21:59.7221] [I] [digibyte-scrypt] Broadcasting job
> [2018-10-26 20:21:59.7851] [I] [dogecoin] Broadcasting job
> [2018-10-26 20:22:02.7345] [I] [digibyte-scrypt] Broadcasting job

**config conf.json:**
```
{
    "logging": {
        "level": "Info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",

    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "somepassword",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 100,
        "shareRecoveryFile": "recovered-shares.txt"
    },
	"api" : {
		"enabled": true,
		"listenAddress": "127.0.0.1",
		"port": 4000
		},
    "pools": [
	
	{
      "id": "dogecoin",
      "enabled": true,
      "coin": "dogecoin",
      "address": "DGDD6EFDogvxis8R3pYjmX8Fh1CyzE2VCx",
      "rewardRecipients": [
        {
          "address": "DGDD6EFDogvxis8R3pYjmX8Fh1CyzE2VCx",
          "percentage": 0.01
        }
      ],
      "blockRefreshInterval": 333,
      "jobRebroadcastTimeout": 3,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "22556": {
          "listenAddress": "0.0.0.0",
          "difficulty": 128,
          "varDiff": {
            "minDiff": 0.05,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 10,
			"maxDelta":500
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 22555,
          "user": "dogecoinrpc",
          "password": "F8en7bN3ej3Li2YA1GDmKLCpc8gzEpbWbnBYXhLeiv28"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    },
	
	{
      "id": "digibyte-scrypt",
      "enabled": true,
      "coin": "digibyte-scrypt",
      "address": "DDksSrZAzsJqSwtVgRMNRY7dDSviVH66Gb",
      "rewardRecipients": [
        {
          "address": "DDksSrZAzsJqSwtVgRMNRY7dDSviVH66Gb",
          "percentage": 0.01
        }
      ],
      "blockRefreshInterval": 333,
      "jobRebroadcastTimeout": 3,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 100,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "12024": {
          "listenAddress": "0.0.0.0",
          "difficulty": 128,
          "varDiff": {
            "minDiff": 0.05,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 14022,
          "user": "digibyterpcuser",
          "password": "digibyterpcpassword"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }
	]
}
```

**log ccminer dogecoin:**
> [2018-10-26 19:14:18] scrypt factor set to 9 (1024)
> [2018-10-26 19:14:29] GPU #1: GeForce GTX 1050, 51.32 kH/s
> [2018-10-26 19:14:50] Stratum difficulty set to 21.3255 (0.00033)
> [2018-10-26 19:15:11] GPU #2: 1381 MHz 92C FAN 0%
> [2018-10-26 19:15:28] scrypt block 2447250, diff 2542943.099
> [2018-10-26 19:15:39] GPU #2: GeForce GTX 1050, 54.36 kH/s
> [2018-10-26 19:16:20] Stratum difficulty set to 1.77641 (0.00003)
> [2018-10-26 19:16:22] GPU #1: GeForce GTX 1050, 54.46 kH/s
> [2018-10-26 19:16:26] GPU #1: GeForce GTX 1050, 53.86 kH/s
> [2018-10-26 19:16:27] accepted: 1/1 (diff 0.000), 53.47 kH/s yes!
> [2018-10-26 19:16:28] accepted: 2/2 (diff 0.000), 51.70 kH/s yes!
> [2018-10-26 19:16:30] GPU #2: GeForce GTX 1050, 52.98 kH/s
> [2018-10-26 19:16:31] accepted: 3/3 (diff 0.000), 50.94 kH/s yes!
> [2018-10-26 19:16:32] GPU #2: 1294 MHz 92C FAN 0%

**log ccminer digibyte:**
> [2018-10-26 20:20:12] accepted: 375/382 (diff 0.000), 90.41 kH/s yes!
> [2018-10-26 20:20:12] GPU #4: 1511 MHz 92C FAN 0%
> [2018-10-26 20:20:21] scrypt block 7557221, diff 125274.232
> [2018-10-26 20:20:23] scrypt block 7557222, diff 120453.830
> [2018-10-26 20:20:29] GPU #4: GeForce GTX 1050, 78.13 kH/s
> [2018-10-26 20:20:30] accepted: 376/383 (diff 0.000), 88.73 kH/s yes!
> [2018-10-26 20:20:38] scrypt block 7557223, diff 153167.333
> [2018-10-26 20:20:47] Stratum difficulty set to 7.30797 (0.00011)
> [2018-10-26 20:21:07] GPU #4: GeForce GTX 1050, 72.74 kH/s
> [2018-10-26 20:21:09] scrypt block 7557224, diff 147276.293
> [2018-10-26 20:21:10] accepted: 377/384 (diff 0.000), 86.78 kH/s yes!
> [2018-10-26 20:21:11] GPU #0: GeForce GTX 1050, 75.79 kH/s
> [2018-10-26 20:21:13] GPU #0: 1499 MHz 92C FAN 0%
> [2018-10-26 20:21:20] GPU #0: GeForce GTX 1050, 80.36 kH/s
> [2018-10-26 20:21:24] GPU #0: GeForce GTX 1050, 80.32 kH/s
> [2018-10-26 20:21:35] GPU #0: GeForce GTX 1050, 80.12 kH/s
> [2018-10-26 20:21:50] GPU #0: GeForce GTX 1050, 79.82 kH/s
> [2018-10-26 20:21:53] scrypt block 7557225, diff 141611.821
> [2018-10-26 20:21:54] GPU #0: GeForce GTX 1050, 80.17 kH/s
> [2018-10-26 20:21:54] accepted: 378/385 (diff 0.001), 81.03 kH/s yes!

**log from wallet dogecoin:**
> {
> "blocks" : 2447331,
> "currentblocksize" : 33016,
> "currentblocktx" : 79,
> "difficulty" : 1905688.92937739,
> "errors" : "",
> "genproclimit" : -1,
> "networkhashps" : 154313562757607,
> "pooledtx" : 80,
> "testnet" : false,
> "chain" : "main",
> "generate" : false
> }

**log from wallet digibyte:**
> {
>   "blocks": 7557309,
>   "currentblockweight": 4000,
>   "pow_algo_id": 1,
>   "pow_algo": "scrypt",
>   "difficulty": 68535.30183350088,
>   "difficulty_sha256d": 1123734147.283833,
>   "difficulty_scrypt": 68535.30183350088,
>   "difficulty_groestl": 454776.6457387084,
>   "difficulty_skein": 448136.3231618071,
>   "difficulty_qubit": 348291.573699254,
>   "errors": "",
>   "pooledtx": 23,
>   "chain": "main",
>   "warnings": ""
> }

**Comment by calebcall** [comment]
Not sure if that's a real password for your dogecoin daemon, probably should edit that out if it is.

**Comment by ycusoy** [comment]
I have tried a number of changes for 2 weeks in the wallet settings and in miningcore config.conf. but still the miningcore process says there are no update blocks and no payments to wallet.

**Comment by oliverw** [comment]
Can you provide some log output where the pool actually finds a **block**, not just a share?
