### ISSUE TITLE
payment processing and network fee

### ISSUE THREAD

**Issue by foxrtb** [coinfoundry/miningcore#453]
does the payment process reduce the network fee from the miners amount?
like miner payment : 1DASH
payout : 1DASH - DASH network TX fee

and if not, how we can add it?

thanks

**Comment by bitspill** [comment]
It's a config setting left for the pool operator to decide, add it to the `paymentProcessing` section of your DASH config if you'd like that to be the case

```
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt",
        "minersPayTxFees": true
    },
```

**Comment by foxrtb** [comment]
hi!
thanks for your prompt reply,
is this feature available also from the version of miningcore from jan/feb 2018
`MiningCore - Pool Mining Engine
v1.0.0.0`
?

**Comment by bitspill** [comment]
The feature was added Dec 18th 2017 https://github.com/coinfoundry/miningcore/pull/125/files#diff-ba553b677aa4d3dc8926d475fbee306dR237

**Comment by oliverw** [comment]
@foxrtb Why on earth would you want to run such an ancient version?
