### ISSUE TITLE
Dev fee not added to API response if payment processing is not enabled.

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#454]
### Description

Disable payment processing and the dev fee is no longer returned in the api.

### Steps to Reproduce

1. Set paymentProcessing - enabled: false
2. Query API for poolfee on a coin that has a dev fee and it will be missing

### Expected behavior

To include the dev fee so api responses are consistent.

### Actual behavior

Dev fee is not included.

### Reproduces how often

100%

### Version

v42

I have one stratum with payments disabled and one with them enabled but both are part of my api VIP and I noticed I was getting inconsistent responses for the fee.  There's probably a better way to architect my stratums to avoid this.

**Comment by oliverw** [comment]
This is by design. In a clustering scenario, there should be a single pool master that does all the payment processing and serves API requests.
