### ISSUE TITLE
Block submission failed! Scrypt fork litecoin legacy

### ISSUE THREAD

**Issue by pedromalito** [coinfoundry/miningcore#461]
When the pool found a block  says! submission failed with : params must be an array!
Its a fork of litecoin SCRYPT Legady Daemon
I am using Ubuntu 16.04 
![captura](https://user-images.githubusercontent.com/28992881/48102956-fabfa900-e1f2-11e8-8437-17905e5738d1.PNG)

**Comment by oliverw** [comment]
What's the Github repo of the coin?

**Comment by pedromalito** [comment]
I use git clone https://github.com/coinfoundry/miningcore

**Comment by pedromalito** [comment]
The coin not have git repo its a new coin from Mexico

**Comment by oliverw** [comment]
Without inspecting the source it's impossible to tell what's going wrong.

**Comment by pedromalito** [comment]
I debug the miningcore the problem its in BitcoinJobManagerBase , method SubmitBlockAsync ,


  var results = await daemon.ExecuteBatchAnyAsync(logger,
                hasSubmitBlockMethod
                    ? new DaemonCmd(BitcoinCommands.SubmitBlock, new string[] { blockHex })
                    : new DaemonCmd(BitcoinCommands.GetBlockTemplate, new { mode = "submit", data = blockHex }),
                new DaemonCmd(BitcoinCommands.GetBlock, new[] { share.BlockHash }));

I change this for string and the problem change, say method submit not found I think because its a legacy daemon Then use new DaemonCmd(BitcoinCommands.SubmitBlock, new string[] { blockHex })

I think with the method getBlockTemplaete works fine!

Then use only new DaemonCmd(BitcoinCommands.GetBlockTemplate, new { mode = "submit", data = blockHex }) 
but say params must be an array
How convert this values in array?, its a object unknown type
