### ISSUE TITLE
There is no hashrate info on client programe

### ISSUE THREAD

**Issue by tenlans** [coinfoundry/miningcore#463]
### Description
There is no hashrate info on client program when client connect to pool after a while.
There are two servers have the same question, I need reboot server to recover.

### Steps to Reproduce

1. start EthDcrMiner64.exe
2. At the beginning you can get hashrate
shot screen: https://imgur.com/a/8cdigEt

3. No hashrate info after a while
shot screen: https://imgur.com/a/E8SAoBX

### Reproduces how often
about 12hr - 24hr

### Version
[Server]
Ubuntu 16.04
Latest miningcore as at Thu Oct 25 2018 from master
Parity v2.0.8-stable
[Client]
Windows 7 or Windows 10
EthDcrMiner64 v11.9

### Additional Information

"pools": [{
        "id": "eth",
        "enabled": true,
        "coin": "ethereum",
        "address": "0x",
        "rewardRecipients": [{
                "type": "op",
                "address": "0x",
                "percentage": 1.0
        }],
        "blockRefreshInterval": 500,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3333": {
                "listenAddress": "0.0.0.0",
                "difficulty": 0.5
            }
        },
        "daemons": [
            {
                "host": "127.0.0.1",
                "port": 8545
            }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.05,
            "minimumPaymentToPaymentId": 5.0,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 2.0
            },
	"coinbasePassword": "xxxx",
            "keepUncles": false,
            "keepTransactionFees": false
        }
    }]

**Comment by bitspill** [comment]
That sounds to me more like an issue with the Miner software than the pool, the local hashrate is calculated by the miner itself not the pool.

Is the miner still reporting `New job from xxxx:3333` periodically?

**Comment by tenlans** [comment]
All  Miner software are same question until I reboot server.
There is no "New job from xxxx:3333" on miner, but it still show "SHARE FOUND".

**Comment by bitspill** [comment]
Do the corresponding lines in the server logs when the miner finds a share continue to appear, is it still actually mining only not reporting the hashrate - or is it a complete disconnect from the server?

What's shown in the server logs?

**Comment by tenlans** [comment]
it only show "Share accepted" on server log, not any warn or error.
I try to use "Nov 5 2018" version to run pool at last week, but get the same question.
