### ISSUE TITLE
Error: "Share persistence queue backlog has crossed 1024"

### ISSUE THREAD

**Issue by Knevil** [coinfoundry/miningcore#467]
### Description

Shares and blocks not being reported to the DB (running multiple pools connecting to the same DB)
Error: "Share persistence queue backlog has crossed 1024"

### Steps to Reproduce

1. Run the pool
2. See all the rigs connecting
3. Share persistence queue backlog has crossed 1024

### Expected behavior

Shares registered for each miner, blocks registered and updating

### Actual behavior

Shares/s drops down, blocks not being reported

### Reproduces how often

Once the error message comes up "Share persistence queue backlog has crossed 1024"
I restart the pool and same thing happens again

### Version
https://github.com/aionnetwork/aion_pool2/tree/master/aion_pool
Ubuntu 18.04 LTS"

**Comment by oliverw** [comment]
@Knevil This would happen if the ShareRecorder cannot keep up with inserting received shares into the database. Miningcore already uses the fastest PostgreSQL batch insert strategy possible. So if that's not enough you need faster storage for your database.

**Comment by oliverw** [comment]
Possible, did you check if MC saturates the network interface to the db server?

**Comment by oliverw** [comment]
Resolved externally.
