### ISSUE TITLE
miningcore release 44 has lessen the accepted shares

### ISSUE THREAD

**Issue by soplainjustliketofu** [coinfoundry/miningcore#468]
### Description

after upgraded to release 44 ,  accepted shares has become lower than before  and many were rejected too . never had this issue in the previous version. 

coin name: PAK coin
algo: scrypt 
legacy daemon: yes
miner:   bitmain  L3+ (firmware version Fri Aug 25 17:28:57 CST 2017 )

### Steps to Reproduce

1. install miningcore v44
2. run miningcore 
3. monitor the log

### Expected behavior

decent shares value and more block can be found

### Actual behavior

1- many shares were rejected 
2 - very low shares value

> [2018-11-12 23:22:11.8911] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:11.9411] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:11.9873] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.0101] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.0545] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.0569] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.0753] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.0846] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.1009] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.1056] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.1122] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.1221] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.1496] [I] [pakcoin] External share accepted: D=0.008
> [2018-11-12 23:22:12.2534] [I] [pakcoin] External share accepted: D=0.008

> [2018-11-12 23:17:13.5236] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:17:13.5317] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:17:15.9638] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:17:27.9643] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:19:30.4779] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:19:30.4973] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:19:30.5293] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:19:30.5649] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:19:30.5705] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:19:30.5825] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:19:36.8055] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:19:36.8196] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:20:06.5603] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:20:22.5647] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:20:22.5701] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:20:22.5701] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found
> [2018-11-12 23:20:22.6047] [I] [pakcoin] [0HLI8U99PP96R] Share rejected: job not found
> [2018-11-12 23:20:53.8774] [I] [pakcoin] [0HLI8U99PP96Q] Share rejected: job not found

### Reproduces how often

100%

### Version

released version : v44
os version : ubuntu 16:04 

### Additional Information

network saturation: none
db performance issue: none

miningcore master config file:
```

{
  "logging": {
    "level": "debug",
    "enableConsoleLog": false,
    "enableConsoleColors": true,
    "logFile": "mc.log",
    "logBaseDirectory": "",
    "perPoolLogFile": true
  },
  "banning": {
    "manager": "integrated",
    "banOnJunkReceive": true,
    "banOnInvalidShares": false
  },
  "notifications": {
    "enabled": true,
    "email": {
      "host": "",
      "port": ,
      "user": "",
      "password": "",
      "fromAddress": "",
      "fromName": ""
    },
    "admin": {
      "enabled": true,
      "emailAddress": "john@doe.com",
      "notifyBlockFound": true
    }
  },
  "persistence": {
    "postgres": {
      "host": "x.x.x.x",
      "port": xxxx,
      "user": "xxxxxxxxxxx",
      "password": "xxxxxxxxxxxxxxxxxxx",
      "database": "xxxxxxxxx"
    }
  },
  "shareRelays": [
    {
      "Url": "tcp://x.x.x.x:xxxx",
      "sharedEncryptionKey": "xxxxxxxx"
    }
  ],
  "paymentProcessing": {
    "enabled": true,
    "interval": 600,
    "shareRecoveryFile": "/logger/recovered-shares.txt",
    "minersPayTxFees": true,
    "WalletPassword": "xxxxx",
    "HasLegacyDaemon": true
  },
  "api": {
    "enabled": false
  },
  "pools": [
    {
      "id": "pakcoin",
      "enabled": true,
      "coin": "pakcoin",
      "hasLegacyDaemon": true,
      "enableInternalStratum": false,
      "address": "xxxxxxxxxxxxxxxxxxxxxxx",
      "rewardRecipients": [
        {
          "address": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
          "percentage": 0.75
        }
      ],
      "blockRefreshInterval": 1000,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "daemons": [
        {
          "host": "x.x.x.x",
          "port": xxxx,
          "user": "aaaaaaaaa",
          "password": "aaaaaaaaaaaaaa"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "HasLegacyDaemon": true,
        "WalletPassword": "xxxxx",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }
  ]
}


```
miningcore slave config:

```
{
  "logging": {
    "level": "info",
    "enableConsoleLog": false,
    "enableConsoleColors": true,
    "logFile": "mc.log",
    "logBaseDirectory": "/logger",
    "perPoolLogFile": true
  },
  "banning": {
    "manager": "integrated",
    "banOnJunkReceive": true,
    "banOnInvalidShares": false
  },
  "notifications": {
    "enabled": false,
    "admin": {
      "enabled": false
    }
  },
  "paymentProcessing": {
    "enabled": false
  },

  "persistence": {},
  "api": {
    "enabled": false
  },
  "shareRelay": {
    "publishUrl": "tcp://0.0.0.0:6006",
    "sharedEncryptionKey": "xxxxxxxx"
  },
  "pools": [
    {
      "id": "pakcoin",
      "enabled": true,
      "coin": "pakcoin",
      "hasLegacyDaemon": true,
      "address": "xxxxxxxxxxxxxxxxxxxx",
      "rewardRecipients": [
        {
          "address": "xxxxxxxxxxxxxxxxxx",
          "percentage": 0.75
        }
      ],
      "blockRefreshInterval": 1000,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "5050": {
          "listenAddress": "0.0.0.0",
          "difficulty": 512,
          "name": "ASIC MINING",
          "varDiff": {
            "minDiff": 64,
            "targetTime": 15,
            "retargetTime": 120,
            "variancePercent": 30

          }
        }
      },
      "daemons": [
        {
          "host": "x.x.x.x",
          "port": xxxx,
          "user": "xxxxxxxx",
          "password": "xxxxxxxxxxxxxxxx"

        }
      ]
    }
  ]
}

```

**Comment by oliverw** [comment]
That's strange because nothing was changed in that area over the last releases. And I'm not experiencing similar issues at coinfoundry.org.

**Comment by oliverw** [comment]
See 42543fde254a6962e78f316e671e5ea898d16afe

**Comment by soplainjustliketofu** [comment]
will arrange the downtime to apply the fix. will share with you the outcome within 24hrs . thanks @oliverw

**Comment by bitspill** [comment]
@oliverw Yes, removing the `validJobs.clear()` seems good to me on a high level since the work was still put in for said jobs so they should be credited with a share contribution even if the network has moved to a new block.

My one concern I haven't looked into yet is what happens if one of these old jobs turns out to be a valid block, will it proceed through the standard calls and be recognized as an orphan or will there be any weird states caused?

**Comment by oliverw** [comment]
@bitspill The block would be submitted as usual and either get rejected by the daemon or become an orphan.

**Comment by soplainjustliketofu** [comment]
I can confirm this issue has been resolved  by for your fix .
