### ISSUE TITLE
Could you add a GlobalToken (GLT)?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#47]
Dears,

Could you add a GlobalToken? it uses a same algorithm of Bitcoin but PoolMiningEngine does not have its information.

GlobalToken info
"name": "GlobalToken",
"symbol": "GLT",
"algorithm": "sha256"

Diff information
Min Diff: 1
Max Diff: 83,886,080

Website:
www.globaltoken.org

Chaininfo URL
https://www.blockexperts.com/glt
https://bchain.info/GLT/

Blockexplorer URL
https://www.blockexperts.com/glt/hash/
https://bchain.info/GLT/hash/

Transactionexplorer URL
https://www.blockexperts.com/glt/tx/
https://bchain.info/GLT/tx/

Thanks in advance.
Regards,
John Ahn

**Comment by oliverw** [comment]
Shouldn't be problem. But I would need someone to test the implementation on a real network of that coin. If you could do that I could implement the coin.

**Comment by jeong760** [comment]
@oliverw thanks and I've already fully tested a GLT using nomp mining pool until today. so if you asking me then I will implement a GLT using a miningcore and test again.

**Comment by oliverw** [comment]
@jeong760 To be clear, do you want to make a pull request with the actual code changes or are you offering to run a GLT test pool to verify that any changes I make actually work?

**Comment by jeong760** [comment]
@oliverw I mean that I use another mining pool software so now I cannot make any PR.

**Comment by jeong760** [comment]
@oliverw Thanks for the comment.  Today I've added a GLT on miningcore and now I am making a test run to see new blocks mint or not.

**Comment by jeong760** [comment]
@oliverw I modified following code of miningcore

ClusterConfig.cs
CoinMataData.cs
BitcoinPayoutHandler.cs
BitcoinPool.cs
BitcoinProperties.cs

Regards,
John Ahn

**Comment by jeong760** [comment]
@oliverw  Just before I found a new block of GLT so it seems work as normal. 
Could you add a GLT in your supported coin list?

[2017-11-12 18:55:16.9602] [I] [BTC] [Pool] [0HL99MA8HM2V3] VarDiff update to 5500
[2017-11-12 18:55:19.0884] [I] [GLT] [Bitcoin Job Manager] Submitting block 255482 [0000000000000cbee695f595e451514758ce9cd5eb1dcebd628b4ed9bf32015d]
[2017-11-12 18:55:19.1770] [I] [GLT] [Bitcoin Job Manager] Daemon accepted block 255482 [0000000000000cbee695f595e451514758ce9cd5eb1dcebd628b4ed9bf32015d]

Regards,
John Ahn

**Comment by oliverw** [comment]
Will be resolved by merging your PR. Thanks for your contributions!
