### ISSUE TITLE
What triggers the confirmation progress update?

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#471]
I've noticed lately (last couple releases) it seems like the confirmation progress has been way off on the actual progress of confirmation.  I've set the correct minimumConfirmations in the config and the percentage it shows is correct when it updates but it seems to take a long time to update.  I have one coin that has a block maturity of 15, the block actually has 26+ confirmations (2 min block time) and my api is reporting it at 81% confirmed.  The wallet has already moved that block from immature to mature as well.

Is there a way to get this more inline/quicker to update?

**Comment by oliverw** [comment]
Update frequency is determined by the interval at which the PayoutManagerruns. 

https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Payments/PayoutManager.cs#L242

**Comment by calebcall** [comment]
thanks
