### ISSUE TITLE
BCD payout error - invalid amount code -3

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#474]
### Description

Found a block on BCD, now when it tries to payout, it's getting an error of the following:
```
[2018-11-14 19:00:55.1485] [I] [BCD] [Bitcoin Payout Handler] Paying out 30.27362 BCD to 16 addresses
[2018-11-14 19:00:55.1793] [E] [BCD] [Bitcoin Payout Handler] sendmany returned error: Invalid amount code -3
```

So different from the "insufficient funds" message.  The entire block (125 BCD) is sitting in the available balance so it has an available balance to send 30 BCD from.

### Reproduces how often

100% of the time when the payout interval rolls around.

### Version

Latest (v44)

**Comment by oliverw** [comment]
Everything based on very new Bitcoin Core versions is exhibiting that problem. The fix for this is already on the dev branch: efafcf4acbb03460dd07a6cb4de0e3c49ddcb208

**Comment by calebcall** [comment]
Great, thank you!

**Comment by calebcall** [comment]
Fixed, thanks!

**Comment by idanzam** [comment]
I have the same issue...
and whats u suugest above :
https://github.com/oliverw/miningcore/commit/efafcf4acbb03460dd07a6cb4de0e3c49ddcb208

already fix in the last version...

[Bitcoin Payout Handler] sendmany returned error: Account has insufficient funds code -6
