### ISSUE TITLE
Merged mining support for same algorithm like following?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#48]
Dears,

How can I setup a merged mining using  MiningPoolEngine for following coins?
- Bitcoin and Namecoin  and GlobalToken
- Dogecoin and Litecoin

Thanks in advance.
Regards,
John Ahn

**Comment by oliverw** [comment]
There are configuration examples for several coins in the examples folder of the repository. Other coins such as Bitcoin should only involve changing the coin type. Namecoin and GlobalToken are currently not supported and would require minor code changes. Feel free to contribute them. 😄

**Comment by goodthebest** [comment]
@jeong760 any luck with merged mining? I'm trying LTC with Dogecoin but no success.
