### ISSUE TITLE
Effort, Reward, Type, Status problem with API

### ISSUE THREAD

**Issue by uurcm16** [coinfoundry/miningcore#485]
### Description

Running Parity and MiningCore, mining seems to be fine but;
When I get the results via **WebAPI**, 

**But when I check the database, i saw that theese values are null/0 in database too"

http://prntscr.com/lmf9ws

1. Effort is **always null**
2. Reward is **always 0**
3. Type is **always null**
4. Status is **always pending**

Is there something that I miss?

### Steps to Reproduce

1. Rent hashpower from NiceHash
2. Mine and find blocks,
3. Check the block from API

### Expected behavior
1. Effort should be some value
2. Reward should be the block reward
3. Type should be block/uncle
4. Status should change

### Actual behavior

1. Effort is **always null**
2. Reward is **always 0**
3. Type is **always null**
4. Status is **always pending**

### Reproduces how often

Always

### Version

Dev #484 
Running on windows 10

### Additional Information
**API Response**
`  {
    "poolId": "EthereumClassic-Test",
    "blockHeight": xxxxx,
    "networkDifficulty": 151966922499457.0,
    "status": "pending",
    "type": null,
    "confirmationProgress": 0.0,
    "effort": null,
    "transactionConfirmationData": "xxxxx:xxxx",
    "reward": 0.000000000000,
    "infoLink": "https://gastracker.io/block/xxxx",
    "hash": "xxx",
    "miner": "xxxx",
    "source": null,
    "created": "2018-11-24T10:25:38.113714"
  }`

**Config**
`{
  "logging": {
    "level": "info",
    "enableConsoleLog": true,
    "enableConsoleColors": true,
    "logFile": "C:\\mLogger\\log.txt",
    "logBaseDirectory": "",
    "perPoolLogFile": false
  },
  "api": {
    "enabled": true,
    "listenAddress": "000.000.000.000",
    "port": 4000,
    "metricsIpWhitelist": [],
    "rateLimiting": {
      "disabled": false, // disable rate-limiting all-together, be careful
      // override default rate-limit rules, refer to https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware#defining-rate-limit-rules
      "rules": [
        {
          "Endpoint": "*",
          "Period": "1s",
          "Limit": 5
        }
      ],
      "ipWhitelist": []
    }
  },
  "banning": {
    "manager": "integrated",
    "banOnJunkReceive": true,
    "banOnInvalidShares": false
  },
  "notifications": {
    "enabled": false,
    "email": {
      "host": "smtp.example.com",
      "port": 587,
      "user": "user",
      "password": "password",
      "fromAddress": "info@yourpool.org",
      "fromName": "support"
    },
    "admin": {
      "enabled": false,
      "emailAddress": "user@example.com",
      "notifyBlockFound": true
    }
  },
  "persistence": {
    "postgres": {
      "host": "127.0.0.1",
      "port": 6344,
      "user": "miningcore",
      "password": "pwd",
      "database": "miningcore"
    }
  },
  "paymentProcessing": {
    "enabled": true,
    "interval": 600,
    "shareRecoveryFile": "recovered-shares.txt"
  },
  "pools": [
    {
      "id": "EthereumClassic-Test",
      "dagDir": "C:/dagTEST",
      "enabled": true,
      "coin": "ethereum-classic",
      "address": "wallet",
      "rewardRecipients": [
        {
          "type": "op",
          "address": "wallet",
          "percentage": 0
        }
      ],
      "blockRefreshInterval": 500,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "16001": {
          "listenAddress": "000.000.000.000",
          "difficulty": 1.7
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 8545,
          "user": "wallet",
          "password": ""
        }
      ],
      "paymentProcessing": {
        "enabled": false,
        "minimumPayment": 0.01,
        "minimumPaymentToPaymentId": 5.0,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        },
        "coinbasePassword": "<your wallet password if you are running parity with wallet locked>",
        "keepUncles": false,
        "keepTransactionFees": false
      }
    }
  ]
}`

**Comment by oliverw** [comment]
You didn't state which API.

**Comment by uurcm16** [comment]
> You didn't state which API.

It is WebAPI. And edited the issue.

**Comment by oliverw** [comment]
I need an URL relative to the API Endpoint to look into it.

**Comment by uurcm16** [comment]
> I need an URL relative to the API Endpoint to look into it.

http://213.14.165.7:4000/api/pools/EthereumClassic-Test/blocks?page=0&pageSize=100

**Comment by uurcm16** [comment]
> I need an URL relative to the API Endpoint to look into it.

I've posted the URL an hour ago and my private pool started getting attacked :D 
Here is the screenshot of the block requests from API.

http://prntscr.com/lmf9ws

**Comment by calebcall** [comment]
Effort is null until the block starts to confirm, then it will update.  Reward is 0 until the block fully confirms, then it will report actual awards. Type always stays null, not sure what it's supposed to show.  Status will go from Pending to either Confirmed once it confirms or to Orphaned if it orphans.

Here's a sample output from mine:
```
{
    "poolId": "HTH",
    "blockHeight": 131917,
    "networkDifficulty": 23035.13950120653,
    "status": "confirmed",
    "type": null,
    "confirmationProgress": 1,
    "effort": 1.8917185197735653,
    "transactionConfirmationData": "33ebc8ee40384e2bc89c497812c15d1738e8c4332e4144610f77bee7da2a5cfb",
    "reward": 1406.25,
    "infoLink": "http://explorer.hthcoin.world/block/0000000000b2697926fde6b3e2d08e77a8beac6d43c482b58afda5c22527425b",
    "hash": "0000000000b2697926fde6b3e2d08e77a8beac6d43c482b58afda5c22527425b",
    "miner": "HDLxAiYLcoFTtJwyEbqtpmdV176MNzoemA",
    "source": null,
    "created": "2018-10-05T12:35:43.272054"
  },
```

**Comment by oliverw** [comment]
@calebcall Type is only used for the Ethereum family, where a block can become an "uncle".

**Comment by uurcm16** [comment]
@oliverw @calebcall  I think the problem was the PaymentProcessor. It was DISABLED due to my config file. 
When I look into code, I saw that theese properties getting updated by the PaymentProcessor. Enabled it, and fixed all.

**Comment by calebcall** [comment]
Yep, that would do it. The block stats update whenever the payment processor runs.
