### ISSUE TITLE
SUQA info

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#488]
Added SUQA but it looks like the recorded hashrate is quite a ways off.  Doing the math it appears it needs about a 175 multiplier, is that correct?

I tried to add "hashrateMultiplier": 175, to my coin config but it didn't seem to do anything to the reported hashrate.  I seem to remember something about multiplier being removed but can't remember if it was hashrateMultiplier or not.

Also, does this look correct for the coin config?
```
"suqa1": {
    "name": "SUQA",
    "symbol": "SUQA",
    "family": "bitcoin",
    "coinbaseHasher": {
      "hash": "sha256d"
    },
    "headerHasher": {
      "hash": "x22i"
    },
    "blockHasher": {
      "hash": "reverse",
      "args": [{ "hash": "x22i" }]
    },
    "shareMultiplier": 256,
    "hashrateMultiplier": 175,    
    "explorerBlockLink": "http://suqaexplorer.com/block/$hash$",
    "explorerTxLink": "http://suqaexplorer.com/tx/{0}",
    "explorerAccountLink": "http://suqaexplorer.com/address/{0}"
  },
```

**Comment by oliverw** [comment]
Be advised that support for <code>hashrateMultiplier</code> was dropped in v45.

**Comment by oliverw** [comment]
I think <code>shareMultiplier</code> has to be removed.

**Comment by calebcall** [comment]
Thanks.  Removing `shareMultiplier` got it in to the range but it's still a little low.  My test miner is reporting 7.7 Mh/s and the pool is reporting 5.7 Mh/s.  Before removing it, it was reporting ~30Kh/s.

**Comment by oliverw** [comment]
Hmm. Did you let it stabilize for like 15-20 mins?

**Comment by calebcall** [comment]
Yeah, it had been running for 20-30 minutes when it was reporting 5.7 Mh/s.  However, I just checked it again (been running this whole time) and it's now reporting ~38 Kh/s again.  Miner is still reporting 7.7 Mh/s.

**Comment by saltyminer** [comment]
I am having the same issue @calebcall, did you have luck with removing the sharemultiplier?

**Comment by calebcall** [comment]
It appeared to help at first but about an hour later it was back to reporting the hash as ~1/175th actual hash.

**Comment by calebcall** [comment]
Well, finally was able to take another look at this and it looks like my config management system had put the wrong config back in place...hence the reason values went back to what they were.  I corrected that and now hashrates look to be correct.
