### ISSUE TITLE
New payee config parameter?

### ISSUE THREAD

**Issue by calebcall** [coinfoundry/miningcore#502]
Looks like for SUQA you added a `hasPayee` config, is that correct?  I added x21s (looks like you did too so I won't open a PR for mine.) but for the blocks I get, I'm getting blocks rejected with `bad-cb-dev-fee`.  I tried adding `"hasPayee": true` to my config but it's still throwing the same error.  Also, for SUQA, I assume I need to add that parameter? (I've had no miners on SUQA so it hasn't been an issue)

**Comment by oliverw** [comment]
Yes Suqa needs hasPayee.
