### ISSUE TITLE
Use Wiki for not-that-important info in README

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#51]
@oliverw can you create Wiki pages (can't do that on my end)? I think API, configuration in README can move into Wiki pages.
We should avoid a super long README.

**Comment by oliverw** [comment]
Already thought about that myself. Good idea.

**Comment by calvintam236** [comment]
@oliverw I will get it done in the next hour. 👍

**Comment by 2zo** [comment]
Can translate on Russian

**Comment by oliverw** [comment]
@2zo Thanks for the kind offer but I think we'll stick to english only for now.
