### ISSUE TITLE
worker name parameter

### ISSUE THREAD

**Issue by tenlans** [coinfoundry/miningcore#514]
- **Parity Ethereum version**: 2.0.9-stable
- **Operating system**: Linux Ubuntu 16.04
- **Installation**: binary
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

I use mineros to connect pool, but it can't set [WalletAddress.WorkerName]
Does the miningcore supports eworker parameter? or other parameter to set worker name?

**Comment by oliverw** [comment]
Yes it does.

<code>0xcb55abBfe361B12323eb952110cE33d5F28BeeE1.myworker1</code>
