### ISSUE TITLE
MiningCore UI

### ISSUE THREAD

**Issue by admimpool4blocks** [coinfoundry/miningcore#517]
### Description ###

Sorry for open a NOT real issue!!!

I want just introduce my UI for MiningCore, it is published on pool4blocks.com

I'm working on, when finish I will publish on github.

If you like or you have suggestion, send me email.

www.pool4blocks.com

**Comment by tommyleo** [comment]
wow really cool!

**Comment by McKenzy83** [comment]
Really Nice! Would you share it with us ? I try in the next few days the same and hope to support the Community... 

Best regards

**Comment by ultra-pool** [comment]
@adminpool4blocks How were you able to add other coins that were not on the support list? I have some coins that are on the support that dont even work on miningcore. Iv been able to get 1 coin that works with miningcore so far out of the 10 coins Iv been trying to get to work.

**Comment by calebcall** [comment]
@ultra-pool If the algo and block template is already supported, then it's just a matter of adding the coins to your own coins.json, defining that in your config.json, and then defining the coin also in config.json (it's pretty simple really).  If it's not an algo or block template that's currently supported, then there's a fair bit more more to do and not really something that's straight forward.

**Comment by minernl** [comment]
Looks nice. I have also a simple Miningcore.UI

https://github.com/minernl/Miningcore.UI

Working on the main page with the pools list.

Live at:   http://eth02.coinstomine.eu
