### ISSUE TITLE
eth blocks orphaned 

### ISSUE THREAD

**Issue by co11ter** [coinfoundry/miningcore#519]
### Description

Mining core sets eth blocks status to orphaned.

### Steps to Reproduce

1. Up ```parity --author 0x0Aaf1317b31289ecB455A090C6C16613f652058C```
2. Set ```"address": "0x0Aaf1317b31289ecB455A090C6C16613f652058C"``` to ethereum pool config
3. Start miningcore and mining
4. Check block statuses in ```/api/pools/eth/blocks``` after payment processing

### Expected behavior

Block statuses is confirmed

### Actual behavior

Block statuses is orphaned 

### Reproduces how often

Always

### Version

OS: Archlinux
Version: master

### Additional Information

It happens because parity send blockInfo.Miner in lower case, but poolConfig.Address isn't: https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs#L152

So, block statuses will be orphaned always.

**Comment by labud888** [comment]
Hi, put a lowcase wallet address in config.json to solve these problems.

**Comment by co11ter** [comment]
> Hi, put a lowcase wallet address in config.json to solve these problems.
> 0x77e5D9264c3981c02cF3bBb64d1F676Fe59bf694
> 0x77e5d9264c3981c02cf3bbb64d1f676fe59bf694

Yes, i solved it. But that is bad behavior, isn't it?

**Comment by labud888** [comment]
Yep, first you have to check what you compare and then compare.
