### ISSUE TITLE
Doesn't read any coin daemon's and not connecting Postgresql

### ISSUE THREAD

**Issue by ultra-pool** [coinfoundry/miningcore#520]
Problem #1 - Not connecting to any coin daemons. Iv tried over 8 of them.
Raven, Stronghands, Gives Coin, Help the homeless, Digibyte, Bitcoin, LiteCoin about 3 others

Problem #2 - Not connecting to Postgresql.

Can this be edited to use MySQL? Something much more stable?
Tested on Ubuntu 16 LTS & Window 2012 server. Same results

**Comment by ultra-pool** [comment]
[2018-12-25 18:05:16.2244] [I] [gives] Waiting for daemons to come online ...

 in the coins.json edited out the gives links.
    },
	    "gives": {
      "name": "Gives Coin",
      "symbol": "GIVES",
      "family": "bitcoin",
      "coinbaseHasher": {
        "hash": "sha256d"
      },
      "headerHasher": {
        "hash": "scrypt"
      },
      "blockHasher": {
        "hash": "reverse",
        "args": [{ "hash": "scrypt" }]
      },
      "explorerBlockLink": "http://*****/block/$height$",
      "explorerTxLink": "http://******/tx/{0}",
      "explorerAccountLink": "http://********/address/{0}"
    },
Postgresql is some what working.

**Comment by calebcall** [comment]
If nothing is connecting , this sounds more like a localized problem.  Firewall maybe?  Bad Credentials?  Bad Config?  Post up your config.json.  Also post your raven.conf config from your daemon (or whatever daemon you have configured).  In all of the above, be sure to remove passwords.

FWIW, postgres is every bit (if not more so) as stable as mysql.  So there's no value in adding mysql support.

**Comment by ultra-pool** [comment]
Postgresql is connecting now. 

Miningcore isnt seeing the daemon of anything atm. Made sure that the needed ports for each wallet is allowed. I will retrying HTH again later.

**Comment by ultra-pool** [comment]
HTH update:
[2018-12-26 19:56:31.6020] [I] [help-the-homeless] Waiting for daemons to connect to peers ...
[2018-12-26 19:56:41.8544] [I] [help-the-homeless] Waiting for daemons to connect to peers ...
[2018-12-26 19:56:52.1062] [I] [help-the-homeless] Waiting for daemons to connect to peers ...
[2018-12-26 19:57:02.3592] [I] [help-the-homeless] Waiting for daemons to connect to peers ...

wallets/HTH/src$ ./hth-cli getinfo
{
  "version": 1020000,
  "protocolversion": 70207,
  "walletversion": 61000,
  "balance": 0.00000000,
  "privatesend_balance": 0.00000000,
  "blocks": 245287,
  "timeoffset": 0,
  "connections": 31,
  "proxy": "",
  "difficulty": 87.6067737842227,
  "testnet": false,
  "keypoololdest": 1545870620,
  "keypoolsize": 1001,
  "paytxfee": 0.00000000,
  "relayfee": 0.00010000,
  "errors": ""
}

**Comment by ultra-pool** [comment]
Able to get 1 coin working out 10 that i would like to add.
