### ISSUE TITLE
Mining pool fee not doesnt work when blocks are paid out

### ISSUE THREAD

**Issue by ultra-pool** [coinfoundry/miningcore#522]
"pools": [
        {
            // DON'T change the id after a production pool has begun collecting shares!
            "id": "paccoin",
            "enabled": true,
            "coin": "paccoin",
            // Address to where block rewards are given (pool wallet)
            "address": "PP49YYuhBABafn2E5jgJSx8bx59bS99rMF",
            // Block rewards go to the configured pool wallet address to later be paid out
            // to miners, except for a percentage that can go to, for examples,
            // pool operator(s) as pool fees or or to donations address. Addresses or hashed
            // public keys can be used. Here is an example of rewards going to the main pool
            // "op"
            "rewardRecipients": [
                {
                    // Pool wallet
                    "address": "PLwLhJPABRPbGfiNnc53MzDifLcYAze28h",
                    "percentage": 1.5

PLwLhJPABRPbGfiNnc53MzDifLcYAze28h is my desktop wallet which the pool fees need to go to.
PP49YYuhBABafn2E5jgJSx8bx59bS99rMF is the address on my server that the pool reads.

Do i have this backwards or something? The server wallet hasn't gained amount and no fees have been sent to my desktop wallet after blocks have been found and paid.

**Comment by calebcall** [comment]
Just curious, is the 1.5 percent still sitting in the pool wallet?  What do the logs show when the payout happens?

**Comment by ultra-pool** [comment]
Nope. Balance hasn't changed. its paying out the 100% minus the TX fees to the miners.
