### ISSUE TITLE
Adding support for mimblewimble (beam, grin)

### ISSUE THREAD

**Issue by Flazky** [coinfoundry/miningcore#523]
Add support for MimbleWimble protocol Beam and Grin

Coin Family - Grin MimbleWimble
Proof of work algo - Cuckoo cycle
Github Repo https://github.com/mimblewimble/grin
Website http://grin-tech.org/

Coin Family - Beam
Proof of work algo - Equihash 150
Github Repo  https://github.com/BeamMW/beam
Website https://beam.mw

**Comment by calvintam236** [comment]
This has merged into #853.
