### ISSUE TITLE
Shares table table get dirty with alot of dead data

### ISSUE THREAD

**Issue by LunarExplorer** [coinfoundry/miningcore#525]
### Description

[Shares table gets alot of dead data churning aprox 600K shares per block]
Auto vacuum does not seem to help. Has there been any thoughts of using table partitions and partition drops instead of deletes? 

### Steps to Reproduce

1. Run pool
2. Monitor gradual payment process backlog growth
3. See that block status in API is unconfirmed for longer than (coinbase maturity)
Share table size is infinitely growing.

### Expected behavior
Process is fast and does not degrade in time.

### Actual behavior

Process slows down and difficulty increases payment processor latency increase.

### Reproduces how often

Systematically reproducible with 250K - 600K shares per block.

**Comment by oliverw** [comment]
Coinfoundry is using PostgreSQL 10's partitions. 

```
CREATE TABLE SHARES_btc1 PARTITION OF shares FOR VALUES IN ('btc1');
CREATE INDEX IDX_SHARES_CREATED_btc1 ON SHARES_btc1(created);
CREATE INDEX IDX_SHARES_MINER_DIFFICULTY_btc1 on SHARES_btc1(miner, difficulty);
```

**Comment by oliverw** [comment]
Instructions for an improved database setup based on PostgreSQL 11 have been added to the readme.
