### ISSUE TITLE
Block notify email

### ISSUE THREAD

**Issue by stalizard** [coinfoundry/miningcore#526]
### Description

Upgraded to V45 from V40 and no longer recieve email notifications.

### Steps to Reproduce
Run V40 and get emails for block submissions

### Expected behavior

Recieve email

### Actual behavior

No email sent,  nothing in logfile.

### Reproduces how often

100%

### Version

V45

**Comment by stalizard** [comment]
Email is working for failed submission,  just not actual good block submission.

**Comment by oliverw** [comment]
This is now fixed in the dev branch.

**Comment by stalizard** [comment]
Manually made the change on my end recompiled and working as intended.  Thanks Oliver
