### ISSUE TITLE
Orphaned blocks on LCC

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#528]
I tried to setup mining pool using miningcore and litecoin cash on the main network, but I keep gettin orphaned blocks. Please correct me if I'm doing something wrong.

### Description

Keep getting Orphaned block on LCC mining.

### Steps to Reproduce
1- Ran the litecoincashd using following config:
```
rpcuser=user
rpcpassword=pass
rpcallowip=0.0.0.0/0
server=1
listen=1
daemon=1
gen=0
------ I added the bellow lines after the second orphan block
block_nTime=1317972665
block_nNonce=2084524493
```
2-I ran the litecoincash-cli getnewaddress command 3 times to get 3 new wallet address:
w1: MJndbgSjR8yp2kdtZMGrFya3zyDEUQa29x    
w2: MUNLbdJy1reUF79uXEFy29QFvmJPUb5ARK    
w3: MWLCYmBqSsSDndNmmAMurkPcrZvH7AuZmq

3- setup the pool config in config.json as follow:
{
      "id": "lcc",
      "enabled": true,
      "coin": "litecoin-cash",
      "address": "MJndbgSjR8yp2kdtZMGrFya3zyDEUQa29x",
      "rewardRecipients": [
        {
          "address": "MUNLbdJy1reUF79uXEFy29QFvmJPUb5ARK",
          "percentage": 1
        }
      ],
      "blockRefreshInterval": 500,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": false,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "41666": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1024,
          "varDiff": {
            "minDiff": 512,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          },
        "41667": {
          "listenAddress": "0.0.0.0",
          "difficulty": 15000,
          "varDiff": {
            "minDiff": 4096,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "89.42.210.101",
          "port": 62457,
          "user": "user",
          "password": "pass"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 2,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2
        }
      }
    }

3- setup the ASIC to mine on the port 41667 with the 3rd wallet I created (MWLCYmBqSsSDndNmmAMurkPcrZvH7AuZmq) and I got a hashrate around 190 TH

### Expected behavior
Not getting orphaned blocks

### Actual behavior

I mined the following blocks so far:
[https://chainz.cryptoid.info/lcc/block.dws?1550421.htm](https://chainz.cryptoid.info/lcc/block.dws?1550421.htm)
[https://chainz.cryptoid.info/lcc/block.dws?1550380.htm](https://chainz.cryptoid.info/lcc/block.dws?1550380.htm)
[https://chainz.cryptoid.info/lcc/block.dws?1550375.htm](https://chainz.cryptoid.info/lcc/block.dws?1550375.htm)

as you can see none of the rewards wen to my [wallet](https://chainz.cryptoid.info/lcc/address.dws?MJndbgSjR8yp2kdtZMGrFya3zyDEUQa29x.htm) but the all wen to another address:
[CTMMwHtPoAnY3DZz27wqbDak9sYUk9RPT2](https://chainz.cryptoid.info/lcc/address.dws?CTMMwHtPoAnY3DZz27wqbDak9sYUk9RPT2.htm)

Now my question is if these blocks are orphaned they all should go to someone else's wallet, right? why they all keep founding in the SAME wallet address which does not belongs to me(CTMMwHtPoAnY3DZz27wqbDak9sYUk9RPT2)? 

### Reproduces how often

Always

### Version

Latest version

**Comment by peysab** [comment]
No I changed both addresses in the config.json to a new address: [MUGqjTwFcA71xUXqtsWBeziAV8RSPUX2yQ](https://chainz.cryptoid.info/lcc/address.dws?MUGqjTwFcA71xUXqtsWBeziAV8RSPUX2yQ.htm)

and now I mined the 4th block [1550445](https://chainz.cryptoid.info/lcc/block.dws?1550445.htm) and the reward went to [Ccqa55NuzBujxwTwMeBAzEire2kgmrFVDk](https://chainz.cryptoid.info/lcc/address.dws?Ccqa55NuzBujxwTwMeBAzEire2kgmrFVDk.htm) address which is different from the previous one. what am I doing wrong????

**Comment by minernl** [comment]
Check the account address your network/wallet daemon is using.
that should be the same as your pool address in the config.json

**Comment by peysab** [comment]
how can I check that? is it the one:
`litecoincash-cli getaccountaddress ""`
if yes they are same, but still not explaining why all my orphan block are going to SAME address, shouldn't it be different addreses?

**Comment by calebcall** [comment]
I don't know anything about LCC but are these segwit addresses?  If so, try and issue a legacy address for the pool address and see if that helps.

**Comment by peysab** [comment]
Thanks for your reply @calebcall , but how can I be sure If the wallet is SegWit or not?
when I'm useing this command `litecoincash-cli getaddressesbyaccount  ""` it shows my wallet in the list

**Comment by peysab** [comment]
Now I ran the SUQA as well and have the same issue with that one. but for HTH it is all good.
Is there anything I need to set for SUQA? I remember I read somewhere about setting the Payee, but have no idea how to do that.
