### ISSUE TITLE
Mining Issue on Ethereum family

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#529]
### Description
I was never able to setup the mining rig to mine any ethereum family coins on miningcore. The stratum closes the connection immediately after the connection accepted. Is this a known issue to miningcore? I'm asking because I even had the same problem when I wanted to mine ETC on https://coinfoundry.org/ and when I told @oliverw he removed ETC from the pool.

[Description of the issue]
Here is the log for the miningcore:
![image](https://user-images.githubusercontent.com/22977536/51434103-85219000-1cad-11e9-973f-6337e80c29a5.png)

Here is the log for mining rig:
![image](https://user-images.githubusercontent.com/22977536/51434051-599ea580-1cad-11e9-9eaa-a3b8fb3b8e71.png)

### Expected behavior
Start mining Without issue.

### Actual behavior
Closing the connection immediately.

### Reproduces how often

100%

### Version
Latest version

### Additional Information

I tried to debug this by pointing the mining rig to my local and here is the error I'm getting:
![image](https://user-images.githubusercontent.com/22977536/51434173-b77fbd00-1cae-11e9-8a23-1254fd734be2.png)
I tried this on the following chains using parity: Classic Kovan Mainnet Testnet and the result was always the same, Is this normal?

**Comment by eketubol** [comment]
First thing I would check is if you have allowed the port through the firewall on Windows.

**Comment by peysab** [comment]
I turned of the firewall on windows, but I have the same error on Production server which is ubuntu and I am pretty sure I opened the ports, have you been able to run for ETH ot ETC?

**Comment by btully** [comment]
I am having the same problem with eth-proxy.  Can anyone confirm that eth mining works this release?

![image](https://user-images.githubusercontent.com/5323824/52887713-c12e0080-3146-11e9-9760-27b200170b1c.png)

**Comment by peysab** [comment]
@oliverw , is mining core currently working with eth or etc or any ethash algo family? and why you removed etc from coinfoundry?

**Comment by oliverw** [comment]
It should be working yes. We've dropped ETH and ETC because all the trouble working with Geth and Parity was not worth the hassle anymore.
