### ISSUE TITLE
Unable to get cgminer work with pool

### ISSUE THREAD

**Issue by samanshahmohamadi** [coinfoundry/miningcore#533]
[Description of the issue]
Hi, I'm trying to connect a cgminer instance to minincore pool on my local machine. The pool is up and healthy, but I don't know how exactly to connect to pool via cgminer command.
I tried this:  
`./cgminer -o 0.0.0.0:3052 --user MY_RPC_USERNAME --pass MY_RPC_PASSWORD `  

when the pool config related section is:  
```
"ports": {
   "3052": {
     "listenAddress": "0.0.0.0",
...
```
And this is what I see in the miningcore log:

> [2019-01-30 16:25:49.8665] [I] [btc-1] [0HLK6LUSCB4M4] Accepting connection from ::ffff:127.0.0.1:53970 ... 
[2019-01-30 16:25:49.8665] [I] [btc-1] [0HLK6LUSCB4M4] Connection from ::ffff:127.0.0.1:53970 accepted on port 3052 
[2019-01-30 16:25:49.8704] [I] [btc-1] [0HLK6LUSCB4M4] Banning unauthorized worker for 60 sec 
[2019-01-30 16:25:49.8704] [I] [btc-1] [0HLK6LUSCB4M4] Connection closed 

Which means the `--user` and `--pass` parameters in the cgminer command is wrong. What username and password should be used when I want to connect to pool? The rpc ones? Or something eles?

**Comment by oliverw** [comment]
Miningcore only supports ETH miners communicating using the Nicehash Ethereum Stratum Protocol.

**Comment by bitspill** [comment]
Instead of using the rpc user/pass you want to connect with the payout address and a dummy password as well as specify stratum in the connection

Along the lines of `./cgminer -o stratum+tcp://127.0.0.1:3052 -u 1111111111111111111114oLvT2 -p x`

Don't actually use that address though or all earnings will be forever burned.

**Comment by samanshahmohamadi** [comment]
@bitspill @oliverw  
Thank you both, I switched to using `minerd` instead of `cgminer`, now the `minerd` connects to pool successfully using payout address instead of rpc username. 
But I didn't get your point on last line of the comment:  
> Don't actually use that address though or all earnings will be forever burned.   

What's that mean?  
And what do you mean by *dummy password*? I can see that even with wrong password, the `minerd` is able to connect to pool via payout address. Does it mean that the password is not important at all?  
I'm using this command to run `minerd`:
```
./minerd -a sha256d --url=stratum+tcp://127.0.0.1:3052 --userpass=MY_PAYOUT_ADDRESS:THE_WRONG_PASSWORD
```
