### ISSUE TITLE
Rejected Blocks on Vert, Lyra2v3

### ISSUE THREAD

**Issue by eketubol** [coinfoundry/miningcore#534]
## Note
Please use the following format to file an issue. Issues that fail to comply will delay our responses.
Please remove this section when you submit the issue. Thank you for your cooperation.

### Description

[Description of the issue]
When running Lyra2v3 for Vert Coin I am received orphaned blocks. I have copied the information from the dev branch to allow lyra2v3 hash on miningcore but I have hit 2 blocks and both have been rejected.

### Version

I am using a clone from the main branch but added the required information to allow Lyra2v3 hash.

**Comment by eketubol** [comment]
`"pools": [
        {
            // DON'T change the id after a production pool has begun collecting shares!
            "id": "vertcoin1",
            "enabled": true,
            "coin": "vertcoin",
            // Address to where block rewards are given (pool wallet)
            "address": "35k4B5MrDjMbLbKH7JT315izXbG9FLEwXE",
            // Block rewards go to the configured pool wallet address to later be paid out
            // to miners, except for a percentage that can go to, for examples,
            // pool operator(s) as pool fees or or to donations address. Addresses or hashed
            // public keys can be used. Here is an example of rewards going to the main pool
            // "op"
            "rewardRecipients": [
                {
                    // Pool wallet
                    "address": "35k4B5MrDjMbLbKH7JT315izXbG9FLEwXE",
                    "percentage": 0.4
                }
            ],
            // How often to poll RPC daemons for new blocks, in milliseconds
            "blockRefreshInterval": 400,
            // Some miner apps will consider the pool dead/offline if it doesn't receive
            // anything new jobs for around a minute, so every time we broadcast jobs,
            // set a timeout to rebroadcast in this many seconds unless we find a new job.
            // Set to zero to disable. (Default: 0)
            "jobRebroadcastTimeout": 10,
            // Remove workers that haven't been in contact for this many seconds.
            // Some attackers will create thousands of workers that use up all available
            // socket connections, usually the workers are zombies and don't submit shares
            // after connecting. This features detects those and disconnects them.
            "clientConnectionTimeout": 600,
            // If a worker is submitting a high threshold of invalid shares, we can
            // temporarily ban their IP to reduce system/network load.
            "banning": {
                "enabled": true,
                // How many seconds to ban worker for
                "time": 600,
                // What percent of invalid shares triggers ban
                "invalidPercent": 50,
                // Check invalid percent when this many shares have been submitted
                "checkThreshold": 50
            },
            // Each pool can have as many ports for your miners to connect to as you wish.
            // Each port can be configured to use its own pool difficulty and variable
            // difficulty settings. 'varDiff' is optional and will only be used for the ports
            // you configure it for.
            "ports": {
                // Binding port for your miners to connect to
                "2120": {
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    // Pool difficulty
                    "difficulty": 25,
                    // TLS/SSL configuration
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    // Variable difficulty is a feature that will automatically adjust difficulty
                    // for individual miners based on their hash rate in order to lower
                    // networking overhead
                    "varDiff": {
                        // Minimum difficulty
                        "minDiff": 5,
                        // Maximum difficulty. Network difficulty will be used if it is lower than
                        // this. Set to null to disable.
                        "maxDiff": 65,
                        // Try to get 1 share per this many seconds
                        "targetTime": 15,
                        // Check to see if we should retarget every this many seconds
                        "retargetTime": 60,
                        // Allow time to very this % from target without retargeting
                        "variancePercent": 30,
                        // Do not alter difficulty by more than this during a single retarget in
                        // either direction
                        "maxDelta": 500
                    }
                },
				"2124": {
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    // Pool difficulty
                    "difficulty": 65,
                    // TLS/SSL configuration
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    // Variable difficulty is a feature that will automatically adjust difficulty
                    // for individual miners based on their hash rate in order to lower
                    // networking overhead
                    "varDiff": {
                        // Minimum difficulty
                        "minDiff": 65,
                        // Maximum difficulty. Network difficulty will be used if it is lower than
                        // this. Set to null to disable.
                        "maxDiff": 125,
                        // Try to get 1 share per this many seconds
                        "targetTime": 15,
                        // Check to see if we should retarget every this many seconds
                        "retargetTime": 60,
                        // Allow time to very this % from target without retargeting
                        "variancePercent": 30,
                        // Do not alter difficulty by more than this during a single retarget in
                        // either direction
                        "maxDelta": 500
                    }
				},
				"2128": {
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    // Pool difficulty
                    "difficulty": 125,
                    // TLS/SSL configuration
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    // Variable difficulty is a feature that will automatically adjust difficulty
                    // for individual miners based on their hash rate in order to lower
                    // networking overhead
                    "varDiff": {
                        // Minimum difficulty
                        "minDiff": 100,
                        // Maximum difficulty. Network difficulty will be used if it is lower than
                        // this. Set to null to disable.
                        "maxDiff": null,
                        // Try to get 1 share per this many seconds
                        "targetTime": 15,
                        // Check to see if we should retarget every this many seconds
                        "retargetTime": 60,
                        // Allow time to very this % from target without retargeting
                        "variancePercent": 30,
                        // Do not alter difficulty by more than this during a single retarget in
                        // either direction
                        "maxDelta": 500
                    }
				}
            },`

**Comment by oliverw** [comment]
Could you please check <code>vertcoind</code>'s debug.log and post the submitblock error found there?

**Comment by eketubol** [comment]
Hi mate, 

2019-02-06 09:12:35 CreateNewBlock(): block weight: 812 txs: 0 fees: 0 sigops 400
2019-02-06 09:12:51 connect() to [2001:bb6:4b3a:1f58:943e:386f:dc8a:955f]:5889 failed: Cannot assign requested address (99)
2019-02-06 09:12:52 UpdateTip: new best=2d0b0ef81a68766394ced3509e5d63a6989825da0323efcb5035a66038a3d229 height=1082658 version=0x20000000 log2_work=66.092347 tx=3524235 date='2019-02-06 09:12:50' progress=1.000000 cache=0.7MiB(5109txo)

**Comment by oliverw** [comment]
That's most likely not the error. Get the found blocks rejected by vertcoind or do they simply become orphaned?

**Comment by eketubol** [comment]
It just seems to go automatically to rejected. I have hit 4 blocks so far on Vert and all of them are rejected.

**Comment by eketubol** [comment]
I am starting to think it's not registering the blocks as I can't find anything with found blocks on the debug.log

**Comment by calebcall** [comment]
Discussed in on discord with @eketubol, I believe this is due to not using a legacy address.  I suggested he use a legacy address and it looks like he's since found a block that hasn't orphaned.

**Comment by oliverw** [comment]
@calebcall Good catch. Thanks for your support! Closing this.
