### ISSUE TITLE
Warning 'RCXX' defined but not used during compile

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#54]
Dears,

I have following errors during Linux compile, does it ok?

sha3/aes_helper.c:90:19: warning: ‘AES3_LE’ defined but not used [-Wunused-const-variable=]
 #define AES3      AES3_LE
                   ^
sha3/aes_helper.c:323:22: note: in expansion of macro ‘AES3’
 static const sph_u32 AES3[256] = {
                      ^~~~
sha3/aes_helper.c:89:19: warning: ‘AES2_LE’ defined but not used [-Wunused-const-variable=]
 #define AES2      AES2_LE
                   ^
sha3/aes_helper.c:256:22: note: in expansion of macro ‘AES2’
 static const sph_u32 AES2[256] = {
                      ^~~~
sha3/aes_helper.c:88:19: warning: ‘AES1_LE’ defined but not used [-Wunused-const-variable=]
 #define AES1      AES1_LE
                   ^
sha3/aes_helper.c:189:22: note: in expansion of macro ‘AES1’
 static const sph_u32 AES1[256] = {
                      ^~~~
sha3/aes_helper.c:87:19: warning: ‘AES0_LE’ defined but not used [-Wunused-const-variable=]
 #define AES0      AES0_LE
                   ^
sha3/aes_helper.c:122:22: note: in expansion of macro ‘AES0’
 static const sph_u32 AES0[256] = {
                      ^~~~
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/hamsi.o sha3/hamsi.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/hamsi_helper.o sha3/hamsi_helper.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_blake.o sha3/sph_blake.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_bmw.o sha3/sph_bmw.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_cubehash.o sha3/sph_cubehash.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_echo.o sha3/sph_echo.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_fugue.o sha3/sph_fugue.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_groestl.o sha3/sph_groestl.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_hefty1.o sha3/sph_hefty1.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_jh.o sha3/sph_jh.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_keccak.o sha3/sph_keccak.c
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_luffa.o sha3/sph_luffa.c
sha3/sph_luffa.c:147:22: warning: ‘RC34’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC34[8] = {
                      ^~~~
sha3/sph_luffa.c:140:22: warning: ‘RC30’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC30[8] = {
                      ^~~~
sha3/sph_luffa.c:101:22: warning: ‘RC14’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC14[8] = {
                      ^~~~
sha3/sph_luffa.c:94:22: warning: ‘RC10’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC10[8] = {
                      ^~~~
sha3/sph_luffa.c:87:22: warning: ‘RC04’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC04[8] = {
                      ^~~~
sha3/sph_luffa.c:80:22: warning: ‘RC00’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC00[8] = {
                      ^~~~
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o sha3/sph_shabal.o sha3/sph_shabal.c

**Comment by oliverw** [comment]
That's normal. The code in question is third party code and I didn't have the time or resources to go over it and fix every single warning.
