### ISSUE TITLE
Correct way to add Equihash 192,7 support. 

### ISSUE THREAD

**Issue by eketubol** [coinfoundry/miningcore#542]
## Note
Please use the following format to file an issue. Issues that fail to comply will delay our responses.
Please remove this section when you submit the issue. Thank you for your cooperation.

### Description

I am currently trying to add support for Vidulum (Equihash 192,7) From what I could gather, Equihash 96,5 144,5 and 209,9 are supported. What is the correct way to add 192,7? I have tried editing EquihashSolver.cs to allow 192,7 but when I try to re-build it throws this error: Crypto/Hashing/Equihash/EquihashSolver.cs(135,45): error CS0117: 'LibMultihash' does not contain a definition for 'equihash_verify_192_7' [/home/pool/miningcore/src/Miningcore/Miningcore.csproj]

I have since tried to look inside Miningcore.csproj file and cannot find anything relevant to equihash there.

### Steps to Reproduce
1. Add changes to EquihashSolver.cs
2. Rebuild using guide on Github
3. Error is produced.

### Expected behavior

Compile complete

### Actual behavior

Error's out. 

### Reproduces how often

100%

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

I am running the latest version of MiningCore and have done some adjustments to the back end to allow Lyra2v3 and x21s. I am running Ubuntu Server 16,04 LTS

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by bitspill** [comment]
It sounds like you haven't added the relevant C code for equihash_verify_192_7 to Libmultihash

Here's an example commit from when Lyra3 was added to roughly see what types of changes need to be made
https://github.com/coinfoundry/miningcore/commit/47ab0e6a2ae2c33629d3c000b65be5d0fba6c66d

**Comment by eketubol** [comment]
Hi thank you for your help, I have since amended the files as requested and this is what I put in my Libmultihash file:
 `[DllImport("libmultihash", EntryPoint = "equihash_verify_192_7_export", CallingConvention = CallingConvention.Cdecl)]
public static extern bool equihash_verify_192_7(byte* header, int headerLength, byte* solution, int solutionLength, string personalization)`

I am now receiving this error,
 
` from assembly 'Miningcore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Miningcore.Crypto.Hashing.Equihash.EquihashSolverFactory.InstantiateSolver(IComponentContext ctx, Object[] args) in /home/pool/miningcore/src/Miningcore/Crypto/Hashing/Equihash/EquihashSolverFactory.cs:line 44`

Which leaves me to line 44 of EquihashSolverFactory.cs: 
> var hashType = typeof(EquihashSolver).Assembly.GetType(hashClass, true);

**Comment by eketubol** [comment]
This has now been solved thanks to @bitspill
