### ISSUE TITLE
Equihash 192,7 Incorrect Solution Size

### ISSUE THREAD

**Issue by eketubol** [coinfoundry/miningcore#544]
## Note
Please use the following format to file an issue. Issues that fail to comply will delay our responses.
Please remove this section when you submit the issue. Thank you for your cooperation.

### Description

Hi, I have managed to add Equihash 192, 7 to mining core with the help of @bitspill. I am now receiving a lot of rejected shares when trying to mine Vidulum. 

Here is my conf file, 
```
"vidulum": {
      "name": "Vidulum",
      "symbol": "VDL",
      "family": "equihash",
      "networks": {
        "main": {
		  "diff1": "0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
          "solutionSize": 100,
          "solutionPreambleSize": 1,
          "solver": {
            "hash": "equihash",
            "args": [ 192, 7, "EquivPoW" ]
          },
          "coinbaseTxNetwork": "main",
          "payFoundersReward": false
        },
        "test": {
          "diff1": "0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
          "solutionSize": 100,
          "solutionPreambleSize": 1,
          "solver": {
            "hash": "equihash",
            "args": [ 192, 7, "EquivPoW" ]
          },
          "coinbaseTxNetwork": "testnet",
          "payFoundersReward": false
        },
        "regtest": {
          "diff1": "0007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
          "solutionSize": 100,
          "solutionPreambleSize": 1,
          "solver": {
            "hash": "equihash",
            "args": [ 192, 7, "EquivPoW" ]
          },
          "coinbaseTxNetwork": "regtest",
          "payFoundersReward": false
        }
      },
      "usesZCashAddressFormat": true,
      "useBitcoinPayoutHandler": false,
      "explorerBlockLink": "https://explorer.vidulum.app/block/$hash$",
      "explorerTxLink": "https://explorer.vidulum.app/tx/{0}",
      "explorerAccountLink": "https://explorer.vidulum.app/address/{0}"
    }

```
I believe the issue is with these two strings,          
```
"solutionSize": 100,
"solutionPreambleSize": 1,
```
When mining to the pool I receive this error 

[2019-02-13 16:45:17.8383] [I] [vidulum1] [0HLKHH0C2KCGG] Share rejected: incorrect size of solution

Does anyone know the correct solutionSize for Equihash 192,7 and the correct solutionPreambleSize? 
### Steps to Reproduce

1. Add Equihash 192,7 Supprt
2. Create Coin,json for Equihash 192,7
3. Run Pool

### Expected behavior

I expect to be able to mine and hit successful shares submitted.

### Actual behavior

I get a bunch of rejected sharess

### Reproduces how often

[What percentage of the time does it reproduce?]
100%
### Version
Latest version of MiningCore with some amendments to allow Lyra2v3 and x21s.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by eketubol** [comment]
Spoke with the Vidulum Dev team and they have said that the solutionSize is 400 with a solutionPreambleSize of 3. This still results in an error "Share rejected: incorrect size of solution"

**Comment by oliverw** [comment]
You probably forgot to fix the solution size checks in both your managed C# Solver and inside the native code.

**Comment by eketubol** [comment]
Hi, I have checked the files within equihashverify.cc and have will provide the example below:
`bool verifyEH_192_7(const char *hdr, const std::vector<unsigned char> &soln, const char *personalization)
{
    unsigned int n = 192;
    unsigned int k = 7;

    if (soln.size() != 400)
        return false;

    if (personalization == NULL)
        personalization = default_personalization_vidulum;

    // Hash state
    crypto_generichash_blake2b_state state;
    EhInitialiseState(n, k, state, personalization);

    crypto_generichash_blake2b_update(&state, (const unsigned char*)hdr, 140);

    bool isValid = Eh192_7.IsValidSolution(state, soln);

    return isValid;
}`

I have also checked the EquihashSolver.cs file and will provide an example below:

`    public unsafe class EquihashSolver_192_7 : EquihashSolver
    {
        public EquihashSolver_192_7(string personalization)
        {
            this.personalization = personalization;
        }

        public override bool Verify(Span<byte> header, Span<byte> solution)
        {
            try
            {
                sem.Value.WaitOne();

                fixed (byte* h = header)
                {
                    fixed (byte* s = solution)
                    {
                        return LibMultihash.equihash_verify_192_7(h, header.Length, s, solution.Length, personalization);
                    }
                }
            }

            finally
            {
                sem.Value.Release();
            }
        }
    }`

I don't see where I have gone wrong on this, could you give any advise?

**Comment by eketubol** [comment]
Fixed issue by inserting below code into exports.cpp:
```
// Explicit instantiations for Equihash<192,7>
template int Equihash<192,7>::InitialiseState(eh_HashState& base_state, const char *personalization);
#ifdef ENABLE_MINING
template bool Equihash<192,7>::BasicSolve(const eh_HashState& base_state,
                                          const std::function<bool(std::vector<unsigned char>)> validBlock,
                                          const std::function<bool(EhSolverCancelCheck)> cancelled);
template bool Equihash<192,7>::OptimisedSolve(const eh_HashState& base_state,
                                              const std::function<bool(std::vector<unsigned char>)> validBlock,
                                              const std::function<bool(EhSolverCancelCheck)> cancelled);
#endif
template bool Equihash<192,7>::IsValidSolution(const eh_HashState& base_state, std::vector<unsigned char> soln);
```
