### ISSUE TITLE
Q: Connect miningcore to another pool?

### ISSUE THREAD

**Issue by samanshahmohamadi** [coinfoundry/miningcore#545]
### Description

This is not an issue actually, It's a question. I did a pool setup using miningcore and it works just well. I wonder if I can connect the miningcore instance to another pool (like antpool, etc.) instead of connecting in to a node directly?
Thank you.

**Comment by oliverw** [comment]
That's not going to work. What you are looking for is a stratum proxy.

**Comment by samanshahmohamadi** [comment]
Thanks, I tried and it seems working using [stratum proxy](https://github.com/Stratehm/stratum-proxy), just in case.
