### ISSUE TITLE
Inconsistent timestamps.

### ISSUE THREAD

**Issue by Serpent6877** [coinfoundry/miningcore#55]
First not sure why UTC is the default time instead of the systems time?

The logging to a file uses system time but the database uses UTC. As well as the API output. Can we get a standard? Preferably system time.

[2017-11-08 18:08:16.2273] [I] [etc1] [Ethereum Job Manager] Submitting block 4802079 
[2017-11-08 18:08:16.2895] [I] [etc1] [Ethereum Job Manager] Daemon accepted block 4802079 

 2 | etc1   |     4802079 |       1.09895e+14 | confirmed |                    1 |        | 0xd5ce9a0f8def543b265753b7f325863f6845ddc3fd7230ca01c71a58db1bb3bf:0x001c9249461b82f7 | 5.000420000000 | 2017-11-09 02:08:16.289697

**Comment by calvintam236** [comment]
@oliverw maybe adding an option in `config.json` for timezone format, so user can choose UTC or local time?

**Comment by oliverw** [comment]
@Serpent6877 Well UTC was chosen because it's easy to display in a user's local time in web frontends, apps. etc.

**Comment by oliverw** [comment]
@calvintam236 Sorry, adding an option for this is currently not possible.
