### ISSUE TITLE
What is the best practise for pool clustering?

### ISSUE THREAD

**Issue by uurcm16** [coinfoundry/miningcore#569]
Hi @oliverw 

What is the best practise for pool clustering?
Should I use ShareReceiver or directly connect to the database remotly and submit shares directly into db. 

Thanks in advance.

**Comment by oliverw** [comment]
ShareRelay + ShareReceiver. Never ever use shared database access.

**Comment by uurcm16** [comment]
Thank you for the fast answer. 
So, single payment instance, single api instance and a few pools connected with ShareRelay and ShareReceiver. İs that correct?

MiningCore recognizes the ethereum mainnet as UNKNOWN ChainType. This is why you are not getting DevFee’s from my pool. I am currently testing the pool but i will go online in a few weeks and i will be happy if I can pay the DevFees.

**Comment by oliverw** [comment]
Exactly.

**Comment by uurcm16** [comment]
What do you think about the coin daemons?
What I'm going to do is; Each location will run its own coin daemons to reduce job broatcasting / block submission latency.

- EU server => Coin daemons & MiningCore pool instance & API **Enabled** & Payments **Enabled**
- US server => Coin daemons & MiningCore pool instance & API Disabled & Payments Disabled
- CH server => Coin daemons & MiningCore pool instance & API Disabled & Payments Disabled

**Comment by oliverw** [comment]
It depends. The setup you described is perfectly viable. Just make sure that only the daemons for the EU server have wallet access. Run the US and CH servers with default generated wallets.

**Comment by uurcm16** [comment]
Hi @oliverw 
We'r ready to open our pool but we have a problem.
EU & US instances are ready (daemons and etc..) No matter what I do, I couln't connect them to eachother.

**Main Server (US instance) ShareRelays config:**
 ` "shareRelay**s**": [
    {
      "url": "tcp://89.xx.xx.xx:16666",
      "sharedEncryptionKey": "testkey"
    }
  ],`

**EU Instance ShareRelay config :**
`  "shareRelay": {
    "connect": false,
    "publishUrl": "tcp://89.xx.xx.xx:16666",
    "sharedEncryptionKey": "testkey"
  },`

**Error Message :**
`System.AggregateException: One or more errors occurred. (EADDRNOTAVAIL(101): Address not available) ---> ZeroMQ.ZException: EADDRNOTAVAIL(101): Address not available
   at ZeroMQ.ZSocket.Bind(String endpoint)`

I'm working on this for hours but it is not working. 

The 16666 port is open on the main instance. 
But what I see is that the main server is NOT listening 16666. Is it just how ZeroMQ works or not? `( sudo lsof -i -P -n | grep :16666)`
Am I doing something wrong here?
