### ISSUE TITLE
[PayoutManager] [btc1] Payment processing failed System.Net.Sockets.SocketException (0x80004005): Connection refused

### ISSUE THREAD

**Issue by chestnyh** [coinfoundry/miningcore#57]
I have such problem when trying connect pool with bitcoin testnet. Config file:

bitcoin.conf: 

rpcuser=bitcoinrpc
rpcpassword=bitcoinrpcpass
rpcallowip=0.0.0.0/0
rpcport=18332
daemon=1
server=1
testnet=1
gen=0

config.json: 

{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated"
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "<my_ip>",
            "port": 5432,
            "user": "miningcore",
            "password": "<user_pass>",
            "database": "miningcore"
        }
    },
    "devDonation": 0.1,
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "api": {
    	 "enabled": true,
    	"listenAddress": "<my_ip>",
    	"port": 4000
    },
    "pools": [{
      "id": "btc1",
      "enabled": true,
      "coin": {
        "type": "BTC"
      },
      "address": "<wallet_address>",
      "rewardRecipients": [
        {
          "type": "op",
          "address": "<wallet_address>",
          "percentage": 0
        }
      ],
      "blockRefreshInterval": 1000,
      "jobRebroadcastTimeout": 55,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3042": {
          "listenAddress": "<my_ip>",
          "difficulty": 1024,
          "name": "ASIC Mining",
          "varDiff": {
            "minDiff": 512,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "<my_ip>",
          "port": 18332,
          "user": "bitcoinrpc",
          "password": "bitcoinrpcpass"
   	    }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }]
}

What's wrong?

**Comment by chestnyh** [comment]
Problem solved.

**Comment by oliverw** [comment]
How?

**Comment by chestnyh** [comment]
I don't. Because in some moment error have disappeared. I think, node was not synchronized fully.
