### ISSUE TITLE
Implement TLS/SSL support for the API/Websocket Connection

### ISSUE THREAD

**Issue by stevecastaneda** [coinfoundry/miningcore#570]
### Description

Current API/Websocket connection is on a non-encrypted connection.  This issue references an enhancement that will add SSL/TLS support to both the API and Websocket connection.  It's noted that exposing both endpoints to the end user is not advised.

### Expected behavior

API and Websocket connections are available via a frontend UI whose domain is secured by SSL.

### Actual behavior

Connections are denied due to a secured connection attempting to connect to a non-secure connection.

### Reproduces how often

100%

### Version

Release 46

**Comment by uurcm16** [comment]
Hi there,

https://github.com/coinfoundry/miningcore/blob/1d79333372d82e9b126a6e69a56861afbd2077a3/src/Miningcore/Program.cs#L760

Just modify this line according to [This article](https://docs.microsoft.com/tr-tr/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2) (Search for **UseHttps**)

Best regards.

**Comment by oliverw** [comment]
Implemented by 957b4437b20549942b19fee03f28c88238994985
