### ISSUE TITLE
New cryptonightR algorithm for XMR (9th March)

### ISSUE THREAD

**Issue by rubenfonseca** [coinfoundry/miningcore#572]
## New XMR algo

On the 9th of March XMR will move to a new CryptonightR algo.

Can we add support for it on Miningcore?

Reference implementation: https://github.com/monero-project/monero/pull/5126

**Comment by oliverw** [comment]
What are you filing an issue for something that is already implemented?

**Comment by rubenfonseca** [comment]
Sorry I filled the issue because I couldn't find any information on the README or any CHANGELOG :) Again, sorry about this!
