### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by jackmagooli** [coinfoundry/miningcore#573]
Hi. i have some problem with the API

wich API should i install.

even i set API true i cant start the pool

**Comment by uurcm16** [comment]
@jackmagooli Please refer to [THIS](https://github.com/coinfoundry/miningcore/blob/master/ISSUE_TEMPLATE.md) document for opening an issue. 
And post some logs / screenshots / config file.

**Comment by jackmagooli** [comment]
Note

Please use the following format to file an issue. Issues that fail to comply will delay our responses. Please remove this section when you submit the issue. Thank you for your cooperation.
Description

i try to connect the Api with the frontend of calvintam.
miningcore works well, but in my frontend i have
"no response from API

Steps to Reproduce

1.    i start the pool (works well)
  2.  i configure the frontend miningcore-ui.js with the id of my pool


Expected behavior

[What you expect to happen]
i expect that the frontend works well :)

[What actually happens]
but the frontend shows no data of my pool

[What percentage of the time does it reproduce?]


If you are using released version, please state your version. If you are using clone from dev branch, please state commit hash of your copy. Also, please include the OS name and version you're currently running.
Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by bitspill** [comment]
The UI by @calvintam236  is no longer maintained nor functional -- the last update to it was nearly a year ago and as of 3 months ago there were reports it no longer functions https://gitlab.com/calvintam236/miningcore-ui/issues/1


You'll have to create your own UI or try using the UI by @minernl at https://github.com/minernl/Miningcore.UI which is more recently updated

**Comment by jackmagooli** [comment]
ok well but i have no data in my frontend.
i use the frontend calvintam
and the minernl

my miningcore config:
    // API Settings
    "api": {
        "enabled": true,
        // Binding address (Default: 127.0.0.1)
        "listenAddress": "127.0.0.1",
        // Binding port (Default: 4000)
        "port": 4000,


Start the miningcore:

[2019-03-07 01:52:28.8022] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2019-03-07 01:52:28.8022] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2019-03-07 01:52:28.9444] [I] [Core] API Online @ 127.0.0.1:4000 [rate-limiting disabled]
[2019-03-07 01:52:28.9444] [I] [Core] Prometheus Metrics Online @ 127.0.0.1:4000/metrics
[2019-03-07 01:52:28.9444] [I] [Core] WebSocket notifications streaming @ 127.0.0.1:4000/notifications
[2019-03-07 01:52:28.9590] [I] [PayoutManager] Online
[2019-03-07 01:52:28.9633] [I] [StatsRecorder] Online
[2019-03-07 01:52:28.9663] [I] [PayoutManager] Processing payments for pool btc1
[2019-03-07 01:52:28.9997] [I] [btc1] Starting Pool ...
[2019-03-07 01:52:29.0199] [I] [btc1] Starting Job Manager ...
[2019-03-07 01:52:29.2200] [I] [btc1] All daemons online
[2019-03-07 01:52:29.3736] [I] [btc1] All daemons synched with blockchain
[2019-03-07 01:52:29.5234] [I] [btc1] Subscribing to ZMQ push-updates from (tcp://127.0.0.1:15101, hashblock)
[2019-03-07 01:52:29.5681] [I] [btc1] Job Manager Online


frontend config:
// config
var API = 'http://localhost:4000/api/'; // Change this in your public API address
var defaultPool = 'btc1'; // Default Pool ID

var currentPool = defaultPool;


But it doesnt work

**Comment by minernl** [comment]
The info your API provides needs to be accessible for the web browser clients.
The best way is the do this:

1.) miningcore config.json (this is already what you have)
- API enabled and 127.0.0.1 at port 4000

2.) Webserver reverse proxy config 
this will redirect http://url_website/api to you local address at port 4000
example nginx (linux):

server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name URL_USED_BY_SITE ;
  root PATH_WEBSITE_FILES;
  index index.html index.htm;
  
  location / {
     try_files $uri $uri/ =404;
  }
  
  location /api/ {
     proxy_pass http://127.0.0.1:4000
   }
 }


3.) miningcore.js file
frontend config:
// config
var API = 'http://localhost:4000/api/';   // Change this in your public API address
this line should be changed in http://url_website/api


you can test this by opening a browser to
http://url_website/api/pools
you should see the pools api info

if you need help, you can give me a personal message.

**Comment by jackmagooli** [comment]
Thx
now my Api works well.
but the Frontend show no information

**Comment by ultra-pool** [comment]
With mine the API doesnt do anything any more. It worked 2 weeks before miningcore crapped out for the 100th time.

**Comment by goodthebest** [comment]
@minernl how can I DM you? Please advise.

**Comment by ghost** [comment]
> The info your API provides needs to be accessible for the web browser clients. The best way is the do this:
> 
> 1.) miningcore config.json (this is already what you have)
> 
> * API enabled and 127.0.0.1 at port 4000
> 
> 2.) Webserver reverse proxy config this will redirect http://url_website/api to you local address at port 4000 example nginx (linux):
> 
> server { listen 80 default_server; listen [::]:80 default_server; server_name URL_USED_BY_SITE ; root PATH_WEBSITE_FILES; index index.html index.htm;
> 
> location / { try_files $uri $uri/ =404; }
> 
> location /api/ { proxy_pass http://127.0.0.1:4000 } }
> 
> 3.) miningcore.js file frontend config: // config var API = 'http://localhost:4000/api/'; // Change this in your public API address this line should be changed in http://url_website/api
> 
> you can test this by opening a browser to http://url_website/api/pools you should see the pools api info
> 
> if you need help, you can give me a personal message.

This is not good use case, you're never going to setup a website for http. You want HTTPS -> HTTP
