### ISSUE TITLE
Pool API bugs

### ISSUE THREAD

**Issue by ultra-pool** [coinfoundry/miningcore#581]
In the pool API when you goto the links. 
/api/pools/coinname/miners
It doesnt pull up anything.

Another one
/api/pools/coinname/payments
It shows "[ ]"

We're to get a API bot working but the API itself isnt showing status.

/api/pools/coinname/
Shows all the info like it should.

**Comment by Konstantin35** [comment]
/api/pools/coinname/blocks?page=0&pageSize=100
/api/pools/coinname/miners?page=0&pageSize=100
/api/pools/coinname/payments?page=0&pageSize=100
/api/pools/coinname/miners/wallet/payments?page=0&pageSize=100

**Comment by ultra-pool** [comment]
It some what worked for afew days. Now all the api's i get a 404 page not found and the front end doesnt display anything. Server reboot did not fix the problem.

**Comment by calebcall** [comment]
As @Konstantin35 suggested, it has a required &pageSize parameter that you're missing.

**Comment by ultra-pool** [comment]
Api is fully down. It worked for 2 weeks. 

Even adding &pagesize at the end.

**Comment by ultra-pool** [comment]
API is still broken as hell.

**Comment by Konstantin35** [comment]
Can you give me more information about what's not working?
