### ISSUE TITLE
POOL API block hash is wrong

### ISSUE THREAD

**Issue by ZhiKosta** [coinfoundry/miningcore#582]
I have deployed v45 and i have noticed that the reported block hash from the api is one count further then the actual network block height.

### Steps to Reproduce

install v45

### Expected behavior

Needs to report the actual block height

### Actual behavior

Gives a block height that is not mined yet

### Reproduces how often
every time

### Version

v45 ubuntu

### Additional Information

API report:
-----------

networkStats |  
-- | --
networkType | "Main"
networkHashrate | 2758143.208152808
networkDifficulty | 196704.422265095
nextNetworkTarget | "00000002aa550000000000000000000000000000000000000000000000000000"
nextNetworkBits | "1d02aa55"
lastNetworkBlockTime | "2019-03-22T07:33:33.6107181Z"
blockHeight | 573730

explorer report:
-------------------
https://screenshots.firefox.com/PKIoSaT9QbdZA4Ku/explorer.bitcoingold.org

**Comment by ZhiKosta** [comment]
Seriously? Guys fix this.

**Comment by minernl** [comment]
If you rethink your info... then you can see this is 100% as it should be.
ask your self, what means "last block"?  this is a block that is completed.
why would/should your pool be working on a blocks that are completed??.. then you get orphans if submitted.
Your pool, is as it should be, working on the new block "last block +1"

**Comment by ZhiKosta** [comment]
Well, up to version 44 the API result for last block was displaying just last block. It never was last block +1. So now all front-ends who use this API data display the wrong blocks. Many people just like me wrote "Last block found by the network: $blocknum". It never was "current block the pool is working on".

So yes. It is wrong.
