### ISSUE TITLE
TLS/SSL Support

### ISSUE THREAD

**Issue by oliverw** [coinfoundry/miningcore#6]
Stratum over TLS eliminates possibility of man-in-the-middle attacks, as the communication between miner and pool is strongly encrypted and the server's identity is digitally signed by a certificate authority. Implementing this feature has top priority.

**Comment by Kukks** [comment]
How would this work? :) Currently, the only worthwhile mining with AMD cards is through the mkxminer. Version 2.01 only allows tls connections(after you circumvent the pool whitelist).

**Comment by oliverw** [comment]
After experimenting with Net Core TLS/SSL support in production, I've come to the conclusion that SSL/TLS support is currently best handled by a SSL capable TCP reverse proxy such as HAProxy or [bud](https://github.com/indutny/bud). The latter being used at coinfoundry.org in produciton.

**Comment by stevecastaneda** [comment]
This issue looks to reference the stratum connection.  What about SSL support on the API or websocket connection?

**Comment by oliverw** [comment]
While I still strongly believe that it is not the best idea to expose the API/WebSocket directly to end users - either directly or indirectly through your Web Frontend - implementing TLS for both is a reasonable request. Feel free to file a separate issue and/or a pull request.
