### ISSUE TITLE
Big ping

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#620]
The question is simple why high ping?
Worker and pool are on the local network

![miner](https://user-images.githubusercontent.com/28952414/57572177-7824da00-741f-11e9-830d-3b66547ba203.png)

![miner2](https://user-images.githubusercontent.com/28952414/57572239-32b4dc80-7420-11e9-9f81-92e8cc896600.png)

**Comment by oliverw** [comment]
@Konstantin35 Care to elaborate? I don't see the problem.

**Comment by Konstantin35** [comment]
@oliverw as you can see in the screenshots each sent shares a delay of 1000ms and 500ms is too much time because of this many orphan blocks
I am currently using only Ethash possible and on other algorithms the same problem

**Comment by oliverw** [comment]
I still don't get what you mean with ping. What I can see on your first screenshot is that the accepted time is extremely high.

**Comment by Konstantin35** [comment]
The lower the ping – the better.
In mining core there is such a problem as to look for the cause of such a large delay, since mining core is much more effective than open-ethereum-pool

sorry for bad English

**Comment by oliverw** [comment]
No problem. We really need to get to the root of this. I'm going to prepare a special build for you with much more logging.

**Comment by oliverw** [comment]
@Konstantin35 Could you try to reproduce this behavior while having Miningcore run with <code>logLevel: "debug"</code> (config.json)?

**Comment by calebcall** [comment]
Easy way to see where the wait is, grab a packet capture on both your client and server only capturing that port.  Pull those in to wireshark and compare the two, you should see pretty quickly where the wait is.

Command would be something like:
`tcpdump -i any -s0 'port 3072' -w cap1.pcap`

Run that just long enough to see the issue and then kill it.  You'll now have your traffic in the cap1.pcap file, open that in wireshark.  So the same on the both client and server (change filename so you don't stomp each other).

**Comment by oliverw** [comment]
@Konstantin35 Any news on this?

**Comment by wiico** [comment]
Maybe :

 Open ethereum pool  is a proxy and a stratum. Response is from proxy to client.  You didnt really know how many time response is between proxy and ethereum node.

**Comment by Konstantin35** [comment]
Here are the files
[core.log](https://github.com/coinfoundry/miningcore/files/3187158/core.log)
[cap1.zip](https://github.com/coinfoundry/miningcore/files/3187161/cap1.zip)

**Comment by oliverw** [comment]
@Konstantin35 Checking.

**Comment by Konstantin35** [comment]
@oliverw I didn't understand

**Comment by oliverw** [comment]
> [2019-05-16 16:02:27.4920] [D] [mix] [0HLMPVM4UV40B] [NET] Received data: {"id":40,"method":"mining.submit","params":["0x1f67a69b581f9339ad1f8ff1b52726753a79dde4","0000005a","000007ac2913"]}
>  
> [2019-05-16 16:02:27.4920] [D] [mix] [0HLMPVM4UV40B] [NET] Waiting for data ... 
> [2019-05-16 16:02:27.4932] [D] [mix] [0HLMPVM4UV40B] [PIPE] Received data: {"id":40,"method":"mining.submit","params":["0x1f67a69b581f9339ad1f8ff1b52726753a79dde4","0000005a","000007ac2913"]}
>  
> [2019-05-16 16:02:27.4932] [D] [mix] [0HLMPVM4UV40B] Dispatching request 'mining.submit' [40] 
> [2019-05-16 16:02:27.4932] [D] [mix] SubmitShareAsync(0HLMPVM4UV40B) 
> [2019-05-16 16:02:27.4932] [D] [mix] Compute() 
> [2019-05-16 16:02:28.3044] [D] [mix] [0HLMPVM4UV40B] Sending: {"result":true,"error":null,"id":40} 
> [2019-05-16 16:02:28.3044] [I] [mix] [0HLMPVM4UV40B] Share accepted: D=0,5 

According to the log you provided the time is indeed spent inside Miningcore. In the example above , processing the submitted share takes 0.81sec.

> [2019-05-16 16:02:27.4932] [D] [mix] Compute() 
> [2019-05-16 16:02:28.3044] [D] [mix] [0HLMPVM4UV40B] Sending: {"result":true,"error":null,"id":40} 

Almost the 100% of the time is spent inside the DAG computation.

**Comment by Konstantin35** [comment]
here are some parameters
[Desktop.zip](https://github.com/coinfoundry/miningcore/files/3190897/Desktop.zip)

**Comment by Konstantin35** [comment]
@oliverw I noticed that when you first start miningcore delay and there is 1 - 3 ms, reboot the server and latency 600 - 800 ms, and remove the generated dag file, run miningcore dag generated new files and again latency 1 - 3 ms.

> To make everything work correctly, you will have to generate new dag files after each reboot of the server

**Comment by Konstantin35** [comment]
To make everything work correctly, you will have to generate new dag files after each reboot of the server
For the test is not very important and a big delay
On the working server, you should specify the path for dwg files in the `tmp` folder to avoid the server memory overflow, I think the problem is solved

**Comment by Konstantin35** [comment]
Everything worked all night fine, but after running the second instance of parity chain CLO again delay 500 - 800 ms

**Comment by wiico** [comment]
try 'top' and look system health, 8gb it's few,  probably system swaping. Is it ssd hd ?

**Comment by Konstantin35** [comment]
Perhaps few resources but on the production server will be more more worried about the fluctuations of the delay are too many min - max, it is certainly the case in miningcore very long obrabatyvat solutions. 

Here are the server statistics:
[https://drive.google.com/file/d/1bn8W8C6n-8-j2hEqKfIm9kmNJ5p-JDOg/view?usp=sharing](https://drive.google.com/file/d/1bn8W8C6n-8-j2hEqKfIm9kmNJ5p-JDOg/view?usp=sharing)

**Comment by wiico** [comment]
statistic felling good , is it in production with two parity instance ? 
hyper v has variable performance, it is possible that performance collapses when main node lacks memory.

**Comment by calebcall** [comment]
This could be a hyper-v problem (I highly doubt it in this case), but all the time is spent after a mining.notify has been sent.  From your capture you have above, you can see that in this particular call, there's 48 seconds before it responds.  This is a single TCP stream that I've filtered out.  There are several that are > 10s all waiting for that mining.notify.

![Screen Shot 2019-05-18 at 10 36 49 AM](https://user-images.githubusercontent.com/1132262/57972518-4056ee80-7959-11e9-8077-42a117064d3d.png)

**Comment by thagrisu** [comment]
I guess your problem is the DAG File. Pool need so check every share against the ethereum DAG file. If your file is located on a disk, then your disk I/O is crucial to the checking process. For a simple test create a filespace in your server RAM and place the DAG file in there.  There is a  dagDir option in the miningcore config to relocate the DAG file.
