### ISSUE TITLE
I cant find any information or configuration examples on Pool Clustering (shareRelay).

### ISSUE THREAD

**Issue by danielbjornadal** [coinfoundry/miningcore#621]
I cant find any information or configuration examples on Pool Clustering (shareRelay).
Do I need a separate ZMQ?
Pool configuration?

**Comment by Konstantin35** [comment]
A lot of information
https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Configuration/ClusterConfig.cs#L586
https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Configuration/ClusterConfig.cs#L595
https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Configuration/ClusterConfig.cs#L605
https://github.com/coinfoundry/miningcore/issues/409#issuecomment-426335307
