### ISSUE TITLE
No network hashrate  ETC parity 2.4.6 MiningCore 4.7

### ISSUE THREAD

**Issue by wiico** [coinfoundry/miningcore#628]
### Description

MiningCore can't load network hashrate with ETC chain 

### Steps to Reproduce

Every time i'm starting  MC app with ethereum-classic config 

 I try with monero and it's works.

### Expected behavior

I would have network hashrate on api reccord.

### Actual behavior

I have 0 Hs on network hashrate data all time

### Reproduces how often

100 %
### Version

MC : 4.7
Parity : 2.4.6

### Additional Information

Linux system ubuntu 16.04 

mining core is very nice, Thanks for that !

**Comment by Konstantin35** [comment]
It already was
https://github.com/coinfoundry/miningcore/issues/360

**Comment by wiico** [comment]
after reading #360 issue and then #386  i c'ant realy solve my problem or i probably miss something.

you said 

#1 :  ' Difficulty / block time '  you mean i have to calculate it in my web ui ?  

#2 : ' use 1.95 parity version '  it's a bit old for now , dont you think ? 

Does 'Geth' node work with mining core ?

**Comment by Konstantin35** [comment]
#1 Hasrat network calculate yourself
_Example:_
[https://github.com/sammy007/open-ethereum-pool/blob/master/www/app/controllers/application.js#L37](https://github.com/sammy007/open-ethereum-pool/blob/master/www/app/controllers/application.js#L37)
#2 Yes parity use the latest version

**Comment by wiico** [comment]
it really doesnt work natively on API   ? i have to do it myself ? Is it working with a full node Geth ?

**Comment by Konstantin35** [comment]
Yes, for ethereum, the network speed is not displayed, for other varieties of coins it is displayed. Get is not supported.

**Comment by wiico** [comment]
ok thank you Konstantin35 for your answer.  I'll stay with Sammy for this timet,  dagger coin works fine.

I'm working on a web gui for mining core, i'll keep it for other coin.
