### ISSUE TITLE
Slack or Discord support group

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#635]
Can we get a Slack or Discord group going for support? Even if the lead Dev doesn't have lots of time, I think there is enough people using MiningCore now to have a community-supported Slack group. As a bonus it would keep a lot of general and configuration questions from appearing on GitHub as "Issues". 

Thoughts?

**Comment by seperatis** [comment]
One other thought... I've got a live Discourse server running that's not really being used right now and I could make a MiningCore Support category to donate to the cause. This might be a better idea than Slack or Discord even, as the "Solutions" to people's problems would be forever visible and searchable, and eventually get indexed by the search engines too. Plus invites wouldn't be necessary either. Love to hear what everyone else thinks....

**Comment by oliverw** [comment]
@seperatis We have a gitter channel that I almost forget about:

https://gitter.im/miningcore/Lobby

I'll try to be a little more active in the future. I will also add a link to it on the main page.
