### ISSUE TITLE
Running multi algo coin on same server

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#637]
Is it possible to run different algo's of same coin within a unique server?
For example for DGB, if I want to run SHA256, Scrypte and Odocrypt, do I need to run multiple instances of the daemon? or is it possible to do it with the same daemon for all of them and if it's possible how should I setup the config file for the daemon?
currently I'm setting algo=sha256d in the config file to set the algo.

and if it's not possible to do that is there any other way to run it on the same server?

@oliverw , I will be appreciated if you can reply to this since you already did this in coinfoundry.

and if none of above are correct then what's the best practice to do that?

**Comment by oliverw** [comment]
@peysab As far as Digibyte is concerned, one daemon as sufficient. You can configure multiple discrete pools in miningcore but you need to adjust the parameter for the `getblocktemplate` RPC.

**Comment by peysab** [comment]
What about the Daemon config? 
should I just change algo=sha256d to anything else?

**Comment by oliverw** [comment]
Daemon config will be the same for all DGB pools, just the gbtargs is different.

**Comment by peysab** [comment]
But in digibyte.conf file we have to set the algo, right? if I don't set it it will get scrypt as default and the sha256 won't work.
and if in the daemon section in the config.json, I set the same port which is running  sha256 for scrypt it will fail right? I tested that before.
can you please explain a bit more where to adjust the parameter for getblocktemplate 

Thanks

**Comment by oliverw** [comment]
CF is running `digibyted` without any config file whatsoever. All pools point to the same digibyted instance (same port, same password, same user etc). The pools only have different values for gbtArgs in their configuration in Miningcore's config.json.

`"gbtArgs": [{"rules": [ "segwit" ]}, "sha256d"],`
`"gbtArgs": [{"rules": [ "segwit" ]}, "scrypt"],`

etc.

**Comment by peysab** [comment]
great thanks, will check that.

**Comment by peysab** [comment]
BTW, CF Supports all Legacy, SegWit, bech32 address types right? if yes I think you need to change it in dgbwiki right now it's only Legacy.
![image](https://user-images.githubusercontent.com/22977536/58615228-e3b2e680-82fd-11e9-995c-c01e82194444.png)

**Comment by oliverw** [comment]
Miningcore only supports legacy addresses for the pool wallet but all addresse types for miners.

**Comment by peysab** [comment]
It worked thanks, BTW for scrypt it's showing the wrong nethash, for example in CF it's showing 84PH right now which should be around 2.5TH any ideas how to fix this?
