### ISSUE TITLE
Not an actual issue, just here for learning. 

### ISSUE THREAD

**Issue by Swaggadan** [coinfoundry/miningcore#638]
I want to try to build a mining pool for a specific coin that isn't integrated here yet. I would like to use this project to build it because I love the support and constant commits. I know python but not as good as the ones that build pools. I understand that I would have to learn c# for this project but is there anything else I need to know? I have never seen any sort of blueprint on what a pool should have or anything of that nature. How can I get started with this project assuming I am a total nub of everything.

**Comment by seperatis** [comment]
Questions like this are probably better for the Gitter support channel located here: https://gitter.im/miningcore/Lobby
