### ISSUE TITLE
Default setup SQL script does not contains partitioning.

### ISSUE THREAD

**Issue by uurcm16** [coinfoundry/miningcore#640]
Hi @oliverw ;

The default sql script does not contains partitioning on shares table (https://raw.githubusercontent.com/coinfoundry/miningcore/master/src/Miningcore/Persistence/Postgres/Scripts/createdb.sql)

Is it like this for a reason or you just missed it?

**Comment by oliverw** [comment]
@uurcm16 No I didn't miss it. I decided to keep the standard setup simple because most novice pool operators would likely miss the necessary step of creating subtables for each partition.
