### ISSUE TITLE
Litecoin testnet 100% orphaned blocks

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#649]
Running litecoind with testnet flag. Config file set for SOLO payment scheme with the litecoind testnet wallet address with another testnet address as reward recipient. 

As you can see from the screenshots below, MiningCore has submitted the blocks and they are accepted by the daemon. However, when you look at the /blocks API endpoint, you can see that all of the blocks stay in a state of either Pending or turn into Orphaned. See screenshots below.

Can anyone explain what is going on here? I wanted to run everything in testnet first to make sure everything is working properly.

![Testnet_blocks_accepted](https://user-images.githubusercontent.com/32314615/58767508-fb2de180-8540-11e9-8db1-f0400d8ae0e0.jpg)

![BLocks_API](https://user-images.githubusercontent.com/32314615/58767513-0254ef80-8541-11e9-9f39-31512858f632.jpg)

**Comment by oliverw** [comment]
What do you get when you run `litecoin-cli gettransaction txid` where `txid` equals any of the ``?`transactionConfirmationData` values returned by the API?

**Comment by seperatis** [comment]
@oliverw I've tried that with multiple tx's and always get this error message:
`Invalid or non-wallet transaction id`

**Comment by seperatis** [comment]
This is probably un-related but I did get some errors when the miner first connects to the pool. 
`Block submission failed with: inconclusive`

As seen in screenshot below:

![Block_Submission_Fail](https://user-images.githubusercontent.com/32314615/58770248-c7fc4a00-8562-11e9-93b5-cd59a01afb32.jpg)

**Comment by seperatis** [comment]
Out of curiosity I tried `litecoin-cli getrawtransaction` and instead of the error above it returned this:

010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff1f034cc810043bbbf45c00bd34a0bc220000000c2f4d696e696e67436f72652f00000000020000000000000000266a24aa21a9edeef7c62d49edf65bff3c32d5ff9d17510feec579fbbeb3ca2ae3c9020f773c9ea07f0495000000001976a9140da49987a73a6c85a101ab068f8224594136c50e88ac0120000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by seperatis** [comment]
Digging further I used https://chain.so/address/LTCTEST to look up the transaction ID and it's saying that these blocks are all confirmed with a block reward of 25 LTCtest, but the wallet address listed isn't mine. Also, the core wallet nor the reward recipient in the config file receive any coins at all. Haven't been getting any errors when the payment processing runs either. I've attached some screenshots for clarification.
![LTC-Test-Net-Explorer](https://user-images.githubusercontent.com/32314615/58781281-605cf380-8590-11e9-9d2d-362c2f6032e1.jpg)

![LTC-testnet-Blocks-API](https://user-images.githubusercontent.com/32314615/58781299-68b52e80-8590-11e9-95c0-20f9de0238a6.jpg)

**Comment by oliverw** [comment]
The *inconclusive* block submission errors are harmless and caused by the miner submitting shares containing a block solution in quick succession. This happens quite frequently on testnet and regtest. It's easy to spot as the block number logged with the submission is duplicated accross multiple submissions.

Regarding your other problem, I strongly believe that this is caused by using a non-legacy address for the pool wallet which is currently not supported but unfortunately nowhere detected nor warned about. This has to change.

**Comment by seperatis** [comment]
In regard to non-legacy address, do you mean inside the config.json or Litecoin Core  (testnet) itself? As I presume the only way to get LTC core to spit out legacy address is to download a very old version.

 I've tried to use https://litecoin-project.github.io/p2sh-convert/ to convert the config.json into a legacy address. No dice.

Is there a fix for this? If I switch from testnet to LTC main chain will the issue persist? Problem is I don't have $5,000 for renting hash power to make sure LTC main chain configuration is correct, hence relying on testnet for that. All thoughts here are much appreciated.

Does BTC Testnet mode have same issue?

**Comment by oliverw** [comment]
`litecoin-cli getnewaddress legacy`

Use the returned address as pool wallet. This also applies to BTC and practically all newer forks based on Bitcoin v0.17+. For very recent forks, including BTC/BCH, the daemon needs to be run with `-deprecatedrpc=accounts`

**Comment by seperatis** [comment]
`litecoin-cli getnewaddress "" legacy` created a legacy address for me which added to config.json, and now I'm seeing a balance grow in LTCtestnet daemon, but getting an `Insufficient Funds` error when the payments try to process. After looking in the wallet, there actually is enough funds. All addresses in config.json are also legacy. One other odd thing is that the `/api/pool/blocks` API is showing the reward for each block always as `0.00000` so that seemed a bit off. One a good note, the API does show the block confirmation % now and it did not before. So it mostly seems to be working now, except for the payment error, attaching screenshot below:
![Insufficient-Funds](https://user-images.githubusercontent.com/32314615/58786791-35c56780-859d-11e9-9f41-54cf5629063a.jpg)

**Comment by seperatis** [comment]
I suppose my big two questions are:
1) Are these things isolated to Testnet?
2) When running MiningCore with wallets on the Main net, do you still need to use Legacy addresses?

It's a bit un-nerving to think that one oversight could cost you 12.5 BTC or 25 LTC either one...

**Comment by oliverw** [comment]
1. No
2. Yes

**Comment by oliverw** [comment]
The insufficient funds error on your testnet pool might be caused by balance changes caused by your previous problems. If I was you I'd clean out the blocks, payments, balances and balance_changes tables and start over with a clean slate.

**Comment by seperatis** [comment]
Wiped the database tables you mentioned above. If I look at `/api/pools/ltc1/miners/minerxyz` it is now showing a `"pendingBalance"` as it was _not_ before.

Looking at `/api/pools/ltc1/blocks` Is still showing `"reward": 0.000000000000` but I'm wondering if that's not for another reason. In testnet, my single L3+ miner is finding blocks really fast, (every 15-30 seconds), so if the API isn't updating the block reward amount until it's actually confirmed this may be showing zero as the block reward simply because new blocks are replacing the data in the API faster than the first full page of blocks confirm. Is this plausible?

Payment processing is still not working. Have a new error this time.

`[I] [ltc1] [Bitcoin Payout Handler] Paying out 29475.41275 LTC to 4 addresses
`
`[E] [ltc1] [Bitcoin Payout Handler] sendmany returned error: Transaction too large code -6
`

This one seems pretty self-explanatory. Is there a limit on transaction sizes inside the payment processor?

**Comment by oliverw** [comment]
Yes that's plausible.

Not a limit of Miningcore but a limit of the blockchain. The transaction is simply too large to be processed because it involves to many inputs. This is something that I've never experienced in production with any coin. A transaction of 30k LTC would be over 1000 blocks.

**Comment by seperatis** [comment]
So I cleaned out all database tables again, then changed the `Payment Interval` from `600` to `60` and turned down the frequency on my L3+ (hoping to mine less blocks) and now payments are processing :-)

Still getting `"reward": 0.000000000000` in the API, I'm going to kill the L3+ miner and use a CPU miner to mine testnet blocks instead, with the goal of no more than 1 block per hour or something and see if the `reward` stat changes to proper block reward in API. As it appears that using an ASIC to mine testnet blocks is just a bad idea due to the extremely low difficulty.

**Comment by seperatis** [comment]
@oliverw The above fixed all the issues. After slowing down the blocks being found and waiting on confirmation to reach 100% the API updated to `"reward": 25.00000000000`

So it appears everything is working as it should now. Thanks for your help with this.

My only last question is why am I seeing the Payment Processor processing payments for the same blocks over and over again? See attached:

![payments](https://user-images.githubusercontent.com/32314615/58901941-086cdc80-86b7-11e9-90cd-27017ebad06b.jpg)

**Comment by oliverw** [comment]
The payment processor runs periodically. It updates each block in `pending` state, checking the state of each block's coinbase transaction for a transition to state `generate` which means its fully confirmed and can be paid out. Once that happens, the block enters the next processing stage where the configured Payout Scheme (PPLNS, Solo etc) kicks in and computes the miner rewards. The resulting amounts are then passed on to the Payment Processor which performs the actual transfer of funds.
