### ISSUE TITLE
Advanced PostgreSQL Database setup Errors

### ISSUE THREAD

**Issue by cryptopool-builders** [coinfoundry/miningcore#651]
postgres@etc:~$ psql -d miningcore -U miningcore -f createdb_postgresql_11_appendix.sql -h 127.0.0.1
Password for user miningcore:
SET
DROP TABLE
psql:createdb_postgresql_11_appendix.sql:17: ERROR:  syntax error at or near "PARTITION"
LINE 13: ) PARTITION BY LIST (poolid);
           ^
psql:createdb_postgresql_11_appendix.sql:19: ERROR:  relation "shares" does not exist
psql:createdb_postgresql_11_appendix.sql:20: ERROR:  relation "shares" does not exist

**Comment by seperatis** [comment]
Did you complete these steps successfully first?
`$ wget https://raw.githubusercontent.com/coinfoundry/miningcore/master/src/Miningcore/Persistence/Postgres/Scripts/createdb.sql`

`$ psql -d miningcore -U miningcore -f createdb.sql`

**Comment by oliverw** [comment]
@cryptopool-builders Are you sure that you are on PostgreSQL 11?

**Comment by cryptopool-builders** [comment]
yes was just about to close this. did a fresh install and no issues with the DB import. Thanks.
