### ISSUE TITLE
LTC Solo Payment Processing Failed on Mainnet

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#652]
After a successful LTC testnet configuration, I switch to the Mainnet and configured pool for Solo.
I rented $100 worth of scrypt hashing power from NiceHash to test the higher difficulty port.

I got super freaking lucky and I found a block in about 2 hours! 😄

After waiting for 100 confirms on the network the payment processor went on to do it's job and kick out the attached error message. Thankfully all 25 LTC are still safe and secure in the pool wallet, but for whatever reason, the other payments didn't go out. (I presume Devs 0.1% fee didn't get paid either).

![Payment-Processing](https://user-images.githubusercontent.com/32314615/59027833-e0908c80-880e-11e9-9afb-bb5b33086cdd.jpg)

**Comment by oliverw** [comment]
```json
{
    "id": "ltc1",
    "enabled": true,
    "coin": "litecoin",
    "address": "LNDA11u4HWzbJaBGiHDvs6SmA8M6avB3wH",
    "rewardRecipients": [
        {
            "address": "LNDA11u4HWzbJaBGiHDvs6SmA8M6avB3wH",
            "percentage": 0.5
        },
        {
            "address": "<your solo wallet>",
            "type": "solo"
        }
    ],
    ...
}
```

**Comment by seperatis** [comment]
@oliverw 
The above fixed the issue and sent payments out. I think I'm going to start an installation/configuration Wiki on some of these configuration settings like this that may not always be apparent. 

**Note:** I would like to point out this is not the expected behavior (in my mind) of a "Solo Pool" though.
I would have thought that when using the  **SOLO** payment scheme that the Miner **_who found the block_** gets the reward, minus the `"rewardRecipients"`  or Pool OP percentages.

Two examples of pools working in this way are:
[solo.ckpool.org](url)
[ltc.tbdice.org](url)

Currently, if you really wanted to mine solo then why not just set a reward recipient to 100%? Is there any other benefit to the as-it-is the current Solo payment scheme?

So maybe this is an improvement request or a feature request, but _is this a possibility_ for future releases of Miningcore? I think it's a great opportunity for Pool OP's and miners especially considering the increased network hash rates. Gives the miners an opportunity to play a little "Blockchain Lottery" and the pool OP's a chance to take a % of the found blocks.

If it's a simple thing maybe just add another payment scheme called "Solo_Pool" or something similar and 100% of block reward **minus** `"rewardRecipients"` goes to the block finders address.

Last but not least.....is the LTC donation address listed on GitHub main page current? I want to donate 10% of this LTC block I found during pool testing towards further development. 

Keep up the great work. Miningcore is coming fantastically!
