### ISSUE TITLE
Additional data in API (Request)

### ISSUE THREAD

**Issue by danielbjornadal** [coinfoundry/miningcore#653]
Request to add additional information to the API response.

* Amount of hashes submited since last block was found. This is used to calculate the current block  effort.
* .poolStats.lastPoolBlockTime allways show null
* The API shows connected miners, but it would be very good to know how many miners and how many workers are connected. (How many miner addresses and how many actually connected)

**Comment by oliverw** [comment]
@danielbjornadal 

1. Computation of this value is quite expensive. No promises.
2. [Fixed[(f29e21618ed59494ed5284450bb6eb6ab5830a76) in dev branch 
3. [Fixed[(358bf79aa87bcfd109501147e6bae1fe80b5e515) in dev branch (just today)

**Comment by danielbjornadal** [comment]
Wow, fast respons :D Very good  job on this pool. Have seen them all, and this looks really promising.
One more thing: Would be great to show .lastPayment on the pool API.

**Comment by danielbjornadal** [comment]
Also, going through and comparing all API data against other top pool softwares.
* minimumConfirmations missing from API response.
* Payment Interval  missing from the API response.
* Miners Paid would be useful information.
* Atomic unit / coin unit would be very useful to have in the API response.
