### ISSUE TITLE
submission failed with: tx-overwinter-active 

### ISSUE THREAD

**Issue by katarinapav** [coinfoundry/miningcore#655]
Hi, having this issue when I mine 144,5 algos. Also having bad-cb-payee on 192 algos. Is there any possibilities to make it working with 144 and 192 algos? I tried zero fork and having same issues depends on algo. Thanks.

**Comment by katarinapav** [comment]
Hi @Konstantin35 , thanks for reply. I will attach coins and config.json. I'm using zero fork which is masternode coin and it should have masternode handler. These bad-cb-payee are because of masternode payments. Regarding overwinter rejects, is it sufficient to add sapling and overwinter true under coins.json? Thanks.
[coins.txt](https://github.com/coinfoundry/miningcore/files/3291551/coins.txt)
[config.txt](https://github.com/coinfoundry/miningcore/files/3291552/config.txt)

**Comment by Konstantin35** [comment]
I think this is all about masternode, see the [dev ](https://github.com/coinfoundry/miningcore/tree/dev) branch.
I think it's the same problem [Issues 617](https://github.com/coinfoundry/miningcore/issues/617)

**Comment by katarinapav** [comment]
Yeah it is about masternodes it seems. Need to check about overwinter rejects as well. I will switch to Issues 617 since it's a same problem so we don't have double tread about same problem. Thanks

**Comment by Konstantin35** [comment]
I want to draw your attention
for vidulum coin needs `EquivPoW` in miningcore it is not, but there is here [Vidulum-MiningCore](https://github.com/vidulum/Vidulum-MiningCore/blob/master/src/Native/libmultihash/equi/equihashverify.cc#L6), [coins.json](https://github.com/vidulum/Vidulum-MiningCore/blob/master/src/Miningcore/coins.json#L1287)

**Comment by katarinapav** [comment]
yeah I know @Konstantin35 thank you. It has been left to fix masternode payments and to check for overwinter rejects as well. It would be nice if you can run all algos on one software.
