### ISSUE TITLE
Verge - Groestl block submission error.

### ISSUE THREAD

**Issue by uurcm16** [coinfoundry/miningcore#656]
### Description

I'm currently testing XVG (Groestl) but daemon rejects found blocks with the error:  `Block 3217487 submission failed with: Block signatures couldn't be created`

I think this issue might be related with this issue: https://github.com/vergecurrency/VERGE/issues/885 

**I'm using v45 btw.**

### Steps to Reproduce

1. Start pool, mine
2. Find block and submit to the daemon.

### Expected behavior

Daemon should accept the block.

### Actual behavior

Daemon rejects the block with the error : `Block XXX submission failed with: Block signatures couldn't be created`

### Reproduces how often

Always

### Version

v45

**Comment by saltyminer** [comment]
Have you seen this https://github.com/vergecurrency/VERGE/issues/885?

**Comment by uurcm16** [comment]
> Have you seen this [vergecurrency/VERGE#885](https://github.com/vergecurrency/VERGE/issues/885)?

Yes, I did see that and I mentioned that issue in my issue.
I investigated the code and coinbase is already conatining a tx. This is why I've started an issue.

**Comment by uurcm16** [comment]
Any idea @oliverw ?

**Comment by saltyminer** [comment]
Did you review the changes made here on this nomp fork to see if that helps?  https://github.com/marpme/node-stratum-pool/commit/12673c137d97d949d8c9b3536a6b731d8331c0fa.  This is from the link in your issue, but wondering if you made these same changes and tried?
