### ISSUE TITLE
adding Sinovate to coins.json

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#657]
I'm trying to add Sinovate to coins.json and I did as following:
`  "sin": {
        "name": "Sinovate",
        "symbol": "sin",
        "family": "bitcoin",
        "coinbaseHasher": {
            "hash": "sha256d"
        },
        "headerHasher": {
            "hash": "x25x"
        },
        "blockHasher": {
            "hash": "reverse",
            "args": [ { "hash": "x25x" } ]
        },
        "hasPayee": true,
        "explorerBlockLink": "http://explorer.sinovate.io/block/$hash$",
        "explorerTxLink": "http://explorer.sinovate.io/tx/{0}",
        "explorerAccountLink": "http://explorer.sinovate.io/address/{0}"
    },`

but when it wants to submit a block I'm facing the following error:
'Block 183316 submission failed with: bad-cb-dev-fee'
any Idea how to fix it? I added '"hasPayee": true,' but still the same.

@oliverw you added this coin to CF, can you please post the setting here? thanks

**Comment by Konstantin35** [comment]
`"hasMasterNodes": true,`

**Comment by oliverw** [comment]
```
      "sin": {
        "name": "Sinovate",
        "symbol": "SIN",
        "family": "bitcoin",
        "coinbaseHasher": {
            "hash": "sha256d"
        },
        "headerHasher": {
            "hash": "x25x"
        },
        "blockHasher": {
            "hash": "reverse",
            "args": [ { "hash": "x22i" } ]
        },
        "hasMasterNodes": true,
        "hasPayee": true,
        "explorerBlockLink": "http://explorer.sinovate.io/block/$hash$",
        "explorerTxLink": "http://explorer.sinovate.io/tx/{0}",
        "explorerAccountLink": "http://explorer.sinovate.io/address/{0}"
      }
```

**Comment by peysab** [comment]
thanks

**Comment by akshaynexus** [comment]
@peysab bad-cb-dev-fee is probably cause pool doesn't pay the devfee if there is one, try using my fork of miningcore and see if that still occurs
