### ISSUE TITLE
Dag Generation is too slow and single-threaded.

### ISSUE THREAD

**Issue by ucyildirim** [coinfoundry/miningcore#658]
Dag generation for ethash coins is too slow. It takes 30 minutes to generate single dag file.
From what I see is, dag files are generated on single thread. Is there any way to make it multi-threaded?

**Comment by saltyminer** [comment]
This would be nice.  If you look at the dag file creation code from ethash it’s nearly identical to our code.  I also run into issues after a few dag file creations and it takes the pool down.  Might be good to abstract the dag file creation from the pool a bit.

**Comment by Konstantin35** [comment]
> 
> 
> Dag generation for ethash coins is too slow. It takes 30 minutes to generate single dag file.
> From what I see is, dag files are generated on single thread. Is there any way to make it multi-threaded?

I think that it is impractical to do a lot of threads let's imagine that several Ethash coins are running and two or more have had a change of eporhi there is no way to please them and they have generated a dag file in all threads while there will be a large load on the server that can affect the performance of the remaining coins.

**Comment by calvintam236** [comment]
> > Dag generation for ethash coins is too slow. It takes 30 minutes to generate single dag file.
> > From what I see is, dag files are generated on single thread. Is there any way to make it multi-threaded?
> 
> I think that it is impractical to do a lot of threads let's imagine that several Ethash coins are running and two or more have had a change of eporhi there is no way to please them and they have generated a dag file in all threads while there will be a large load on the server that can affect the performance of the remaining coins.

How about something like a queue for multithreaded (something like [this](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library?redirectedfrom=MSDN))? Since the CPU trend is going for multi-threads, running in single thread might be a penalty for server has a lot of thread counts? (Like consumer grade midrange AMD CPUs has 16 threads+)

**Comment by oliverw** [comment]
> > > Dag generation for ethash coins is too slow. It takes 30 minutes to generate single dag file.
> > > From what I see is, dag files are generated on single thread. Is there any way to make it multi-threaded?
> > 
> > 
> > I think that it is impractical to do a lot of threads let's imagine that several Ethash coins are running and two or more have had a change of eporhi there is no way to please them and they have generated a dag file in all threads while there will be a large load on the server that can affect the performance of the remaining coins.
> 
> How about something like a queue for multithreaded (something like [this](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library?redirectedfrom=MSDN))? Since the CPU trend is going for multi-threads, running in single thread might be a penalty for server has a lot of thread counts? (Like consumer grade midrange AMD CPUs has 16 threads+)

The code generating the DAG is native code. We have no control how it handles concurrency, nor should we. There's nothing we can reasonably do here. Sorry.
