### ISSUE TITLE
Bitcoin Gold Minincore pools are no longer SEGWIT capable

### ISSUE THREAD

**Issue by ZhiKosta** [coinfoundry/miningcore#659]
close

**Comment by oliverw** [comment]
Why did you close it?

**Comment by ZhiKosta** [comment]
I was referencing codes from the latest version of MC while looking at local codes from v45 which is outdated. While segwit is disabled in v45 (and possibly 44) for Bitcoin Gold i could see that by adding extra configuration option in the latest versions you have taken care of that problem.

For anyone else that finds their pools not including segwit transactions in the mined blocks, the solution for BitcoinGold is to include the segwit option for getBlockTemplate call like this:

v45/src/Miningcore/Blockchain/Equihash/EquihashJobManager.cs 

```
            getBlockTemplateParams = new object[]
            {
                new
                {
                    capabilities = new[] { "coinbasetxn", "workid", "coinbase/append" },
                    rules = new[] { "segwit" }
                }
            };
        }
```

**Comment by oliverw** [comment]
Fixed in dev.
