### ISSUE TITLE
Basic Front End Website

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#66]
Has anyone created a basic front end website for display statistics for the miners and pool hashrate/miners?

Thanks

**Comment by jeong760** [comment]
Dears,

You can check and  change hard coded web front end on following github
Owner wrote on currently it does not fully developed but possible to use your purpose I think.

https://github.com/calvintam236/miningcore-ui

Regards,
John Ahn

**Comment by pfeiflelukas** [comment]
Hi John,

Thanks for that. Is there a read me for how to implement that with miningcore?

Thanks

**Comment by jeong760** [comment]
Dears,

Currently no. but you will need to modificaiton a miningcore-ui.js under js folder, then it sould be work. 

Regards,
John Ahn

**Comment by pfeiflelukas** [comment]
Awesome i will have a go and post my findings/solutions :)

**Comment by pfeiflelukas** [comment]
I did just successfully compile miningcore and i was setting up the conf file to be run and saw that there was only one coin in the example. Does this mean that each coin needs a separate conf file to be run, and how would the miningcore-ui recognise all the API's created?

Thanks
