### ISSUE TITLE
Question, Thanks

### ISSUE THREAD

**Issue by knowndragon** [coinfoundry/miningcore#679]
## Note
First Thanks, This software is is amazing. I have searched issues and read where some will say this software will crap out on you. I don't think that is the case. Now messing around with it, I have figured out if you set you vardif to low for an ASIC you will get rejected shares. Not what i am asking about. 

I really don't have an issue just some questions about the future of the software...

Do you plan on having merged or switching algo added to this project? I was just curious, I am wanting to build a Front end by scratch and don't want to waste time on something that might not be added...

**Comment by oliverw** [comment]
@knowndragon Thanks. Also switching is on the roadmap but since I'm currently quite swamped in my day job, I might take a while to get it done.

**Comment by oliverw** [comment]
Submit a PR.
