### ISSUE TITLE
How can I use a 2 power n integer var diff?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#69]
Dears

The 2 power of n integer var diff support by miningcore and can assign it to the mininer using var diff algorithem?

Regards,
John Ahn

**Comment by jeong760** [comment]
I means that initially miner start from 64 and 64 and 128 and so on var diff assgin from the pool

**Comment by oliverw** [comment]
You mean you want the vardiff algorithm always adjust the diff in power of 2 steps?

**Comment by jeong760** [comment]
@oliverw yes, I want to use a vardiff algorithm always adjust a diff in power of 2 like a 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096 and so on ..

**Comment by oliverw** [comment]
That's currently not supported. If you need absolutely need this, I would invite you to submit a PR that includes configuration options for turning on this feature.
