### ISSUE TITLE
SOLO Mining

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#696]
Hello,
Is there a way to have a SOLO mining on a separate port for a coin? I don't want to pay to the reward to pool's reward address. I want the reward to be payed to the miners wallet which finds the block.

Thanks

**Comment by Konstantin35** [comment]
> 
> 
> Hello,
> Is there a way to have a SOLO mining on a separate port for a coin? I don't want to pay to the reward to pool's reward address. I want the reward to be payed to the miners wallet which finds the block.
> 
> Thanks

Added https://github.com/coinfoundry/miningcore/pull/799
