### ISSUE TITLE
MAJOR BUG: Duplicate share vulnerability, needs immediate patch

### ISSUE THREAD

**Issue by stevecastaneda** [coinfoundry/miningcore#710]
## Description
An attacker may submit duplicate shares without being caught by the pool stratum due to the lack of checking for case sensitivity on nonce1 and the nTime.  

https://github.com/coinfoundry/miningcore/blob/9ff1e2f044c3d45049c6e5672b776e1c735cf4ef/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs#L293

### Expected behavior

Should be denying the share due to duplicate.

### Actual behavior

Share is accepted.

### Reproduces how often

100%

### Additional Information

To fix, please rebuild with the following code.

```
var key = new StringBuilder()
                .Append(extraNonce1)
                .Append(extraNonce2)
                .Append(nTime)
                .Append(nonce)
                .ToString()
                .ToLower(); // lowercase as we don't want to accept case-sensitive values 
```

https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Blockchain/Equihash/EquihashJob.cs

Is also effected and should be updated accordingly.

**Comment by peysab** [comment]
OMG, Thanks alot @stevecastaneda , this little fix saved my life. 
my pool was being attacked for the past few month and the attacker was stealing a lot from my pool using this bug.

Thanks again

**Comment by oliverw** [comment]
Thanks for reporting this @stevecastaneda

**Comment by stevecastaneda** [comment]
Happy to help.  What about the calls to `.toLower()` that were updated?  I'm curious on the benefits from commit d72db18 vs. just updating as I did.

**Comment by oliverw** [comment]
I've already removed them in the Dev branch.
