### ISSUE TITLE
Why miningcore does not use a redis?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#72]
Dears,

I have a question why miningcore does not use a Redis as handling shares and handling payment. 
Because Redis is much efficient to handle a thousand shares from miner and payment calculation.

Regards,
John Ahn

**Comment by Bratan** [comment]
Redis is just a caching system, not related to handing shares and/or payments.

**Comment by jeong760** [comment]
@Bratan  yes I know but it will reduce a overhaed to wrriten all imfo directly into the DB. And Redis is more faster then db.

**Comment by oliverw** [comment]
PostgreSQL is an extremely mature and fast RDBMS. But even it wouldn't be as fast, it wouldn't matter as the shares are recorded and processed completely decoupled from the performance critical parts of the share processing pipeline. 

I suggest you take a look at this: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Payments/ShareRecorder.cs
