### ISSUE TITLE
What is the usual jobbroadcastTimeout value for sha256 coins?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#74]
Dears,

Just I wonder how I set a JobbroadcaseTimeout value for sha256 coins such as BTC and GLT. 
What is the usual value or suitable second for these type coins? should I set it their new block generation time such 600?

Regards,
John Ahn

**Comment by oliverw** [comment]
It's the number of seconds until the pool broadcasts the current job again IF and only IF there no new block detected on the blockchain. This is to ensure that miners do think the pool went dead. New blocks are sent to all miners immediately of course. We currently use 55sec for all pools on poolmining.org.

**Comment by jeong760** [comment]
Thank you.  And I think we need to make a some wiki explanation each configurable item on config file.

**Comment by oliverw** [comment]
Absolutely.
