### ISSUE TITLE
DGB-Odocrypt support??

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#768]
Does Miningcore currently support DGB Odocrypt?

**Comment by seperatis** [comment]
bump

**Comment by oliverw** [comment]
Won't happen unless someone submits a PR. I've experimented with Odo before they actually introduced it, but failed due to lack of a proper hardware miner.

**Comment by calvintam236** [comment]
@oliverw I am reopening this just for visibility for PR contribution.
