### ISSUE TITLE
Addition of Bitconnect Coin

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#77]
Can we add this to the coin list please :)

**Comment by oliverw** [comment]
It appears to be a scrypt coin so adding it should be easy. Why don't you get your hands dirty? 😄

**Comment by pfeiflelukas** [comment]
@oliverw Just trying now.

            // SHA256
            { CoinType.BTC, sha256Coin },
            { CoinType.BCC, sha256Coin },
            { CoinType.NMC, sha256Coin },
            { CoinType.PPC, sha256Coin },
	    { CoinType.GLT, sha256Coin },

What is the BCC sha256Coin? Bitconnect has the abbreviation of BCC and is scrypt.

**Comment by oliverw** [comment]
Ok, let me just do it in a branch. I'll tell you when it's ready later today.

**Comment by pfeiflelukas** [comment]
@oliverw I have fixed the BCH issues and added BCC and also tried to implement peercoin. No errors appear but both of them just continually say "Waiting for daemons to come online...".

I have used the same configuration file for the previous coins which has been working well. I have even copied the default configuration file from both BCC and PPC sources but still no success. 

I can also use telnet IP:PORT and it comes out as connected but the server refuses to connect. Any ideas?

**Comment by oliverw** [comment]
Are you sure that the daemon runs at the correct port matching the pool config?

**Comment by oliverw** [comment]
And you are right Bitcoin Cash is using the wrong symbol BCC. That needs to be changed.

**Comment by pfeiflelukas** [comment]
Yep the config port matches the port in the conf file for each coin. I have been using:

rpcuser=user
rpcpassword=password
rpcallowip=internal address of the server
rpcport=high port number
listen=1
server=1
daemon=1

**Comment by oliverw** [comment]
What happens if you run this (make sure to replace 1234 with the actual daemon port):

```
curl -u user:pass --data-binary '{"jsonrpc": "2.0", "id":"1", "method": "getnetworkinfo", "params": [] }' -H 'content-type: application/json' -X POST http://127.0.0.1:1234
```
If you need curl for windows look here: https://curl.haxx.se/download.html and use this command line:

```
curl -u user:pass --data-binary "{'jsonrpc': '2.0', 'id':'1', 'method': 'getnetworkinfo', 'params': [] }" -H "content-type: application/json" -X POST http://127.0.0.1:1234
```

**Comment by pfeiflelukas** [comment]
Both result in the same.
{"result":null,"error":{"code":-32601,"message":"Method not found"},"id":"1"}

Does this mean that the server is trying to call "getworkinfo" but these coins dont have the corresponding rpc command?

**Comment by oliverw** [comment]
Looks like. Try "getinfo", "getmininginfo" and "getpeerinfo".

**Comment by pfeiflelukas** [comment]
All of those work for the two coins :)

**Comment by oliverw** [comment]
Supporting them would be a bit more involved since I just phased out support for getinfo a couple days ago since all major coins will stop supporting it soon.

**Comment by pfeiflelukas** [comment]
Ah dam, any idea when this will be done?

**Comment by oliverw** [comment]
I'll see what I can do. No promises though.

**Comment by pfeiflelukas** [comment]
Awesome thanks
