### ISSUE TITLE
Please enroll in Github Sponsor Program

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#775]
I know a handful of people who want to sponsor this project (including me), but cannot, because it's not set up properly. (Github Sponser), or @oliverw maybe has not enrolled into it.

@oliverw please fix this.

I'm hoping enough people can sponsor this project to get @oliverw to come back to working on it. Miningcore is hands-down the best open-source solution for mining pool software.

I know @oliverw spent **a lot of time** on here playing "Tech Support" for issues that were absolutely unrelated to MC software, and mostly related to peoples lack of experience/knowledge about using Linux, Postgres, or understanding basic networking, and/or how coin daemons work. 

I've started a very detailed WIKI on Miningcore (will release soon) that will hopefully take care of the most common issues that people run into so that if @oliverw did come back to the project he can spend a lot less time doing tech support and actually work on the software instead.

Miningcore is really great and I don't want to see this project die. I know a lot of people are still using it b/c of all the questions we get in the Gitter channel.

@oliverw If you see this, please come back! We've missed you sir! 😄

**Comment by seperatis** [comment]
bump

**Comment by calvintam236** [comment]
I think now is a good time to bump this for @oliverw.
