### ISSUE TITLE
How To Display All Sections Without Mining Coins

### ISSUE THREAD

**Issue by ryanmoutsourcing** [coinfoundry/miningcore#823]
Description

I have been asked to design some pages around this mining pool to style it . 

Without active mining going on, none of the pages display.

Which parts within the code can I change to make all pages appear without any mining going on?

Thanks,

**Comment by arubinofaux** [comment]
you would need to populate the database with dummy data so that the API has data to return. or better method would be to run the miningcore instance with a testnet coin

**Comment by seperatis** [comment]
Actually you can use my JSON API endpoint on my development server to populate all your data if you'd like.

This will allow you to develop without having to setup your own mining pool and sever. 

Here is the main API endpoint.

http://157.245.208.21:4000/api/pools/

You can view my front end here: http://157.245.208.21

Cheers

**Comment by seperatis** [comment]
PS - take a look here for all the API endpoint options and data available.

https://github.com/coinfoundry/miningcore/wiki/API
