### ISSUE TITLE
Connection json error state: Unexpected character encountered while parsing value: P. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by TechyGuy17** [coinfoundry/miningcore#824]
Hello, i started a zcash pool with this software but after a bit of thinking i came to the conclusion zcash is almost dead. So i looked thru the list of supported coins and chose ravencoin. I changed the config, synced the node. But when i start it it first only says

"Using configuration file config.json"

and after a few minutes a error message occur:

"[E] [<poolname>] [0HM7ARH53GU9G] Connection json error state: Unexpected character encountered while parsing value: P. Path '', line 0, position 0."

I cant figure out what part is failing. 
I would be happy if someone could help me figure out what is wrong. I have tried reinstalling the db software (postgreSQL) and looked thru the config many times.

Kind regards, TechyGuy

**Comment by calvintam236** [comment]
What version of `zcashd` and `miningcore` version you are using?

**Comment by seperatis** [comment]
Ravencoin is not supported anymore. They've switched algo's twice since being implemented and Miningcore has not been updated for this.

X16R >> X16Rv2 >> KawPow

**Comment by oliverw** [comment]
There's currently no way to communicate clearly what's really working in `coins.json` and what's not, except for removing it from the file which is also not ideal.

**Comment by seperatis** [comment]
> There's currently no way to communicate clearly what's really working in `coins.json` and what's not, except for removing it from the file which is also not ideal.

Perhaps for now we can simply add some comments on coins that are **not** working. Long-Term maybe some error handling that can spit-out an error for coins that are not supported. I dunno....

**Comment by oliverw** [comment]
> > There's currently no way to communicate clearly what's really working in `coins.json` and what's not, except for removing it from the file which is also not ideal.
> 
> Perhaps for now we can simply add some comments on `coins.json` for those which are **not** working. Long-Term maybe some error handling that can spit-out an error for coins that are not supported. I dunno....

Comments in the code or in discussions?

**Comment by seperatis** [comment]
@oliverw I was thinking for now something even just as simple as this:

[https://i.imgur.com/vYZ2bNn.png](url)

**Comment by oliverw** [comment]
In the json. Yeah thats a good solution for now.

**Comment by TechyGuy17** [comment]
After a while i actually got the ravencoin pool to run. But i guess it would not work as is should. I knew from before that they switched from x16r But hoped you just hadnt updated the name of the algo...

**Comment by calvintam236** [comment]
> In the json. Yeah thats a good solution for now.

I think that won’t work. JSON has no native comment syntax. Maybe use Projects in the repo and create an task issue for each outdated coin?

**Comment by oliverw** [comment]
> > In the json. Yeah thats a good solution for now.
> 
> I think that won’t work. JSON has no native comment syntax. Maybe use Projects in the repo and create an task issue for each outdated coin?

Comments in JSON are in a semi-legal state. But JSON.Net can handle them.

**Comment by oliverw** [comment]
Closing this as this discussion is no longer related to the issue itself. :)

**Comment by mxride** [comment]
Has the issue with 
encountered while parsing value: . Path '', line 0, position 0.

Was there ever a resolution for this. My Asci miners when connecting trigger this. then end up getting banned

**Comment by TechyGuy17** [comment]
As far as i know there were never a fix

**Comment by mxride** [comment]
@TechyGuy17  thank you. 
I turned on debug mode and can see the garbage from my Goldershell miners,
Would you know which file does the parsing or a way  I can strip this? Thanks in advance

 Received data:  ~�ʯ�6��Y(E���uӅ3    ���:R�V�G �oGM��O��9�>Y�2��:�(i��n'H�r�>�,�0��+�/��$�(k�#�'g�
�9�     �3��=<5/��



0.                                                                                                                                                                              + -3R$ ���!���YbR�Y�a�
 E���� @
[2022-04-28 20:01:45.3314] [D] [ltc1] [0HMH9A7LUA2PO] [NET] Waiting for data ...
PuTTYPuTTYPuTTYPuTTYPuTTY[2022-04-28 20:01:45.3420] [D] [ltc1] [0HMH9A7LUA2PO] [PIPE] Waiting for data ...
[2022-04-28 20:01:45.3426] [D] [ltc1] [0HMH9A7LUA2PO] [PIPE] Received data:  ~�ʯ�6��Y(E���uӅ3   ���:R�V�G �oGM��O��9�>Y�2��:�(i��n'H�r�>�,�0��+�/��$�(k�#�'g�
�9�     �3��=<5/��

0.                                                                                                                                                                              + -3R$ ���!���YbR�Y�a�
 E���� @
PuTTYPuTTYPuTTYPuTTYPuTTY[2022-04-28 20:01:45.3562] [E] [ltc1] [0HMH9A7LUA2PO] Connection json error: Unexpected character encountered while parsing value: . Path '', line 0, position 0.

**Comment by TechyGuy17** [comment]
I gave up on getting it done so sadly not. Didnt look in to the code

**Comment by mxride** [comment]
Im starting to. What machine did you  use when you saw this error? Was it a Glodshell

**Comment by mxride** [comment]
So digging into this more. I start the pool, I connect no miners at all. then the API starts and kicks the error

Connection json error: Unexpected character encountered while parsing value: G. Path '', line 0, position 0.

Debug log below

Accept: /
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Origin: http://motominer.us/
Referer: http://motominer.us/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

[2022-04-28 23:54:46.9971] [E] [ltc1] [0HMH9E9SPK57C] Connection json error: Unexpected character encountered while parsing value: G. Path '', line 0, position 0.
[2022-04-28 23:54:47.0068] [I] [ltc1] [0HMH9E9SPK57C] Connection closed

**Comment by oliverw** [comment]
Most likely Script kiddies. Get used to it and ignore 😉

**Comment by mxride** [comment]
Oliver,
Its not Script kiddies that I can tell, I connect my miner and immediately the Unexpected character encountered while parsing value: G. Path '', line 0, position 0  error shows up. The miner will connect, so I'm thinking the Goldshell miner is sending random ASCII characters. I have check multiple miners and they all generate the error. Was wondering what DLL is doing the Json parsing of the connection string?

**Comment by oliverw** [comment]
Json.Net, used by millions of projects.

**Comment by mxride** [comment]
Thanks Oliver for the quick reply. Kind regards

**Comment by oliverw** [comment]
- It appears that 8443 had an old SSL config attached was the issue.

Attached? Are we talking about Windows here?

**Comment by mxride** [comment]
No, Ubuntu 20.04 LTS. UFW disabled, 
Port 8443 may not be the true cause, but surely the simple changing of the miner port from 8443 to 3052 solved my issue.
