### ISSUE TITLE
ETC Support

### ISSUE THREAD

**Issue by CryptoCyberCid** [coinfoundry/miningcore#844]
Hello !

First of all it is not an issue more likely a request.
You deleted Ethereum but what about ETC ?
You will support it ?
What about Vertcoin which changes to Verthash ?

With best Regards
CCC

**Comment by oliverw** [comment]
The Ethereum related code was removed because it hadn't been maintained for a long time. In hindsight it will propably return inside in archive folder here in the repo. In case someone wants to pick it up.

If Verthash is going to be supported depends on the magnitude of changes required for it. But probably yes.

**Comment by Konstantin35** [comment]
Today I started the return of Ethereum in my [repository](https://github.com/Konstantin35/miningcore), I took Release 53 as a basis, stay tuned, I will test it on the Mainnet, I will post the code

**Comment by oliverw** [comment]
> Today I started the return of Ethereum in my [repository](https://github.com/Konstantin35/miningcore), I took Release 53 as a basis, stay tuned, I will test it on the Mainnet, I will post the code

If you can get it to work, I'll gladly accept a PR to bring it back into `master`.

**Comment by Konstantin35** [comment]
> 
> 
> > Today I started the return of Ethereum in my [repository](https://github.com/Konstantin35/miningcore), I took Release 53 as a basis, stay tuned, I will test it on the Mainnet, I will post the code
> 
> If you can get it to work, I'll gladly accept a PR to bring it back into `master`.

I have created my own repository for my own project and there are minor changes in the code regarding the default name of the worker on all coins. I will create a PR separately if possible and in time.

**Comment by calvintam236** [comment]
@Konstantin35 just a friendly reminder: if you want to make a PR to here, your repo has to be forked from this repo. Otherwise, the PR option is not available. You can branch out at tag `v53` and add your code from there.

**Comment by Konstantin35** [comment]
> 
> 
> @Konstantin35 just a friendly reminder: if you want to make a PR to here, your repo has to be forked from this repo. Otherwise, the PR option is not available. You can branch out at tag `v53` and add your code from there.

Hi I understand I will do this separately.
