### ISSUE TITLE
support for geth on ethreum based pow coins

### ISSUE THREAD

**Issue by frndxyz** [coinfoundry/miningcore#86]
as much of ethbased pow coins provide geth config and convert it to parity is much difficult to test with pool, geth support is needed.

any possibility to implement it in future?

**Comment by oliverw** [comment]
Highly unlikely at the moment because parity has a couple features not present in geth. The most important one being the presence of the block height in its getWork response.

**Comment by oliverw** [comment]
Closing this for now.
