### ISSUE TITLE
What is private const int MaxRequestLength = 8192; means?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#87]
Dears

I have a question about private const int MaxRequestLength = 8192;.
if I changed from an 8192 to more bigger value what things affected?

Regards,
John Ahn

**Comment by oliverw** [comment]
@jeong760 MaxRequestLength is to prevent someone from bombarding the server with megabytes of junk data with the intent to crash the server. Feel free to increase it to your liking.

**Comment by jeong760** [comment]
Dears,

Does it related to ew RecyclableMemoryStreamManager(0x200, 16 * 0x200, 0x20000);?
if I change a 16*0x200 to 32 * 0x200, what affect?

Regards,
John Ahn

**Comment by oliverw** [comment]
Why would you want to do that?

**Comment by jeong760** [comment]
I want to see the result what affect
