### ISSUE TITLE
Coin support request: Straks (STAK)

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#88]
https://github.com/DeckerSU/yiimp/commit/baf855a4de8b9a6b55ff37723e6437ab643c8311#diff-c4b7ae2ce5a76e060ff0ba2ea76d8f7e

Looking to add straks support to this library. Any idea how that commit added support?

**Comment by oliverw** [comment]
The commit just adds another output (to charity) to the coinbase tx. I can't see any changes that appear to be mandatory to make it work.

**Comment by Kukks** [comment]
That was my initial thought too. I'll go through the branch some more and
see what else is there. Thanks! I'll be throwing a prayer your way with
some new work I've been doing soon.

 Great work so far on this!

**Comment by oliverw** [comment]
@Kukks Thanks 😄

**Comment by Kukks** [comment]
@oliverw Apart from the 5% charity donation, there must also be some more stuff added to the block. 
When using the straks testnet and submitting a block, MiningCore tells me it is inconclusive locally..

**Comment by oliverw** [comment]
@Kukks Inconclusive usually just means that the daemon thinks he is not on the longest chain. Are you mining against testnet or regtest?

**Comment by Kukks** [comment]
@oliverw Testnet. It was going crazy with the new blocks found though.

**Comment by oliverw** [comment]
Do you get "inconclusive" all the time or just ocasionally?

**Comment by Kukks** [comment]
All the time

**Comment by Kukks** [comment]
I'm not at my dev pc, but I'll try get you a more detailed report on what issues I've experienced. I got a completely different error on my vps configured for straks testnet. Something about no balance in treasury fund but no blocks were being recorded in the postgres database.

**Comment by oliverw** [comment]
Might still be something with your testnet connection. Any chance for running two coin daemons in regtest mode interconnected locally using addnode?

**Comment by Kukks** [comment]
@oliverw This is the other error:
```
[2017-11-23 14:32:08.5784] [I] [straks1] [Pool] [0HL9IEQA01K87] Share accepted: D=1
[2017-11-23 14:32:09.1993] [I] [straks1] [Bitcoin Job Manager] Submitting block 53845 [f5374001ac60e9bfc21dd11e5fabe9f422ac35f1689727e7c30204aba80c42ff]
[2017-11-23 14:32:09.2089] [W] [straks1] [Bitcoin Job Manager] Block 53845 submission failed with: cb-no-treasury-funding
```

I'll set up another daemon now

**Comment by oliverw** [comment]
Ok, sounds like a consensus rule violation which would confirm your assumption that supporting that coin requires some code changes.

**Comment by oliverw** [comment]
Confirmed: According to their [chainparams](https://github.com/straks/straks/blob/master/src/chainparams.cpp) they are utilizing both treasury rewards and masternodes (similar to Dash).

**Comment by Kukks** [comment]
I've tried this so far instead of the current Bitcoin Job based on the ZCash one:
```
        private Transaction HandleStraksOutputTransaction()
        {
            rewardToPool = new Money(Math.Round(BlockTemplate.CoinbaseValue * (1m - (5) / 100m)) + rewardFees, MoneyUnit.Satoshi);

            var tx = new Transaction();
            tx.AddOutput(rewardToPool, poolAddressDestination);

            // treasury reward (t-addr)
            var destination = FoundersAddressToScriptDestination(GetTreasuryRewardAddress());
            var amount = new Money(Math.Round(BlockTemplate.CoinbaseValue * (5/ 100m)), MoneyUnit.Satoshi);
            tx.AddOutput(amount, destination);

            return tx;
        }
```

Still same error though

**Comment by oliverw** [comment]
@Kukks Not bad for a first shot. I'm pretty sure you realize that this would actually go into derived class similar to ZCashJob.

**Comment by Kukks** [comment]
@oliverw For sure, I'm just trying to get this up and running before the mining rewards go live( in ~2 hours). I'm still getting `cb-no-treasury-funding` however. Do you think I missed something? Based on the commit in the first post, I think it's ok but I don't know C++ so I guessed my way around it.. This is the generated transaction:
```
{{
  "hash": "32b4a6ce6d03dc20bd262d032204d71cc81b547fca599f860efff56ff3e5e1ec",
  "ver": 1,
  "vin_sz": 0,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 76,
  "in": [],
  "out": [
    {
      "value": "9.50000000",
      "scriptPubKey": "OP_DUP OP_HASH160 fda6713373fd3183a13e9d1980432fd0a752de4f OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.50000000",
      "scriptPubKey": "OP_HASH160 5e65cb7e463900a2d3b2b48e17bac0e086ad6ad3 OP_EQUAL"
    }
  ]
}}
```

**Comment by oliverw** [comment]
@Kukks Being not familiar with that coin myself there's not much I can do to help you with that besides recommending you my go-to approach when dealing with issues like that and that is reading the coin's [miner.cpp](https://github.com/straks/straks/blob/master/src/miner.cpp) and comparing what they do there with my own implementation.

**Comment by Kukks** [comment]
@calvintam236  @oliverw  This task is done once my PR(#90 ) is merged.
