### ISSUE TITLE
Eth not connected 

### ISSUE THREAD

**Issue by FndNur1Labs** [coinfoundry/miningcore#888]
Did I need fill user and pass on daemon. And how. There no eth used that except we create address.

![IMG-20210626-WA0005.jpg](https://user-images.githubusercontent.com/11433397/124380021-af803000-dce4-11eb-8588-465a0685d25d.jpg)

![Screenshot_20210704-163019.png](https://user-images.githubusercontent.com/11433397/124380117-359c7680-dce5-11eb-877a-829f733c0ef4.png)

**Comment by calvintam236** [comment]
Please provide more information e.g. what version, your setup. This also looks like a support question, which should be opened in the Discussions.

**Comment by Konstantin35** [comment]
@FndNur1Labs 
Are you sure that the installation rented on MRR supports `EthereumStratum/1.0.0`

**Comment by oliverw** [comment]
You could set the `logLevel` parameter to debug in your pool config and post the log after attempting to point MRR to your pool.

**Comment by elsanosi** [comment]
MRR does not Support EthereumStratum/1.0.0.
You can use External Stratum setup explained by Oliverw earlier.

**Comment by oliverw** [comment]
> MRR does not Support EthereumStratum/1.0.0.
> You can use External Stratum setup explained by Oliverw earlier.

AFAIK @Konstantin35 is planning to implement it soon.

**Comment by seperatis** [comment]
> MRR does not Support EthereumStratum/1.0.0.
> You can use External Stratum setup explained by Oliverw earlier.

Explained by OliverW earlier, where exactly?

**Comment by FndNur1Labs** [comment]
I'm curious about this but thank for respond. Did I need reinstall extra stratum?
