### ISSUE TITLE
master broken currently?

### ISSUE THREAD

**Issue by justnx** [coinfoundry/miningcore#89]
Can't compile on Debian:

Throwing me:

find . -name '*.o' -exec rm -r {} \;
rm libcryptonote.so
gcc -Wall -c -fPIC -O2 -g -Wno-pointer-sign -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers   -c -o bcrypt.o bcrypt.c
In file included from bcrypt.c:40:0:
./stdint.h:34:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^
In file included from bcrypt.c:40:0:
./stdint.h:94:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'int64_t'
 typedef signed __int64       int64_t;
                              ^
./stdint.h:95:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'uint64_t'
 typedef unsigned __int64     uint64_t;
                              ^
./stdint.h:102:9: error: unknown type name 'int64_t'
 typedef int64_t   int_least64_t;
         ^
./stdint.h:106:9: error: unknown type name 'uint64_t'
 typedef uint64_t  uint_least64_t;
         ^
./stdint.h:112:9: error: unknown type name 'int64_t'
 typedef int64_t   int_fast64_t;
         ^
./stdint.h:116:9: error: unknown type name 'uint64_t'
 typedef uint64_t  uint_fast64_t;
         ^
./stdint.h:128:9: error: unknown type name 'int64_t'
 typedef int64_t   intmax_t;
         ^
./stdint.h:129:9: error: unknown type name 'uint64_t'
 typedef uint64_t  uintmax_t;
         ^
<builtin>: recipe for target 'bcrypt.o' failed
make: *** [bcrypt.o] Error 1
cp: cannot stat '../Native/libmultihash/libmultihash.so': No such file or directory
find . -name '*.o' -exec rm -r {} \;
rm libmultihash.so
rm: cannot remove 'libmultihash.so': No such file or directory
Makefile:26: recipe for target 'clean' failed
make: *** [clean] Error 1

**Comment by rterbush** [comment]
Not having any trouble here compiling and running master. You compiling with gcc6?

**Comment by justnx** [comment]
i solved it by removing stdint.h

that should be excluded in universal build repos isn't it?

**Comment by oliverw** [comment]
@justnx Could you help me out here. What's the issue with stdint.h?

**Comment by justnx** [comment]
when compiling: src/Native/libmultihash it throws:
./stdint.h:34:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
#error "Use this header only with Microsoft Visual C++ compilers!"

on my linux environment.

Weirdly on latest git pull it works again, so anything have been fixed/modified to bypass this header?

**Comment by oliverw** [comment]
@justnx Nope. No recent commits touching this area.

**Comment by justnx** [comment]
@oliverw Very weird. Since it works, im closing this issue.
