### ISSUE TITLE
Seg fault at building v57

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#903]
**Describe the bug**
Seg fault thrown at building v57.

**To Reproduce**
https://github.com/r3gistry/docker_miningcore/blob/master/57/Dockerfile.amd64

**Expected behavior**
Successful build.

**Additional context**

```
10 8.410 Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET
#10 8.410 Copyright (C) Microsoft Corporation. All rights reserved.
#10 8.410
#10 9.897 Determining projects to restore...
#10 24.70 Restored /tmp/miningcore-57/src/Miningcore/Miningcore.csproj (in 14.23 sec).
#10 28.10 Segmentation fault (core dumped)
#10 28.11 /root/.nuget/packages/gitversion.msbuild/5.6.10/tools/GitVersion.MsBuild.targets(9,9): error MSB3073: The command "dotnet --roll-forward Major "/root/.nuget/packages/gitversion.msbuild/5.6.10/tools/netcoreapp3.1/gitversion.dll" "/tmp/miningcore-57/src/Miningcore" -output file -outputfile obj/gitversion.json" exited with code 139. [/tmp/miningcore-57/src/Miningcore/Miningcore.csproj]
```

**Comment by chadouming** [comment]
I had this issue when trying to build from alpine linux. Building from ubuntu worked fine though. I'm not sure if it's an alpine dotnet issue or a miningcore issue.

**Comment by calvintam236** [comment]
> I had this issue when trying to build from alpine linux. Building from ubuntu worked fine though. I'm not sure if it's an alpine dotnet issue or a miningcore issue.

not sure either. v56 builds fine with same dotnet image, so it is probably miningcore?

**Comment by calvintam236** [comment]
By reviewing the error message and checking blame, 

https://github.com/coinfoundry/miningcore/blob/091c1094791577f701e82d153d801cff2cce4449/src/Miningcore/Miningcore.csproj#L47-L50

was added in 091c1094791577f701e82d153d801cff2cce4449 and causing the seg fault.

@oliverw can we revert this and add this back once https://github.com/GitTools/GitVersion/issues/2656 has fixed?

**Comment by oliverw** [comment]
> By reviewing the error message and checking blame,
> 
> https://github.com/coinfoundry/miningcore/blob/091c1094791577f701e82d153d801cff2cce4449/src/Miningcore/Miningcore.csproj#L47-L50
> 
> was added in [091c109](https://github.com/coinfoundry/miningcore/commit/091c1094791577f701e82d153d801cff2cce4449) and causing the seg fault.
> 
> @oliverw can we revert this and add this back once [GitTools/GitVersion#2656](https://github.com/GitTools/GitVersion/issues/2656) has fixed?

I'm tired of constantly chasing Alpine related bugs, so no.
