### ISSUE TITLE
Unable to payout Bitcoin format address

### ISSUE THREAD

**Issue by chadouming** [coinfoundry/miningcore#906]
**Describe the bug**
First character of the wallet is converted to a lowercase. Seems very similar to issue #20 

Seems to be happening since the JsonRPC overhaul. Might have forgotten a serializer setting somewhere. Going through the whole commit as I'm writing this.

**Comment by oliverw** [comment]
Any news?

**Comment by oliverw** [comment]
Might be fixed by 4a9b499ad99cdb355eccca474d36da25b2d39327

**Comment by oliverw** [comment]
Fixed in Release 59.
