### ISSUE TITLE
DGB-Odocrypt support??

### ISSUE THREAD

**Issue by belmix** [coinfoundry/miningcore#925]
### Discussed in https://github.com/coinfoundry/miningcore/discussions/849

<div type='discussions-op-text'>

<sup>Originally posted by **seperatis** August 15, 2020</sup>
Does Miningcore currently support DGB Odocrypt?</div>

**Comment by oliverw** [comment]
Nope. The implementation I once did prior the the release of the odominer hardware, did not actually work.

**Comment by belmix** [comment]
as far as I understand, just need to calculate the odo-key and pass it to json
![odokey](https://user-images.githubusercontent.com/4902701/132350380-b751483a-6501-4e71-913a-a5c7031a4abd.png)
![odokey2](https://user-images.githubusercontent.com/4902701/132350505-ee961d71-55ea-4868-8761-6a4832c6a172.jpg)

**Comment by belmix** [comment]
![image](https://user-images.githubusercontent.com/4902701/132350900-274e32a1-498e-41e0-9b49-7568f491443d.png)

**Comment by belmix** [comment]
![image](https://user-images.githubusercontent.com/4902701/132350975-1248d76f-af01-40a9-8055-ee46fa2c04e0.png)

**Comment by belmix** [comment]
![image](https://user-images.githubusercontent.com/4902701/132352199-f802c7fe-8f89-40b2-a1f1-cfb9f2fd03ab.png)

**Comment by belmix** [comment]
sorry for the pictures )
