### ISSUE TITLE
Send miner payments on same new-found block by the pool

### ISSUE THREAD

**Issue by cryptagoras** [coinfoundry/miningcore#95]
I was wondering if the following is currently or would be possible:
In case the pool finds a new block, to include the payments to the miners on the same block.

I can see it being useful for certain cases for extra profitability etc., although on the other hand there's the possibility of losing the reward to a new block due to the extra delay to prepare the payment tx.

Thanks

**Comment by oliverw** [comment]
Sorry not possible. The risk of losing the block due to delayed submission is simply too high. There's simply to much work involved in the payment calculation (database queries) to make it realtime capable.
