### ISSUE TITLE
Payouts not registered in Ergo testnet

### ISSUE THREAD

**Issue by szilardkoppel** [coinfoundry/miningcore#950]
Hello,

My problem is that im testing miningcore on ergo. Everything working fine except payouts not registered in db.

My terminal log:
[I] [erg1] [Ergo Payout Handler] Unlocked block 76457 worth 67.5 ERG
[I] [erg1] [Ergo Payout Handler] Unlocked block 76458 worth 67.5 ERG 
[I] [erg1] [Ergo Payout Handler] Unlocked block 76459 worth 67.5 ERG 
[I] [erg1] [Ergo Payout Handler] Unlocked block 76461 worth 67.5 ERG 
[I] [erg1] [Ergo Payout Handler] Unlocked block 76462 worth 67.5 ERG 
[I] [PayoutManager] Processing payments for pool erg1, block 76457 
[I] [erg1] Adding 0.6075 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim 
[I] [PPLNS Payment] Fetching page 0 of shares for pool erg1, block 76457 
[I] [PPLNS Payment] Balance-calculation for pool erg1, block 76457 completed with accumulated score 0.2 (100%) 
[I] [PPLNS Payment] Adding 66.8925 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim for 0 K (0.3332537773228919) shares for block 76457 
[I] [PPLNS Payment] Fetching page 0 of discarded shares for pool erg1, block 76457 
[I] [PPLNS Payment] 0 K (0.02130356052579787) total discarded shares, block 76457 
[I] [PPLNS Payment] 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim = 0 K (0.02130356052579787) discarded shares, block 76457 
[I] [PPLNS Payment] Deleting 27 discarded shares before 2021-09-19T11:23:49.5364390 
[I] [PPLNS Payment] 0 K (0.33) shares contributed to a total payout of 66.8925 ERG (100.00% of block reward) to 1 addresses 
[I] [PayoutManager] Processing payments for pool erg1, block 76458 
[I] [erg1] Adding 0.6075 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim 
[I] [PPLNS Payment] Fetching page 0 of shares for pool erg1, block 76458 
[I] [PPLNS Payment] Balance-calculation for pool erg1, block 76458 completed with accumulated score 0.2 (100%) 
[I] [PPLNS Payment] Adding 66.8925 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim for 0 K (0.47855096654361956) shares for block 76458 
[I] [PPLNS Payment] Fetching page 0 of discarded shares for pool erg1, block 76458 
[I] [PPLNS Payment] 0 K (0.006058440988760387) total discarded shares, block 76458 
[I] [PPLNS Payment] 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim = 0 K (0.006058440988760387) discarded shares, block 76458 
[I] [PPLNS Payment] Deleting 8 discarded shares before 2021-09-19T11:24:54.5724000 
[I] [PPLNS Payment] 0 K (0.48) shares contributed to a total payout of 66.8925 ERG (100.00% of block reward) to 1 addresses 
[I] [PayoutManager] Processing payments for pool erg1, block 76459 
[I] [erg1] Adding 0.6075 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim 
[I] [PPLNS Payment] Fetching page 0 of shares for pool erg1, block 76459 
[I] [PPLNS Payment] Balance-calculation for pool erg1, block 76459 completed with accumulated score 0.2 (100%) 
[I] [PPLNS Payment] Adding 66.8925 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim for 0 K (0.4) shares for block 76459 
[I] [PPLNS Payment] Fetching page 0 of discarded shares for pool erg1, block 76459 
[I] [PPLNS Payment] 0 K (0.0060098817523467005) total discarded shares, block 76459 
[I] [PPLNS Payment] 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim = 0 K (0.0060098817523467005) discarded shares, block 76459 
[I] [PPLNS Payment] Deleting 10 discarded shares before 2021-09-19T11:27:01.8075230 
[I] [PPLNS Payment] 0 K (0.4) shares contributed to a total payout of 66.8925 ERG (100.00% of block reward) to 1 addresses 
[I] [PayoutManager] Processing payments for pool erg1, block 76461 
[I] [erg1] Adding 0.6075 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim 
[I] [PPLNS Payment] Fetching page 0 of shares for pool erg1, block 76461 
[I] [PPLNS Payment] Balance-calculation for pool erg1, block 76461 completed with accumulated score 0.2 (100%) 
[I] [PPLNS Payment] Adding 66.8925 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim for 0 K (0.3923294907738739) shares for block 76461 
[I] [PPLNS Payment] Fetching page 0 of discarded shares for pool erg1, block 76461 
[I] [PPLNS Payment] 0 K (0.0193490266342969) total discarded shares, block 76461 
[I] [PPLNS Payment] 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim = 0 K (0.0193490266342969) discarded shares, block 76461 
[I] [PPLNS Payment] Deleting 24 discarded shares before 2021-09-19T11:30:35.7075680 
[I] [PPLNS Payment] 0 K (0.39) shares contributed to a total payout of 66.8925 ERG (100.00% of block reward) to 1 addresses 
[I] [PayoutManager] Processing payments for pool erg1, block 76462 
[I] [erg1] Adding 0.6075 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim 
[I] [PPLNS Payment] Fetching page 0 of shares for pool erg1, block 76462 
[I] [PPLNS Payment] Balance-calculation for pool erg1, block 76462 completed with accumulated score 0.2 (100%) 
[I] [PPLNS Payment] Adding 66.8925 ERG to balance of 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim for 0 K (0.48544615209519804) shares for block 76462 
[I] [PPLNS Payment] Fetching page 0 of discarded shares for pool erg1, block 76462 
[I] [PPLNS Payment] 0 K (0.0034288111049573123) total discarded shares, block 76462 
[I] [PPLNS Payment] 3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim = 0 K (0.0034288111049573123) discarded shares, block 76462 
[I] [PPLNS Payment] Deleting 3 discarded shares before 2021-09-19T11:31:16.6227670 
[I] [PPLNS Payment] 0 K (0.49) shares contributed to a total payout of 66.8925 ERG (100.00% of block reward) to 1 addresses 
[I] [erg1] [Ergo Payout Handler] Paying 337.5 ERG to 1 addresses 
[I] [erg1] [Ergo Payout Handler] Unlocking wallet 
[I] [erg1] [Ergo Payout Handler] Wallet unlocked 
[I] [erg1] [Ergo Payout Handler] Current wallet balance is 2492.5504 ERG 
[I] [erg1] Validating addresses ... 
[I] [erg1] [Ergo Payout Handler] Payment transaction id: 16a72856972a685fa6bb236357e54928bb6d47669cfe2f3a67b62b9a7ad02f77 
[I] [erg1] [Ergo Payout Handler] Locking wallet 

so far everything looks good
[https://testnet.ergoplatform.com/en/transactions/59b362af5d1880f3ba875338944564c2c698897cc09badc92e880b34f166d899](url)

My settings:
        "paymentProcessing": {
            "enabled": true,
            "WalletPassword": "password",
            "MinimumConfirmations": 100,
            "minimumPayment": 1,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 0.2
            }
        }

But in the api:
      "totalPaid": 0,
      "totalBlocks": 13,
      "lastPoolBlockTime": "2021-09-19T11:31:24.247849"

totalpaid 0, and payments database table empty. Any idea?

**Comment by oliverw** [comment]
Weird. Have balances been reset to 0 (balances table)?

**Comment by szilardkoppel** [comment]
yes

Balance changes table:
"id"	"poolid"	"address"	"amount"	"usage"	"tags"	"created"
"1"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76436"	"{}"	"19/9/2021 14:06:21.394882"
"2"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76436"	"{}"	"19/9/2021 14:06:21.4566"
"3"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"-67.5"	"Balance reset after payment"	"{}"	"19/9/2021 14:06:21.871679"
"4"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76438"	"{}"	"19/9/2021 14:16:22.016286"
"5"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76438"	"{}"	"19/9/2021 14:16:22.037964"
"6"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76442"	"{}"	"19/9/2021 14:16:22.052029"
"7"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76442"	"{}"	"19/9/2021 14:16:22.056526"
"8"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76443"	"{}"	"19/9/2021 14:16:22.064274"
"9"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76443"	"{}"	"19/9/2021 14:16:22.068101"
"10"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"-202.5"	"Balance reset after payment"	"{}"	"19/9/2021 14:16:22.358836"
"11"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76447"	"{}"	"19/9/2021 14:36:22.615474"
"12"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76447"	"{}"	"19/9/2021 14:36:22.636373"
"13"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76448"	"{}"	"19/9/2021 14:36:22.64712"
"14"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76448"	"{}"	"19/9/2021 14:36:22.6569"
"15"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"-135"	"Balance reset after payment"	"{}"	"19/9/2021 14:36:22.924637"
"16"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76449"	"{}"	"19/9/2021 14:46:23.041618"
"17"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76449"	"{}"	"19/9/2021 14:46:23.048935"
"18"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76453"	"{}"	"19/9/2021 14:46:23.054452"
"19"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76453"	"{}"	"19/9/2021 14:46:23.060486"
"20"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"-135"	"Balance reset after payment"	"{}"	"19/9/2021 14:46:23.344432"
"21"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76457"	"{}"	"19/9/2021 16:17:47.534274"
"22"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76457"	"{}"	"19/9/2021 16:17:47.596006"
"23"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76458"	"{}"	"19/9/2021 16:17:47.649857"
"24"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76458"	"{}"	"19/9/2021 16:17:47.657784"
"25"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76459"	"{}"	"19/9/2021 16:17:47.669853"
"26"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76459"	"{}"	"19/9/2021 16:17:47.675325"
"27"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76461"	"{}"	"19/9/2021 16:17:47.686307"
"28"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76461"	"{}"	"19/9/2021 16:17:47.692074"
"29"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0.6075"	"Reward for block 76462"	"{}"	"19/9/2021 16:17:47.704842"
"30"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"66.8925"	"Reward for 0 K shares for block 76462"	"{}"	"19/9/2021 16:17:47.710776"
"31"	"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"-337.5"	"Balance reset after payment"	"{}"	"19/9/2021 16:17:48.114973"

and balances table:
"poolid"	"address"	"amount"	"created"	"updated"
"erg1"	"3Wx8uqKzEYrLLBNEYg56kY7X4RqL4iJooopeCDL1VEcifziGxAim"	"0"	"19/9/2021 14:06:21.394882"	"19/9/2021 16:17:48.115835"

**Comment by oliverw** [comment]
I have no idea how this is possible since access to both tables is wrapped inside an ACID transaction: https://github.com/coinfoundry/miningcore/blob/e06baab2bd0f10306d7a822f0721a6f802a0e1ab/src/Miningcore/Payments/PayoutHandlerBase.cs#L113

**Comment by calvintam236** [comment]
> I have no idea how this is possible since access to both tables is wrapped inside an ACID transaction:
> 
> https://github.com/coinfoundry/miningcore/blob/e06baab2bd0f10306d7a822f0721a6f802a0e1ab/src/Miningcore/Payments/PayoutHandlerBase.cs#L113

i think there is a if condition at line 125. probably it was not true in this case.

**Comment by szilardkoppel** [comment]
> > I have no idea how this is possible since access to both tables is wrapped inside an ACID transaction:
> > https://github.com/coinfoundry/miningcore/blob/e06baab2bd0f10306d7a822f0721a6f802a0e1ab/src/Miningcore/Payments/PayoutHandlerBase.cs#L113
> 
> i think there is a if condition at line 125. probably it was not true in this case.

probably yes. i tried in other os and postgres v11 and v13 too so i think its not the system, same issue

**Comment by szilardkoppel** [comment]
okey totally my bad, sorry for this. now i understand the code. reward address was same as the miner address and this is why the payments insert not triggered. thanks calvintam236. case closed
