### ISSUE TITLE
Payouts not working

### ISSUE THREAD

**Issue by riksarchen** [coinfoundry/miningcore#954]
Getting an error message on startup saying the pool address is not owned by the daemon. The address IS owned by the daemon, confirmed in the daemon. 

No payments are processed at all. It only happens to v58.

I'm running vertcoin
Daemon wallet is unlocked. Everything works in v57

**Comment by oliverw** [comment]
@riksarchen It should be a warning, not an error.

**Comment by oliverw** [comment]
@riksarchen Would need to see some payment processing logs.

**Comment by riksarchen** [comment]
> @riksarchen Would need to see some payment processing logs.

Where do I find the logs?

**Comment by riksarchen** [comment]
[Bitcoin Payout Handler] Paayng 125.65118 VTC to 5 addresses

[Bitcoin Payout Handler] sendmany returned error: Invalid Bitcoin address: vxnVkm6bWCD5yEYn9ygPzaFygBBHev4o1 code -5

**Comment by oliverw** [comment]
This is the result of an old bug I've finally fixed recently. In short you've got an invalid address (containing leading or trailing whitespace) in your shares table. The payment system propagated the invalid address into the balances table and now the final RPC to transfer coins fails because of that. 

Solution: Fix the address in both 'balances' and 'shares tables manually.
On 22.09.2021 10:13:40, riksarchen ***@***.***> wrote:
[Bitcoin Payout Handler] Paayng 125.65118 VTC to 5 addresses
[Bitcoin Payout Handler] sendmany returned error: Invalid Bitcoin address: vxnVkm6bWCD5yEYn9ygPzaFygBBHev4o1 code -5

**Comment by riksarchen** [comment]
Thanks for your reply. Will this keep happening if someone joins the pool with an incorrect address or is this a one time thing?

Can you guide how to do this manually?

**Comment by oliverw** [comment]
> Thanks for your reply. Will this keep happening if someone joins the pool with an incorrect address or is this a one time thing?

It used to happen again and again due to the bug (very annoying) but not anymore.
 
> Can you guide how to do this manually?

Connect to database using Postgres's psql utility:

```sql
UPDATE shares SET miner = '<correct address>' WHERE poolid = '<pool_id>' AND miner = '<wrong address>';
UPDATE balances SET address = '<correct address>' WHERE poolid = '<pool_id>' AND address = '<wrong address>';
```

**Comment by riksarchen** [comment]
Awesome. Thanks a lot for your help. Will try this in an hur or so and report back

**Comment by oliverw** [comment]
> Awesome. Thanks a lot for your help. Will try this in an hour or so and report back

Please report back.

**Comment by riksarchen** [comment]
Looks ok? I've done this now. Waiting for payment to execute.

You are now connected to database "miningcore" as user "postgres".
miningcore=# UPDATE shares SET miner = 'vxnVkm6bWCD5yEYn9ygPzaFygBB
Hev4o1' WHERE poolid = 'vert1' AND miner ILIKE '%vxnVkm6bWCD5yEYn9y
gPzaFygBBHev4o1%';
UPDATE 0
miningcore=# UPDATE balances SET address = 'vxnVkm6bWCD5yEYn9ygPzaF
ygBBHev4o1' WHERE poolid = 'vert1' AND address ILIKE '%vxnVkm6bWCD5
yEYn9ygPzaFygBBHev4o1%';
UPDATE 0
miningcore=#

**Comment by riksarchen** [comment]
Same error still. I Wonder if something went wrong with UPDATE as it said UPDATE 0?

**Comment by riksarchen** [comment]
Its a bit strange. Looking at the api the address don't have any pending balances?

https://api.miningpoolsweden.eu/api/pools/vert1/miners/vxnVkm6bWCD5yEYn9ygPzaFygBBHev4o1

**Comment by oliverw** [comment]
> Looks ok? I've done this now. Waiting for payment to execute.
> 
> You are now connected to database "miningcore" as user "postgres".
> miningcore=# UPDATE shares SET miner = 'vxnVkm6bWCD5yEYn9ygPzaFygBB
> Hev4o1' WHERE poolid = 'vert1' AND miner ILIKE '%vxnVkm6bWCD5yEYn9y
> gPzaFygBBHev4o1%';
> UPDATE 0
> miningcore=# UPDATE balances SET address = 'vxnVkm6bWCD5yEYn9ygPzaF
> ygBBHev4o1' WHERE poolid = 'vert1' AND address ILIKE '%vxnVkm6bWCD5
> yEYn9ygPzaFygBBHev4o1%';
> UPDATE 0
> miningcore=#

Nothing was updated (UPDATE 0). 

Can you find it using 

`SELECT * from balances where poolid = 'vert1' AND amount > 0;`

**Comment by riksarchen** [comment]
VxnVkm6bWCD45yEYn9ygPzaFygBBHev4o1          |  0.875293771750 | 2021-08-24 00:41:16.859236 | 2021-09-22 00:26:16.321383

**Comment by riksarchen** [comment]
Hm, I missed a 4 in the address. I'll try to update again

**Comment by oliverw** [comment]
Could you please build from branch `oliverw` and check if it makes a difference?

**Comment by riksarchen** [comment]
Ok. I'm out now but will try in a few hours

**Comment by riksarchen** [comment]
How do I clone other branches?

**Comment by oliverw** [comment]
```
git clone https://github.com/coinfoundry/miningcore
git checkout oliverw
```

**Comment by miketweaver** [comment]
I'm just about to read this, but I have the same error:
```
[2021-09-22 15:59:48.5800] [I] [PayoutManager] Processing payments for pool dfc1 
[2021-09-22 15:59:48.5845] [I] [PayoutManager] Processing payments for pool dfc1, block 1464595 
[2021-09-22 15:59:48.5845] [I] [PayoutManager] Processing payments for pool dfc1, block 1464615 
[2021-09-22 15:59:48.5882] [I] [PayoutManager] Processing payments for pool dfc1, block 1464624 
[2021-09-22 15:59:48.5882] [I] [PayoutManager] Processing payments for pool dfc1, block 1464639 
[2021-09-22 15:59:48.5912] [I] [PayoutManager] Processing payments for pool dfc1, block 1464642 
[2021-09-22 15:59:48.5912] [I] [PayoutManager] Processing payments for pool dfc1, block 1464644 
[2021-09-22 15:59:48.5912] [I] [PayoutManager] Processing payments for pool dfc1, block 1464647 
[2021-09-22 15:59:48.5966] [I] [dfc1] [Bitcoin Payout Handler] Paying 247.5 DFC to 2 addresses 
[2021-09-22 15:59:48.5966] [E] [dfc1] [Bitcoin Payout Handler] sendmany returned error: Invalid Defcoin address: dmdVpSC4KeczCt8YfJ1givGV25WX6Z5yEG code -5 
root@defcoin-miningcore:~/miningcore# sudo -H -u postgres bash -c "psql -d miningcore -c 'select * from balances;'"
 poolid |              address               |      amount      |          created          |          updated          
--------+------------------------------------+------------------+---------------------------+---------------------------
 dfc1   | DMTwnxXWMrdaU7USXRxekgT1y6TroC67zh |  78.770592140167 | 2021-09-22 11:09:47.7359  | 2021-09-22 15:49:48.54323
 dfc1   | DMDVpSC4KeczCt8YfJ1givGV25WX6Z5yEG | 168.729407859833 | 2021-09-22 11:09:47.72547 | 2021-09-22 15:49:48.54323
(2 rows)
```

**Comment by oliverw** [comment]
> I'm just about to read this to catch up, but I have the same error:
> 
> ```
> [2021-09-22 15:59:48.5800] [I] [PayoutManager] Processing payments for pool dfc1 
> [2021-09-22 15:59:48.5845] [I] [PayoutManager] Processing payments for pool dfc1, block 1464595 
> [2021-09-22 15:59:48.5845] [I] [PayoutManager] Processing payments for pool dfc1, block 1464615 
> [2021-09-22 15:59:48.5882] [I] [PayoutManager] Processing payments for pool dfc1, block 1464624 
> [2021-09-22 15:59:48.5882] [I] [PayoutManager] Processing payments for pool dfc1, block 1464639 
> [2021-09-22 15:59:48.5912] [I] [PayoutManager] Processing payments for pool dfc1, block 1464642 
> [2021-09-22 15:59:48.5912] [I] [PayoutManager] Processing payments for pool dfc1, block 1464644 
> [2021-09-22 15:59:48.5912] [I] [PayoutManager] Processing payments for pool dfc1, block 1464647 
> [2021-09-22 15:59:48.5966] [I] [dfc1] [Bitcoin Payout Handler] Paying 247.5 DFC to 2 addresses 
> [2021-09-22 15:59:48.5966] [E] [dfc1] [Bitcoin Payout Handler] sendmany returned error: Invalid Defcoin address: dmdVpSC4KeczCt8YfJ1givGV25WX6Z5yEG code -5 
> 
> 
> root@defcoin-miningcore:~/miningcore# sudo -H -u postgres bash -c "psql -d miningcore -c 'select * from balances;'"
>  poolid |              address               |      amount      |          created          |          updated          
> --------+------------------------------------+------------------+---------------------------+---------------------------
>  dfc1   | DMTwnxXWMrdaU7USXRxekgT1y6TroC67zh |  78.770592140167 | 2021-09-22 11:09:47.7359  | 2021-09-22 15:49:48.54323
>  dfc1   | DMDVpSC4KeczCt8YfJ1givGV25WX6Z5yEG | 168.729407859833 | 2021-09-22 11:09:47.72547 | 2021-09-22 15:49:48.54323
> (2 rows)
> ```
> 
> For some reason the first 3 letters of that address have lost their capitalization.

I know. Thats why I encourage everyone affected by this problem to temporarily try out the dev branch (oliverw).

**Comment by miketweaver** [comment]
```
[2021-09-22 16:10:51.7181] [I] [Core] Version 58.0.1.0-oliverw [4a9b499ad99cdb355eccca474d36da25b2d39327] 
...
[2021-09-22 16:11:52.7760] [I] [PayoutManager] Processing payments for pool dfc1, block 1464647 
[2021-09-22 16:11:52.8078] [I] [dfc1] [Bitcoin Payout Handler] Paying 247.5 DFC to 2 addresses 
[2021-09-22 16:11:52.8405] [I] [dfc1] [Bitcoin Payout Handler] Payment transaction id: f477ba06c863043c5cac1b444cf4e33212c3a607f1cd6784e09b93834fe74b7e 
```
Switching to that `oliverw` branched worked!

**Comment by oliverw** [comment]
> ```
> [2021-09-22 16:10:51.7181] [I] [Core] Version 58.0.1.0-oliverw [4a9b499ad99cdb355eccca474d36da25b2d39327] 
> ...
> [2021-09-22 16:11:52.7760] [I] [PayoutManager] Processing payments for pool dfc1, block 1464647 
> [2021-09-22 16:11:52.8078] [I] [dfc1] [Bitcoin Payout Handler] Paying 247.5 DFC to 2 addresses 
> [2021-09-22 16:11:52.8405] [I] [dfc1] [Bitcoin Payout Handler] Payment transaction id: f477ba06c863043c5cac1b444cf4e33212c3a607f1cd6784e09b93834fe74b7e 
> ```
> 
> Switching to that `oliverw` branched worked!

Good. Everything else working as well?

**Comment by miketweaver** [comment]
> Good. Everything else working as well?
I'll watch, but so far I don't see any issues with payouts. They posted through to the RPC just fine, the balances in the database dropped to 0, and I see them on-chain.

**Comment by oliverw** [comment]
> > Good. Everything else working as well?
> 
> I'll watch, but so far I don't see any issues with payouts. They posted through to the RPC just fine, the balances in the database dropped to 0, and I see them on-chain.

I'm asking because this change affects pretty much all communication between the pool and the daemon AND the pool and every miner. So it's not a minor change even though the code change it [tiny](4a9b499ad99cdb355eccca474d36da25b2d39327).

**Comment by riksarchen** [comment]
Worked for me too.. however payment thresholds seems to have been reset? All payouts was processed even for addresses with a custom payout threshold. When looking at api it seems the custom setting was lost somehow as it says no settings found.

**Comment by oliverw** [comment]
@riksarchen @miketweaver Did you stay on branch `oliverw` and if so, any anomalies detected?

**Comment by riksarchen** [comment]
I'm still in Oliverw branch without any issues as far as I know

**Comment by oliverw** [comment]
> I'm still in Oliverw branch without any issues as far as I know

Did you have active miners during that period?

**Comment by riksarchen** [comment]
Yeah.. me and a friend is mining 24/7

**Comment by miketweaver** [comment]
I am also still using the Oliverw branch with 2 miners, it has been fine so far. (getting close to moving prod to the oliverw branch)

**Comment by riksarchen** [comment]
I got this error now
Failed to pay out 1.019065434129 VTC from pool vert1: sendmany returned error: Transaction fee and change calculation failed code -6

**Comment by oliverw** [comment]
> I got this error now
> Failed to pay out 1.019065434129 VTC from pool vert1: sendmany returned error: Transaction fee and change calculation failed code -6

Well I would ask this the Vertcoin guys.

**Comment by riksarchen** [comment]
Ok, not a problem with Oliverw bransch?

**Comment by oliverw** [comment]
> Ok, not a problem with Oliverw bransch?

I don't think so.

**Comment by oliverw** [comment]
Fixed in Release 59.
