### ISSUE TITLE
low difficulty share and incorrect extraNonce2 in nonce only with t-rex miner

### ISSUE THREAD

**Issue by szilardkoppel** [coinfoundry/miningcore#958]
Hello,

im testing Ergo on main net after on testnet everything went fine. So i connected 10GH/s to my pool. Every rig doing fine but one with t-rex 0.22.1 have 2 type of errors and one with nanominer have 1 type of error.

**Issue 1 with nanominer:**
Share rejected: job not found [nanominer/3.3.5-cuda11] 

**Issue 1 with t-rex:**
Share rejected: low difficulty share (1.622755973752) [t-rex/0.22.1] 

**Issue 2 with t-rex:**
Share rejected: low difficulty share (1.7530226835) [t-rex/0.22.1]

Im using vardiff. 

My config:
  "blockRefreshInterval": 100,
  "jobRebroadcastTimeout": 60,

  "difficulty": 0.5,
  "varDiff": {
      "minDiff": 0.1,
      "maxDiff": null,
      "targetTime": 15,
      "retargetTime": 90,
      "variancePercent": 30,
  }

Thank you

**Comment by szilardkoppel** [comment]
some more info. node and miningcore and postgres are on the same server communicating locally with each other. between the server and the rig there is 32-40 ms in some rare cases jumping up to 200ms but no more.

**Comment by oliverw** [comment]
@szilardkoppel May I ask why you've closed it?

**Comment by szilardkoppel** [comment]
job not found solved with incrased maxactivejobs and incrased blockrefreshinterval. and with trex nothing to do on the pool. its mining rig sided issue. if i allow maxdelta 1 in 90s vardiff change then trex is good. but if vardiff jump 3 or more diff then trex still sending shares with old diff. for example mining start on 0.5 then all ok for 90s. then vardiff change to 8.7 for example then trex still send some old 0.5 share. but on the same rig with other software like nbminer all of the shares good except trex. so conclusion with 3070 cards dont use trex.

**Comment by oliverw** [comment]
T-Rex has always been problematic with Ergo. Not only in my own testing but according to other pool ops as well.

**Comment by szilardkoppel** [comment]
yes i got that too

**Comment by oliverw** [comment]
> yes i got that too

Okay, thanks.
