### ISSUE TITLE
High hashrate gets 1 rejected share

### ISSUE THREAD

**Issue by riksarchen** [coinfoundry/miningcore#964]
This is not a big problem, just annoying for miners to get a rejected on the statistics of there miningsoftware.

I've set diff to 1 by default which works for most miners. But for a miner with higher hashrate they get one rejected share (even though they set static diff in config). Seems like static diff is set with a slight delay after a share is submitted.

**Comment by oliverw** [comment]
No static diff is sent immediately upon login. If the first share is sent using a diff lower than what being told by the pool is a problem of the miner, not the pool. Closing.
