### ISSUE TITLE
Pool of Pools

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#98]
I saw a feature noted down in the ric-nomp roadmap stating this:
`
To reduce variance for pools just starting out which have little to no hashing power a feature is planned which will allow your own pool to connect upstream to a larger pool server. It will request work from the larger pool then redistribute the work to our own connected miners.`

Seems like a good feature to implement. What kind of work would be needed for this?

**Comment by oliverw** [comment]
@Kukks I honestly have no idea. Could you provide a link?

**Comment by Kukks** [comment]
https://github.com/vagabondan/ric-nomp

**Comment by oliverw** [comment]
Well according to git blame that feature was added to the roadmap by the original authors of NOMP more than 4 years ago and never worked on. 😏

**Comment by Kukks** [comment]
I can work on it if feasible. Any idea of how it could work? 
I guess it would just funnel the work to the other pool and cut out the pool fee once it gets paid.

**Comment by oliverw** [comment]
@Kukks I would like to postpone work on this as improving the API in order to make a capable web-frontend possible is now getting my attention.

**Comment by rterbush** [comment]
@oliverw any hints or thoughts toward your direction with the API? I'm currently looking at this as well.

I've found a nice example in this, https://github.com/M5M400/poolui as it sits on top of this: https://github.com/Snipa22/nodejs-pool/blob/master/lib/api.js

**Comment by oliverw** [comment]
@rterbush As much as I would love to make the API compatible with existing frontends, that probably won't happen due to time constraints. Developing this project, running poolmining.org and a day job is pretty taxing 😄

**Comment by rterbush** [comment]
Understand completely. I'm slowly getting up to speed here so if you can give me a bit of direction, I will try to work within your design constraints and try to share the work load. That's how this works, yes? :-)

**Comment by Kukks** [comment]
@oliverw @rterbush I can open source my current repo once straks is integrated. It's an SPA and still basic and rough but it should be a good base. :)

**Comment by rterbush** [comment]
Any chance of setting up a Gitter for the project? I have a lot to say about this topic and others but am sensitive about not junking up the issue list with this chatter.

**Comment by Kukks** [comment]
@rterbush https://gitter.im/miningcore/Lobby
This ok?

**Comment by samanshahmohamadi** [comment]
@Kukks You can use a stratum proxy. I tested it with [stratum-proxy](https://github.com/Stratehm/stratum-proxy) and miningcore, it seems working on the test environment. Take a look at that.
