### ISSUE TITLE
ERGO Stratum: Block 615914 submission failed with: Invalid block mined: requirement failed: h(f) < b condition not met

### ISSUE THREAD

**Issue by vinnielima** [coinfoundry/miningcore#990]
**Describe the bug**
We have experienced this error three times now, from different stratum and different node combinations.  

On Miningcore stratum:

```
[2021-11-09 19:59:19.9642] [I] [ergo1] Submitting block 615914 []
[2021-11-09 19:59:20.4041] [W] [ergo1] Block 615914 submission failed with: Invalid block mined: requirement failed: h(f) < b condition not met
```

On the Ergo node:

```
06:59:20.308 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/93.123.180.164:9030, local=/10.1.2.4:43966, direction=Outgoing)
06:59:20.365 INFO  [tor.default-dispatcher-14] o.e.m.CandidateGenerator - New block mined, header: Header({"extensionId":"f24752386c96881c6177dd21eb6334041fcb9817ecf0d8004887165bf53d8beb","difficulty":"2076938810163200","votes":"000000","timestamp":1636459156974,"size":220,"stateRoot":"e3eb8495652d771314767d130855933b7e1b31107012399eacc35fcc86d0422617","height":615929,"nBits":117924087,"version":2,"id":"82484bb06abe5eb8edba97f887be953e20a2f35ac192cab294f060afcb73bcb9","adProofsRoot":"fd66557beeac91a49d7ee8aae253bd6946e1542223e23986c352f6d097ce903d","transactionsRoot":"89bfe51466e5172383c39a2fd913cea30794a94d9686d38abe0a8bc07398032b","extensionHash":"eb715ad70c258b497aaa007c920b20b22fd766a4681e3162fc04ef44cd63af29","powSolutions":{"pk":"0302122c332fd4e3c901f045ac18f559dcecf8dc61f6f94fbb34d0c7c3aac71fb7","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"a0b3655c998b6444","d":0},"adProofsId":"e8d0b10e86af6e9b8218d9b2fb8a4e79cdd5dede70d3a02f7405f1f2f6135324","transactionsId":"787727cb8dfda03a2467b31e13b86eba1e7a89b7cc33f1c384f68c1f6ba42db2","parentId":"d92695d75e26644c4dee1f3fe7eb98dc56799b850223f1107f470545660845bc"})
```

**To Reproduce**
Not sure how to reproduce this.

**Expected behavior**

**Screenshots**
See above

**OS**
 This is on Ubuntu 20.04

**Additional context**
Multiple stratum and nodes deployed, persisting to same Postgresql back end.  Stratum nodes are paired with their own Nodes.  Nodes have same pool wallet loaded, same API key used.

**Comment by oliverw** [comment]
It's a known issue and even after talking to the ergo team its unclear why this happens.

**Comment by vinnielima** [comment]
This is a problem with Job Broadcasting.  

This seems to be an issue with new jobs not being rebroadcasted when a block is found.

Code that notifies new jobs to miners (ErgoPool.cs):

![image](https://user-images.githubusercontent.com/6125290/142639747-922df6a5-50ce-477a-979d-d8cd601fe89a.png)

Needs to be invoked when a block is found (in ErgoJobManager.cs):
![image](https://user-images.githubusercontent.com/6125290/142639809-b73b08cd-9ab9-47e7-b0b0-7288797c94f1.png)

In our testing, no Job broadcast is occuring when a new block is mined, causing miners to continue to submitting shares for old blocks.

**Comment by oliverw** [comment]
I need some clarification on this. When you say "when a new block is mined", do you mean mined by this pool or mined by anyone else?

**Comment by oliverw** [comment]
To make it a little more obvious. Once a block is found by the pool, a job update is triggered here:

https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs#L339

and picked up here:

https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs#L59

which ultimately forces a job update to be sent to the miners:

https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs#L85

**Comment by vinnielima** [comment]
@oliverw  I would look at the below ErgoJobManager.cs.  Effectively what was happening is that once a block was mined by the pool, the miners would never get a job update and would continue to submit shares for the previous block. That is what caused the error in this issue.

https://github.com/GetBlok-io/miningcore/blob/master/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs

We had to add some additional debugging to the code to track this down in testnet, once confirmed the behavior, our devs were able to fix it. We rolled to mainnet last night, and have successfully mined a block.

Would be beneficial to merge it back to your repo.  Unfortunate you could not help on solve this issue after numerous attempts by me and my team, could have saved a lot of time and benefited the greater community. Great code base.

**Comment by oliverw** [comment]
> @oliverw I would look at the below ErgoJobManager.cs. Effectively what was happening is that once a block was mined by the pool, the miners would never get a job update and would continue to submit shares for the previous block. That is what caused the error in this issue.
> 
> https://github.com/GetBlok-io/miningcore/blob/master/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs

The linked version of ErgoJobManager.cs does not contain any substantial changes, just added logging and thus won't make any difference whatsoever related to the original problem.

**Comment by vinnielima** [comment]
What was added was the method SendJob() at the end of OnNewJobAsync()

**Comment by oliverw** [comment]
> What was added was the method SendJob() at the end of OnNewJobAsync()
> 
> So whenever it said “broadcasting job” it wasn’t actually broadcasting it

There is no method `OnNewJobAsync` in the linked file. Did you mean https://github.com/GetBlok-io/miningcore/blob/master/src/Miningcore/Blockchain/Ergo/ErgoPool.cs?

**Comment by vinnielima** [comment]
Correct. Linked wrong file.

**Comment by vinnielima** [comment]
Correct wrong file linked
